### ISSUE TITLE
Question: execute notify after "Received lower prio advert"

### ISSUE THREAD

**Issue by hugochinchilla** [acassen/keepalived#100]
I've installed Keepalived to create a HA pair of Nginx load balancers. I'm hosting them on OVH and switching a failover IP from one server to another requires an API call. I've created a script to make those API calls using the notify_master directive.

This has been working nicely until last night. The backup server became master for a few seconds (probably because of a packet loss or something which impeded it from seeing the VRRP announcements from the master), causing the following message on the real master: "Received lower prio advert, forcing new election". The server went back to backup state but, as there were no changes in the primary server, the last execution of the script was from the secondary one, causing OVH to route the IPS to the secondary server while the interfaces where configured on the primary one. 

Is there a way to make keepalived execute the script after forcing a new election?

Here I attach the logs and config files for better understanding of my problem.

```
root@glados:~# salt -G 'roles:lb' cmd.run 'grep -i keepalived /var/log/syslog.1'
glados.xxxx.com:
    Jul 13 23:46:44 glados Keepalived_vrrp: VRRP_Instance(LOAD_BALANCER) Received lower prio advert, forcing new election
    Jul 13 23:47:01  Keepalived_vrrp: last message repeated 6 times
borg.xxxx.com:
    Jul 13 23:46:44 borg Keepalived_vrrp: VRRP_Instance(LOAD_BALANCER) Transition to MASTER STATE
    Jul 13 23:46:45 borg Keepalived_vrrp: VRRP_Instance(LOAD_BALANCER) Entering MASTER STATE
    Jul 13 23:46:45 borg Keepalived_vrrp: Opening script file /usr/local/src/keepalived/take-ips.py
    Jul 13 23:46:48 borg Keepalived_vrrp: VRRP_Instance(LOAD_BALANCER) Received higher prio advert
    Jul 13 23:46:48 borg Keepalived_vrrp: VRRP_Instance(LOAD_BALANCER) Entering BACKUP STATE
    Jul 13 23:46:51 borg Keepalived_vrrp: VRRP_Instance(LOAD_BALANCER) Transition to MASTER STATE
    Jul 13 23:46:52 borg Keepalived_vrrp: VRRP_Instance(LOAD_BALANCER) Entering MASTER STATE
    Jul 13 23:46:52 borg Keepalived_vrrp: Opening script file /usr/local/src/keepalived/take-ips.py
    Jul 13 23:46:52 borg Keepalived_vrrp: VRRP_Instance(LOAD_BALANCER) Received higher prio advert
    Jul 13 23:46:52 borg Keepalived_vrrp: VRRP_Instance(LOAD_BALANCER) Entering BACKUP STATE
```

```
# keepalived.conf in glados (primary server)
vrrp_instance LOAD_BALANCER {
  nopreempt
  interface eth1
  state MASTER
  virtual_router_id 51
  priority 100

  virtual_ipaddress_excluded {
    ***.***.***.** dev eth1 label eth1:1
    ***.***.***.** dev eth1 label eth1:2
    ***.***.***.** dev eth1 label eth1:3
    ***.***.***.** dev eth1 label eth1:4
    ***.***.***.** dev eth1 label eth1:5
    ***.***.***.** dev eth1 label eth1:6
    ***.***.***.** dev eth1 label eth1:7
    ***.***.***.** dev eth1 label eth1:8
    ***.***.***.** dev eth1 label eth1:9
    ***.***.***.** dev eth1 label eth1:10

  }

  notify_master "/usr/local/src/keepalived/take-ips.py"
}
```

```
# keepalived.conf in borg (secondary server)
vrrp_instance LOAD_BALANCER {
  nopreempt
  interface eth1
  state MASTER
  virtual_router_id 51
  priority 90

  virtual_ipaddress_excluded {
    ***.***.***.** dev eth1 label eth1:1
    ***.***.***.** dev eth1 label eth1:2
    ***.***.***.** dev eth1 label eth1:3
    ***.***.***.** dev eth1 label eth1:4
    ***.***.***.** dev eth1 label eth1:5
    ***.***.***.** dev eth1 label eth1:6
    ***.***.***.** dev eth1 label eth1:7
    ***.***.***.** dev eth1 label eth1:8
    ***.***.***.** dev eth1 label eth1:9
    ***.***.***.** dev eth1 label eth1:10

  }

  notify_master "/usr/local/src/keepalived/take-ips.py"
}
```

**Comment by odiszapc** [comment]
@hugochinchilla which one?

**Comment by hugochinchilla** [comment]
@odiszapc I did not find any solution using keepalived config, the problem has never ocurred again so we never implemented any solution to it, now I'm thinking maybe it could be solved using syslogng and executing a script when the message "Received lower prio advert" appears on the syslog.

**Comment by dud225** [comment]
Hello

I found this crappy solution : 
```
vrrp_script keepalived_lower_prio_advert {
    script "if journalctl -u keepalived.service --since '1 min ago' | grep -q 'Received lower prio advert, forcing new election'; then exit 1; else exit 0; fi"
    interval 60
    weight -5
}
```

That causes a small imbalance so that the erroneous backup server that actually has the FO IP gets promoted forcibly for a small time. Then the other server becomes master again and that makes it rerun the notify script.

That makes me aware Keepalived is not suited for such use-cases...

@acassen : it looks like the construct `script "! command"` is not working. For example Keepalived considers `"! exit 0"` to be successful. I guess it is because exclamation marks are considered as comments ? Also using simple quote instead of double quote isn't working either : `'exit 0'` always fails.

**Comment by merlineus** [comment]
Hi,
@hugochinchilla could you publish your script for moving failover IP via API?
And how long does it takes to switch IP from one instance to another?

**Comment by pqarmitage** [comment]
It is probably the case that the original problem described was caused when the backup server became a master, and it sent GARP messages. When the backup server became backup again, the master didn't send GARP messages, and so the ARP caches still pointed to the backup  server.

Keepalived v1.3.5 implements a new keyword `higher_prio_send_advert` to resolve this problem. See the descriptions in issue #542 for details of how to configure it.

`Is possible to switch one failover IP between different datacenter locations?`
Yes it is. If the datacentres are on the same subnet (so that multicasts can be sent from one to the other), just configure keepalived as normal. If you are using routing between them so that the systems you want to run keepalived on do not share a subnet, use `unicast_src_ip` and `unicast_peer`.

**Comment by merlineus** [comment]
The question was regarding OVH infrastucture )

**Comment by hugochinchilla** [comment]
Hi @merlineus, I posted the script here https://gist.github.com/hugochinchilla/35a16b47d0a6910de665fd450914b045

You will need to edit it heavily, we use salt to populate the script configuration.

OVH may take some minutes to actually move the IP, and the success rate of they moving a failover IP is somewhat around 90%, this means whe have had several downtimes because of their fault, so I don't really recomend using it lightly

**Comment by arainho** [comment]
IMO, on the _`borg (secondary server)`_ config file the `state` should be changed to `BACKUP` so that the node initializes to the backup state before elections occur.  You can check more info in [at digitalocean](https://www.digitalocean.com/community/tutorials/how-to-set-up-highly-available-web-servers-with-keepalived-and-floating-ips-on-ubuntu-14-04#create-the-keepalived-configuration-file)
