### ISSUE TITLE
keepalived-2.0.7 bfd bug

### ISSUE THREAD

**Issue by postren** [acassen/keepalived#1037]
keepalived-2.0.7/lib/scheduler.c **+1163** is 
`thread_list_make_ready(&m->timer, t, m, t->type);`
m->timer pop and m->ready push

when a **THREAD_TIMER** thread by `thread_list_make_ready` push into `m->ready`, and `thread_cancel `it, will be at scheduler.c **+846** 
`thread_list_delete(&thread->master->timer, thread);`
`m->timer` pop again, and thread is not belong to it.

keepalived will be **CRASH** or else.

**Comment by pqarmitage** [comment]
As I understand it, what you are saying is that when thread_cancel() is called, it doesn't know whether the thread is on the unexpired timer list or the ready list.

Since v2.0.7 the code in this area has changed significantly, and it now uses red-black trees. The problem that you have described still exists, though.

I will have a look at the code and sort out a fix.

Many thanks for reporting this.

**Comment by pqarmitage** [comment]
On further investigation I have found that the problem has already been fixed in the latest code, since now threads of type THREAD_TIMER can only exist on the timer queue, and when they time out, the thread type is changed to THREAD_READY. I did find one instance of a thread type that could occur on a waiting queue and the ready queue, and that was THREAD_CHILD. Since that type of thread could never be cancelled, we didn't have a problem, but to be safe I have produced patch 15df3ca that changes the thread type to THREAD_CHILD_TERMINATED for when it is on the ready queue.
