### ISSUE TITLE
error occur when compile with header <netinet/in.h> without #define IP_MULTICAST_ALL

### ISSUE THREAD

**Issue by dzc15331066** [acassen/keepalived#1054]

**Comment by pqarmitage** [comment]
Looking at the latest code, so far as I can see all uses of IP_MULTICAST_ALL are protected by:
`#if HAVE_DECL_IP_MULTICAST_ALL`.

Could you please provide the following information so we can investigate this further:
1. Exactly what version of keepalived source code are you using
2. What Linux distro and version are you using
3. The full compiler error messages.

**Comment by dzc15331066** [comment]
I use Linux3.10.0 with glibc2.13, the script "configure" determines `HAVE_DECL_IP_MULTICAST_ALL`  with `<linux/in.h>`, but `vrrp_if.c`  include `<netinet.h>`, which does not define `IP_MULTICAST_ALL`   when using glibc2.13

**Comment by pqarmitage** [comment]
Since the kernel has IP_MULTICAST_ALL we want to use the definition, but if we include linux/in.h when building keepalived we get compile failures due to conflicting definitions.

Commit 00e8b4d make configure create a definition for IP_MULTICAST_ALL using the value in linux/in.h if it is not defined in netinet/in.h.
