### ISSUE TITLE
In keepalived 1.3.5, notify_master does not execute

### ISSUE THREAD

**Issue by lovlyhao** [acassen/keepalived#1091]
keepalived.conf 
-------------------------start-------------------------------------
vrrp_instance VI_82 {
    state BACKUP
    state BACKUP
    nopreempt
    interface ens33
    virtual_router_id 82
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }

    virtual_ipaddress {
        192.168.0.190
    }

     notify_master "/bin/bash /usr/local/bin/a.sh"
}

-------------------end-------------------------

a.sh
---------------------------------------------------
#/bin/bash
/bin/echo 'dadad' >> /usr/local/bin/a.txt

**Comment by lovlyhao** [comment]
The a.txt file was not created

**Comment by lovlyhao** [comment]
![image](https://user-images.githubusercontent.com/30038949/50448846-78d03e80-095e-11e9-9f24-19498541c02d.png)

**Comment by pqarmitage** [comment]
It works fine for me with both v1.3.5 and the current head of master branch.

Is the first line of a.sh supposed to start with a shebang?

You could modify a.sh to match the following:
```
#!/bin/bash
echo 'dadad' >>/usr/local/bin/a.txt
```
You could also modify (if a.sh is executable)
`notify_master "/bin/bash /usr/local/bin/a.sh"`
to
`notify_master /usr/local/bin/a.sh`

If you run keepalived with the `-D` option, what do the logs show? You could also send a USR1 signal to the parent keepalived process and check in /tmp/keepalived.data that the notify_master script is correctly configured.

Are you running keepalived in a container or directly on the host system?

**Comment by lovlyhao** [comment]
> 对于v1.3.5和当前的master分支头，它对我来说都很好。
> 
> a.sh的第一行应该从shebang开始吗？
> 
> 您可以修改a.sh以匹配以下内容：
> 
> ```
> #!/bin/bash
> echo 'dadad' >>/usr/local/bin/a.txt
> ```
> 你也可以修改（如果a.sh是可执行文件）
> `notify_master "/bin/bash /usr/local/bin/a.sh"`
> 到
> `notify_master /usr/local/bin/a.sh`
> 
> 如果您使用该`-D`选项运行keepalived，日志会显示什么？您还可以向父keepalived进程发送USR1信号，并在/tmp/keepalived.data中检查notify_master脚本是否已正确配置。
> 
> 您是在容器中运行keepalived还是直接在主机系统上运行？

Yes, "a.sh" is a demo file that can be executed, but notify_master does not see the call. It is no problem to call "a.sh" alone. I use the keepalived-D log as follows. I see from the log that keepalived is changed from a slave node to a master node. Why did not the alarm event trigger? Does "a.sh" need to change its group?

------------------------------------------------------------------------------------
Dec 26 15:04:23 localhost Keepalived[1946]: Starting Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2
Dec 26 15:04:23 localhost Keepalived[1946]: Opening file '/etc/keepalived/keepalived.conf'.
Dec 26 15:04:23 localhost Keepalived[1947]: Starting Healthcheck child process, pid=1948
Dec 26 15:04:23 localhost Keepalived[1947]: Starting VRRP child process, pid=1949
Dec 26 15:04:23 localhost Keepalived_vrrp[1949]: Registering Kernel netlink reflector
Dec 26 15:04:23 localhost Keepalived_vrrp[1949]: Registering Kernel netlink command channel
Dec 26 15:04:23 localhost Keepalived_vrrp[1949]: Registering gratuitous ARP shared channel
Dec 26 15:04:23 localhost Keepalived_vrrp[1949]: Opening file '/etc/keepalived/keepalived.conf'.
Dec 26 15:04:23 localhost Keepalived_vrrp[1949]: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
Dec 26 15:04:23 localhost Keepalived_vrrp[1949]: VRRP_Instance(VI_82) removing protocol VIPs.
Dec 26 15:04:23 localhost Keepalived_vrrp[1949]: Using LinkWatch kernel netlink reflector...
Dec 26 15:04:23 localhost Keepalived_vrrp[1949]: VRRP_Instance(VI_82) Entering BACKUP STATE
Dec 26 15:04:23 localhost Keepalived_vrrp[1949]: VRRP sockpool: [ifindex(2), proto(112), unicast(0), fd(10,11)]
Dec 26 15:04:23 localhost Keepalived_healthcheckers[1948]: Opening file '/etc/keepalived/keepalived.conf'.
Dec 26 15:04:26 localhost Keepalived_vrrp[1949]: VRRP_Instance(VI_82) Transition to MASTER STATE
Dec 26 15:04:27 localhost Keepalived_vrrp[1949]: VRRP_Instance(VI_82) Entering MASTER STATE
Dec 26 15:04:27 localhost Keepalived_vrrp[1949]: VRRP_Instance(VI_82) setting protocol VIPs.
Dec 26 15:04:27 localhost Keepalived_vrrp[1949]: Sending gratuitous ARP on ens33 for 192.168.0.190
Dec 26 15:04:27 localhost Keepalived_vrrp[1949]: VRRP_Instance(VI_82) Sending/queueing gratuitous ARPs on ens33 for 192.168.0.190
Dec 26 15:04:27 localhost Keepalived_vrrp[1949]: Sending gratuitous ARP on ens33 for 192.168.0.190
Dec 26 15:04:27 localhost Keepalived_vrrp[1949]: Sending gratuitous ARP on ens33 for 192.168.0.190
Dec 26 15:04:27 localhost Keepalived_vrrp[1949]: Sending gratuitous ARP on ens33 for 192.168.0.190
Dec 26 15:04:27 localhost Keepalived_vrrp[1949]: Sending gratuitous ARP on ens33 for 192.168.0.190
Dec 26 15:04:32 localhost Keepalived_vrrp[1949]: Sending gratuitous ARP on ens33 for 192.168.0.190
Dec 26 15:04:32 localhost Keepalived_vrrp[1949]: VRRP_Instance(VI_82) Sending/queueing gratuitous ARPs on ens33 for 192.168.0.190
Dec 26 15:04:32 localhost Keepalived_vrrp[1949]: Sending gratuitous ARP on ens33 for 192.168.0.190
Dec 26 15:04:32 localhost Keepalived_vrrp[1949]: Sending gratuitous ARP on ens33 for 192.168.0.190
Dec 26 15:04:32 localhost Keepalived_vrrp[1949]: Sending gratuitous ARP on ens33 for 192.168.0.190
Dec 26 15:04:32 localhost Keepalived_vrrp[1949]: Sending gratuitous ARP on ens33 for 192.168.0.190

**Comment by pqarmitage** [comment]
I get the following in the log:
Dec 26 22:17:29 Host Keepalived[26805]: Starting Keepalived v1.3.5 (03/19,2017)
Dec 26 22:17:29 Host Keepalived[26805]: Unable to resolve default script username 'keepalived_script' - ignoring
Dec 26 22:17:29 Host Keepalived[26805]: Opening file '/home/quentin/keepalived/github.pqa/../utils/configs/1091.conf'.
Dec 26 22:17:29 Host Keepalived[26806]: Starting Healthcheck child process, pid=26808
Dec 26 22:17:29 Host Keepalived_healthcheckers[26808]: Initializing ipvs
Dec 26 22:17:29 Host Keepalived[26806]: Starting VRRP child process, pid=26809
Dec 26 22:17:29 Host Keepalived_healthcheckers[26808]: Opening file '/home/quentin/keepalived/github.pqa/../utils/configs/1091.conf'.
Dec 26 22:17:29 Host Keepalived_vrrp[26809]: Registering Kernel netlink reflector
Dec 26 22:17:29 Host Keepalived_vrrp[26809]: Registering Kernel netlink command channel
Dec 26 22:17:29 Host Keepalived_vrrp[26809]: Registering gratuitous ARP shared channel
Dec 26 22:17:29 Host Keepalived_vrrp[26809]: Opening file '/home/quentin/keepalived/github.pqa/../utils/configs/1091.conf'.
Dec 26 22:17:29 Host Keepalived_vrrp[26809]: VRRP_Instance(VI_82) removing protocol VIPs.
Dec 26 22:17:29 Host Keepalived_vrrp[26809]: SECURITY VIOLATION - scripts are being executed but script_security not enabled.
Dec 26 22:17:29 Host Keepalived_vrrp[26809]: Using LinkWatch kernel netlink reflector...
Dec 26 22:17:29 Host Keepalived_vrrp[26809]: VRRP_Instance(VI_82) Entering BACKUP STATE
Dec 26 22:17:29 Host Keepalived_vrrp[26809]: VRRP sockpool: [ifindex(6), proto(112), unicast(0), fd(10,11)]
Dec 26 22:17:33 Host Keepalived_vrrp[26809]: VRRP_Instance(VI_82) Transition to MASTER STATE
Dec 26 22:17:34 Host Keepalived_vrrp[26809]: VRRP_Instance(VI_82) Entering MASTER STATE
Dec 26 22:17:34 Host Keepalived_vrrp[26809]: VRRP_Instance(VI_82) setting protocol VIPs.
Dec 26 22:17:34 Host Keepalived_vrrp[26809]: Sending gratuitous ARP on eth0 for 192.168.0.190
Dec 26 22:17:34 Host Keepalived_vrrp[26809]: VRRP_Instance(VI_82) Sending/queueing gratuitous ARPs on eth0 for 192.168.0.190
Dec 26 22:17:34 Host Keepalived_vrrp[26809]: Sending gratuitous ARP on eth0 for 192.168.0.190
Dec 26 22:17:34 Host Keepalived_vrrp[26809]: Sending gratuitous ARP on eth0 for 192.168.0.190
Dec 26 22:17:34 Host Keepalived_vrrp[26809]: Sending gratuitous ARP on eth0 for 192.168.0.190
Dec 26 22:17:34 Host Keepalived_vrrp[26809]: Sending gratuitous ARP on eth0 for 192.168.0.190
Dec 26 22:17:34 Host Keepalived_vrrp[26809]: Opening script file /bin/bash
Dec 26 22:17:39 Host Keepalived_vrrp[26809]: Sending gratuitous ARP on eth0 for 192.168.0.190
Dec 26 22:17:39 Host Keepalived_vrrp[26809]: VRRP_Instance(VI_82) Sending/queueing gratuitous ARPs on eth0 for 192.168.0.190
Dec 26 22:17:39 Host Keepalived_vrrp[26809]: Sending gratuitous ARP on eth0 for 192.168.0.190
Dec 26 22:17:39 Host Keepalived_vrrp[26809]: Sending gratuitous ARP on eth0 for 192.168.0.190
Dec 26 22:17:39 Host Keepalived_vrrp[26809]: Sending gratuitous ARP on eth0 for 192.168.0.190
Dec 26 22:17:39 Host Keepalived_vrrp[26809]: Sending gratuitous ARP on eth0 for 192.168.0.190

The differences are:
I have a log entry: `Unable to resolve default script username 'keepalived_script' - ignoring`
and I also have `Opening script file /bin/bash`

Do you have a user keepalived_script configured on your system? If so, can that user execute a.sh, and does it create /usr/local/bin/a.txt? It may well be that user keepalived_user does not have write permission to /usr/local/bin. Can you try changing a.sh so that it writes to /tmp/a.txt and see if that works. You could also try creating /usr/local/bin/a.txt with everyone having write permission to it.

If the above does not work can you try adding at the beginning of your configuration:
```
global_defs {
    script_user root
}
```
and see if that works.

**Comment by lovlyhao** [comment]
> global_defs { script_user root }
谢谢，我是使用的 <pre><code>global_defs {
    script_user root
}
</code></pre>

**Comment by lovlyhao** [comment]
> Specifying `script_user root` is probably not the best way to resolve the issue, but it does indicate where the problem lies.
> 
> The best solution would be to modify a.sh so that it writes to somewhere that user keepalived_script has write access to.

Uh huh! I'll try. Thank you.
