### ISSUE TITLE
virtual_routes IPv6 src

### ISSUE THREAD

**Issue by storm49152** [acassen/keepalived#1102]
When I have a virtual_routes section like this:

```
  virtual_routes {
    1.2.225.0/24 dev eth1 scope link src 1.2.225.89
    default via 1.2.225.1 dev eth1 src 1.2.225.89
    1:2:2000:29::/64 dev eth1 src 1:2:2000:29::89
    default via inet6 1:2:2000:29::1 dev eth1
  }
```

This works for IPv4. But it does not for IPv6. A route for the 1:2:2000:29::/64 network will be created, but not with src (so it's probably created when the IPv6 address was assigned). Also the default gateway is not defined; when I remove the src, the default gateway is assigned so it seems something goes wrong when setting the src IP.

What I'm getting is:

```
# ip -6 r
[...]
1:2:2000:20::/64 dev eth0 proto kernel metric 256 pref medium
[...]
```

What I'm expecting is:
```
# ip -6 r
[...]
1:2:2000:29::/64 dev eth1 src 1:2:2000:29::89 metric 1024 pref medium
[...]
```

We need this to work, because the server is multi-homed and picks the wrong IPv6 address when sending packets out.

Is it something we're doing wrong, or does this need fixing?

**Comment by pqarmitage** [comment]
It looks like you are not using a recent version of keepalived since your route is installed with `proto kernel` whereas recent versions of keepalived install routes with `proto 112` or (if a line `112    keepalived` is added to /etc/iproute2/rt_protos), `proto keepalived`.

Using keepalived v2.0.11, and with a virtual route block
```
  virtual_routes {
    1.2.225.0/24 dev eth1 scope link src 10.1.1.3
    default via 1.2.225.1 dev eth1 src 10.1.1.3
    1:2:2000:29::/64 dev eth1 src fd00:0:1:101::3
    default via inet6 1:2:2000:29::1 dev eth1
  }
```
and the output of ip -6 r is:
```
1:2:2000:29::/64 dev eth1 proto keepalived src fd00:0:1:101::3 metric 1024 pref medium
[...]
default via 1:2:2000:29::1 dev eth1 proto keepalived metric 1024 pref medium
```
which I believe is exactly what you want.

Can you try updating your keepalived to v2.0.11 and see if that resolves your problem.

**Comment by storm49152** [comment]
I'm currently using 2.0.10, but will update to 2.0.11 and report back.

**Comment by storm49152** [comment]
I'm on a fully updated CentOS-7, and I receive this when compiling 2.0.11:
```
configure: error: kernel source path /lib/modules/3.10.0-957.1.3.el7/build appears to be an unprocessed kernel source tree
```
First, when installing kernel-heades, I get the headers files installed in /lib/modules/3.10.0-957.1.3.el7.x86_64, but I created a symlink for that. Then I get the above error.

How can I solve this?

**Comment by pqarmitage** [comment]
Please see https://github.com/acassen/keepalived/issues/1098#issuecomment-451937964 ; in essence you need to install the kernel-headers package, and not specify `--with-kernel-dir`.

I'm not sure there is any difference in the handling of routes betwee v2.0.10 and v2.0.11, although it is worth try it. Could you please post your full configuration and I will try it on a CentOS 7 VM to see if I can reproduce the problem.

**Comment by storm49152** [comment]
That worked, thanks. I'm building keepalived using the spec file and --with-kernel-dir is in there. Going forward from here.

**Comment by storm49152** [comment]
I updated to 2.0.11 but it's not working for me.

There is a VI for eth0 and eth1, and they share identical config for virtual_ipaddress, virtual_ipaddress_excluded and virtual_routes. My redacted vrrp_instance config is:
(IP addresses starting with 1.2.x.y are internal, IP addresses starting with 3.4.x.y are external.)

```
vrrp_instance VI_eth0 {
  state BACKUP
  interface eth0
  virtual_router_id 1
  priority 100
  advert_int 1
  authentication {
    <blah>
  }
  virtual_ipaddress {
    1.2.20.89/32 dev eth0
    3.4.225.89/24 dev eth1
  }
  virtual_ipaddress_excluded {
    1:2:2085:20::89/64 dev eth0
    3:4:2000:29::89/64 dev eth1
  }
  virtual_routes {
    3.4.225.0/24 dev eth1 scope link src 3.4.225.89
    default via 3.4.225.1 dev eth1 src 3.4.225.89
    3:4:2000:29::/64 dev eth1 src 3:4:2000:29::89
    default via inet6 3:4:2000:29::1 dev eth1
  }
}
```

After stopping keepalived on both servers and then starting keepalived, these are the relevant routes that I get on the active server (ip -6 r):

```
3:4:2000:29::/64 dev eth1 proto kernel metric 256 pref medium
default via 3:4:2000:29::1 dev eth1 proto 112 metric 1024 pref medium
```

So a route is added because the IP address has /64, but I'm missing "src 3:4:2000:29::89".

When I run keepalived in debug mode (keepalived -nldD), I see this:

```
Wed Jan  9 16:47:57 2019: (VI_eth0) setting Virtual Routes
Wed Jan  9 16:47:57 2019: Netlink: error: Invalid argument, type=RTM_NEWROUTE(24), seq=1547048892, pid=0
Wed Jan  9 16:47:57 2019: Netlink: error: No route to host, type=RTM_NEWROUTE(24), seq=1547048893, pid=0

Wed Jan  9 16:47:57 2019: (VI_eth1) setting Virtual Routes
Wed Jan  9 16:47:57 2019: Netlink: error: Invalid argument, type=RTM_NEWROUTE(24), seq=1547048900, pid=0
Wed Jan  9 16:47:57 2019: Netlink: error: No route to host, type=RTM_NEWROUTE(24), seq=1547048901, pid=0
```

When I remove "src 3:4:2000:29::89" from the IPv6 virtual_routes then this error goes away (and I don't get the required result).

AFAICS "src 3:4:2000:29::89" should be valid; if I add the route manually using "ip route add" it works as expected.

**Comment by pqarmitage** [comment]
It looks to me that the `--with-kernel-dir` option is for Red Hat Linux 9 (i.e. the version released in 2003), which ran on Linux 2.4. I think I ought to remove references to RH9, and also EL3 since that too is based on Linux 2.4 and we no longer support that.

**Comment by pqarmitage** [comment]
When you say `There is a VI for eth0 and eth1, and they share identical config for virtual_ipaddress, virtual_ipaddress_excluded and virtual_routes` does that mean that VI_eth0 and VI_eth1 have exactly the same virtual ip_addresses etc, i.e. both VI_eth0 and VI_eth1 have VIPs 1.2.20.89/32 and 3.4.225.89/24 etc. If that is the case, I'll have to try that, but I won't be able to do anything more for a few hours now. If you could post your full configuration, so that it includes VI_eth0, VI_eth1and anything else in the configuration that would really helpful, since it might show up some strange interdependencies.

**Comment by pqarmitage** [comment]
Yes, I'm happy for you to send the configuration to me directly at the email address in my profile.

**Comment by pqarmitage** [comment]
At https://github.com/acassen/keepalived/issues/1102#issuecomment-452751186 you indicate that the following routes are installed:
```
3:4:2000:29::/64 dev eth1 proto kernel metric 256 pref medium
default via 3:4:2000:29::1 dev eth1 proto 112 metric 1024 pref medium
```
From this we can see that the default route is being installed by keepalived, but the 3:4:2000:29::/64 route with src 3:4:2000:29::89 is not being installed. The route to 3:4:2000:29::/64 is being installed by the kernel when the virtual IP address 3:4:2000:29::89 is added by keepalived.

Unfortunately keepalived isn't helpful when it reports netlink errors in this sort of circumstance, since it doesn't report what specific command the error relates to. You are getting two errors for each vrrp instance, but only one of the (IPv6) virtual routes is not being installed. It would be helpful to see the output of `ip route show` after the keepalived instances have become master, to see whether one of the errors relates to an IPv4 route.

**Comment by pqarmitage** [comment]
Can you try adding `metric 128` to the virtual route `3:4:2000:29::/64 dev eth1 src 3:4:2000:29::89` on VI_eth0 and `metric 129` on VI_eth1 and see what happens then.

**Comment by pqarmitage** [comment]
Could you also add `metric 1023` to the default IPv6 route on VI_eth0.

**Comment by pqarmitage** [comment]
The problem that I am seeing is that when adding IP address 3:4:2000:29::89 the kernel installs route
`3:4:2000:29::/64 dev eth1 proto kernel metric `**256**` pref medium`
and keepalived installs the route
`3:4:2000:29::/64 dev eth1 proto 112 src 3:4:2000:29::89 metric` **1024** `pref medium`

This means that the kernel installed route is used since the metric is lower than the keepalived installed route.

There are two solutions to this:
i) Specify a metric lower than 256 for the keepalived route
ii) Add `noprefixroute` to the virtual_ipaddress to stop the kernel installing its route, since we don't want the kernel adding the route.

My preference is a combination of both:
i) Add `noprefixroute` to the virtual_ipaddress_excluded entries for `3:4:2000:29::89/64 dev eth1`
and
ii) Add `metric 256` to the virtual route entries to 3:4:2000:29::/64

This certainly works for me.

**Comment by storm49152** [comment]
With @pqarmitage I fixed/changed some things in my configuration but that didn't solve the issue with the src parameter. Eventually I did a yum update to fetch the latest packages as of today, and suddenly my configuration **with** the src parameter started working. So, what I posted about does not appear to be a keepalived issue.
