### ISSUE TITLE
notify script does not execute with |'s in the bash script

### ISSUE THREAD

**Issue by matthewbassett** [acassen/keepalived#1107]
Hi All,

Really loving keepalived. I'm using it to run an HAproxy cluster with a floating IP at the moment, and it has been running great. I would like to setup some notifications to a slack channel however. There is an NPM package that I use for this called pipe-slack. I wrote a little one liner script:
`echo "date Called with args: $@" | /usr/local/bin/p2s "#haproxy-monitor" | tee /tmp/katest.log`
which works great if I run it myself from the keepalived_script user, however when it gets called by a STATE change in keepalived the script doesn't seem to get run, and there is no error written to syslog. However if I run: 
`echo "date Called with args: $@" >> /tmp/katest.log`
the execution works great and writes all of the args to that file.
Any thoughts on why this would be the case, or any suggestions on better methods to debug?

Thanks!

**Comment by matthewbassett** [comment]
Whoops sorry, neglected to add the line I'm calling it with from my /etc/keepalived/keepalived.conf
Its: `notify "/opt/notify.sh" keepalived_script`

**Comment by pqarmitage** [comment]
Why do you want to pipe the output of p2s to tee? When keepalived invokes a script, output to stdout has nowhere to go (actually stdin, stdout and stderr are all opened on /dev/null).

Since I don't really know what /usr/local/bin/p2s does (does it write to stdout? it seems to be designed to send stdin to the specified slack channel and then write "PIPE TO SLACK COMPLETED" to the console log), I replaced p2s with cat, so my notify.sh script is:
`echo "date Called with args: $@" | cat | tee /tmp/katest.log`
and this does indeed write "date Called with args: " to /tmp/katest.log.

Each time /opt/notify.sh is called, it will overwrite /tmp/katest.log, since tee does not append to the specified file unless the option `--append` is specified (and I'm not sure that p2s writes anything to stdout anyway).

Do you actually want /opt/notify.sh to be:
```
#!/bin/bash

echo "$(date) Called with args: $@" | tee --append /tmp/katest.log | /usr/local/bin/p2s
```
This will append the output to /tmp/katest.log and also send the message to the slack channel.

**Comment by pqarmitage** [comment]
Does keepalived log anything at startup about security issues with the script. keepalived can refuse to run the script if it thinks it is insecure, e.g. if it has group or world write permission, but this will be logged when keepalived starts. 

Can you add a line to /opt/notify.sh at the beginning:
`echo "$0 running at $(date)" >>/tmp/notify_run.log`
to really see if the script is running or not.

**Comment by matthewbassett** [comment]
Good thought. If I add the line you suggested it does indeed work. So it seems like the execution is failing at the pipe-to-slack application. Interestingly enough I added another echo to that file after the pipe-to-slack command and it also is writing to the file... So I think there is something security-wise that's keeping the execution of that specific piece to run. I'll have to think through a different method of pushing keepalived status information to slack. Thanks for the assistance!

**Comment by pqarmitage** [comment]
You could try running the p2s script as use root and see if that works.

I think it is reasonable to conclude it is not a keepalived issue now, so I'll close the issue. It you need to reopen it, just add an entry to that affect and it can be reopened.
