### ISSUE TITLE
Multiple Protocols for virtual_server

### ISSUE THREAD

**Issue by soudaburger** [acassen/keepalived#1139]
I currently have several `virtual_server` blocks, tied to a single `vrrp_instance` which has a `track_script` and `virtual_ipaddress {}` entries.  

Currently, our instance is configured for UDP only.  I would like to configure it for TCP also, not in lieu of.  The issue appears to be surrounding the fact that we have `notify_down` and `notify_up` methods on the `real_server` so bring up/down the interface as necessary.  

1) What is the proposed/best method for having multiple protocols managed by KA?
2) I assume that `virtual_server <ip> <port>` duplications cause problems?  Or at least because they have notify up/down scripts?
3) Any other advice you can provide would be great.  Thanks!

Sample Configs:

```
vrrp_instance VI_1 {
  interface                 eth0
  state                     MASTER
  virtual_ipaddress {
    1.2.3.4
  }
virtual_server <ip> 53 {
  delay_loop 6
  lb_algo lc
  lb_kind TUN
  persistence_timeout 0
  alpha
  omega
  quorum 1
  protocol UDP
  real_server <ip> 53 {
    weight 1
    notify_down  "/sbin/ipvsadm -d -u <ip>:53 -r <other_ip>"
    notify_up    "/sbin/ipvsadm -a -u <ip>:53 -r <other_ip> -i -w 100"
    MISC_CHECK {
      misc_path "/etc/keepalived/scripts/monitor.backends.sh <other_ip>"
      misc_timeout 15
    }
}
```

**Comment by pqarmitage** [comment]
@soudaburger From the information you have given above it is difficult to understand what you want to achieve, in part since the configuration above will not run (at least on recent versions of keepalived). It has the following errors (identified by #**):
```
vrrp_instance VI_1 {
  interface                 eth0
  state                     MASTER
  virtual_router_id  1      #** Add this line
  virtual_ipaddress {
    1.2.3.4
  }
}                #** Add missing brace (curly bracket)
virtual_server <ip> 53 {
  delay_loop 6
  lb_algo lc
  lb_kind TUN
  # persistence_timeout 0     #** a value of 0 is invalid; don't specify persistence_timeout for no persistence
  alpha
  omega
  quorum 1
  protocol UDP
  real_server <ip> 53 {
    weight 1
    notify_down  "/sbin/ipvsadm -d -u <ip>:53 -r <other_ip>"
    notify_up    "/sbin/ipvsadm -a -u <ip>:53 -r <other_ip> -i -w 100"
    MISC_CHECK {
      misc_path "/etc/keepalived/scripts/monitor.backends.sh <other_ip>"
      misc_timeout 15
    }
}
}          #** Add missing brace
```

I am assuming that <ip> is an IP address on the server on which keepalived is running, and <other_ip> is the IP address of a remote real server.

When you add the real server to <other_ip>, you end up with two real servers, and since you are using _lc_ scheduling, packets will be forwarded to either real server, depending on which has the fewer active jobs (at appears the weight is not used with _lc_ scheduling - that would need _wlc_, but still that won't stop some packets being forwarded to the <ip> real server). To ensure that packets are only forwarded to the highest weighted real server, you need the 'fo' scheduler [details here](https://git.kernel.org/pub/scm/utils/kernel/ipvsadm/ipvsadm.git/commit/?id=0dd79e16e53378e9f999d082ac0baae4668a53bf).

I think you can achieve what you are currently doing (i.e. the real server <other_ip> is only configured when the MISC_CHECK is successful) with the following configuration (which has the benefit that keepalived is directly configuring IPVS in a standard way):
```
vrrp_instance VI_1 {
  interface                 eth0
  state                     MASTER
  virtual_router_id  1
  virtual_ipaddress {
    1.2.3.4
  }
}
virtual_server <ip> 53 {
  delay_loop 6
  lb_algo lc
  lb_kind TUN
  # persistence_timeout 0
  alpha
  omega
  quorum 1
  protocol UDP
  real_server <ip> 53 {
    weight 1
  }
  real_server <other_ip> 53 {
    weight 100
    MISC_CHECK {
      misc_path "/etc/keepalived/scripts/monitor.backends.sh <other_ip>"
      misc_timeout 15
    }
}
}
```

It isn't clear to me whether you really want the real server on IP address <ip> or whether that is just a mechanism for adding/deleting the real server on <other_ip>. Depending on what you want will change what is the best configuration for you. The scheduling method will also depend on what you want to achieve, and _wlc_ or _fo_ scheduling may be better for you.

A more standard way of achieving what I think you want to achieve is to configure the virtual server on a VRRP virtual IP address. The virtual server and real servers will always remain configured while keepalived is running, but since the VRRP virtual IP address will not be configured when the VRRP instance is not master, only the virtual server on the VRRP master will be active.

```
vrrp_script remote_rs_check {
      script "/etc/keepalived/scripts/monitor.backends.sh <other_ip>"
      timeout 15
}

vrrp_instance VI_1 {
  interface                 eth0
  state                     MASTER
  virtual_router_id  1
  virtual_ipaddress {
    1.2.3.4
    <virtual_server_ip>
  }
  track_script {
     remote_rs_check
  }
}
virtual_server <virtual_server_ip> 53 {
  delay_loop 6
  lb_algo lc
  lb_kind TUN
  # persistence_timeout 0
  alpha
  omega
  quorum 1
  protocol UDP
  real_server <virtual_server_ip> 53 {
    weight 1
  }
  real_server <other_ip> 53 {
    weight 100
    MISC_CHECK {
      misc_path "/etc/keepalived/scripts/monitor.backends.sh <other_ip>"
      misc_timeout 15
    }
}
}
```

Now to actually consider the question you asked about having a UDP virtual server and a TCP virtual server.

The following should work, but has the disadvantage that the monitor.backends.sh script is run twice as often.
```
vrrp_instance VI_1 {
  interface                 eth0
  state                     MASTER
  virtual_router_id  1
  virtual_ipaddress {
    1.2.3.4
  }
}
virtual_server <ip> 53 {
  delay_loop 6
  lb_algo lc
  lb_kind TUN
  # persistence_timeout 0
  alpha
  omega
  quorum 1
  protocol UDP
  real_server <ip> 53 {
    weight 1
  }
  real_server <other_ip> 53 {
    weight 100
    MISC_CHECK {
      misc_path "/etc/keepalived/scripts/monitor.backends.sh <other_ip>"
      misc_timeout 15
    }
}
}

virtual_server <ip> 53 {
  delay_loop 6
  lb_algo lc
  lb_kind TUN
  # persistence_timeout 0
  alpha
  omega
  quorum 1
  protocol TCP
  real_server <ip> 53 {
    weight 1
  }
  real_server <other_ip> 53 {
    weight 100
    MISC_CHECK {
      misc_path "/etc/keepalived/scripts/monitor.backends.sh <other_ip>"
      misc_timeout 15
    }
}
}
```

Would the following work for you:
```
vrrp_script remote_rs_check {
      script "/etc/keepalived/scripts/monitor.backends.sh <other_ip>"
      timeout 15
}

vrrp_instance VI_1 {
  interface                 eth0
  state                     MASTER
  virtual_router_id  1
  virtual_ipaddress {
    1.2.3.4
    <virtual_server_ip>
  }
  track_script {
     remote_rs_check
  }
}
virtual_server <virtual_server_ip> 53 {
  delay_loop 6
  lb_algo lc
  lb_kind TUN
  # persistence_timeout 0
  alpha
  omega
  quorum 1
  protocol UDP
  real_server <virtual_server_ip> 53 {
    weight 1
  }
  real_server <other_ip> 53 {
    weight 100
}
}

virtual_server <virtual_server_ip> 53 {
  delay_loop 6
  lb_algo lc
  lb_kind TUN
  # persistence_timeout 0
  alpha
  omega
  quorum 1
  protocol TCP
  real_server <virtual_server_ip> 53 {
    weight 1
  }
  real_server <other_ip> 53 {
    weight 100
}
}
```

If you can explain more about how you want the vrrp_instance and virtual servers to work and what you want to achieve, then we could make appropriate suggestions to achieve an optimal solution.

**Comment by soudaburger** [comment]
Thanks for the reply!  I definitely can provide more information, I was just trying to keep it short/sweet.  Ultimately, we currently have KA doing UDP load balancing for DNS, however we would like to have KA do BOTH UDP/TCP for DNS.  

* The `<other_ip>` referenced above would end up being the DNS backends serving this LB.
* The `<ip>` for the `real_server` ends up being the ip for the DNS backend. 
* The `<ip>` for the `virtual_server` corresponds to an interface/ip on the KA instance.

Does that help?  I will look at your last example and see if I can make things work.  I'm also wanting to make sure our `notify_down`/`notify_up` `ipvsadm` commands are still present as we want to manage connectivity of those IPs as the health of the backends changes accordingly.  So juggling those across the virtual_servers is important too.

**Comment by pqarmitage** [comment]
@soudaburger I'm still not clear exactly what you want to achieve. It would be helpful if you could provide your full configuration, albeit with IP addresses changed (e.g. change the first two numbers to 10.0, but leave them as IP addresses that can be referred to). If you could also state where each IP address resides, and what services they provide, that would help.

Are you running keepalived on more than one system, and so have keepalived master and backups?

My understanding from the configuration you have provided is that you want both the real servers to be removed if the monitor.backend.sh script returns a non zero exit code, but if it returns a 0 exit code, you want both the real servers to be configured. If this is the case, keepalived can do all that for you, without needing to add and delete the real server in the notify scripts.

You haven't said what monitor.backends.sh checks to ensure the health of the backends. You might want to consider using DNS_CHECK for the real servers using UDP and TCP_CHECK for the real servers using TCP.

**Comment by soudaburger** [comment]
I'm sorry for the delay in getting back to you, I believe I have solved my problem.  You can close this.  The original issue was _not_ caused by keepalive, but rather our networking configurations on our end that caused the testing and validation to hang.  Sorry for any confusion.
