### ISSUE TITLE
Sync all the states (tcp connection) from the Master LVS to Backup LVS #1138

### ISSUE THREAD

**Issue by kttang88** [acassen/keepalived#1140]
I noticed the issue was closed. Can you please reopen it? I have not get the solution yet.

**Comment by pqarmitage** [comment]
Issue reopened. This issue was closed since your question _I added lvs_sync_daemon_interface eno16780032 to sync the daemon, is this correct?_ was answered.

**Comment by kttang88** [comment]
I added lvs_sync_daemon_interface eno16780032 to sync the daemon, is this correct but is defective as the ipvsadm -L -c -n shows that both servers are not in sync.

**Comment by pqarmitage** [comment]
The output of `ipvsadm -L --daemon` shows that keepalived is configuring the IPVS sync daemon correctly, so yes, your keepalived configuration is correct.

The problem is that the IPVS sync daemon is not behaving as expected, and as @acassen said in issue #1138, this is an IPVS issue, and needs to taken up on the lvs-users mailing list. There is nothing more that keepalived support can help with. Again as @acassen suggested, in the first place try setting up your IPVS configuration (including the sync daemons) using ipvsadm, so that keepalived isn't involved, and get that working. Once that is working, migrate the ivpsadm based configuration into keepalived.

**Comment by kttang88** [comment]
Noted.
