### ISSUE TITLE
master state flap appears correlated with a bonding lag immediately after reboot

### ISSUE THREAD

**Issue by shallot** [acassen/keepalived#1143]
Hi,

So the other day this happened to me upon a reboot of a machine that has bridge interfaces upon VLAN interfaces upon a bonding interface, which are bound in a keepalived VRRP sync group, and this machine is a low-priority backup (together with 3 others, one of which is master):

```
...
Mar  5 14:46:53 motmot kernel: [   14.441145] IPv6: ADDRCONF(NETDEV_UP): bond0: link is not ready
...
Mar  5 14:46:55 motmot Keepalived[4182]: Starting Keepalived v1.3.2 (12/03,2016)
...
Mar  5 14:46:55 motmot systemd[1]: Started Keepalive Daemon (LVS and VRRP).
...
Mar  5 14:46:56 motmot kernel: [   17.276156] bond0: first active interface up!
Mar  5 14:46:56 motmot kernel: [   17.276170] IPv6: ADDRCONF(NETDEV_CHANGE): bond0: link becomes ready
...
Mar  5 14:46:59 motmot Keepalived_vrrp[4211]: VRRP_Instance(vef_vlan5) Transition to MASTER STATE
Mar  5 14:46:59 motmot Keepalived_vrrp[4211]: VRRP_Group(vef_group) Syncing instances to MASTER state
Mar  5 14:46:59 motmot Keepalived_vrrp[4211]: VRRP_Instance(vef_vlan1272) Transition to MASTER STATE
Mar  5 14:46:59 motmot Keepalived_vrrp[4211]: VRRP_Instance(vef_vlan15) Transition to MASTER STATE
Mar  5 14:46:59 motmot Keepalived_vrrp[4211]: VRRP_Instance(vef_vlan31) Transition to MASTER STATE
Mar  5 14:46:59 motmot Keepalived_vrrp[4211]: VRRP_Instance(vef_vlan56) Transition to MASTER STATE
...
Mar  5 14:47:01 motmot Keepalived_vrrp[4211]: VRRP_Instance(vef_vlan5) Received advert with higher priority 201, ours 51
Mar  5 14:47:01 motmot Keepalived_vrrp[4211]: VRRP_Instance(vef_vlan5) Entering BACKUP STATE
Mar  5 14:47:01 motmot Keepalived_vrrp[4211]: VRRP_Group(vef_group) Syncing instances to BACKUP state
...
```

This causes an unnecessary election, which is practically immediately won by the old master, but it's still annoying.

Can I do anything to make it stop happening?

TIA.

**Comment by shallot** [comment]
Another example log from another reboot just now, this time with a notify script in place:

```
...
Mar  6 12:47:21 motmot Keepalived_vrrp[4251]: VRRP_Instance(vef_vlan5) Entering BACKUP STATE
Mar  6 12:47:21 motmot Keepalived_vrrp[4251]: Opening script file /etc/keepalived/notify.sh
...
Mar  6 12:47:21 motmot /etc/keepalived/notify.sh[4255]: reloading firewall upon state transition: GROUP vef_group BACKUP 0
Mar  6 12:47:21 motmot systemd[1]: Started Keepalive Daemon (LVS and VRRP).
...
Mar  6 12:47:22 motmot kernel: [   17.591808] IPv6: ADDRCONF(NETDEV_CHANGE): bond0: link becomes ready
...
Mar  6 12:47:25 motmot /etc/keepalived/notify.sh[4255]: completed reloading firewall upon state transition: GROUP vef_group BACKUP 0
Mar  6 12:47:25 motmot Keepalived_vrrp[4251]: VRRP_Instance(vef_vlan5) Transition to MASTER STATE
Mar  6 12:47:25 motmot Keepalived_vrrp[4251]: VRRP_Group(vef_group) Syncing instances to MASTER state
...
Mar  6 12:47:25 motmot /etc/keepalived/notify.sh[5856]: reloading firewall upon state transition: GROUP vef_group MASTER 0
...
Mar  6 12:47:26 motmot /etc/keepalived/notify.sh[5856]: completed reloading firewall upon state transition: GROUP vef_group MASTER 0
Mar  6 12:47:27 motmot Keepalived_vrrp[4251]: VRRP_Instance(vef_vlan5) Received advert with higher priority 161, ours 51
Mar  6 12:47:27 motmot Keepalived_vrrp[4251]: VRRP_Instance(vef_vlan5) Entering BACKUP STATE
Mar  6 12:47:27 motmot Keepalived_vrrp[4251]: VRRP_Group(vef_group) Syncing instances to BACKUP state
...
```

**Comment by pqarmitage** [comment]
The `-D` command line option will provide more detailed logging, and will log that it has transitioned to master due to not receiving adverts. In fact, the only reason that a vrrp instance can transition to master from backup is if it doesn't receive any higher or equal priority adverts within (generally) 3 * advert_interval + (255 - priority) / 255 * advert_interval.

**Comment by pqarmitage** [comment]
When I have seen this before, it was caused by the bond interface not passing traffic for several seconds after the bond interface becomes ready (in this case it appears to take 5 seconds from the link becoming ready to traffic being passed).

The first option to try is `preempt delay` with a delay of 7 seconds or so on the vrrp interface, but that will also delay subsequent transitions from backup to master.

An alternative is to delay the starting of keepalived, but synchronising that to when the bond interface is really passing traffic could be difficult.

Another option would be to have a vrrp track script with `init_fail` set, that attempts to ping, or connect to, a remote system via the bond interface (or vlans on the bond interface). The disadvantage of that would be that the script will run periodically, and also the remote system would have to be up (are all the physical interfaces that are bonded to bond0 connected to the same switch, and is that switch pingable? If there is more than one switch, a script could try pinging them in turn until one responds).

There are some other possibilities but they would require adding new features to keepalived, for example a "one-shot" script that must succeed before a vrrp instance can come up, or making a track_script run frequently until successful, but then only infrequently when it is succeeding (rather like the delay_before_retry feature of IPVS checkers). It would also be possible to add built-in checkers for VRRP instances like there are for IPVS real servers. Another possibility would be to add an option so that a VRRP instance cannot transition to master for a number of seconds after keepalived initialised.

**Comment by shallot** [comment]
OK, so with the assumption that something is blocking those packets from coming in, I pinged the machine while it was rebooting, and observed that once it started responding, a couple seconds afterwards it went silent for a couple of seconds, and then continued on its merry way. I'm guessing that's the critical interval where things go awry.

So then I've increased the interval from the default 1 to 5, and after the next reboot it didn't flap, and the ping during the boot was no longer erratic in that way.

Is it possible that keepalived config was in some way responsible for this? The kernel wasn't logging anything about any throttling. This keepalived.conf currently mentions a total of 616 IP addresses, so I could imagine the volume of gratuitous ARPs to be significant, but not prior to the election trigger...

**Comment by pqarmitage** [comment]
Can you try starting rebooting without keepalived starting, and see if it still goes silent for a couple of seconds, That would tell us if it is keepalived causing the problems or not. I don't think adding the addresses is the cause of the problem, since keepalived will wait for 3 advert intervals before attempting to transition to master, and it only adds the addresses (and starts sending gratuitous ARPs) after it hasn't received any adverts for 3 advert intervals.

Although increasing the advert interval to 5 seconds resolves the boot flapping problem, it will mean that when a master fails, it will take longer for a backup vrrp instance to take over (with a 5 second advert interval it could be between 10 and 20 seconds, depending on priority and when the last advert was received).

If you could post, or email your full config, then I can try it and see if I can see a cause of the problem. I could also possibly make some recommendations for improvements.

Are you using vmac (macvlan) interfaces with keepalived. It is possible that adding a large number of those might cause a delay in packets being passed, although I haven't tested this.

I not that you are using keepalived v1.3.2. There have been very many improvements in keepalived since that was released (over 2 years ago). Upgrading to the current version (v2.0.13) would be worthwhile, even if it doesn't resolve your problem.

**Comment by shallot** [comment]
@pqarmitage those would make a lot of sense if the bonding delay was homogenous, but my observation seems to have been that it let through some, then went AWOL, and then came back. It'd be very hard to fight against that...

Perhaps the best thing keepalived could do is to start logging missed advertisements, and the interface where it was missing them, especially when grouping is in effect. That would make it easier for user to diagnose where exactly things are going wrong.

**Comment by shallot** [comment]
Here's the config, with a modicum of censorship:

```
global_defs {
  notification_email {
    <my email address>
  }
  notification_email_from <my email address>
  smtp_server localhost
  router_id motmot
  enable_script_security
}

vrrp_sync_group vef_group {
  group {
    vef_vlan5
    vef_vlan1272
    vef_vlan15
    vef_vlan31
    vef_vlan56
  }
  notify /etc/keepalived/notify.sh root root
  smtp_alert
}

vrrp_instance vef_vlan5 {
  state BACKUP
  interface br5
  virtual_router_id 5
  priority 51
  advert_int 5
  authentication { 
    auth_type PASS
    auth_pass <CENSORED>
  }
  virtual_ipaddress {
    10.0.96.1/21
    10.0.96.2/21
  }
  virtual_ipaddress_excluded {
    <list of 3 IPs skipped here>
  }
}

vrrp_instance vef_vlan1272 {
  state BACKUP
  interface br1272
  virtual_router_id 127
  priority 51
  advert_int 5
  authentication { 
    auth_type PASS
    auth_pass <CENSORED>
  }
  virtual_ipaddress {
    161.53.96.2/24
  }
  virtual_ipaddress_excluded {
    <list of 100+ IPs from a /24 L3 segment skipped here>
    <list of 400+ IPs from a /23 L3 segment skipped here>
  }
}

vrrp_instance vef_vlan15 {
  state BACKUP
  interface br15
  virtual_router_id 15
  priority 51
  advert_int 5
  authentication { 
    auth_type PASS
    auth_pass <CENSORED>
  }
  virtual_ipaddress {
    10.0.48.1/24
  }
}

vrrp_instance vef_vlan31 {
  state BACKUP
  interface br31
  virtual_router_id 31
  priority 51
  advert_int 5
  authentication { 
    auth_type PASS
    auth_pass <CENSORED>
  }
  virtual_ipaddress {
    10.0.31.1/24
  }
}

vrrp_instance vef_vlan56 {
  state BACKUP
  interface br56
  virtual_router_id 56
  priority 51
  advert_int 5
  authentication { 
    auth_type PASS
    auth_pass <CENSORED>
  }
  virtual_ipaddress {
    10.0.56.1/24
  }
}
```

**Comment by shallot** [comment]
Also no macvlan is in use, and I'll be upgrading when it arrives in Debian stable

**Comment by pqarmitage** [comment]
@shallot With the configuration you have, prior to any vrrp instance becoming master, keepalived doesn't do any configuration regarding network interfaces or addresses, and it doesn't send any packets; the only thing that keepalived will do is open two sockets on each of the 5 interfaces that are specified for the vrrp instances.

However, at startup keepalived does read details of all the network interfaces on the system. If you have a very large number (does br1272 indicate that you have more that 1272 interfaces?), it could keep the kernel busy responding to the request for details of all interfaces, and potentially cause some netlink receive buffer overflows. If this were the case however, if would probably happen whenever keepalived started up, and not just at boot time. There are configuration options in keepalived to increase the netlink receive buffer sizes for situations where there are large numbers of interfaces, but that wasn't introduced until keepalived v2.0.7.

Other that the potential issue of reading details of a large number of interfaces (if indeed that is the case), it is very unlikely that keepalived is having any impact on the ability of the system to receive packets, for the reasons given above.

Regarding logging missed adverts, keepalived does log that with the '-D' option when it times out and transitions to master, but that was added somewhat after v1.3.2. If any further logging detail were to be added, it would probably be to log when adverts are received (for diagnostic purposes), rather than the absence of receiving packets.

It would be worth trying to run tcpdump to capture to a file what is happening in terms of packets being received, but I realise you would need to create a systemd unit file to start up tcpdump early enough in the boot process.

**Comment by shallot** [comment]
@pqarmitage sadly, no, that's not the case, it's basically only those five interfaces on the system. It's a bit tricky to debug, and to compound the problem it's a server that has a painfully slow UEFI so the reboot itself takes quite a while. Maybe if bonding is indeed the problem I'll be able to reproduce the problem by reloading that, I'll play with it.

I figure the main thing about logging detail would be to list the exact interface where a timeout triggers transitions - does the newer version already do that?

**Comment by pqarmitage** [comment]
@shallot It would be helpful to try reloading the bonding and starting keepalived at the same time, although the problem could be caused by the underlying interfaces being slow to come up properly.

What is logged with the -D option when an advert timeout occurs is:
```
Thu Mar  7 14:24:47 2019: (vef_vlan31) Receive advertisement timeout
Thu Mar  7 14:24:47 2019: (vef_vlan31) Entering MASTER STATE
```
If interface can be deduced from the interface the vrrp instance is configured on.

If you can try reloading the bonding and reporting what happens, then I will try to produce some patches to see if we can get further information; the patches will be against the v2.0.13 code base though. Will you be happy to build keepalived from sources with the patches for testing purposes?

**Comment by pqarmitage** [comment]
Commit 5c7a7d7 adds a `global_defs` configuration option `vrrp_startup_delay` which is specified in seconds.

If you add
```
global_defs {
    vrrp_startup_delay 10
}
```
it should stop you problem of a lower priority vrrp instance taking over as master while the system is booting.

I can't think of another way for keepalived to handle it.

**Comment by pqarmitage** [comment]
@shallot This is probably as far as keepalived can help with the problem. If you have further issues with this, this issue report can be reopened.

**Comment by michael2009** [comment]
2019-04-23 09:26:11 local0.info Keepalived[17054]:  Starting Keepalived v2.0.15 (04/04,2019), git commit v2.0.14-53-g9de2817c+
2019-04-23 09:26:11 local0.info Keepalived[17054]:  Running on Linux 4.9.162 #0 SMP Sun Apr 14 17:39:46 2019 (built for Linux 4.9.162)
2019-04-23 09:26:11 local0.info Keepalived[17054]:  Command line: '/usr/sbin/keepalived' '-D' '-S' '0'
2019-04-23 09:26:11 local0.info Keepalived[17054]:  Opening file '/etc/keepalived/keepalived.conf'.
2019-04-23 09:26:11 local0.info Keepalived[17055]:  Starting VRRP child process, pid=17056
2019-04-23 09:26:11 local0.info Keepalived_vrrp[17056]:  Registering Kernel netlink reflector
2019-04-23 09:26:11 local0.info Keepalived_vrrp[17056]:  Registering Kernel netlink command channel
2019-04-23 09:26:11 local0.info Keepalived_vrrp[17056]:  Opening file '/etc/keepalived/keepalived.conf'.
2019-04-23 09:26:11 local0.info Keepalived_vrrp[17056]:  WARNING - default user 'keepalived_script' for script execution does not exist - please create.
2019-04-23 09:26:11 local0.info Keepalived_vrrp[17056]:  SECURITY VIOLATION - scripts are being executed but script_security not enabled.
2019-04-23 09:26:11 local0.info Keepalived_vrrp[17056]:  Assigned address 192.168.9.19 for interface eth1
2019-04-23 09:26:11 local0.info Keepalived_vrrp[17056]:  (Web) entering FAULT state
2019-04-23 09:26:11 local0.info Keepalived_vrrp[17056]:  Registering gratuitous ARP shared channel
2019-04-23 09:26:11 local0.info Keepalived_vrrp[17056]:  Delaying startup for 3 seconds

Enter entering FAULT state before "Delaying startup for 3 seconds".  
vrrp_startup_delay bug ?

        nopreempt
        state BACKUP
        virtual_router_id 100
        track_interface {
                eth2
        }
eth2 not up when keepalived init.  Then i had set vrrp_startup_delay 3

**Comment by pqarmitage** [comment]
@michael2009 You appear to be reporting that something is not working as you expect, but it is not clear what the problem is. Could you please raise a new issue and provide all the information requested.

**Comment by michael2009** [comment]
If set vrrp_startup_delay 3 then VRRP startup at 2019-04-23 09:26:11 + 3s 
But track_interface function start nodelay. at 2019-04-23 09:26:11

**Comment by michael2009** [comment]
I can reproduce the bug aways 
Step:
1. Set keepalived vrrp_startup_delay 30
2. Set track_interface  ethX 
3. Remove cable from ethX
4. Run keepalived 
Then Keepalived com FAULT status after 1s. Nerver delay check after 30s.

**Comment by michael2009** [comment]
Still issue with 2.0.16 version.

**Comment by pqarmitage** [comment]
@michael2009 has opened issue #1254 repeating the above information.
