### ISSUE TITLE
Could anyone anwser which version is stablable and support VRRP3*advert int 0.01s  thanks！ 

### ISSUE THREAD

**Issue by AlexFeng123** [acassen/keepalived#1147]
Could anyone anwser which version is stablable and support VRRP3*advert int 0.01s  thanks！

**Comment by pqarmitage** [comment]
v2.0.13 is the current version and has had no significant issue reports, nor any significant commits since its release. I have tested this version with 1400 VRRP instances, each with advert interval 0.01s and it worked successfully.

v2.0.13 has new code to support very high advertisment rates better, so is the version to go for with advert intervals as low as 0.01 seconds. Previous versions would not have supported 1400 VRRP instances each with 0.01second advert interval.

**Comment by AlexFeng123** [comment]
hi  pqarmitage， thanks a lot！

**Comment by AlexFeng123** [comment]
> 
> 
> hi pqarmitage， thanks a lot！



> 
> 
> v2.0.13 is the current version and has had no significant issue reports, nor any significant commits since its release. I have tested this version with 1400 VRRP instances, each with advert interval 0.01s and it worked successfully.
> 
> v2.0.13 has new code to support very high advertisment rates better, so is the version to go for with advert intervals as low as 0.01 seconds. Previous versions would not have supported 1400 VRRP instances each with 0.01second advert interval.

hi pqarmitage， thanks a lot！
