### ISSUE TITLE
Keepalived v2.0.13 if same priority will auto choose higher IP?

### ISSUE THREAD

**Issue by oldGarey** [acassen/keepalived#1148]
i have 2 node, configure file on node 1:
global_defs {
   router_id LVS_DEVEL
}
vrrp_sync_group VG1{
    group {
      VI_1
    }
}
vrrp_instance VI_1 {
    state BACKUP
    interface bond0
    virtual_router_id 51
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        192.168.1.130 dev bond0 label bond0:1
    }
}
virtual_server 192.168.1.130 3306 {
    delay_loop 2
    lb_algo rr
    lb_kind DR
    nat_mask 255.255.255.0
    persistence_timeout 50
    protocol TCP

    real_server 192.168.1.131 3306 {
        weight 1
        notify_down /etc/checkmysql.sh
        TCP_CHECK {
          connect_timeout=10
          nb_get_retry 3
          delay_before_retry 3
          connect_port 3306
       }
   }
}
node 2:
global_defs {
   router_id LVS_DEVEL
}
vrrp_sync_group VG1{
    group {
      VI_1
    }
}
vrrp_instance VI_1 {
    state BACKUP
    interface bond0
    virtual_router_id 51
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        192.168.1.130 dev bond0 label bond0:1
    }
}
virtual_server 192.168.1.130 3306 {
    delay_loop 2
    lb_algo rr
    lb_kind DR
    nat_mask 255.255.255.0
    persistence_timeout 50
    protocol TCP

    real_server 192.168.1.150 3306 {
        weight 1
        notify_down /etc/checkmysql.sh
        TCP_CHECK {
          connect_timeout=10
          nb_get_retry 3
          delay_before_retry 3
          connect_port 3306
       }
   }
}

when ever if node2:192.168.1.150 keepalived service up, the vip 192.168.1.130 will auto jump to it, the message on node2 like this:
(VI_1) Received advert from 192.168.1.131 with lower priority 100, ours 100, forcing new election
Sending gratuitous ARP on bond0 for 192.168.1.130
Message on node 1:
(VI_1) Master received advert from 192.168.1.150 with same priority 100 but higher IP address than ours
(VI_1) Entering BACKUP STATE

if same priority will auto choose higher ip?

Best Regards
Garey

**Comment by pqarmitage** [comment]
@oldGarey What you describe is not correct. If a backup instance receives an advert with the same priority as its own priority, it should treat it in the same way as if it received a higher priority advert, and remain in backup mode.

RFC5798 explains this in section 6.4.2 (VRRP instance in backup state):

            (445) * If Preempt_Mode is False, or if the Priority in the
            ADVERTISEMENT is greater than or equal to the local
            Priority, then:

               (450) @ Set Master_Adver_Interval to Adver Interval
               contained in the ADVERTISEMENT

The only time a comparison of IP address is made is if a vrrp instance in master state receives an advert with equal priority, then the one with a lower IP address must change to backup state.

This situation you show above:
node2 like this:
`(VI_1) Received advert from 192.168.1.131 with lower priority 100, ours 100, forcing new election
Sending gratuitous ARP on bond0 for 192.168.1.130`
Message on node 1:
`(VI_1) Master received advert from 192.168.1.150 with same priority 100 but higher IP address than ours`
`(VI_1) Entering BACKUP STATE`

means that both node1 and node2 were in master state, and both were sending adverts. So in this case, IP address comparison is used to decide which node should be master. For both nodes to have become master indicates that for some reason the nodes had not been able to see each other's adverts, since otherwise the second one to start up would have remained in backup state.
