### ISSUE TITLE
fwmark port 0 virtual_server syntax no longer accepted (keepalived 2.0.14)

### ISSUE THREAD

**Issue by sim-** [acassen/keepalived#1186]
Hello!

I just tried upgrading from 2.0.5 to upstream git master (2.0.14 / 399ec31229) and now the previously-used "port 0" syntax for fwmark virtual_server entries is being rejected. The configuration syntax (simplified) is:

```
virtual_server fwmark 31 {
        delay_loop 6
        lb_kind DR
        lb_algo lblc
        persistence_timeout 30
        persistence_granularity 255.255.255.192

        real_server 1.1.1.1 0 {
                weight 100
                MISC_CHECK { ... }
        }
        real_server 1.1.1.2 0 {
                weight 100
                MISC_CHECK { ... }
        }
        sorry_server 1.1.1.1 0
}
```

This logs errors for both the real_server and sorry_server lines:

```
Keepalived_healthcheckers[8062]: (Line 124) number '0' outside range [1, 65535]
Keepalived_healthcheckers[8062]: (Line 124) Invalid real server ip address/port 1.1.1.2/0 - skipping
Keepalived_healthcheckers[8062]: (Line 324) number '0' outside range [1, 65535]
Keepalived_healthcheckers[8062]: (Line 324) Invalid sorry server IP address 1.1.1.1 - skipping
```

(Note the port is missing for the sorry server error. Probably should be the same as the real server error.)

The keepalived.conf.SYNOPSIS file, when it existed, used to list the PORT as optional for real_server and mandatory for sorry_server. The newly-updated keepalived.conf man page seems to list both as mandatory. The old behaviour of accepting 0 used to result in the port being passed through unchanged, which is what we want here (since the real servers are handling multiple ports).

In the case where it was working, "ipvsadm-save -n" outputs rules with port 0.

I tested a few combinations of 0 and non-0 ports with DR and NAT modes and I see that port 0 does appear to be a feature. With DR it seems to not matter, but with NAT it will pass the port unchanged if port 0 is specified; otherwise, it will translate the target port to the specified one. So, it does appear that port 0 should perhaps just be allowed again.

The ipvsadm man page also documents the use of port 0 though it says it is only valid when persistence is enabled, which is also incorrect since it is still valid and works when fwmarks are used. I did the above testing with and without persistence options.

**Comment by pqarmitage** [comment]
The offending commit appears to be d98f07c, although since all it changed was to check the return status from the function parsing the ip address and port, it appears entirely reasonable! Prior to that commit, anything could be configured for the port (and the ip address).

So far as I can see, keepalived.SYNOPSIS listed the port for the virtual server as being optional, but did not suggest that the port for real servers was optional.

Your description of the ipvsadm man page appears to be confusing the description for virtual servers and real servers (the man page refers to port 0 requiring persistence for virtual servers rather than real servers).

I will endeavour to ensure that keepalived supports all the options that ipvsadm supports (although keepalived does support some options that released versions of ipvsadm do not yet).

It also seems that keepalived allows different ports to be specified for a virtual server and its real servers, even when using TUN or DR. Although in this circumstance it configures ipvs with different ports for the real and virtual servers, the kernel ignores it, since it cannot work if the port is changed.

**Comment by sim-** [comment]
Sorry, skimming things too quickly. Yes, real_server and sorry_server always required a port according to keepalived.SYNOPSIS. BTW, we have in the past used real_server and sorry_server with port 0 and a non-zero connect_port for a specific TCP_CHECK or similar, but that's another story.

ipvsadm does accept 0 and non-0 ports for DR and TUN modes, but I guess the kernel ignores them, as you say. Most people just normally have configured the port they expect to use regardless of mode, even though the kernel only attempts to update it in NAT mode. However, it is a feature that different real servers can have different ports for NAT mode since that is one balancing method (virtual service on one port (or even a fwmark that may not care)) balancing to perhaps multiple ports on the same real server.

Anyway, I can't think of a way that would cleanly reject any cases that may be invalid or superfluous today that wouldn't still break forward and reverse compatibility with existing configurations.

**Comment by pqarmitage** [comment]
I'm currently working on some patches to:
a) Allow port 0 (or no port specified) where permissible
b) When configuring IPVS, sets the real server port to equal the virtual server port if not NAT
c) Warns of any invalid configuration (e.g. virtual server and real server port don't match and not NAT, or virtual server is a fwmark and real server port not 0 and not NAT)
d) Corrects the real server port if it is not a virtual server group.

Where the configuration is wrong (e.g. VS and RS ports don't match and not NAT), then the best thing is just to log a warning, and to correct the configuration. If strict_mode is enabled, keepalived will reject the configuration.

My testing has shown that the kernel ignores the real server port for DR and TUN modes; ipvsadm appears to silently correct (ignore) the real server port, and configure IPVS correctly.

Virtual server groups add a whole further level of complexity; at best we can warn of anything not sensible, and configure IPVS correctly.

I hope to have the patches available in the next day or so.

**Comment by sim-** [comment]
OK, I can test in a few places when you have something (building from git is easy).

Hmm, there's not much point in correcting the port if IPVS ignores it anyway, unless reporting the issue actually helps somebody see a typo that would otherwise have caused issues, no?

I'm all for validation on configuration parsing as opposed to later (we once had an outage because vrid was not validated to be <= 255, and at the time, the behaviour was to assert fail and exit when it went to transmit the packet, and the child restarted once per second, which made it look like it was functioning correctly for the other vrrp instances). But rather than trying to "fix up" something that is wrong, it probably it makes more sense to focus on ways to more flexibly leave things out of the configuration (avoid repeating) instead of trying to correct it...

**Comment by pqarmitage** [comment]
I have pushed several commits that should allow port 0, or no port, to be specified for real servers and sorry servers. They also attempt to ensure that the correct port is specified for real servers when configuring IPVS, and will log warnings if virtual and real server ports don't match when using TUN or TR.

**Comment by sim-** [comment]
Testing this seems to work as intended. I realize I was using the unused port as a "comment" in terms of helping to remember which fwmark is for which service, but oh well. It threw warnings for those services that were not set to use port 0, and it longer throws warnings with no port or port 0 specified to real_server and sorry_server under virtual_server fwmark entries.

BTW, how can I debug this new error on reload?

Keepalived_vrrp[1576]: IPVS (cmd 1163, errno 19): No such device

**Comment by pqarmitage** [comment]
Yes, these error messages are quite unhelpful; I have it on my list of things to do to translate the cmd no into a meaningful string. The cmd number is the number defined in /usr/include/linux/ip_vs.h in the section `IPVS socket operations`. IP_VS_BASE_CTL = 1152, so cmd 1163 == IP_VS_BASE_CTL + 11 == IP_VS_SO_SET_STARTDAEMON.

The error suggests that the interface specified in the `lvs_sync_daemon` configuration entry does not exist (or maybe is down).

If you find any problems with this, please open a new issue, since it is different to this issue.
