### ISSUE TITLE
vmac alongside with macvtap and on top of a net card which doesn't have an IP

### ISSUE THREAD

**Issue by kingofmeazza** [acassen/keepalived#1194]
Hello,
I have a cluster hosting VMs, and I'm using macvtap to enable host vm intercommunication. The only IP is on macvtap and the physical net card doesn't have an IP on it.
Here is my network configuration:
```
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 1000
    link/ether 08:00:27:b6:31:68 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:feb6:3168/64 scope link 
       valid_lft forever preferred_lft forever
19: macvtap0@enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 500
    link/ether 2a:4a:ea:67:40:99 brd ff:ff:ff:ff:ff:ff
    inet 10.0.208.3/20 scope global macvtap0
       valid_lft forever preferred_lft forever
    inet6 fe80::284a:eaff:fe67:4099/64 scope link 
       valid_lft forever preferred_lft forever
```
Then I set up a vrrp on top of macvtap, it works perfectly before vmac was enabled. With vmac enabled, keepalived correctly found enp0s8, the base interface of macvtap0, and created vrrp.1 on the base interface, then goes faulty. After some debugging, it shows that keepalived failed to find an available IP on the interface and set the interface faulty, which led to vrrp faulty.
Here is the configure file:
```
global_defs {
  vrrp_version 2
  vrrp_iptables KUBE-KEEPALIVED-VIP
  script_user root
  enable_script_security
}

vrrp_instance vips1 {
  state BACKUP
  interface macvtap0
  virtual_router_id 1
  priority 33
  advert_int 1
  
  use_vmac
  notify_master "/vmac_tweak.sh vrrp/1"
  
  virtual_ipaddress { 
    10.0.208.100
  }
}
```
And this is the code marks interface faulty:
```
static void
initialise_vrrp_tracking_priorities(vrrp_t *vrrp)
{
	element e;
	tracked_sc_t *tsc;
#ifdef _WITH_BFD_
	tracked_bfd_t *tbfd;
#endif

	/* If no src address has been specified, and the interface doesn't have
	 * an appropriate address, put the interface into fault state */
	 if (vrrp->saddr.ss_family == AF_UNSPEC) {
	 	vrrp->num_script_if_fault++;
	 	log_message(LOG_INFO, "miao file(%s) line(%d) iname(%s)", __FILE__, __LINE__, vrrp->iname);
	 	vrrp->state = VRRP_STATE_FAULT;
	 }
```
My question is, did I not make the configure file proper for keepalived, or is this networking layout  not supported? Is there a orthodox way for this scenrio?
Thanks in advance for any help!

BTW, there is extra information that might help. I tried to disable the code that mark the interface faulty, as below:
```
static void
initialise_vrrp_tracking_priorities(vrrp_t *vrrp)
{
	element e;
	tracked_sc_t *tsc;
#ifdef _WITH_BFD_
	tracked_bfd_t *tbfd;
#endif

	/* If no src address has been specified, and the interface doesn't have
	 * an appropriate address, put the interface into fault state */
	// if (vrrp->saddr.ss_family == AF_UNSPEC) {
	// 	vrrp->num_script_if_fault++;
	// 	log_message(LOG_INFO, "miao file(%s) line(%d) iname(%s)", __FILE__, __LINE__, vrrp->iname);
	// 	vrrp->state = VRRP_STATE_FAULT;
	// }
```
The code went on without a valid source IP, and actually sent vrrp advertisement out. The source IP of the packet is the virtual address, so I guess keepalived went MASTER at first and configured the virtual IP on vrrp.1, then the kernel automatically filled the packet with virtual IP since the source ip of the packet to be sent is 0 and virtual IP is the only IP on the interface.
The packet will fail on vrrp checksum in VRRP V3, but in V2 this looks like a workable workaround.

**Comment by pqarmitage** [comment]
There is a complication creating macvlans on macvlan or macvtap interfaces, since the kernel actually creates them on the underlying interface. Before keepalived was aware of this, it created some issues; now keepalived anticipates what the kernel will do, and in your case it adjusts the configuration so that it treats the parent interface of the macvlan as enp0s8 (if you send SIGUSR1 to the parent keepalived process and look at /tmp/keepalived.data you will see that).

The problem, as you have identified, is that keepalived cannot find a source address from enp0s8 to use as its source address. It could be argued that keepalived should use the IP address from the macvtap0 interface, and I will have a look at whether that can be done, but there are certainly complications involved with that.

For now, the easy solution for you, and it doesn't involve any code changes, is to specify
`mcast_src_ip 10.0.208.3`
in the vrrp_instance configuration block. I have just tested this and it works.

**Comment by kingofmeazza** [comment]
Thanks a lot! That seems to be the elegant solution. I'll adjust my configuration.
