### ISSUE TITLE
When using IPv6: vrrp packet too long, length 40 and expect 36

### ISSUE THREAD

**Issue by thojanssens** [acassen/keepalived#1198]
I just changed the virtual address from IPv4 to IPv6:
```
        virtual_ipaddress {
                2a14:2875:15::598c:0:1/64 dev eth0
        }
```
And since then it logs: ```vrrp packet too long, length 40 and expect 36```

Distro is CentOS 7.6.1810 (Linux 3.10.0-957.10.1.el7.x86_64 x86_64), Keepalived 2.0.14

And I don't see the IPv6 address attached to eth0 using ```ip a s dev eth0```

**Comment by pqarmitage** [comment]
I am assuming that you are using the same configuration as issue #1197, and have made the above change on one of you systems, and not the other.

I also assume that you are getting the following log entry on the system on which you have made the change:
> (Line 35) (VI_1): address family must match VRRP instance [2a14:2875:15::598c:0:1/64] - ignoring

If my assumptions are correct, the problem is that you have specified IPv4 addresses for unicast peer and unicast source ip, but you are specifying an IPv6 VIP. keepalived is correctly logging that you cannot have a mix of IPv4 and IPv6 in a vrrp instance and saying that it is ignoring the IPv6 VIP address. That means that the instance has no VIP addresses, and it is expecting to receive 0 IPv4 VIPs in an advert, hence it is expecting to receive 36 bytes. However, the other instance, which hasn't had its configuration modified, is sending 1 IPv4 VIP in an advert, and so the advert it is sending is 40 bytes long.
