### ISSUE TITLE
Is it possible to rolling update without losing request?

### ISSUE THREAD

**Issue by tamutamu** [acassen/keepalived#1206]
In the following environment, Is it possible to rolling update without losing request?

- Server A, B (installed keepalived).
- Server A(master), Sever B(backup)
- Request 100TPS.

1. It update keepalived of ServerB and restart keepalived.
1. It change master node, from ServerA to ServerB.
1. It update keepalived of ServerA and restart keepalived.

※When changed master node, Request is not lost.

**Comment by pqarmitage** [comment]
We work very hard to try and ensure that keepalived remains backwards compatible, so that newer versions will still run with older configurations. There have, however, been one or two unavoidable incompatible changes introduced, where it was found that keepalived was not operating correctly. For example, the VRRPv3 checksum was found to be being calculated incorrectly, and so this had to be changed; in order to support upgrades while running, if keepalived receives old (incorrect) checksums being used, it will fall back to the old (incorrect) checksum.

It you stop keepalived on server A, it will send a priority 0 advert, which causes a fast takeover by the backup server to master. If using VRRPv2, the down time will be (256 - priority) / 256 seconds (i.e. less that 1 second, and the higher the priority the shorter the time); if using VRRPv3 the down time will be (256 - priority) / 256 * advert interval (i.e. a fraction of 1 advert interval). In other words, if you use priorities 254 and 253 you will get faster failover times than using priorities 2 and 1). There will be no loss of data with TCP connections, due to TCP retry mechanisms; due to the small window of the fast takeover, UDP packets could be lost.

If you want to make sure that the configuration is valid with the new version of keepalived, you could run the new keepalived with the `--config-test=LOG_FILE` option before restarting the running keepalived.

The upgrade process could be:
On server B
1. Install new version of keepalived
2. Run keepalived --config-test=LOG_FILE -f CONFIG_FILE, check for any reported configuration errors, and correct them if there are any.
3. Stop and restart keepalived

Once happy, restart the process on Server A.
