### ISSUE TITLE
Is it possible to use Bridge or VEPA mode macvlan for vmac?

### ISSUE THREAD

**Issue by kingofmeazza** [acassen/keepalived#1209]
Hello,
When using vmac, it might be useful to set macvlan mode other than Private mode, so that some applications on the same host could also communicate with the virtual IP via another macvlan/macvtap interface.
Is there a technical restriction that makes keepalived support Private mode only?
Thanks in advance!

**Comment by pqarmitage** [comment]
The comment in the code says:
```
 /*
  * In private mode, macvlan will receive frames with same MAC addr
  * as configured on the interface.
  */
```

VRRP adverts have to be sent with the virtual MAC address, i.e. the MAC address that is configured on the macvlan interface. However, keepalived also needs to be able to receive adverts from other systems/devices running VRRP, and so it must be able to receive adverts that have the source address matching the MAC address of the macvlan interface.

**Comment by kingofmeazza** [comment]
Thank you for your light speed reply!
So this is because other modes refuse to accept a frame with mac address same as on the local interface, is my understanding correct?

**Comment by pqarmitage** [comment]
I have now tested macvlans using other modes, and obtained the following results:

VEPA and BRIDGE: added interfaces OK but could not receive advertisement packets
PASSTHRU: Could not set MAC address, and only one macvlan could be created per underlying interface
SOURCE: This allows keepalived to work, and for adverts to be received; presumably this means that it allows packets to be received that have a source MAC address that matches the MAC address of the macvlan interface. However, ARP resolution doesn't work unless the MAC address of the requester is in the source MAC address for the macvlan.

It appears the VEPA and BRIDGE mode will not accept frames from the same MAC address as a local interface. SOURCE mode will accept frames from the same MAC address as a local interface, and so could potentially be used. Since PASSTHRU doesn't allow the MAC address of the macvlan interface to be configured, it is of no use to us.

I will have a think about whether using source mode and specifying permitted source MAC addresses would be useful. So far as I can see it would allow a vrrp instance to be configured to work for only a specified set of MAC addresses; would this be useful to anyone?

**Comment by kingofmeazza** [comment]
The senario that I have been thinking useful was letting VMs visit VIPs on the same host, but now I understand neither BRIDGE nor VEPA works for VMAC.
I guess the need to support SOURCE mode is not so urgent, not only because its limitation on usage, but alse because SOURCE mode is a relatively new feature on Linux?

**Comment by pqarmitage** [comment]
Well, it was Linux 3.18, some 4 1/2 years ago, that SOURCE mode was introduced, and the only LTS kernel that doesn't support it is 3.16, so I think the only real issue is whether it would actually be useful to anyone to add support for SOURCE mode macvlans.
