### ISSUE TITLE
Add support to reconnect to the masterx socket

### ISSUE THREAD

**Issue by darix** [acassen/keepalived#1222]
the current situation is:

snmpd has to be running before keepalived is started, otherwise the snmp support doesn't work.
for this we now patched the service file to help systemd with the ordering:

```
Index: keepalived-2.0.15/keepalived/keepalived.service.in
===================================================================
--- keepalived-2.0.15.orig/keepalived/keepalived.service.in
+++ keepalived-2.0.15/keepalived/keepalived.service.in
@@ -1,7 +1,7 @@
 [Unit]
 Description=LVS and VRRP High Availability Monitor
-After= network-online.target syslog.target
-Wants=network-online.target
+After= network-online.target syslog.target snmpd.service
+Wants=network-online.target snmpd.service
 
 [Service]
 Type=forking
```

But strictly speaking this is not correct. because in this configuration I can restart the snmpd and afterwards the snmp support is broken. So instead of ```Wants=snmpd.service```, we would need to use ```BindsTo=snmpd.service```. But this would mean for every restart of your snmpd, the keepalived would restart as well and cause network changes.

Strictly speaking all this is just a workaround for lack of support to reconnect to the masterx socket.

**Comment by darix** [comment]
And it would also bring up the question if the After+Wants/BindsTo for the snmpd.service should also be in the upstream service file.

**Comment by pqarmitage** [comment]
I have just started keepalived without snmpd running, and after half a minute started snmpd, and I had the following log entries:
> Wed Apr 17 15:57:05 2019: Warning: Failed to connect to the agentx master agent ([NIL]): 
Wed Apr 17 15:57:20 2019: Warning: Failed to connect to the agentx master agent ([NIL]): 
Wed Apr 17 15:57:35 2019: NET-SNMP version 5.7.3 AgentX subagent connected

and I can successfully run snmpwalk.

Also, stopping snmpd and restarting it while keepalived is running works, with keepalived reconnection to AgentX.

Can you provide more details of what you are doing, along with a copy of your configuration, the output of `keepalived -v` and the keepalived log entries, so that we can try and understand what is happening.

**Comment by darix** [comment]
hmm ... so I just didnt wait long enough for it to reconnect in my tests?

**Comment by pqarmitage** [comment]
For me it attempts to reconnect every 15 seconds. I don't think that is configurable.

**Comment by darix** [comment]
confirmed. so it was really just my impatience. Adding ```After=snmpd.service``` does not harm though.

**Comment by pqarmitage** [comment]
Commit 3c67401 adds snmpd.service as suggested above if keepalived is built with snmp enabled.
