### ISSUE TITLE
Parent interface replies to ICMP-requests sent to MACVLAN

### ISSUE THREAD

**Issue by MikhaylovOA** [acassen/keepalived#1230]
## Describe the bug
When trying to ping virtual address (192.168.0.10) ICMP-request is being sent to MACVLAN interface, but I get ICMP-reply from parent interface (eth0).

### Configure keepalived.conf with use_vlan parameter:

vrrp_sync_group 0 {
  group {
    eth0_51
  }
}
vrrp_instance eth0_51 {
  interface eth0
  virtual_ipaddress {
    192.168.0.10/24
  }
  priority 100
  advert_int 3
  virtual_router_id 51
  use_vmac
  vmac_xmit_base
  notify_master "/usr/local/bin/vmac_tweak.sh 51"
}

### vmac_tweak.sh:

#!/bin/bash
sysctl -w net.ipv4.conf.vrrp/$1.arp_filter=0
sysctl -w net.ipv4.conf.vrrp/$1.accept_local=1
sysctl -w net.ipv4.conf.vrrp/$1.rp_filter=0
exit 0

### Configure sysctl parameters in /etc/sysctl.conf (as described here: https://github.com/acassen/keepalived/blob/master/doc/NOTE_vrrp_vmac.txt):

#my params
net.ipv4.conf.all.arp_ignore=1
net.ipv4.conf.all.arp_announce=1
net.ipv4.conf.all.arp_filter=0
net.ipv4.conf.eth0.arp_filter=1

## Expected behavior
ICMP-replies are expected to have MACVLAN source address.

## Keepalived version
Output of `keepalived -v`

Keepalived v2.0.15 (04/04,2019), git commit v2.0.14-53-g9de2817c+

Copyright(C) 2001-2019 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.9.144
Running on Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2+st1 (2018-11-16)

configure options: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --enable-dbus --enable-log-file --enable-snmp-vrrp --enable-snmp --enable-sha1 --enable-snmp-rfcv2 --enable-snmp-rfcv3 --enable-json --with-init=systemd build_alias=x86_64-linux-gnu CFLAGS=-g -O2 -fdebug-prefix-map=/root/build/keepalived/keepalived-2.0.15=. -fstack-protector-strong -Wformat -Werror=format-security LDFLAGS=-Wl,-z,relro CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2

Config options:  LIBIPTC LIBIPSET_DYNAMIC LVS VRRP VRRP_AUTH JSON OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 DBUS FILE_LOGGING LOG_FILE_APPEND EINTR_CHECK

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV RTA_VIA FRA_OIFNAME IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPSET_PRE_V7 NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK

## Distro:
 - Name Debian
 - Version 9
 - x86_64

## System Log entries
In attachment.
[tmp_logs_vmac.txt](https://github.com/acassen/keepalived/files/3098224/tmp_logs_vmac.txt)

**Comment by pqarmitage** [comment]
Unfortunately NOTE_vrrp_vmac.txt is somewhat out of date. keepalived nowadays sets the relevant sysctl options itself, so it is worth trying this without using vmac_tweak.sh. I have updated NOTE_vrrp_vmac.txt to reflect this.

When you say you are getting responses to the ping from the parent interface, I assume you are looking at the source MAC address of the ICMP echo reply.

I assume that you have an address 192.168.0.x/24 configured on eth0. If you execute `ip route show` when keepalived is master, you will probable see route entries something like:
> 192.168.0.0/24 dev eth0 proto kernel scope link src 192.168.0.101 
192.168.0.0/24 dev vrrp.51 proto kernel scope link src 192.168.0.10 

This is saying that the system can route to 192.168.0.x/24 via eth0 or vrrp.51, and it chooses eth0 to send the reply, and hence uses its MAC address.

If you delete the 192.168.0.x/24 address from eth0, then the system replies using the MAC address of the MACVLAN.

In order to ensure that the replies are sent with the MAC address of the MACVLAN interface, you could add something like the following to your configuration:
```
global_defs {
    dynamic_interfaces
}
```
and in the vrrp_instance block
```
	virtual_rules {
		from 192.168.0.10/32 to 192.168.0.0/24 table 100
	}
	virtual_routes {
		192.168.0.0/24 dev vrrp.51 src 192.168.0.10 table 100
	}
```
I need to update the code to allow the vmac interface to be specified in virtual routes without needing to specify dynamic_interfaces, but for now, dynamic_interfaces needs to be specified.

**Comment by MikhaylovOA** [comment]
Thank you!
It works for me.
