### ISSUE TITLE
vrrp_startup_delay not handle delay for track_interface

### ISSUE THREAD

**Issue by michael2009** [acassen/keepalived#1254]
Set keepalived.conf

global_defs {
    vrrp_startup_delay 3
}
    nopreempt
    state BACKUP
    virtual_router_id 100
    track_interface {
            eth2
    }

Put eth2 to down , Run keepalived then VRRP come FAULT immediately. 

2019-05-05 11:50:13 local0.info Keepalived_vrrp[10819]:  Assigned address 1.2.2.1 for interface eth1
2019-05-05 11:50:13 local0.info Keepalived_vrrp[10819]:  (Srv01) entering FAULT state
2019-05-05 11:50:13 local0.info Keepalived_vrrp[10819]:  Registering gratuitous ARP shared channel
2019-05-05 11:50:13 local0.info Keepalived_vrrp[10819]:  Delaying startup for 3 seconds
2019-05-05 11:50:13 local0.info Keepalived_vrrp[10819]:  Deassigned address 1.1.2.1 from interface eth2
2019-05-05 11:50:16 local0.info Keepalived_vrrp[10819]:  VRRP sockpool: [ifindex(3), family(IPv4), proto(112), unicast(0), fd(11,12)]
2019-05-05 11:50:19 local0.info Keepalived_vrrp[10819]:  VRRP_Script(sync_config) succeeded

**Comment by pqarmitage** [comment]
I don't believe that what you have shown above is a bug, as you have stated in #1143. The original issue (#1143) reported the following:
>This causes an unnecessary election, which is practically immediately won by the old master, but it's still annoying.
>
>Can I do anything to make it stop happening?

caused by interfaces at boot time starting to pass traffic, then stopping for a while before starting again.

Commit 5c7a7d7 added `vrrp_startup_delay` in order to delay vrrp instances running the vrrp protocol (i.e. delaying the startup of running the vrrp protocol) for the time specified, thereby stopping a system while booting taking over as master and sending adverts because it wasn't receiving traffic.

The scenario you appear to have is that keepalived is starting up when an interface is down. keepalived is correctly identifying that the interface is down, and so it transitions to the fault state. While in the fault state, the vrrp instance cannot send adverts and so the problem identified in issue #1143 cannot occur.

I am not clear why a vrrp instance transitioning to fault state when an interface it is tracking is down should be a problem. The vrrp instance will remain dormant until the interface comes up.

If you have a specific problem relating to starting keepalived when interfaces are in a fault state, then I think you have two options:
1. Run keepalived from a scripts that checks for when the required interfaces are up, and then it starts keepalived
2. Provide a detailed description of the problem the current behaviour is causing, why you think the problem is applicable to others too, and what needs to be done to resolve the problem. If we believe that the problem has general applicability, then we will attempt to resolve it.

**Comment by michael2009** [comment]
Beucase interface bootup delay 3-5 sec , Then i had test with script to delay start keepalived. Solved
Thanks
