### ISSUE TITLE
False positive when trying to detect shebang

### ISSUE THREAD

**Issue by chr4** [acassen/keepalived#1266]
**Describe the bug**

The following error appears in the logs:

```
Error: Please add a #! shebang to script myscript.sh
```

The script has a `#!/bin/sh` shebang and `file` detects them as `POSIX shell script, ASCII text executable`.

I suppose this is a false positive of the magic library?

[Refrence code section](https://github.com/acassen/keepalived/blob/ef48b007a04c1f4b874709bcb85bb4a232cb3d3b/lib/notify.c#L913)

**Expected behavior**

Shebang is correctly recognized

**Keepalived version**

`v2.0.16-11-g1b96509+` (worked fine with `2.0.15`)

**Distro (please complete the following information):**
 - Name Ubuntu
 - Version 18.04
 - Architecture  x86_64

**Did keepalived coredump?**

No.

**Comment by pqarmitage** [comment]
This issue is caused by magic_file() returning `ASCII text` on 18.04 whereas on 16.04 with the same snap, magic_file() returns `POSIX shell script, ASCII text executable`, which is correct.

Running the same code on 18.04 but not built as a snap doesn't exhibit the problem, so this appears to be an issue with snaps rather than an issue with keepalived.

I have raised the issue with Canonical and hope to get a response next week.

**Comment by mahomedh** [comment]
Hi. Was there ever any response to this? Still appears to be an issue on `Ubuntu 19.10` with `Keepalived v2.0.20`

**Comment by 4ltieres** [comment]
Hi, we're facing the same issue here, using keepalived v2.1.2 as snap on Debian 10.4.

**Comment by pqarmitage** [comment]
Commit 4d4f4e4 resolves the problem. The environment variable MAGIC needed to be set to point to the magic data file in the snap itself rather than it picking up the default which was the host system's magic data file.

The updated snaps are now available in the beta and edge channels at snapcraft.io.
