### ISSUE TITLE
Updated keepalived.conf.SYNOPSIS with latest changes

### ISSUE THREAD

**Issue by kustodian** [acassen/keepalived#131]
Since the documentation for keepalived is mostly outdated, it would be really nice if the `keepalived.conf.SYNOPSIS` is up to date with the latest changes. If it is already up to date, then all is good and close this, but I guess it is outdated, since for protocol it says `Only TCP is implemented`, but UDP works as well.

**Comment by pqarmitage** [comment]
Commit 2761edb updated the SYNOPSIS file to add that UDP is supported (and also added SCTP support). The SYNOPSIS file is gradually coming up to date, but the keepalived.conf(5) man page at doc/man/man5/keepalived.conf.5 should be fully up to date, since that is installed as part of the keepalived package installation.
