### ISSUE TITLE
Keepalived track_script is not proper

### ISSUE THREAD

**Issue by narasago** [acassen/keepalived#1371]
**Describe the bug**
The keepalived status doesn't get back to normal when the track_script fails and the failure is rectified

**To Reproduce**
Add any track_script to keepalived.conf, make it fail and correct the failure. The keepalived logs will stay say that the script is failing.

**Expected behavior**
Once the reason for failure is corrected, the track_script execution by the keepalived should be successful and proper messages should be logged.

**Keepalived version**
Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2

** Configuration of keepalived **
! Configuration File for keepalived

vrrp_script chk_service {           # Requires keepalived-1.3.5
    script "killall -0 keepalived"  # cheaper than pidof
    interval 2                      # check every 2 seconds
    weight 2                       # add 2 points of prio if OK
}

vrrp_script chk_nginx {
   script "/usr/libexec/keepalived/chk_nginx.sh"
   interval 2                      # check every 2 seconds
   weight 2                       # add 2 points of prio if OK
}

vrrp_instance VI_16 {
    interface eth2
    track_interface {
      eth1
      eth2
    }
	track_script {
       chk_service
       chk_nginx
    }
    virtual_router_id 16
    garp_master_delay 5
    priority 180
    advert_int 2
    virtual_ipaddress {
       10.32.136.123 dev eth2
       172.16.4.250 dev eth1
       2019:2019::fffb dev eth1
       2a00:8a00:4000:20c::89:118 dev eth2
    }
    notify_master "/usr/libexec/keepalived/insert_vip_egress_neo.sh 10.32.136.123,eth2 2a00:8a00:4000:20c::89:118,eth2"
    notify_backup "/usr/libexec/keepalived/delete_vip_egress_neo.sh 10.32.136.123,eth2 2a00:8a00:4000:20c::89:118,eth2"
    notify_fault "/usr/libexec/keepalived/delete_vip_egress_neo.sh 10.32.136.123,eth2 2a00:8a00:4000:20c::89:118,eth2"
    nopreempt
}

** Track script **
#!/bin/bash

function usage {
    echo "Usage: $0 [-c <path to nginx.conf>] [-pid-file <nginx pid file>] [-d|-debug]"
    return 0
}

unset RELEASE NAME

DEBUG=0
ICP=citm-ingress-controller

while [ ! $# = 0 ]
do
    case ${1/#--/-} in
        -name-space)
            shift
            NS=$1
            ;;
        -d|-debug)
            DEBUG=1
            ;;
        -release)
            shift
            RELEASE=$1
            ;;
        -full-pod-name)
            shift
            NAME=$1
            ;;
        -help|*)
            usage
            exit 0
            ;;
    esac
    shift
done

if [ ! -z "${RELEASE:-}" ]
then
    PODL=$(kubectl get pods | awk '{print $1}' | grep "^${RELEASE}-citm-ingress-controller-")
else
    PODL=$(kubectl get pods | awk '{print $1}' | grep "\-citm-ingress-controller-")
fi

#RC=0
for P in $PODL
do
    kubectl exec $P /ingress-controller/check_nginx.sh >/dev/null 2>&1
    RRC=$?
    [ $DEBUG = 1 ] && echo "Checking $P. RC=$RRC"
    [ $RRC != 0 ] && RC=1
done
[ $DEBUG = 1 ] && echo "nginx ingress controller status: $RC"
exit $RC

**Comment by pqarmitage** [comment]
Unfortunately we are unable to do anything with this issue report without a copy of your keepalived configuration file, and the track script. Although you appear to have used the bug template for reporting this issue, there are several items of information requested that have not been provided; please provide all the missing information.

The version of keepalived is very old, and it may well be that in the intervening 30 releases this problem has been resolved.

**Comment by narasago** [comment]
@pqarmitage I have added the configuration as well as the script that is used for tracking. When the scipt is executed manually the RC is 0. But, when keepalived is used, the RC is not 0. Because of this the IPs will not switched over.

**Comment by pqarmitage** [comment]
What is the purpose of script `chk_service`? If the script is being run then keepalived must be running, and so it will always be successful.

I am assuming that it is the chk_nginx script that is failing, although you don't say so. The script you have posted above does not initialise RC (the initialisation line is commented out). Since DEBUG is initialised to 0 and the chk_nginx.sh script is not run with the `-d` option, the line
`[ $DEBUG = 1 ] && echo "..."`
has an exit status of 1. `exit $RC` is then called, but since $RC is not set, this amounts to just calling `exit` which exits with the status of the last command executed, which is 1.
It may well be in the environment when you run chk_nginx.sh manually RC is set (or you run it with the -d option).

Track_scripts do work, and the status does return to normal following rectification of the failure, so if something is still not working, then it will either be the script not working as expected, or an edge case with keepalived.

If you continue to have problems, please upgrade to v2.0.18 to see if that resolves your problem before reporting further issues.
