### ISSUE TITLE
Keepalived pics up link local address on dual stack interface

### ISSUE THREAD

**Issue by johannbg** [acassen/keepalived#1419]
**Describe the bug**

Not sure if a bug or pebcak issue but better to mentioned it. 

**To Reproduce**

Create a systemd networkd file /etc/systemd/network/10-wired.network
[Match]
Name=enp1s0

[Network]
Domains=<your-domain>
DNS=<your-ipv4-dns01> <your-ipv4-dns02> 
DNS=<your-ipv6-dns01> <your-ipv6-dns02 >
Address=<your-ipv4-address>
Address=<your-ipv6-address>
Gateway=<your-ipv4-gw>
Gateway=<your-ipv6-gw>

[Route]
Gateway=<your-ipv4-address>
Gateway=<your-ipv6-address>

run systemctl restart systemd-networkd

Configure keepalive 

Expected behavior...
Keepalived_vrrp[748]: Assigned address <the-configure-ipv4-address> for interface enp1s0
Keepalived_vrrp[748]: Assigned address <the-configured-ipv6-address> for interface enp1s0

Reality...
Keepalived_vrrp[748]: Assigned address <the-ipv4-address> for interface enp1s0
Keepalived_vrrp[748]: Assigned address fe80::X:X:fX:X for interface enp1s0

**Distro (please complete the following information):**
 Fedora 30 + x86_64/keepalived-2.0.11+ 

Workaround is simply to disabling the link local creation by adding LinkLocalAddressing=no in the [Network] section of the systemd-networkd network file and adding net.ipv6.conf.enp1s0.autoconf=0 to /etc/sysctl.d/30-keepalived.conf and reboot then keepalived correctly picks up the configured ipv6 address since there is not link local address ;)

Disabling the link local creation might be someone one is supposed to do and hence just close this report if not there is the workaround until the issue is resolved.

A sample sysctl.d snippet with the relevant keepalived sysctl relevant kernel parameters set or disable against current upstream kernel/keepalived would probably help alot.

**Comment by pqarmitage** [comment]
@johannbg From looking at the code (keepalived/vrrp/vrrp.c around line 2140), there should always be an address printed between `address` and `for` in the messages above. If you are getting messages without an address, then that would be a bug (it might be that that is something that has been fixed since keepalived v2.0.11 - I am using v2.0.19).

I'm not clear why you don't want keepalived to use the IPv6 link local address of an interface. The VRRP RFC (RFC5798) states in section 1.6: _Primary IP Address ... In IPv6, the link-local address of the interface over which the packet is transmitted is used._ This is the address used for sending adverts.

If you wish not to use the first link local address on an interface as the source address for VRRP adverts, then you can use the `mcast_src_ip` option to specify the source address to use (but it has to be an address configured on the interface).

If you could confirm that this answers your issue, then we can close this.

**Comment by johannbg** [comment]
Yeah just close this
