### ISSUE TITLE
RPORT error in version v2.0.19

### ISSUE THREAD

**Issue by onioner** [acassen/keepalived#1431]
Hi,
There is an error about real port. In the v2.0.19, ipvsadm displays real port is 0, but I configured the real port to 80 or 443, and it seems to be working normally.

```ipvsadm -Ln``` displays infos like this, the real port is 0.
```
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
FWM  3 wrr
  -> 10.0.88.214:0              Local   1      0          0
  -> 10.0.88.215:0              Route   1      0          0
FWM  7 wrr
  -> 10.0.88.214:0              Local   1      0          0
  -> 10.0.88.215:0              Route   1      0          0
```
This is the log when keepalived starts.
[keepalived.log](https://github.com/acassen/keepalived/files/3831148/keepalived.log)

This is keepalived.conf
```
vrrp_script chk {
    script "/etc/keepalived/checkPort.sh"
    interval 2
    weight -10
    fall 2
    rise 2
}

vrrp_instance VI_1 {
    state BACKUP
    interface bond0
    virtual_router_id 93
    priority 99
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass ec6Zf2goL8
    }
    virtual_ipaddress {
        10.0.88.254
    }
    track_script {
        chk
    }
}

virtual_server fwmark 3 {
    delay_loop 3
    lb_algo wrr
    lb_kind DR
    persistence_timeout 0
    protocol TCP

    real_server 10.0.88.214 443 {
        weight 1
        SSL_GET {
            url {
                path /up.do
                status_code 200
            }
            connect_timeout 3
        }
    }

    real_server 10.0.88.215 443 {
        weight 1
        SSL_GET {
        url {
                path /up.do
                status_code 200
            }
            connect_timeout 3
        }
    }
}

virtual_server fwmark 7 {
    delay_loop 3
    lb_algo wrr
    lb_kind DR
    persistence_timeout 0
    protocol TCP

    real_server 10.0.88.214 80 {
        weight 1
        HTTP_GET {
            url {
                path /up.do
                status_code 200
            }
            connect_timeout 3
        }
    }

    real_server 10.0.88.215 80 {
        weight 1
        HTTP_GET {
        url {
                path /up.do
                status_code 200
            }
            connect_timeout 3
        }
    }
}
```
Environment:
version: v2.0.19
OS: CentOS 6.8 x64
Kernel: 2.6.32-642.el6.x86_64

Thanks in advance!

**Comment by pqarmitage** [comment]
The syslog output that keepalived writes for your configuration is:
```
(Line 34) number '0' outside range [1, 4294967295]
(Line 34) persistence_timeout invalid
(Line 64) number '0' outside range [1, 4294967295]
(Line 64) persistence_timeout invalid
Warning: Virtual server FWM 3: protocol specified for fwmark - protocol will be ignored
WARNING - fwmark virtual server FWM 3, real server [10.0.88.214]:tcp:443 has port specified - clearing 
WARNING - fwmark virtual server FWM 3, real server [10.0.88.215]:tcp:443 has port specified - clearing 
Warning: Virtual server FWM 7: protocol specified for fwmark - protocol will be ignored
WARNING - fwmark virtual server FWM 7, real server [10.0.88.214]:tcp:80 has port specified - clearing 
WARNING - fwmark virtual server FWM 7, real server [10.0.88.215]:tcp:80 has port specified - clearing 
```
so you have a number of errors which ought to be corrected.

The persistence_timeout errors are self explanatory.

`protocol specified for fwmark - protocol will be ignored` means that the protocol option cannot be used with a fwmark (look at how virtual servers are configured with ipvsadm, it is either `--tcp-service`, `--udp-service`, `--sctp-service` or `--fwmark-service`).

The `fwmark virtual server FWM 3, real server [10.0.88.214]:tcp:443 has port specified - clearing` warning, which is what your question is about, is because the destination port cannot be changed when using tunneling or direct routing forwarding methods (see the --real-server section in the ipvsadm man page). If you want to change the port you must use the NAT forwarding method.

It is quite possible when using ipvsadm to specify the real server port when using TUN or DR forwarding methods, and the ipvsadm -Ln output shows the port. However, this is confusing since the real server port is ignored for TUN and DR. Rather than continue this confusion when using keepalived, commit fcd3efa added logging warnings if TUN and DR destination ports don't match the virtual server port, or if fwmark is being used and the real server has a port specified.

The comment with the commit was
```
    Log warnings if real server and virtual server ports don't match
    
    This commit adds logging warnings if virtual and real server ports,
    when using TUN or DR, don't match.
    
    It also sets the real server ports to be the same as the virtual server
    ports.  Although listing the IPVS configuration with ipvsadm will look
    different, the kernel ignored the port of a real server when using DR
    or TUN, so the behaviour isn't changed, but when looking at the
    configuration it now shows what is actually happening.
```

So, for example, if you used iptables of nftables to mark a tcp packet with destination port **80** with fwmark 3,  the kernel would forward it to 10.0.88.214 or 10.0.88.215 with destination port **80**, and not to port **443** which your configuration suggests. keepalived behaving as it does means that commit fcd3efa has done its job, because it has made you ask what is happening.
