### ISSUE TITLE
>=keepalived-2.0.19: cannot configure with --disable-dbus --disable-dbus-create-instance

### ISSUE THREAD

**Issue by hydrapolic** [acassen/keepalived#1443]
````
keepalived-2.0.19 $ ./configure --disable-dbus --disable-dbus-create-instance
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether make sets $(MAKE)... (cached) yes
checking for ranlib... ranlib
checking for grep that handles long lines and -e... /bin/grep
checking whether ln -s works... yes
checking for a sed that does not truncate output... /bin/sed
checking for strip... strip
checking for ldd... ldd
checking for ar... ar
checking the archiver (ar) interface... ar
configure: error: enable-dbus-create-instance requires enable-dbus
````

Same for git master.

**Comment by pqarmitage** [comment]
The error message might not be very helpful, but if dbus is disabled it doesn't make sense to disable dbus-create-instance since there is no dbus functionality enabled. Just configure with --disable-dbus without the --disable-dbus-create-instance. Furthermore, the default is for dbus to be disabled (configure --help shows an --enable-dbus option rather than a --disable-dbus option), so there is no need to specify --disable-dbus at all.

**Comment by hydrapolic** [comment]
@pqarmitage 

This is how we do it in Gentoo Linux:
https://github.com/gentoo/gentoo/blob/master/sys-cluster/keepalived/keepalived-2.0.18.ebuild#L48

You can configure whether you want dbus support in which case we call --enable-dbus --enable-dbus-create-instance, otherwise (default) we call --disable-dbus --disable-dbus-create-instance. It worked for 2.0.18, but it fails for 2.0.19.

**Comment by pqarmitage** [comment]
I would strongly advise against using --enable-dbus-create-instance. It doesn't create a vrrp instance (for one thing it doesn't even allow the specification of virtual ip addresses); all it does is create a DBus object. When the original DBus patch was submitted it included the DBus create instance functionality without creating the vrrp instance and so I didn't think it the functionality should be included since it doesn't create a VRRP instance. My recollection is that the original submitter of the patch didn't want the create instance facility removed, and so I added conditional compilation around it so that it would not be enabled by default.

I think your best solution is to remove dbus-create-instance from your ebuild file since it is misleading, and no-one can be using it to do what it suggests it does, i.e. create a VRRP instance. Alternatively, it should be specified as a separate option so that it isn't enabled by default whenever dbus is enabled.

It looks to me as though you will have a similar problem if regex is disabled, since if parent options are disabled (e.g. regex), then sub-options cannot be specified. The reason for this is to reduce the likelihood of someone manually accidentally misconfiguring their build. So if `disable-regex` is specified, then the use of `disable-regex-timers` is not allowed. However, the use of `regex-timers` is really a debugging aid, and it shouldn't automatically be enabled just because `regex` is enabled.

`enable-snmp` enables `snmp-vrrp` and `snmp-checker`, and so the `snmp-vrrp` and `snmp-checker` options are superfluous and should be removed. `enable-snmp-rfc` enables `snmp-rfc-v2` and `snmp-rfc-v3` and so `snmp-rfc-v2` and `snmp-rfc-v3` are superfluous and should be removed also. That just leaves `enable-snmp` and `enable-snmp-rfc`, and these are independent of each other.

**Comment by hydrapolic** [comment]
Thanks for the feedback, I'll try to accommodate the ebuild based on your suggestions.
