### ISSUE TITLE
>=keepalived-2.0.19: fails to build with debug

### ISSUE THREAD

**Issue by hydrapolic** [acassen/keepalived#1444]
````
./configure --enable-debug

...

Keepalived configuration
------------------------
Keepalived version       : 2.0.19
Compiler                 : gcc
Preprocessor flags       : -D_GNU_SOURCE -I/usr/include/libnl3
Compiler flags           : -g -g -O2 -Wall -Wextra -Wunused -Wstrict-prototypes -Wabsolute-value -Waddress-of-packed-member -Walloca -Walloc-zero -Warray-bounds=2 -Wattribute-alias -Wbad-function-cast -Wcast-align -Wcast-qual -Wdate-time -Wdisabled-optimization -Wdouble-promotion -Wduplicated-branches -Wduplicated-cond -Wfloat-conversion -Wfloat-equal -Wformat-overflow -Wformat-security -Wformat-signedness -Wformat-truncation -Wframe-larger-than=5120 -Wimplicit-fallthrough=3 -Winit-self -Winline -Wjump-misses-init -Wlogical-op -Wmissing-declarations -Wmissing-field-initializers -Wmissing-prototypes -Wnested-externs -Wnormalized -Wnull-dereference -Wold-style-definition -Woverlength-strings -Wpointer-arith -Wredundant-decls -Wshadow -Wshift-overflow=2 -Wstack-protector -Wstrict-overflow=4 -Wstrict-prototypes -Wstringop-overflow=2 -Wsuggest-attribute=cold -Wsuggest-attribute=const -Wsuggest-attribute=format -Wsuggest-attribute=malloc -Wsuggest-attribute=noreturn -Wsuggest-attribute=pure -Wsync-nand -Wtrampolines -Wundef -Wuninitialized -Wunknown-pragmas -Wunsuffixed-float-constants -Wunused-const-variable=2 -Wunused-macros -Wvariadic-macros -Wwrite-strings -fPIE -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -O2
Linker flags             : -pie -Wl,-z,relro -Wl,-z,now
Extra Lib                : -lm -lcrypto -lssl -lnl-genl-3 -lnl-3 -lmagic -lip4tc -lip6tc
Use IPVS Framework       : Yes
IPVS use libnl           : Yes
IPVS syncd attributes    : Yes
IPVS 64 bit stats        : Yes
HTTP_GET regex support   : No
fwmark socket support    : Yes
Use VRRP Framework       : Yes
Use VRRP VMAC            : Yes
Use VRRP authentication  : Yes
With ip rules/routes     : Yes
With track_process       : Yes
With linkbeat            : Yes
Use BFD Framework        : No
SNMP vrrp support        : No
SNMP checker support     : No
SNMP RFCv2 support       : No
SNMP RFCv3 support       : No
DBUS support             : No
SHA1 support             : No
Use JSON output          : No
libnl version            : 3
Use IPv4 devconf         : Yes
Use iptables             : Yes
Use libiptc              : Yes
Use libipset             : No
Use nftables             : No
init type                : undetected
Strict config checks     : No
Build genhash            : Yes
Build documentation      : Yes
Use Debug flags          : Yes

*** WARNING --enable-debug is only for debugging purposes and isn't expected to work properly

...

  CC       vrrp_ip_rule_route_parser.o
  CC       vrrp_firewall.o
  CC       vrrp_iptables.o
  CC       vrrp_iptables_lib.o
  CC       vrrp_iptables_calls.o
  AR       libvrrp.a
make[2]: Leaving directory '/tmp/keepalived/keepalived-master/keepalived/vrrp'
Making all in check
make[2]: Entering directory '/tmp/keepalived/keepalived-master/keepalived/check'
  CC       check_daemon.o
check_daemon.c: In function 'start_check.constprop':
check_daemon.c:295:59: warning: null pointer dereference [-Wnull-dereference]
  295 |       (!global_data->lvs_process_name != !prev_global_data->lvs_process_name ||
      |                                           ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
  CC       check_data.o
  CC       check_parser.o
  CC       check_api.o
  CC       check_tcp.o
  CC       check_http.o
In file included from ./../include/check_data.h:42,
                 from ./../include/check_api.h:35,
                 from check_http.c:39:
check_http.c: In function 'http_request_thread':
check_http.c:1524:35: error: 'url' undeclared (first use in this function); did you mean '_url'?
 1524 |  DBG("Processing url(%s) of %s.", url->path, FMT_CHK(checker));
      |                                   ^~~
../../lib/utils.h:45:57: note: in definition of macro 'DBG'
   45 | #define DBG(fmt, msg...) log_message(LOG_DEBUG, fmt, ## msg)
      |                                                         ^~~
check_http.c:1524:35: note: each undeclared identifier is reported only once for each function it appears in
 1524 |  DBG("Processing url(%s) of %s.", url->path, FMT_CHK(checker));
      |                                   ^~~
../../lib/utils.h:45:57: note: in definition of macro 'DBG'
   45 | #define DBG(fmt, msg...) log_message(LOG_DEBUG, fmt, ## msg)
      |                                                         ^~~
make[2]: *** [Makefile:389: check_http.o] Error 1
make[2]: Leaving directory '/tmp/keepalived/keepalived-master/keepalived/check'
make[1]: *** [Makefile:593: all-recursive] Error 1
make[1]: Leaving directory '/tmp/keepalived/keepalived-master/keepalived'
make: *** [Makefile:429: all-recursive] Error 1
````

Same with git master.

**Comment by pqarmitage** [comment]
@hydrapolic I see you have updated the keepalived .ebuild file to remove enabling debug. That is what I would have suggested, since its only use is for debugging, and as the configure output says:
`*** WARNING --enable-debug is only for debugging purposes and isn't expected to work properly`
It hasn't been used for a long time, and hence hasn't been maintained.

The problem with the `--enable-debug` option is that it doesn't fork child processes for the vrrp, bfd,  and ipvs/checker processes, and runs all the functionality in one process. However, there are certain functions whose behaviour depends on whether they are the vrrp, checker, bfd process, and that cannot work when all the functionality is running in a single process.

It appears that since v2.0.15 keepalived has not built with the `--enable-debug` option. I'm in two minds whether we should fix building with `--enable-debug`, leave it to the next person who wants to use it to fix it, or remove it entirely. I'll talk to Alexandre Cassen to see what he thinks.

**Comment by hydrapolic** [comment]
There are times when users run into problems and will want a debug build (it's disabled by default of course). However I think https://github.com/pqarmitage/keepalived/commit/28869ea8f3136529179031c6f955c7c08d52df27#diff-39269721f1e29bd6955a1d739079c611R225 will make it harder for us because then we'll have to pass --enable-debug and also patch/sed core/main.c to build with debugging. I think it's enough if it's disabled by default and can be enabled via ./configure --enable-debug. 

We want users to have a smooth experience:
by default: emerge sys-cluster/keepalived
having trouble?: USE="debug" emerge sys-cluster/keepalived

**Comment by pqarmitage** [comment]
@hydrapolic I have to confess to not understanding how the .ebuild file works. It looked to me as though the --enable-debug option was always enabled, was I correct in that assumption/guess? It is absolutely imperative that the main build of keepalived is without --enable-debug, for the reasons set out above, i.e. it doesn't work properly, if at all. It also significantly alters the behaviour of keepalived, and so is not really useful in debugging.

There are now much better debugging options available at configure time, and these can be selectively enabled at runtime, and if a separate debug build is wanted, it is probably these options that should be used.

The configure debug options are:
```
--enable-smtp-alert-debug
--enable-epoll-debug
--enable-epoll-thread-dump
--enable-timer-check
--enable-netlink-timers
--enable-regex-debug
--enable-tsm-debug
--enable-regex-timers
--enable-vrrp-fd-debug
--enable-asserts
--enable-eintr-debug
--enable-network-timestamp
--enable-track-process-debug
--enable-parser-debug
--enable-dump-keywords
```

To check for memory leaks (creates files /tmp/Keepalived_mem.PID.log, /tmp/Keepalived_mem_vrrp.PID.log etc)
`--enable-mem-check`

For performance analysis
`--enable-perf`

Some options to make debugging easier
`--disable-hardening --disable-optimise`

Since some of the debugging options create large volumes of output, it is better not to log via syslog, but rather log directly to files. The following configure option enables this runtime option.
`--enable-log-file`
The runtime options are `-g/PATH_TO_LOG_FILES`, `-G` and `--flush-log-file`
If `-g/tmp/keepalived.log` is specified, log files /tmp/keepalived.log, /tmp/keepalived_vrrp.log, /tmp/keepalived_check.log and /tmp/keepalived_bfd.log are created. `-G` stops logging via syslog, and `--flush-log-files` causes the log files to be written unbuffered.

The runtime options to selectively turn on debugging are:
```
     --perf[=PERF_TYPE]       Collect perf data, PERF_TYPE=all, run(default) or end
     --debug[=...]            Enable debug options. p, b, c, v specify parent, bfd, checker and vrrp processes
                                   T - timer debug
                                   M - email alert debug
                                   E - epoll debug
                                   D - epoll thread dump debug
                                   F - vrrp fd dump debug
                                   R - regex debug
                                   X - regex timers
                                   S - TSM debug
                                   N - netlink timer debug
                                   P - network timestamp debug
                                   O - track process debug
                                   A - track process debug with extra detail
                                   C - parser (config) debug
                                   K - dump keywords
                                 Example --debug=TpMEvcp
```
as displayed in the `keepalived -h` output.

Perhaps `--enable-debug` should be changed to enable all the above options rather than what it does now. @hydrapolic What do you think?

**Comment by hydrapolic** [comment]
Lets look at version 2.0.18 in Gentoo:
````
IUSE="+bfd dbus debug -json regex snmp"

	econf \
		--with-init=custom \
		--with-kernel-dir=/usr \
		--enable-sha1 \
		--enable-vrrp \
		$(use_enable bfd) \
		$(use_enable debug) \
````

This means, that if you don't do anything special an just fire the basic install command like `emerge sys-cluster/keepalived`, then we call this:
````	
	./configure \
		--with-init=custom \
		--with-kernel-dir=/usr \
		--enable-sha1 \
		--enable-vrrp \
		--enable-bfd \
		--disable-debug) \
````

Yeah, it probably means we also have to enable all those features if you do `USE=debug emerge sys-cluster/keepalived` (this triggers --enable-debug for configure). Or you may hide all those debug options behind a single --enable-debug ;)

**Comment by pqarmitage** [comment]
@hydrapolic I have taken you point at https://github.com/acassen/keepalived/issues/1444#issuecomment-557475383 and removed the #error. The option to make keepalived run as a single process is now `--enable-one-process-debug`. The remaining functionality that was enabled by `--enable-debug` is now separated out into individual configure and runtime debug options.

Commit 844e197 implements the above, and also `--enable-debug` now enables all debug options except `--enable-one-process-debug` and `--enable-genhash-debug`. It also enables `--enable-log-file` so that when debugging log output can, if specifed to keepalived at runtime, be written to specific files rather than to syslog. With `--enable-debug` the default functionality of keepalived is not altered compared to when `--enable-debug` is not specified, but the various debugging functionality can be turned on at runtime.

It is now safe for you to re-enable the `--enable-debug` option in the keepalived .ebuild file, but I would strongly advise against building a debug version with `--enable-one-process-debug`.

With many apologies for any problems I may have caused by going down the wrong track initially, and I hope this solution works for you.

**Comment by hydrapolic** [comment]
Many thanks. I'll adjust it like this for the next version: 
- normally we will just call --disable-debug since we hope everything will work fine :)
- if a user wants a debug build, we will call --enable-debug --enable-one-process-debug --enable-genhash-debug

The second variant will have to be explicitly enabled by the user, it will be disabled by default.

Thanks for your help and suggestions!

**Comment by pqarmitage** [comment]
I really would encourage you not to use `--enable-one-process-debug` since it doesn't help with debugging and since it probably won't even work properly it will mean that your debug build almost certainly won't be usable.

Also because keepalived will behave quite differently if it does work at all, it will be counter productive to debugging. I have never used it for debugging because it make things behave too differently from normal, whereas without it keepalived will behave as normal but with the debugging options enabled.

I will test it later with `--enable-one-process-debug` and confirm the results.

**Comment by hydrapolic** [comment]
Ok, so for debug we will use ``--enable-debug --enable-genhash-debug``

**Comment by pqarmitage** [comment]
Many thanks for that.

I have just found one bit of debug output that was enabled by default if have been included when keepalived was built, so I need to push another commit to resolve that.

**Comment by pqarmitage** [comment]
Commit 14c835d  is now merged.

**Comment by hydrapolic** [comment]
Thank you
