### ISSUE TITLE
Keepalived does not manipulate the IPVS Subsystem

### ISSUE THREAD

**Issue by romulus010689** [acassen/keepalived#1446]
**Describe the bug**
Running Debian 10, Buster, keepalived starts perfectly and applied the configuration to the IPVS subsystem. However it seems that the process is not able to manipulate this in any way, if healthchecks are failing, the node is not removed from the virtual_server, if I comment out a real_server and reload as well as restart keepalived, this server is not removed from the real_server block.

I only found this errormessage in the log, no other errors are there:
Nov 22 10:18:36 lb1 Keepalived[2486]:   Please report a bug at https://github.com/acassen/keepalived/issues
Nov 22 10:18:36 lb1 Keepalived[2486]:   and include this log from when keepalived started, a description
Nov 22 10:18:36 lb1 Keepalived[2486]:   Also provide the output of keepalived -v, what Linux distro and version
Nov 22 10:18:36 lb1 Keepalived[2486]:   you are running on, and whether keepalived is being run in a container or VM.
Nov 22 10:18:36 lb1 kernel: [78716.738643] keepalived[2487]: segfault at 0 ip 000055e0bd4227f2 sp 00007fff22c96328 error 4 in keepalived[55e0bd3c3000+62000]
Nov 22 10:18:36 lb1 Keepalived[2486]:   Command line: '/usr/sbin/keepalived' '--dont-fork'
Nov 22 10:18:36 lb1 Keepalived[2486]:                      -fdebug-prefix-map=/build/keepalived-8agDac/keepalived-2.0.10=.

**To Reproduce**
Upgraded the keepalived system from a debian 7, to 8, 9 and now 10. With the keepalived version from the official repo. We are only using Direct routeing and different LB algos (rr, wrr and wlc), it happens with all of them.

**Expected behavior**
If I manipulate the config and reload or restart keepalived the ipvs subsystem should be updated, additionally if the healthchecks for a real_server are failing, those servers should also be removed.
**Keepalived version**
Output of `keepalived -v`

**Distro (please complete the following information):**
 - Name Debian 10
 - Version 10
 - Architecture x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
We are running on hardware machines here.

**Configuration file:**
it is an much to big configuration to past it here, spreaded over around 60 files..

**Notify and track scripts**
only have the healthcheckers check_http and check_nrpe from nagios project. And we are using tcp healthchecks.

**System Log entries**
Nov 22 10:17:36 lb1 Keepalived[2486]: Command line: '/usr/sbin/keepalived' '--dont-fork'
Nov 22 10:17:36 lb1 Keepalived[2486]: Opening file '/etc/keepalived/keepalived.conf'.
Nov 22 10:17:36 lb1 Keepalived[2486]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived[2486]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived[2486]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived[2486]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived[2486]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived[2486]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived[2486]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived[2486]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived[2486]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived[2486]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived[2486]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived_healthcheckers[2487]: Opening file '/etc/keepalived/keepalived.conf'.
Nov 22 10:17:36 lb1 Keepalived_healthcheckers[2487]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived_healthcheckers[2487]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived_healthcheckers[2487]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived_healthcheckers[2487]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived_healthcheckers[2487]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived_healthcheckers[2487]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived_healthcheckers[2487]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived_healthcheckers[2487]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived_vrrp[2488]: Opening file '/etc/keepalived/keepalived.conf'.
Nov 22 10:17:36 lb1 Keepalived_healthcheckers[2487]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived_vrrp[2488]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived_healthcheckers[2487]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived_healthcheckers[2487]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived_vrrp[2488]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived_vrrp[2488]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived_vrrp[2488]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived_vrrp[2488]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived_vrrp[2488]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived_vrrp[2488]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived_vrrp[2488]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived_vrrp[2488]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived_vrrp[2488]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived_vrrp[2488]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:17:36 lb1 Keepalived_healthcheckers[2487]: WARNING - default user 'keepalived_script' for script execution does not exist - please create.
Nov 22 10:18:36 lb1 Keepalived[2486]:   Please report a bug at https://github.com/acassen/keepalived/issues
Nov 22 10:18:36 lb1 Keepalived[2486]:   and include this log from when keepalived started, a description
Nov 22 10:18:36 lb1 Keepalived[2486]:   Also provide the output of keepalived -v, what Linux distro and version
Nov 22 10:18:36 lb1 Keepalived[2486]:   you are running on, and whether keepalived is being run in a container or VM.
Nov 22 10:18:36 lb1 kernel: [78716.738643] keepalived[2487]: segfault at 0 ip 000055e0bd4227f2 sp 00007fff22c96328 error 4 in keepalived[55e0bd3c3000+62000]
Nov 22 10:18:36 lb1 Keepalived[2486]:   Command line: '/usr/sbin/keepalived' '--dont-fork'
Nov 22 10:18:36 lb1 Keepalived[2486]:                      -fdebug-prefix-map=/build/keepalived-8agDac/keepalived-2.0.10=.
Nov 22 10:18:36 lb1 Keepalived_healthcheckers[2768]: Opening file '/etc/keepalived/keepalived.conf'.
Nov 22 10:18:36 lb1 Keepalived_healthcheckers[2768]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:18:36 lb1 Keepalived_healthcheckers[2768]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:18:36 lb1 Keepalived_healthcheckers[2768]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:18:36 lb1 Keepalived_healthcheckers[2768]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:18:36 lb1 Keepalived_healthcheckers[2768]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:18:36 lb1 Keepalived_healthcheckers[2768]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:18:36 lb1 Keepalived_healthcheckers[2768]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:18:36 lb1 Keepalived_healthcheckers[2768]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:18:36 lb1 Keepalived_healthcheckers[2768]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:18:36 lb1 Keepalived_healthcheckers[2768]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:18:36 lb1 Keepalived_healthcheckers[2768]: Opening file '/etc/keepalived/prio.conf'.
Nov 22 10:18:36 lb1 Keepalived_healthcheckers[2768]: WARNING - default user 'keepalived_script' for script execution does not exist - please create.
Nov 22 10:19:44 lb1 keepalived[2486]: double free or corruption (fasttop)
Nov 22 10:19:48 lb1 keepalived[2486]: double free or corruption (fasttop)
Nov 22 10:19:48 lb1 systemd[1]: keepalived.service: Main process exited, code=killed, status=6/ABRT
Nov 22 10:19:48 lb1 systemd[1]: keepalived.service: Failed with result 'signal'.
**Did keepalived coredump?**
If so, can you please provide a stacktrace from the coredump, using gdb.

**Comment by romulus010689** [comment]
An additional hint, I found out, that this strange behaviour of not cleaning up the IPVS configurations after keepalived is stoppen only appears if I control the daemon via systemd! If I start the deamon via Console, everything is fine and working well!

**Comment by romulus010689** [comment]
A bit more information on that:
If the Keepalived process ends up with this message on termination:

Fri Nov 22 12:10:42 2019: checker process failed to die - forcing termination

Then the IPVS is not cleaned up.

**Comment by pqarmitage** [comment]
@romulus010689 I'm happy to look at this, but further information is needed in order to know what we are looking at.

Could you please provide the following:
1. Output of `keepalived -v`. Please note that we only provide patches to the HEAD of the master branch, and so the latest version of keepalived that you have tested against should be used.
2. The full set of configuration files that you are using; without these it simply is not possible to attempt to reproduce the problem. The easiest way to include the configuration files when there are a large number of them is to create a compressed tar file of them and attach the file to a comment here. From your logs however, it appears that only two configuration files are being used - keepalived.conf and prio.conf.
3. You refer to the check_http and check_nrpe checkers from the nagios project. Can you please either post then here or post links to them.

The reason that the IPVS configuration isn't being cleared is due to the keepalived healthchecker process segfaulting before it manages to clear the old configuration. A new healthchecker process is started, but since the configuration file has been updated it doesn't know what the old configuration was, and so cannot clear it.

There is also an issue of the parent keepalived process reporting that the healthchecker child process has not terminated which means that it has taken more than 5 seconds (default) for the healthchecker process to exit after it was requested to exit.

The message `keepalived[2486]: double free or corruption (fasttop)` is interesting too, since we don't tend to see that.

**Comment by romulus010689** [comment]
Hi @pqarmitage,

Here the Information you requested:

root@lb1:# keepalived -v
Keepalived v2.0.10 (11/12,2018)

Copyright(C) 2001-2018 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.18.20
Running on Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20)

configure options: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --with-kernel-dir=debian/ --enable-snmp --enable-sha1 --enable-snmp-rfcv2 --enable-snmp-rfcv3 --enable-dbus --enable-dbus-create-instance --enable-json --enable-bfd build_alias=x86_64-linux-gnu CFLAGS=-g -O2 -fdebug-prefix-map=/build/keepalived-8agDac/keepalived-2.0.10=. -fstack-protector-strong -Wformat -Werror=format-security LDFLAGS=-Wl,-z,relro CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2

Config options:  LIBIPSET_DYNAMIC LVS VRRP VRRP_AUTH JSON BFD OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 DBUS DBUS_CREATE_INSTANCE

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPSET_PRE_V7 LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK

I've attached a tar archive containing the anonymized configuration and the used check scripts.

An additional hint, I compiled keepalive 1.4.5 now for buster and its working smoothly.

Thanks for your help!
[keepalived-conf.tar.gz](https://github.com/acassen/keepalived/files/3879711/keepalived-conf.tar.gz)

**Comment by pqarmitage** [comment]
First of all I will comment on some issues that I found in the configuration files, and then I will comment on the issues reported.

Configuration issues
--------------------------

There appear to be three errors in the configuration files:

1. The include conf.d/\*.conf and include conf.d/cloud/\*.conf statements in /etc/keepalived/keepalived.conf are not working. Paths need to be specified as absolute paths from the root directory, since keepalived does a `cwd("/")`, and so all paths are from /. There is a shortcut to this in newer versions of keepalived by using ${_PWD}. ${_PWD} expands to the directory of the config file that is currently being read, so when reading /etc/keepalived/keepalived.conf, ${_PWD} is /etc/keepalived. So the lines at the end of keepalived.conf become:
```
include ${_PWD}/conf.d/*.conf

include ${_PWD}/conf.d/cloud/*.conf
```
You could also change all lines:
` include /etc/keepalived/prio.conf`
to
` include ${_PWD}/prio.conf`
It would then still work if all the configuration files were moved to a different path.

The above issue explains why in your logs above only keepalived.conf and prio.conf are being read, and none of the conf.d/\*.conf or conf.d/cloud/\*.conf are being read (there are no log entries referring to these files being opened); this means that none of the IPVS configuration is loaded.

2. anon20.conf is missing a } at the end. This appears to stop any of the checker or vrrp configuration being processed (I can't remember if this is intentional or not). Old versions of keepalived, e.g. v1.4.5, would ignore the missing } and still load the configuration, more up to date versions of keepalived log the error, since there have been considerable improvements in the parser.

3. anon2.conf: the port of virtual_server 123.123.123.123 443 and the ports of the real servers don't match, and with lb_kind DR they must match. Only with lb_kind NAT can the port be different. Recent versions of keepalived log an error and correct the port; older versions configure the port specified but the kernel ignores it.

Issues reported
--------------------
At Nov 22 10:18:36 the keepalived_healthchecker process segfaulted. That means that any ipvs configuration that keepalived had configured before the segfault will probably remain. When keepalived starts again (if it is a version that detects the missing }), it will not have any ipvs configuration, and so it will leave the old configuration. Any further modifications to the configuration (that don't correct the missing }) will not result in keepalived seeing a different configuration, and so it will not update the ipvs configuration.

There are other issues I have discovered, such as when reloading after starting keepalived with the
includes in keepalived.conf finding files, but at the reload no include files are found, then the ipvs configuration does not get cleared, and when keepalived terminates the healthchecker process segfaults.

Next actions
----------------
1. I will try and find out what keepalived is doing with the bad configuration and sort it out.

2. @romulus010689 Could you please correct your configuration files and try this again, using v2.0.10 (or preferably v2.0.19) and see if you still get the problems.

Configuration simplification/improvements
-----------------------------------------------------
1. Remove `state MASTER` from all the vrrp instances. You don't want the lower priority instances trying to start as master (although they won't!).

2. The system that you have reported the problems from is lb1. Assuming the other system you are using is lb2, you could simplify your VRRP configuration as follows:

Near the top of keepalived.conf, add the following lines:
```
@lb1 $PRIORITY=150
@lb2 $PRIORITY=100   # I don't know what priority you use on lb2, but set it accordingly here
```
The above sets the $PRIORITY variable to 150 if the system id is lb1, and to 100 if the system id is lb2.

In all the vrrp instances, change every line:
` include /etc/keepalived/prio.conf`
to
` priority $PRIORITY`
You will then be able to use the same configuration files on lb1 and lb2 without needing to even have a different prio.conf file.

**Comment by pqarmitage** [comment]
I have found and fixed two issues in the code.

1. If there was an error when parsing the configuration due to a missing } or an extra { the vrrp and checker processes would skip the vrrp and IPVS configuration. Commit d58dc78 now clears the parser state flags each time before the configuration is read, and so the configuration is now successfully read, even when there is a missing }.

2. When using ha_suspend, after a reload an old pointer was not cleared or re-established. This mean that when keepalived subsequently terminated it tried using the stale pointer, and often segfaulted. It also meant that after a reload the ha_suspend functionality would no longer work. Commit 251c39e resolves this issue.

These two fixes, along with fixing your configuration about, should resolve all the issues you have identified.

Since you have a relatively large number of virtual servers and real servers, you may want to add
`lvs_flush_onstop VS`
to the global_defs section of your config. This will speed up the shutdown of the checker process, since it skips explicitly removing the real servers, and just removes the virtual servers, which removes their real servers anyway.

If nothing else is setting any IPVS configuration, you can use
`lvs_flush_onstop`
which simply flushes the entire IPVS configuration when keepalived stops. This is quicker still, but will remove all IPVS configuration, including that set up by anything other than keepalived.
