### ISSUE TITLE
To view all the Master/Backup devices connected

### ISSUE THREAD

**Issue by Vnktvshl** [acassen/keepalived#1458]
Hi..Thanks in advance for the help.
I am new to keepalived . I would like to know if there is some command or some other way which will help to view all the devices connected in the bridge.

****Setup Details****
I have connected 3 of my laptops with keepalived running.
Version using :- Keepalived v1.2.24 (02/14,2019)

1)Is there a command to view the list of devices which are engaged as backup in detail.
2)Is there any table formed for the cause of election processes before selection.If so where is this table stored in the code?

Could you please add an enhancement for the same...

Thank you.

**Comment by pqarmitage** [comment]
`1)Is there a command to view the list of devices which are engaged as backup in detail.`
It is not possible for either the master or backup instances to know what backup instances are running. This is because backup instances remain silent on the network, so there is no network traffic to detect their presence.
There are a couple of ways you could view the state:
1. Use snmp to monitor keepalived. If you use the proprietary MIB, the keepalived processes will report when they are in backup state. The RFC compliant MIBs unfortunately do not report backup state.
2. Collect and process notify FIFO output (v1.2.24 is too old to support notify_fifo). Collecting this sort of information via notify scripts is not reliable, since you cannot guarantee the sequence of scripts running. You would need to write a notify_fifo script to forward all the information to a central point which could then report the status.

`2)Is there any table formed for the cause of election processes before selection.If so where is this table stored in the code?`
As described above, no keepalived instance can know of the existence of VRRP instances in backup state, so no, there is no table stored. The only place when currently the information is available centrally is via SNMP.

`Could you please add an enhancement for the same...`
Since this information is already available via SNMP, it does not seem appropriate to add a proprietary way of doing this, especially since it could not work with VRRP instances which are not keepalived.

The notify_fifo feature allows someone to write scripts to centralise the state information and could build a table. If someone produced such scripts, I am sure we would be happy to add them to the source code.

I would strongly recommend that you upgrade from v1.2.24 to a recent version, such as v2.0.19; v1.2.24 is very old and there have been many enhancements, bug fixes and security fixes since v1.2.24 was released.

**Comment by Vnktvshl** [comment]
Thank you very much for your reply in a very short span of time.

**Comment by Vnktvshl** [comment]
Hi pqarmitage ,

I have one more doubt about this. Let's take a scenario. If there is a failure of the Master Router, then there must be an election. Now I would like to know how all routers which have the same virtual id's are contesting in the election.In some point they are elected, right? At that time they must know all the devices present in for the election and we will come to know all the devices present in the same bridge.If this is not, how does election occur.

Thank you for your help.

**Comment by pqarmitage** [comment]
@Vnktvshl For a full explanation of how the election process works see the VRRP RFC [RFC5798](https://tools.ietf.org/html/rfc5798).

In summary, backup routers run timers which are reset each time they receive an advert, so they all reset the timers at the same time. It is upon expiration of the timer that a router will take over as master. The timer is `(3 * Master_Adver_Interval) + Skew_time` where Skew_time is `((256 - priority) * Master_Adver_Interval) / 256`. So the backup router with the highest priority times out first, sends an advert and becomes master. None of the other (lower priority) backup routers send an advert, so no-one knows about them.

**Comment by Vnktvshl** [comment]
Thank you...I had got an idea for proceeding.

**Comment by pqarmitage** [comment]
@Vnktvshl Once you have sorted out your idea it would be good if you could share it here, and we'll look to see if we can include it in the source code.

**Comment by Vnktvshl** [comment]
Hi @pqarmitage 
I will surely come back to u once I am done with some way to sort out this. I have come out with one more doubt. This may sound little fishy or even the way I understood may be wrong.

**Configuration file**
vrrp_instance haproxy_web_ips {
    state BACKUP
        nopreempt
        interface wlp2s0
        virtual_router_id 40
        priority 194
        advert_int 10
        authentication {
            auth_type PASS
            auth_pass 1234
        }
        virtual_ipaddress {
            192.168.20.100
        }

This is been the configuration file in both the devices running keepalived. Now once the master device fails. As per your explanation is given in the above.

The timer is (3 * Master_Adver_Interval) + Skew_time where Skew_time is ((256 - priority) * Master_Adver_Interval) / 256. So the backup router with the highest priority times out first sends an advert and becomes master.

If I have understood rightly. It must take minimum 6 seconds for the next transition to of master state. But in my case, it takes merely 3 seconds. I even changed and saw the interval to 10 . Still, it took just 7 seconds.

Could you please help me to sort out this. Which is lingering my mind for the past 3 days?

**Comment by pqarmitage** [comment]
There is a difference between the master device failing and the master device shutting down.

As stated above, if a backup device doesn't receive an advert for `(3 * Master_Adver_Interval) + Skew_time` where Skew_time is ((256 - priority) * Master_Adver_Interval) / 256` (VRRPv3), or `(256 - priority) / priority` (VRRPv2) seconds after the last advert it received, it will take over as master and send an advert.

There is an alternative scenario though. When a master device shuts down (i.e. when keepalived terminates normally), it sends an advert with priority 0, which means that it is shutting down. The backup devices then wait for Skew_time to elapse (i.e. without the 3 * Advert_Interval) before timing out to become master. This allows for faster takeover by a new master when the old master goes down in a controlled way. For VRRPv2 this should be within 1 second, for VRRPv3 it should be within one advert interval. You are using VRRPv2, since not only is it the default, but authentication only works with VRRPv2.

The above is what SHOULD happen. However, if you are still using keepalived v1.2.24 then backup routers will wait one extra advert interval before taking over as master (`Entering MASTER STATE` in log). This extra advert interval delay was removed quite some time ago, but I cannot remember in which version of keepalived.

I'm not sure why you are seeing the delays of 3 seconds and 7 seconds. What I experience with v1.2.24 is what I have described above, including the extra advert interval delay.

You state that the configuration above is what is used in both devices. You should have a different priority in each device, otherwise, at least with 3 or more devices, you won't reliably get the same behaviour after a failure.

**Comment by Vnktvshl** [comment]
Thank u @pqarmitage 
I had some issues in the configuration file actually.

Can I get some input on Gratuitous ARP the way it updates the switches about the device mac and how does it update if its in different VLANs?

**Comment by pqarmitage** [comment]
A gratuitous ARP message tells any end system that is listening that the advertised IP address can be reached via the specified MAC address.

With regard to switches, a switch uses ARP messages differently from end systems; it uses the ARP message to learn which port a MAC address is on, so that when it needs to forward a packet to the destination MAC address, it can then send it only on the required interface, rather than on all interfaces (which is what a hub does).

Regarding VLANs, if a switch receives a packet on a VLAN, it will only send the packet on the same VLAN. The decision of which port to send it on is as described in the previous paragraph.

I'm not sure what you mean by `how does it update if its in different VLANs`.

**Comment by Vnktvshl** [comment]
Thank you ...
My question is like as of my knowledge...
The GARP reaches the client and client maintains a table regarding the Mac (CAM) Table...
The case am exploring is Now Am having two VLANs and two different routers which is connected to the switch.
So therefore there are two different Virtual Ip provided.Inter vlan routing is enabled.

Vlan 1:- Router 1 :- 192.168.1.10
             Router 2 :- 192.168.1.11
               VIP:-192.168.1.100
Vlan 2:-  R1:-192.168.2.10
              R2:-192.168.2.11
               VIP:-192.168.2.100

When inter-VLAN routing is activated. We must be able to ping clients from vlan1 to vlan2.In this case how does the clients get updated with  the ARP table is my query. 

Does the switch/Router maintains the ARP table or only the client does?

**Comment by pqarmitage** [comment]
A switch and a router have different needs.

A switch only needs to know the physical port to use for each MAC address. A router needs to know the MAC address for each local IP address, and so has to maintain an ARP table in the same way as a client.

**Comment by Vnktvshl** [comment]
Thank you very much for being so informative...
