### ISSUE TITLE
track_script doesn’t work when running in a container

### ISSUE THREAD

**Issue by jirutka** [acassen/keepalived#1469]
**Describe the bug**

track_script doesn’t work when running in a container, keepalived logs:

    Failed to set/clear process event listen - errno 111 - Connection refused

I found one relevant SO topic about the issue with using netlink inside a namespace: https://stackoverflow.com/questions/35987286/sendmsg-to-netlink-fails-with-econnrefused-if-application-is-running-in-lxc-cont/36786152

**Keepalived version**
v2.0.16

**Distro (please complete the following information):**
- Alpine Linux
- v3.10
- x86_64 
 
**Details of any containerisation or hosted service (e.g. AWS)**
Running in a privileged LXC container, the host system is SUSE Linux Enterprise Server 15.1. 

**Configuration file:**

```
global_defs {
	enable_script_security
	script_user nobody
	vrrp_version 3
}

vrrp_track_process check_nginx_proc {
	process "nginx"
	quorum 3
	fork_delay 2
	terminate_delay 1
}

vrrp_instance vi_ipv4 {
	interface eth0
	state MASTER
	virtual_router_id 42
	priority 150
	track_process {
		check_nginx_proc
	}
	virtual_ipaddress {
		1.2.3.4/24 dev eth1
	}
	virtual_routes {
		default via 1.2.3.1 dev eth1
	}
}
```

**System Log entries**

```
Dec 21 11:53:33 test-1 daemon.info Keepalived[9608]: Starting Keepalived v2.0.16 (06/02,2019)
Dec 21 11:53:33 test-1 daemon.info Keepalived[9608]: WARNING - keepalived was build for newer Linux 4.19.36, running on Linux 4.12.14-197.26-default #1 SMP Wed Nov 6 13:59:49 UTC 2019 (493622b)
Dec 21 11:53:33 test-1 daemon.info Keepalived[9608]: Command line: '/usr/sbin/keepalived' '--dont-fork' '--use-file=/etc/keepalived/keepalived.conf'
Dec 21 11:53:33 test-1 daemon.info Keepalived[9608]:               '--config-id=master'
Dec 21 11:53:33 test-1 daemon.info Keepalived[9608]: Opening file '/etc/keepalived/keepalived.conf'.
Dec 21 11:53:33 test-1 daemon.info Keepalived[9608]: Starting VRRP child process, pid=9615
Dec 21 11:53:33 test-1 local1.info Keepalived_vrrp[9615]: Registering Kernel netlink reflector
Dec 21 11:53:33 test-1 local1.info Keepalived_vrrp[9615]: Registering Kernel netlink command channel
Dec 21 11:53:33 test-1 local1.info Keepalived_vrrp[9615]: Opening file '/etc/keepalived/keepalived.conf'.
Dec 21 11:53:33 test-1 local1.info Keepalived_vrrp[9615]: Failed to set/clear process event listen - errno 111 - Connection refused
Dec 21 11:53:33 test-1 local1.info Keepalived_vrrp[9615]: (vi_ipv4) entering FAULT state
Dec 21 11:53:33 test-1 local1.info Keepalived_vrrp[9615]: Registering gratuitous ARP shared channel
```

**Did keepalived coredump?**
No.

**Comment by pqarmitage** [comment]
The key log entry is:
`Failed to set/clear process event listen - errno 111 - Connection refused`
This appears to be a kernel issue with using CN_PROC in a container, as is also identified in the stackoverflow link you included above..

See https://github.com/moby/moby/issues/30176 for further discussion.

I note that there is also the a warning logged - `WARNING - keepalived was build for newer Linux 4.19.36, running on Linux 4.12.14-197.26-default #1 SMP Wed Nov 6 13:59:49 UTC 2019 (493622b)`. This can cause problems and you should try and ensure the keepalived is running on a kernel on newer that the kernel headers used when keepalived was built.

I don' use containers, but I will see if I set up a container environment to try and understand this problem better.

**Comment by pqarmitage** [comment]
I have now built a docker image using the updated Dockerfile from commit e49f14c. The container environment matches yours:
-    Alpine Linux
-    v3.10
-    x86_64
but the host environment is Fedora 28, which has a 5.0.16 kernel and I am using the latest keepalived code (v2.0.19+).

Running keepalived in that environment I have discovered that keepalived works fine if I run docker with `--net=host`, but if I don't run with that option then I get the error
`Failed to set/clear process event listen - errno 111 - Connection refused`.

However, if I run without `--net=host` but add `--pid=host` then again I don't get the problem.

So it appears that in order for the process events connector to work, it needs to have at least one namespace the same as the host's. Since there are ways of docker running the container process without the error with the process events connector, I think we can conclude that the problem does not lie with keepalived, but either with the kernel or docker.

Are you running nginx in the same container as keepalived, or in the host in in another container? I can't test this with nginx in another container and using the `--pid=container:<name|id>` docker option, so I don't know if that will work.

**Comment by pqarmitage** [comment]
@jirutka Can we close this issue now?

**Comment by pqarmitage** [comment]
Closing due to no response for over a fortnight. If there is still a problem this issue can be re-opened.

**Comment by shaba** [comment]
I have the same bug inside systemd-nspawn.
```
Failed to set/clear process event listen - errno 111 - Connection refused
```
Exist any workaround?

**Comment by pqarmitage** [comment]
It would appear that the container does not allow writing to an event connector socket.

The man page for systemd-nspawn states "In many ways it is similar to chroot(1), but more powerful since it fully virtualizes the file system hierarchy, as well as the process tree ...". Since the process tree is virtualized, i.e. the container has its own PID namespace, is using keepalived's track_process going to achieve anything?

It might be worth trying running the container with `--capability=all` and seeing if that resolves your problem. If so, then it will be a matter of elimination to work out which capability/capabilities are needed to make it work (and it would be helpful if this issue could be updated with the results of that).

**Comment by shaba** [comment]
Usually, docker is app container with one process and track_process not relevant for docker. Or docker should can access to all PID namespace.
But lxc/lxd and systemd-nspawn OS container with many processes.
I am use keepalived(vrrp)+conntractd+bird for "virtual" firewall+router with HA in one OS-level container systemd-nspawn (in one PID namespace). Obviously  track_process should see running bird in one PID namespace.

Run with  "--capability=all" is first thing i tried. 
Unsuccessfully.

PS: keepalived-2.2.4, kernel-5.10.90, systemd-249.7

**Comment by pqarmitage** [comment]
I think the key error message is the one before the message quoted above, i.e.
`Failed to bind to process monitoring socket - errno 1 - Operation not permitted`

If you look at the articles referenced in [comment 1](https://github.com/acassen/keepalived/issues/1469#issue-541314064) and [comment 2](https://github.com/acassen/keepalived/issues/1469#issuecomment-574395954) you should see that this is a kernel issue.

There is a comment in keepalived_main: `If we want to monitor processes, we have to do it before calling setns() ...`. Unfortunately, running keepalived in a container means that setns() has already been called before keepalived has started, and so it track_process won't work.

https://marc.info/?l=linux-netdev&m=150810725403605&w=2 is also interesting for some details about why, from the kernel perspective, it doesn't work.

If you could file a kernel bug for this, and I think you would need to give some justification for why you need it since Eric Biederman didn't seem keen to get it working in namespaces, then that would be very helpful.
