### ISSUE TITLE
Package managers latest version

### ISSUE THREAD

**Issue by clwluvw** [acassen/keepalived#1473]
Hi. Why Keepalived latest version isn't in package managers like `apt`?

**Comment by pqarmitage** [comment]
@clwlucw I am not clear what your question means. Fedora/RedHat/Centos have keepalived available to install via `dnf install keepalived`, Ubuntu/Debian can install keepalived via `apt-get install keepalived` (although snaps provide more up to date versions).

Could you please explain what you are wanting to do that isn't working for you.

**Comment by clwluvw** [comment]
@pqarmitage I wanted to install Keepalived from Ubuntu repository but the available version for that was Keepalived 1.3.9 that has some bugs and I can't use it. Won't you update Keepalived for Ubuntu repositories?

**Comment by pqarmitage** [comment]
@clwluvw As upstream, we do not build the packages for the individual distros; the distros themselves are responsible for building their packages. If you want the distro to build a more recent version, the best thing to do is to file a bug on their bug tracking system asking them to update to a recent version.

However, since you are using Ubuntu, the way to go is to use the snapped version of keepalived, and we do manage the snap setup. The latest/stable version is 36 commits after v2.0.19, and the edge version is the latest version in the master branch.
