### ISSUE TITLE
failover

### ISSUE THREAD

**Issue by yohan212** [acassen/keepalived#1521]
Hello everyone,

I have some trouble today ! 
I have 4 servers for a futur kubernetes cluster, but anyway..
I have 3 masters, master1-2-3
Master 1 is the master for the loadbalancing. 
if I shutdown ok kill the keepalived daemon, master2 become the master. 
So everything is working.
But if I don't halt or kill the daemon but just shutdown the interface of master 1, the master 2 never become master :/
So do you have some idea ? 

thanks a lot

**Comment by pqarmitage** [comment]
Does shutting down the interface on master 1 cause the interface on master 2 to go down?

Does shutting down the interface on master 1 cause the vrrp instance on master 1 to go to fault state, or does it continue sending adverts?

What happens if you add an iptable rule on master 1 to stop the vrrp adverts being sent?

**Comment by yohan212** [comment]
Hello, 
thx for your response !

1) nope
2) If I shutdown the interface on master1, nothing change when I do systemctl keepalived status, or in /var/log/messages
3) how can I check if the master1 send vrrp request, only with tcpdump ? or via a specific log directory ?

**Comment by yohan212** [comment]
If I shutdown the interface with ifdown on master1 the packet are also sent when I do a tcpdump. But if I shut the interface in my VMware settings, the master2 come up directly !

**Comment by yohan212** [comment]
<img width="533" alt="image" src="https://user-images.githubusercontent.com/61455325/76834160-f36bcf00-682c-11ea-90c0-c8a876724cad.png">

**Comment by pqarmitage** [comment]
I appears that doing ifdown does not cause the interface to stop operating, and that explains why master 2 does not take over as master. You have also confirmed that keepalived is operating correctly when you shutdown the interface in your VMWare settings.

I think this issue must be put down to a mis-expectation of what happens when you use ifdown.
