### ISSUE TITLE
Notify script should not mkfifo

### ISSUE THREAD

**Issue by reinderien** [acassen/keepalived#1524]
This:

https://github.com/acassen/keepalived/blob/f0f31557ead9dd12343e5d9613a6e5fcdedf33aa/doc/samples/sample_notify_fifo.sh#L47

should not be calling `mkfifo`, since this code:

https://github.com/acassen/keepalived/blob/dfdf8f22af7af0f481730f210c54de86744a846e/lib/notify.c#L235

will always create it beforehand.

**Comment by pqarmitage** [comment]
Many thanks for reporting this. However, if you look at the full block of code from which the second extract above is taken, you will see that it handles the FIFO already existing:
https://github.com/acassen/keepalived/blob/dfdf8f22af7af0f481730f210c54de86744a846e/lib/notify.c#L235-L245
It is therefore quite reasonable for a script that handles reading the FIFO to create the FIFO before keepalived is run. In fact, it would be much harder to code the script if it didn't create the FIFO.

When keepalived terminates, if it successfully created the FIFO it will remove it; if the FIFO already existed it does not remove it.

**Comment by reinderien** [comment]
> script that handles reading the FIFO to create the FIFO before keepalived is run

For my understanding: under what circumstances would a notify script start before keepalived itself?

**Comment by pqarmitage** [comment]
You may want to have a process that continuously reads the FIFO (or indeed multiple FIFOs) and takes appropriate actions. In this case, it may be better if the script/process starts independently of keepalived, creates the FIFO(s) and waits on a read of the FIFO(s).

The alternative, as I think you have realised, is that keepalived creates the FIFOs and then executes the FIFO script.

Either way is supported, so that different users can choose which way they want to handle the FIFOs.
