### ISSUE TITLE
Is there a way to make node with highest IP address to NOT takeover as master from the the current master?

### ISSUE THREAD

**Issue by senthilnathann** [acassen/keepalived#1528]
**Describe the issue**
A clear and concise description of what the issue is.

We have set nopreempt and priorities are equal on VRRP nodes . We faced split brain issue ,due to this , Slave took over as master as master's advt didn't reach slave. Slave send garp for the VIPs.Once the master is back to n/w, slave received higher prio. So the slave entered into backup state. So updated GARP not available in N/W  and faced outage .

It's due highest IP address is keep on MASTER ( as per RFC rules ) .

Is there a way to make node with highest IP address to NOT takeover as master from the the current master?

**To Reproduce**
Any steps necessary to reproduce the behaviour:

**Expected behavior**

**Keepalived version**
Output of `keepalived -v`

Keepalived v2.0.7 (08/23,2018)

**Distro (please complete the following information):**
 - Name [e.g. Fedora, Ubuntu]
 - Version [e.g. 29]
 - Architecture [e.g. x86_64]

CentOS 7.4.1708
x86_64
**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details

**Configuration file:**
A full copy of the configuration file, obfuscated if necessary to protect passwords and IP addresses
BACKUP SERVER : 
global_defs {
        notification_email {
                xxxxx
        }
        notification_email_from xxxxx
        smtp_server 192.168.100.16
        smtp_connect_timeout 30
        router_id LVSID01
}
vrrp_instance VI_1 {
        priority 100
        interface bond0
        virtual_router_id 90
        nopreempt
        advert_int 1
        authentication {
                auth_type xxxx
                auth_pass xxxxx
        }
        virtual_ipaddress {
                172.20.131.115
                172.20.31.90
                172.20.31.92
        }
}
=====================
MASTER SERVER:
 global_defs {
        notification_email {
                xxxxx
        }
        notification_email_from xxxxx
        smtp_server 192.168.100.16
        smtp_connect_timeout 30
        router_id LVSID01
}
vrrp_instance VI_1 {
        priority 100
        interface bond0
        virtual_router_id 90
        advert_int 1
        authentication {
                auth_type xxxx
                auth_pass xxxxx
        }
        virtual_ipaddress {
                172.20.131.115
                172.20.31.90
                172.20.31.92
        }
}

**Notify and track scripts**
If any notify or track scripts are in use, please provide copies of them

**System Log entries**
Full keepalived system log entries from when keepalived started

Backup Server LOGS : 
Once split brain issue resolved : 

Mar 31 01:50:40 l3-newversion-1 Keepalived_vrrp[18241]: (VI_1) Master received advert from 172.20.131.114 with same priority 100 but higher IP address than ours
Mar 31 01:50:40 l3-newversion-1 Keepalived_vrrp[18241]: (VI_1) Entering BACKUP STATE
Mar 31 01:50:40 l3-newversion-1 Keepalived_vrrp[18241]: (VI_1) removing VIPs.

**Did keepalived coredump?**
If so, can you please provide a stacktrace from the coredump, using gdb.

**Additional context**

**Comment by pqarmitage** [comment]
@senthilnathann You ask:
`Is there a way to make node with highest IP address to NOT takeover as master from the the current master?`

The situation you are in is that, due to a network issue, you have two instances that are both acting as master. Once the network issue is resolved, they start seeing each others' adverts again, and they therefore know that one of them has to revert to backup. The procedure when the priorities are the same is, as you indicate above, set out in the RFC; i.e. the one with the lower IP address reverts to backup. 

You ask:
`Is there a way to make node with highest IP address to NOT takeover as master from the the current master?`
The simple answer is **NO**. When both systems are in master state, one of the systems must stop being master, and the RFC dictates how that is done.
`nopreempt` is not relevant here, since both instances are in master state. `nopreempt` stops a VRRP instance in backup state, but with a higher priority than the current master, taking over as master.

The way around your problem is to configure different priorities for the two different VRRP instances, and configure the instance that you prefer to be master to have the higher priority. You can also configure `nopreempt` which will stop a higher priority instance taking over as master from a lower priority instance. 

I note that the configuration you refer to as MASTER does not have `nopreempt` configured. However, since the VRRP instances are configured with the same priority, neither one will preempt the other to take over as master from backup state.

What you probably want to do is to decide which VRRP node you prefer to be master after a split brain issue and configure that with a higher priority than the other node. If you then configure `nopreempt` on the higher priority node, it will not take over as master from the lower priority node when it is in backup state; it is probably safer to configure `nopreempt` on both nodes, although strictly it is only necessary on the higher priority node.

You also mention a GARP issue that occurs when both instances have been master due to a split brain issue, and following the network being repaired, the VRRP node that continues as master does not send a GARP message to refresh ARP caches. `global_defs` `vrrp_higher_prio_send_advert` is designed to help with this, and `vrrp_lower_prio_no_advert`, `vrrp_garp_lower_prio_delay` and `vrrp_garp_lower_prio_repeat` can help tune the behaviour (see keepalived.conf(5) man page for more info).

**Comment by senthilnathann** [comment]
Thanks for your explanation . 
Our main issue is after split brain issue, GARP is not refreshed from current MASTER node  and we faced VIP's are unreachable and got outage for some time.

How to solve ?
1 )  Once split brain issue resolved , If last took over Master (during split brain time took over master) is need to maintain their state as MASTER ,existing master need to go as Backup .

So that have tried noprempt , but it's not possible ,when we have same priority .

Do we have any other methods to achieve this ? 

2 ) Above you mentioned configurations need configure . 

I have tried above mentioned configurations too,it's also not working ,have attached  my configurations , 
Keeplaived version : 2.0.7
Master : 
global_defs {
        notification_email {
                xxxxxx
        }
        notification_email_from xxxxxxx
        smtp_server 192.168.100.16
        smtp_connect_timeout 30
        router_id LVSID01
        vrrp_higher_prio_send_advert true
        vrrp_garp_lower_prio_repeat 2
        vrrp_garp_lower_prio_delay 30
}
vrrp_instance VI_1 {
        priority 100
        interface bond0
        virtual_router_id 90
        advert_int 1
        authentication {
                auth_type xxxxxx
                auth_pass xxxxxx
        }
        virtual_ipaddress {
                172.20.131.115
                172.20.31.90
                172.20.31.92
        }
}

Backup also using same configuration .
Once split brain issue solved , no garp will be sent or refreshed . 

Kindly check and give the solution to solve my issue .

**Comment by pqarmitage** [comment]
I have tested this with both keepalived v2.0.20 and v2.0.7 and with the following configuration the keepalived instance that remains master following recovery from a split-brain situation always sends gratuitous ARP messages:
```
global_defs {
	notification_email {
		xxxxx
	}
	notification_email_from xxxxx
	smtp_server 192.168.100.16
	smtp_connect_timeout 30
	router_id LVSID01
	vrrp_higher_prio_send_advert true
}

vrrp_instance VI_1 {
	priority 100    # priority 90 on other system
	interface bond0
	virtual_router_id 90
	advert_int 3
	nopreempt
 	authentication {
 		auth_type xxxx
 		auth_pass xxxxx
 	}
	virtual_ipaddress {
		172.20.131.115
		172.20.31.90
		172.20.31.92
	}
}
```

**Comment by senthilnathann** [comment]
I have tried the same ,not working for me. after split brain recovery ,no GARP send from remains MASTER.



From splitbrain time took over Master  :

> Apr  3 19:56:45 l3-newversion-1 Keepalived_vrrp[11827]: (VI_1) Master received priority 0 message
> Apr  3 19:56:45 l3-newversion-1 Keepalived_vrrp[11827]: (VI_1) Master received advert from 172.20.131.114 with same priority 100 but higher IP address than ours
> Apr  3 19:56:45 l3-newversion-1 Keepalived_vrrp[11827]: (VI_1) Entering BACKUP STATE
> Apr  3 19:56:45 l3-newversion-1 Keepalived_vrrp[11827]: (VI_1) removing VIPs.
>

**Comment by pqarmitage** [comment]
You are running with the **same** priority on both systems. Can you change the configuration so that the priorities are **different** on the two systems; I can see no point having the same priority on both systems. I have only tested it with different priorities on the two systems, as should be the case.

**Comment by senthilnathann** [comment]
I have tried with different priorities ,not worked .after split brain recovery ,no GARP send from remains MASTER.pls check
From splitbrain time took over Master :

> Apr  4 01:24:33 l3-newversion-1 Keepalived_vrrp[24894]: (VI_1) Master received priority 0 message
> Apr  4 01:24:33 l3-newversion-1 Keepalived_vrrp[24894]: (VI_1) Master received advert from 172.20.131.114 with higher priority 100, ours 90
> Apr  4 01:24:33 l3-newversion-1 Keepalived_vrrp[24894]: (VI_1) Entering BACKUP STATE
> Apr  4 01:24:33 l3-newversion-1 Keepalived_vrrp[24894]: (VI_1) removing VIPs.

**Comment by pqarmitage** [comment]
How are you determining that no gratuitous ARP messages are being sent? Are you running keepalived with the `-D` option?

**Comment by senthilnathann** [comment]
yes , my keepalived is running with KEEPALIVED_OPTIONS="-D" option .

**Comment by pqarmitage** [comment]
Can you please provide the output of `ip -d link show bond0`

**Comment by pqarmitage** [comment]
I think it would also be helpful to see the full keepalived logs of both systems from the time keepalived starts up, through the split brain phase and then recovery from the split brain phase and finally keepalived shutting down.

Could you please also send a USR1 signal to the parent keepalived processes on each system; this will generate  files /tmp/keepalived.data and post those files.

**Comment by senthilnathann** [comment]
Please find the needed details ,

Keepalived starting time logs :
**Master :   172.20.131.114**

> Apr  6 17:58:30 l3-newversion-2 Keepalived[13920]: Starting Keepalived v2.0.7 (08/23,2018)
> 
> Apr  6 17:58:30 l3-newversion-2 Keepalived[13920]: Running on Linux 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 (built for Linux 3.10.0)
> 
> Apr  6 17:58:30 l3-newversion-2 Keepalived[13920]: Command line: 'keepalived' '-D'
> 
> Apr  6 17:58:30 l3-newversion-2 Keepalived[13920]: Opening file '/etc/keepalived/keepalived.conf'.
> 
> Apr  6 17:58:34 l3-newversion-2 Keepalived[13925]: Starting Healthcheck child process, pid=13926
> 
> Apr  6 17:58:34 l3-newversion-2 Keepalived[13925]: Starting VRRP child process, pid=13927
> 
> Apr  6 17:58:34 l3-newversion-2 Keepalived_vrrp[13927]: Registering Kernel netlink reflector
> 
> Apr  6 17:58:34 l3-newversion-2 Keepalived_vrrp[13927]: Registering Kernel netlink command channel
> 
> Apr  6 17:58:34 l3-newversion-2 Keepalived_vrrp[13927]: Opening file '/etc/keepalived/keepalived.conf'.
> 
> Apr  6 17:58:34 l3-newversion-2 Keepalived_vrrp[13927]: Assigned address 172.20.131.114 for interface bond0
> 
> Apr  6 17:58:34 l3-newversion-2 Keepalived_vrrp[13927]: Assigned address fe80::ec4:7aff:fe81:d36a for interface bond0
> 
> Apr  6 17:58:34 l3-newversion-2 Keepalived_vrrp[13927]: Registering gratuitous ARP shared channel
> 
> Apr  6 17:58:34 l3-newversion-2 Keepalived_vrrp[13927]: (VI_1) removing VIPs.
> 
> Apr  6 17:58:34 l3-newversion-2 Keepalived_vrrp[13927]: (VI_1) Entering BACKUP STATE (init)
> 
> Apr  6 17:58:34 l3-newversion-2 Keepalived_vrrp[13927]: VRRP sockpool: [ifindex(4), proto(112), unicast(0), fd(8,9)]
> 
> Apr  6 17:58:38 l3-newversion-2 Keepalived_vrrp[13927]: (VI_1) Receive advertisement timeout
> 
> Apr  6 17:58:38 l3-newversion-2 Keepalived_vrrp[13927]: (VI_1) Entering MASTER STATE
> 
> Apr  6 17:58:38 l3-newversion-2 Keepalived_vrrp[13927]: (VI_1) setting VIPs.
> 
> Apr  6 17:58:38 l3-newversion-2 Keepalived_vrrp[13927]: Sending gratuitous ARP on bond0 for 172.20.131.115
> 
> Apr  6 17:58:38 l3-newversion-2 Keepalived_vrrp[13927]: (VI_1) Sending/queueing gratuitous ARPs on bond0 for 172.20.131.115
> 
> Apr  6 17:58:38 l3-newversion-2 Keepalived_vrrp[13927]: Sending gratuitous ARP on bond0 for 172.20.31.90
> 
> Apr  6 17:58:38 l3-newversion-2 Keepalived_vrrp[13927]: (VI_1) Sending/queueing gratuitous ARPs on bond0 for 172.20.31.90
> 
> Apr  6 17:58:38 l3-newversion-2 Keepalived_vrrp[13927]: Sending gratuitous ARP on bond0 for 172.20.31.92
> 
> Apr  6 17:58:38 l3-newversion-2 Keepalived_vrrp[13927]: (VI_1) Sending/queueing gratuitous ARPs on bond0 for 172.20.31.92
> 
> Apr  6 17:58:38 l3-newversion-2 Keepalived_vrrp[13927]: Sending gratuitous ARP on bond0 for 172.20.131.115
> 
> Apr  6 17:58:38 l3-newversion-2 Keepalived_vrrp[13927]: Sending gratuitous ARP on bond0 for 172.20.31.90
> 
> Apr  6 17:58:38 l3-newversion-2 Keepalived_vrrp[13927]: Sending gratuitous ARP on bond0 for 172.20.31.92
> 

**Backup :  172.20.131.113**



> Apr  6 18:00:54 l3-newversion-1 Keepalived[15529]: Starting Keepalived v2.0.7 (08/23,2018)
> 
> Apr  6 18:00:54 l3-newversion-1 Keepalived[15529]: Running on Linux 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 (built for Linux 3.10.0)
> 
> Apr  6 18:00:54 l3-newversion-1 Keepalived[15529]: Command line: 'keepalived' '-D'
> 
> Apr  6 18:00:54 l3-newversion-1 Keepalived[15529]: Opening file '/etc/keepalived/keepalived.conf'.
> 
> Apr  6 18:00:54 l3-newversion-1 Keepalived[15530]: Starting Healthcheck child process, pid=15531
> 
> Apr  6 18:00:54 l3-newversion-1 Keepalived[15530]: Starting VRRP child process, pid=15533
> 
> Apr  6 18:00:54 l3-newversion-1 Keepalived_vrrp[15533]: Registering Kernel netlink reflector
> 
> Apr  6 18:00:54 l3-newversion-1 Keepalived_vrrp[15533]: Registering Kernel netlink command channel
> 
> Apr  6 18:00:54 l3-newversion-1 Keepalived_vrrp[15533]: Opening file '/etc/keepalived/keepalived.conf'.
> 
> Apr  6 18:00:54 l3-newversion-1 Keepalived_vrrp[15533]: Assigned address 172.20.131.113 for interface bond0
> 
> Apr  6 18:00:54 l3-newversion-1 Keepalived_vrrp[15533]: Assigned address fe80::ec4:7aff:feb0:149e for interface bond0
> 
> Apr  6 18:00:54 l3-newversion-1 Keepalived_vrrp[15533]: Registering gratuitous ARP shared channel
> 
> Apr  6 18:00:54 l3-newversion-1 Keepalived_vrrp[15533]: (VI_1) removing VIPs.
> 
> Apr  6 18:00:54 l3-newversion-1 Keepalived_vrrp[15533]: (VI_1) Entering BACKUP STATE (init)
> 
> Apr  6 18:00:54 l3-newversion-1 Keepalived_vrrp[15533]: VRRP sockpool: [ifindex(4), proto(112), unicast(0), fd(8,9)]

**During Split brain :**  Communication break up done  b/w Master/Backup using iptables  .

  **Master server :      172.20.131.114**

                No changes happens ,so no logs available .Its'  running as Master Continuously .

**Backup Server : 172.20.131.113 .**

> Apr  6 18:05:50 l3-newversion-1 Keepalived_vrrp[15533]: (VI_1) Receive advertisement timeout
> 
> Apr  6 18:05:50 l3-newversion-1 Keepalived_vrrp[15533]: (VI_1) Entering MASTER STATE
> 
> Apr  6 18:05:50 l3-newversion-1 Keepalived_vrrp[15533]: (VI_1) setting VIPs.
> 
> Apr  6 18:05:50 l3-newversion-1 Keepalived_vrrp[15533]: Sending gratuitous ARP on bond0 for 172.20.131.115
> 
> Apr  6 18:05:50 l3-newversion-1 Keepalived_vrrp[15533]: (VI_1) Sending/queueing gratuitous ARPs on bond0 for 172.20.131.115
> 
> Apr  6 18:05:50 l3-newversion-1 Keepalived_vrrp[15533]: Sending gratuitous ARP on bond0 for 172.20.31.90
> 
> Apr  6 18:05:50 l3-newversion-1 Keepalived_vrrp[15533]: (VI_1) Sending/queueing gratuitous ARPs on bond0 for 172.20.31.90
> 
> Apr  6 18:05:50 l3-newversion-1 Keepalived_vrrp[15533]: Sending gratuitous ARP on bond0 for 172.20.31.92
> 
> Apr  6 18:05:50 l3-newversion-1 Keepalived_vrrp[15533]: (VI_1) Sending/queueing gratuitous ARPs on bond0 for 172.20.31.92
> 
> Apr  6 18:05:50 l3-newversion-1 Keepalived_vrrp[15533]: Sending gratuitous ARP on bond0 for 172.20.131.115
> 
> Apr  6 18:05:50 l3-newversion-1 Keepalived_vrrp[15533]: Sending gratuitous ARP on bond0 for 172.20.31.90
> 
> Apr  6 18:05:50 l3-newversion-1 Keepalived_vrrp[15533]: Sending gratuitous ARP on bond0 for 172.20.31.92
> 
> Apr  6 18:05:50 l3-newversion-1 Keepalived_vrrp[15533]: Sending gratuitous ARP on bond0 for 172.20.131.115
> 
> Apr  6 18:05:50 l3-newversion-1 Keepalived_vrrp[15533]: Sending gratuitous ARP on bond0 for 172.20.31.90
> 
> Apr  6 18:05:50 l3-newversion-1 Keepalived_vrrp[15533]: Sending gratuitous ARP on bond0 for 172.20.31.92
> 
> Apr  6 18:05:50 l3-newversion-1 Keepalived_vrrp[15533]: Sending gratuitous ARP on bond0 for 172.20.131.115

**Once recovered :** 

**Master :  172.20.131.114**

No changes happens,So no logs available . It's runing as Master .

**Backup : 172.20.131.113**


> Apr  6 20:35:33 l3-newversion-1 Keepalived_vrrp[15533]: (VI_1) Master received priority 0 message
> 
> Apr  6 20:35:33 l3-newversion-1 Keepalived_vrrp[15533]: (VI_1) Master received advert from 172.20.131.114 with higher priority 100, ours 90
> 
> Apr  6 20:35:33 l3-newversion-1 Keepalived_vrrp[15533]: (VI_1) Entering BACKUP STATE
> 
> Apr  6 20:35:33 l3-newversion-1 Keepalived_vrrp[15533]: (VI_1) removing VIPs.
> 
> 
> 
> 
> 
**ip -d link show bond0 outputs :** 

**Master :  172.20.131.114**

> 4: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT qlen 1000
>     link/ether 0c:c4:7a:81:d3:6a brd ff:ff:ff:ff:ff:ff promiscuity 0 
>     bond mode active-backup active_slave eth0 miimon 1000 updelay 5000 downdelay 0 use_carrier 1 arp_interval 0 arp_validate none arp_all_targets any primary eth0 primary_reselect always fail_over_mac none xmit_hash_policy layer2 resend_igmp 1 num_grat_arp 100 all_slaves_active 0 min_links 0 lp_interval 1 packets_per_slave 1 lacp_rate slow ad_select stable tlb_dynamic_lb 0 addrgenmode eui64 

**Backup : 172.20.131.113**

> 4: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT qlen 1000
>     link/ether 0c:c4:7a:b0:14:9e brd ff:ff:ff:ff:ff:ff promiscuity 0 
>     bond mode active-backup active_slave eth0 miimon 1000 updelay 5000 downdelay 0 use_carrier 1 arp_interval 0 arp_validate none arp_all_targets any primary eth0 primary_reselect always fail_over_mac none xmit_hash_policy layer2 resend_igmp 1 num_grat_arp 100 all_slaves_active 0 min_links 0 lp_interval 1 packets_per_slave 1 lacp_rate slow ad_select stable tlb_dynamic_lb 0 addrgenmode eui64 


Both servers keepalived data has been attached .
[backupkeepalived.txt](https://github.com/acassen/keepalived/files/4439329/backupkeepalived.txt)
[masterkeepalived.txt](https://github.com/acassen/keepalived/files/4439331/masterkeepalived.txt)

**Comment by pqarmitage** [comment]
When the split brain recovers, what we can see from the logs is that l3-newversion-1 receives an advert from l3-newversion-2: `Master received priority 0 message` (note the priority may not be 0 - the following log message indicates the priority is 100). This causes the l3-newversion-1 to send an advert. Meanwhile, l3-newversion-2 does **not** receive the advert sent by l3-newversion-1, since otherwise it would log a message `Received advert from 172.20.131.113 with lower priority 90, ours 100, forcing new election`.

The only way that I can see this would happen is if l3-newversion-2 is not receiving adverts from l3-newversion-1. I have set up that scenario and the logs I get are precisely the same as yours.

You could try removing `nopreempt` from the configurations, setting the vrrp priority on l3-newversion-1 to be higher than the priority on l3-newversion-2 and see what happens. I suspect they will both become master.

**Comment by senthilnathann** [comment]
As per my understanding ,
When will get this message " `Received advert from 172.20.131.113 with lower priority 90, ours 100, forcing new election" ?`

During split brain issue time ,newly took over Master ( l3-newversion-1) will able to reach to existing Master ( l3-newversion-2) ,but still l3-newversion-2 is not able to reach l3-newversion-1 ,during that time we got this message,So this happens only during split brain issue time,not after split brain issue recovery.

When split brain recovers ?

Once Existing Master ( l3-newversion-2 ) is able to reach to new took over Master (  l3-newversion-1 ) ,it's recovered and got this message( `Master received priority 0 message`) and went to Backup state. 
Before took over Backup (l3-newversion-1) need to send one advert to ( l3-newversion-2 ) existing Master. but I think it's not send and no logs printed in l3-newversion-1 (like advert send.. ) or we can't able to find it's send or another one is received.

I think ,no advert will be send . Pls check and clarify on this .

**Comment by pqarmitage** [comment]
`Received advert from 172.20.131.113 with lower priority 90, ours 100, forcing new election` is logged when a VRRP instance in master state receives an advert with a lower priority than its own priority.

You state that you are using iptables to create the split brain, but you haven't indicated what iptables entries you are adding/removing on which system or the order of adding/removing or the time intervals between each command. This could affect how keepalived recovers from the split-brain situation, and could cause the lack of GARP messages. In order to properly simulate a split brain with iptables, the iptables entries need to all be added/deleted at the same time; a gap of even a second between iptables entries being deleted would not properly simulate split-brain recovery. It is also necessary to block adverts in both directions.

You state:
```
Before took over Backup (l3-newversion-1) need to send one advert to ( l3-newversion-2 ) existing
Master. but I think it's not send and no logs printed in l3-newversion-1 (like advert send.. ) or we can't 
able to find it's send or another one is received.
```
When keepalived logs `Master received priority 0 message` it sends an advert. Your logs show that the advert is not being received by l3-newversion-2, otherwise it would log `Received advert from 172.20.131.113 with lower priority 90, ours 100, forcing new election` and GARP messages would be sent.

I guess the problem is something to do with the way you are using iptables to simulate the split-brain state; it works perfectly for me when I add/delete the iptables rules without any delays whatsoever, and also block traffic in both directions. It might be that you need to stop using iptables and actually disconnect the network between the two machines.

**Comment by senthilnathann** [comment]
Thanks for the explanation . 

Yes , iptables rules are deleted with some delay ,due to this it's not working as expected .
Now I have deleted the iptables rules with same time ,after split brain issue recovery , it's working as you said ,garp messages will be sent from l3-newversion-2. 

Final conclusion : 
If we configure ``vrrp_higher_prio_send_advert true` option,
After split brain issue recovery ,garp will be sent from remains high priority Master . 

`Have using Iptables rules :
In l3-newversion-2 : 
/sbin/iptables -A INPUT -s 172.20.131.113 -j DROP 
In l3-newversion-1: 
/sbin/iptables -A INPUT -s 172.20.131.114 -j DROP

Thanks for your support .... :+1:
