### ISSUE TITLE
fined grained namespace support

### ISSUE THREAD

**Issue by wdauchy** [acassen/keepalived#1575]
Hello,

We have a setup such as:
- physical interface is in the root namespace
- VIP are placed within a dedicated namespace

We would like to be able to do the health checks from the root namespace, and configure ipvs routes in a dedicated namespace. The main advantage is to easily isolate the two types of traffic on a given host and to minimise performance penalties associated with a conventional bridge + veth setup.
For now, we understood that the only possible setup was to move all the processes within a dedicated namespace which lacks of flexibility. Other processes such as HAProxy made the choice to allow users to bind each IP in a specific netns, this allows the healtchecks and backend traffic to happen in the root netns (see https://cbonte.github.io/haproxy-dconv/2.1/configuration.html#5.1-namespace)

Do you think it would be an acceptable feature?

**Comment by wdauchy** [comment]
(@pqarmitage even though I'm waiting for your approval regarding this feature, I started something on my side and might propose a patch for a minimal support of such feature)

**Comment by pqarmitage** [comment]
I'm very happy to have a look at a patch.

Some thoughts that have occurred to me and will/might cause problems:
1. The use of `lvs_sync_daemon` will not work as it does currently, since the configuring of the sync daemon is handled by the VRRP process rather than the health checker process.
1. Will SNMP, JSON and DBus still work?
1. Will communication between the VRRP and BFD process and between the health checker and BFD process still work?
1. One use of keepalived with IPVS is for the virtual server addresses to be managed by the VRRP process, thereby creating master/backup IPVS servers. This will not work with the vrrp process and the healthchecker process in different network namespaces.

These are just a few pointers to some of the issues that may need to be considered when implementing different namespaces.

Is there any disadvantage running two separate instances of keepalived, one in each namespace?

**Comment by wdauchy** [comment]
> 1. The use of `lvs_sync_daemon` will not work as it does currently, since the configuring of the sync daemon is handled by the VRRP process rather than the health checker process.
> 2. Will SNMP, JSON and DBus still work?
> 3. Will communication between the VRRP and BFD process and between the health checker and BFD process still work?
> 4. One use of keepalived with IPVS is for the virtual server addresses to be managed by the VRRP process, thereby creating master/backup IPVS servers. This will not work with the vrrp process and the healthchecker process in different network namespaces.
> 
> These are just a few pointers to some of the issues that may need to be considered when implementing different namespaces.

Thank you very much.
I will have a look at the different points raised as I'm not an expert user of keepalived. However, what do you think about a first minimal support which would do:
- add new global keyword `namespace_with_ipvs`
- once set, this keyword will change the `net_namespace` parameter behaviour such as: the process won't be moved into a different namespace, but only socket to ipvs would be open in the mentioned namespace.
The end result should have minimal impact on the rest of the processes, unless I'm missing something.
In my opinion this has the benefit to not be too intrusive in the current functionalities.

> Is there any disadvantage running two separate instances of keepalived, one in each namespace?

I don't see what you mean by that. In our case, the one within the VIP namespace cannot do any healthchecks so I don't see how this might be possible to correctly setup ipvs. I'm probably missing something here.

**Comment by wdauchy** [comment]
@pqarmitage I've pushed a first proposal. What do you think? If not perfect, it should give a first idea of what it could be / what I had in mind.

**Comment by pqarmitage** [comment]
@wdauchy Many thanks for this patch. I have a small number of comments:

1. `namespace_with_ipvs` is not, I think, the most descriptive name, and also the way it is implemented means that the vrrp process can only run in the default network namespace. Could you please change it to `net_namespace_ipvs` which takes an optional parameter which is the network namespace name; if the optional parameter is not specified, then use the default network namespace. `namespace_with_ipsets` has a completely different meaning to here, and was used to force using network namespaces on kernels prior to 3.13 if ipsets were in use, since prior to 3.13 ipsets were not namespace aware.

1. I think `my_socketat()` would be more meaningfully called `socket_netns()`.

1. `dump_global_data()` needs to be updated

1. Use `snprintf()` rather than `sprintf()`

1. I don't think `init_ipvs_namespaces()` should be called from the parent keepalived process; it should only be called in the healthchecker process, and the vrrp process if `lvs_sync_daemon` is configured. I think that will largely be sorted out by the first point above.

If you would rather not do the changes above just let me know and I will complete them.

**Comment by wdauchy** [comment]
Thanks for the feedbacks! I will have a look.

**Comment by wdauchy** [comment]
@pqarmitage I just uploaded an updated version of the patch:

1. change done apart from using the default network namespace name if `net_namespace_ipvs` parameter is not specified. Indeed I'm not entirely convinced by this implicit behaviour; it also complexifies the code for no major reason. But if you still think it is worth it, I can change it. So for now `net_namespace_ipvs` requires a parameter.
2. done. `my_socketat` was in fact inspired from the original submission of `socketat` see https://lwn.net/Articles/407613/ ; but ok for me as well with this naming.
I however took the opportunity to split the call to `socket_netns` and avoid two statements on the same line, making the reading easier in my opinion.
3. thanks for the pointer, I completely missed it. now fixed.
4. ah good catch, I should have thought about it. fixed.
5. good point, fixed. Please note I did not tested the `lvs_sync_daemon` case yet.

**Comment by pqarmitage** [comment]
I think the socketat() you reference was misnamed. The `*at()` functions, compared to the versions of the functions without the `at` act on files etc where relative paths are taken to be relative to a directory referenced by an fd instead of the current directory. That was not the case with the proposed `socketat()` function.

Many thanks for updating your patch following the updates I pushed earlier. I am looking at it now and hope to be able to merge it later.

**Comment by wdauchy** [comment]
thanks, feel free to ask more changes, I can handle them.

**Comment by pqarmitage** [comment]
@wdauchy Many thanks for you patch which I have now merged along with a couple of other commits just to tidy things up a bit.

**Comment by wdauchy** [comment]
thanks a lot @pqarmitage 
I saw you finally preferred to put the argument optional, ok for me, I could have done the changes if needed though :)

I however personally don't like commit 41b9e5e87b06990ecbdfeac12a8c8dab6b9cff88 because the code is less readable to me. calling the same function in all cases was for me clearer and transparent, i.e condition such as `(default_namespace >= 0 && ipvs_namespace && setns(ipvs_namespace, CLONE_NEWNET)` had the ability to make it 100% transparent to the user.
it avoids many `ifdef` condition, in a lot of places in the code. The error cases is also less simple in this version with the different `close` which are needed in those cases.

**Comment by pqarmitage** [comment]
@wdauchy There were a few things that inspired commit 41b9e5e.

The reason I made the changes for using the default namespace was that I needed it for sorting out the issues which I resolved in commit 0878c05 - fix use of libnl for IPVS, otherwise I would have asked you to do it.

The main reason for commit 41b9e5e was that I had changed the code so that the IPVS netlink socket is now kept open from the first time it is needed until keepalived terminates, rather than being opened and closed every time keepalived wanted to update the keepalived configuration; this meant that the network namespace fds only need to be open while the IPVS netlink socket is opened.

The second point is that the code needed to be able to compile on a system which doesn't support network namespaces (i.e. pre 3.0 kernels) such as RHEL 5 and RHEL6 (we currently support building on kernels back to at least 2.6.13). If network namespaces are not supported, then namespaces.c is not included in the build and so nl_ipvs_connect() was not available as a function. I think whichever way we had gone, we would have ended up with approximately the same amount of conditional compilation. I actually feel that closing the namespace fds immediately after they are no longer needed, rather than having to close them in both the success and error paths is simpler.

Regarding assignment within an if, that is purely a matter of style, and within the keepalived project it is a style we have adopted.

I am not saying that I am right or that you are wrong in any of these aspects; I have just tried to give an explanation as to why I did them the way I did. And you are never going to find a coding style that everyone agrees with 100%!

Finally, many thanks for your help with this.

**Comment by wdauchy** [comment]
Thanks a lot for the explanation @pqarmitage - it helps a lot as the commit message was not verbose on those points.
I was not particularly focusing on coding style, which I agree is a matter of choice.
My comment was more on making sure we have a unique call, so that it allows simple extension in the future for a socket opening, but it's true I overlooked the case where setns call is not available. I still find the error path harder to read.

thanks for your work!
