### ISSUE TITLE
monitoring tools

### ISSUE THREAD

**Issue by gabbiano83** [acassen/keepalived#1579]
I'm wondering if there is any graphical monitoring tool to monitor IPVS session, status, and so on for recent linux distribution.

I'm searching and found old mon.cgi project: http://moncgi.sourceforge.net/index.php/mon.cgi/cvs
But with recent version does not work correctly due to lvs init.d script.
 
Thanks for your help

**Comment by pqarmitage** [comment]
This is not really a question about keepalived, but rather about IPVS, and would be better addressed to  the LVS mailing list - see http://www.linuxvirtualserver.org/mailing.html.

Since keepalived supports SNMP, any SNMP graphical monitoring tool should be able to provide an element of what you want, but from your question it appears that it is IPVS that you want to monitor and not keepalived.
