### ISSUE TITLE
No gratuitous arp on recovery

### ISSUE THREAD

**Issue by smcmurray** [acassen/keepalived#160]
If hosts A and B share an ip, where A has higher priority, if the network connection to A is cut, B will take over the ip, but A will not release the ip. When the network connection is restored to A, B will relinquish the ip, but A does not send a gratuitous arp. Hosts on the wire will continue to think B has the ip. It can take some time before an arp clears up the confusion.

**Comment by smcmurray** [comment]
Perhaps vrrp_state_leave_master or some such could do an arp when releasing an ip.

**Comment by sim-** [comment]
I noticed this and replied partially because on my to do list is debugging a similar issue that occurs in a virtual environment when A is suspended temporarily to migrate to a new VM host. In this particular instance, the clients move to and get stuck on B until keepalived restarted on A to force a gratuitous ARP. Positive (but broken) positive feedback mechanisms in modern neighbor implementations combined with applications that send periodically UDP packets, etc., can make this stick indefinitely.

I think the assumption here is that the network will be re-established in a perfect, bidirectional fashion without any packet loss :), and A will get a lower priority advertisement from B and log "forcing new election", which presumably follows a path to re-gratuitously-ARPing from A.

However, if B receives a higher priority advertisement from A first, I think the RFC just states to enter backup mode and release the IPs. A won't know anything occurred, which can cause this problem.  This can also happen if the network converges in a directionally-challenged way momentarily, preventing A from receiving B's lower priority advertisement. I think the only mechanism that can assist here is FAULT state, which relies on local link state detection (no help if the network splits somewhere in the middle or if A pauses).

Per your suggestion of vrrp_state_leave_master() doing a gratuitous ARP when releasing an IP, what would it ARP? Advertising the "other node's" MAC isn't useful here, since it would change the switch path and hurt more than help (especially with reserved MACs actually in use). Maybe it should sent a shutdown or something instead, but there's still no reliable way of A knowing that the network broke especially if B's packets go missing.

Maybe the best effort would be something like a timer started from the entry to backup state that would fire a "late" lower prio advertisement solely to poke the master into knowing something bad happened earlier. I don't know how this would play with preemption, though.

**Comment by smcmurray** [comment]
Sorry. I don't suggest that B does a gratuitous arp. I suggest that it does an arp probe, or something like "arp who has A.ip, tell everyone". Something to nudge A into arping.

**Comment by acassen** [comment]
please have a look to config keyword : garp_master_refresh, garp_master_repeat, garp_master_refresh_repeat.

I have also a pending patch to throttle garp (no yet merged)

but mainly this is one of the reason I would love finding out time to introduce BFD into VRRP.

regs,
