### ISSUE TITLE
startup_script as dependency of keepalived instances

### ISSUE THREAD

**Issue by Mint-M** [acassen/keepalived#1601]
**Is your feature request to resolve a problem or provide enhanced functionality? Please describe.**
The feature helps vrrp instances (and other instances) start conditionally.

**Describe the solution you would like**
Add an option to make startup_script become dependency of keepalived instances. For example, if the startup_script is not found or it exits with a failed code, instances dependent on startup_script will turn to fault state.

**Describe alternatives you have considered**
It seems that vrrp instances don't care whether the startup_script is executed successfully.
An alternative would be executing another script and killing keepalived if that script failed which is not graceful. 

Keepalived[22602]: Running startup script /etc/keepalived/start.sh
Keepalived[22602]: startup script failed, status 1
Keepalived[22602]: Starting VRRP child process, pid=22604
Keepalived_vrrp[22604]: Registering Kernel netlink reflector
Keepalived_vrrp[22604]: Registering Kernel netlink command channel
Keepalived_vrrp[22604]: Opening file '/etc/keepalived/keepalived.conf'.
Keepalived_vrrp[22604]: Assigned address  for interface eth0
Keepalived_vrrp[22604]: Assigned address  for interface eth0
Keepalived_vrrp[22604]: Registering gratuitous ARP shared channel
Keepalived_vrrp[22604]: (eth0) removing VIPs.
Keepalived_vrrp[22604]: (eth0) Entering BACKUP STATE (init)
Keepalived_vrrp[22604]: VRRP sockpool: [ifindex(2), family(IPv4), proto(112), unicast(0), fd(13,14)]
Keepalived_vrrp[22604]: (eth0) Receive advertisement timeout
Keepalived_vrrp[22604]: (eth0) Entering MASTER STATE

Keepalived[22907]: WARNING - default user 'keepalived_script' for script execution does not exist - please create.
Keepalived[22910]: Script /etc/keepalived/start.sh cannot be accessed - No such file or directory
Keepalived[22910]: NOTICE: setting config option max_auto_priority should result in better keepalived performance
Keepalived[22910]: Starting VRRP child process, pid=22911
systemd[1]: Started LVS and VRRP High Availability Monitor.
Keepalived_vrrp[22911]: Registering Kernel netlink reflector
Keepalived_vrrp[22911]: Registering Kernel netlink command channel
Keepalived_vrrp[22911]: Opening file '/etc/keepalived/keepalived.conf'.
Keepalived_vrrp[22911]: Assigned address  for interface eth0
Keepalived_vrrp[22911]: Assigned address  for interface eth0
Keepalived_vrrp[22911]: Registering gratuitous ARP shared channel
Keepalived_vrrp[22911]: (eth0) removing VIPs.
Keepalived_vrrp[22911]: (eth0) Entering BACKUP STATE (init)
Keepalived_vrrp[22911]: VRRP sockpool: [ifindex(2), family(IPv4), proto(112), unicast(0), fd(13,14)]
Keepalived_vrrp[22911]: (eth0) Receive advertisement timeout

**Would the feature request be of benefit only to you, or is it more generally applicable?**
Under most circumstances, startup_script should be executed without error if the ip addresses provided by keepalived instances depend on function of the script.

**Keepalived version**
The latest snapshot.

**Additional context**
shutdown_script is not so mandatory in most cases, however, should keepalived give some alert or exit without code 0 to indicate that administrators should check their scripts or configuration?

**Comment by Mint-M** [comment]
Besides, it seems that keepalived only check whether eth shutdown script exist when it starts. If the shutdown script did't exits that time, it would't be executed even the script had been placed to the correct location before shutdown.

A reload before shutdown would help, but the logs during reload shown nothing about startup/shutdown scripts.

Should keepalived recheck shutdown scripts before shutdown and gives information about startup/shutdown scripts during reload?

**Comment by pqarmitage** [comment]
@Mint-M I'm glad to see that someone is using the startup script feature; it was something I added on the basis that I thought it might be useful, but I didn't know of anyone had a real use for it.

I think what you are asking for in the first section can be achieved already, and rather than add further specific code to keepalived, it is better to use existing functionality.

If you add a `track_file` to each specific vrrp instance, scripts can then update the track files accordingly to make the vrrp instances go to fault state as desired. So your startup script can write the appropriate values to the various track files in the event that it exists with an exit code of 1, or of course any other value.

That doesn't deal with the startup script not existing. I would argue that that is a system configuration error, since it is the system administrator's responsibility to set up the system correctly and to configure a system utility (keepalived) to execute a script that does not exist is a configuration error. However, there is a way to handle this, again using track files. If you add `init_file 1 overwrite` to the track file configuration, then that track file will start in the fault state, and so will any vrrp instances tracking it. The startup script could wrote 0 to the track files (or remove the track files), and then the vrrp instances will no longer be in the fault state due to the track file. If the startup script doesn't run, then the track files will not be updated and the vrrp instances will be in the fault state.

It is correct that keepalived only checks that the shutdown script exists, and is secure, when keepalived starts. This does not seem unreasonable to me; why configure keepalived to use something (the shutdown script) when it doesn't exist? We have to rely on the system administrator (root) being reasonable in what the scripts do, since they are executed with root privileges, so I think we should also be able to rely on the system administrator having configured the system in accordance with how they have configured keepalived. If you can provide a use case for why it is necessary to be able to start keepalived when the shutdown script doesn't exist and to be able to add the script later, then we can consider this further, but at the moment I can't see why this is necessary.

**Comment by Mint-M** [comment]
@pqarmitage Startup script is definitely useful when some service is supposed to be activated before the start of some instances. In my case, virtual ip addresses act as the default gateway for other machine. Therefore, iptables has to be configured so that NAT works with the virtual ip addresses. I used to write scripts which contained NAT rules and they were executed by notify_master/notify_backup/notify_fault/notify_stop even if notifying scripts were not meant to handle this function.

However, when it comes to loads of network traffic and the packet arrives before the related iptables rule is added and after the vrrp instance become master state acquiring the virtual ip address, netfilter will record it without the expected NAT in nf_conntrack. After the retransmission of that packet, the timer of related nf_conntrack timer will be refreshed again and again (especially for udp packets) and iptables will never get that packet NATed.

Currently, my workaround is to create a systemd unit for the iptables script and add "Before=keepalived.service RequiredBy=keepalived.service" to it. I'm interested in startup script so that the systemd unit could be merged in keepalived configuration. Although combining track_file and startup script together is a good solution , systemd dependency is a more graceful solution in my point of view.

For the misconfigured scripts, you are right. It is too demanding for keepalived to handle an incorrect configuration.

**Comment by pqarmitage** [comment]
@Mint-M Are you happy for this issue to be closed now?
