### ISSUE TITLE
Add a default  delay for child processes if they exit too frequently in a short time

### ISSUE THREAD

**Issue by Mint-M** [acassen/keepalived#1602]
**Is your feature request to resolve a problem or provide enhanced functionality? Please describe.**
It prevents keepalived from restarting child process too frequently when they won't recover.

**Describe the solution you would like**
Add a default delay child processes if they exit too frequently in a short time.

**Describe alternatives you have considered**
No alternative solutions.

**Would the feature request be of benefit only to you, or is it more generally applicable?**
When keepalived child process exit abnormally, keepalived always tries to restart it without limitation.
Although coredump or logs generated by the segfault should be managed or limited by other applications , restarting the child process continuously makes no sense and consumes much cpu.
There is supposed to implement a limitation or delay between each restart,say delaying the next restart after ten exits in a minute.
When I review the coredump files generated in the issue blew, I found that keepalived had restarted its child process too frequently.
https://github.com/acassen/keepalived/issues/1591
TIME                   
Fri 2020-05-29 17:44:51
Fri 2020-05-29 17:44:52
Fri 2020-05-29 17:44:52
Fri 2020-05-29 17:44:52
Fri 2020-05-29 17:44:53
Fri 2020-05-29 17:44:53
Fri 2020-05-29 17:44:53
Fri 2020-05-29 17:44:54
Fri 2020-05-29 17:44:54
Fri 2020-05-29 17:44:55
Fri 2020-05-29 17:44:55
Fri 2020-05-29 17:44:55
Fri 2020-05-29 17:44:56
Fri 2020-05-29 17:44:56
Fri 2020-05-29 17:44:57
Fri 2020-05-29 17:44:57
Fri 2020-05-29 17:44:57
Fri 2020-05-29 17:44:58
Fri 2020-05-29 17:44:58
Fri 2020-05-29 17:44:58
Fri 2020-05-29 17:44:59
Fri 2020-05-29 17:44:59
Fri 2020-05-29 17:45:00
Fri 2020-05-29 17:45:00
Fri 2020-05-29 17:45:00
Fri 2020-05-29 17:45:01
Fri 2020-05-29 17:45:01
Fri 2020-05-29 17:45:02
Fri 2020-05-29 17:45:02
Fri 2020-05-29 17:45:02
Fri 2020-05-29 17:45:03
Fri 2020-05-29 17:45:03
Fri 2020-05-29 17:45:03
Fri 2020-05-29 17:45:04
Fri 2020-05-29 17:45:04
Fri 2020-05-29 17:45:04
Fri 2020-05-29 17:45:05
Fri 2020-05-29 17:45:05
Fri 2020-05-29 17:45:06
Fri 2020-05-29 17:45:06
Fri 2020-05-29 17:45:06
Fri 2020-05-29 17:45:07
Fri 2020-05-29 17:45:07
Fri 2020-05-29 17:45:07
Fri 2020-05-29 17:45:08
Fri 2020-05-29 17:45:08
Fri 2020-05-29 17:45:09
Fri 2020-05-29 17:45:09
Fri 2020-05-29 17:45:09
Fri 2020-05-29 17:45:10
Fri 2020-05-29 17:45:10
Fri 2020-05-29 17:45:10
Fri 2020-05-29 17:45:11
Fri 2020-05-29 17:45:11
Fri 2020-05-29 17:45:12
Fri 2020-05-29 17:45:12
Fri 2020-05-29 17:45:12
Fri 2020-05-29 17:45:13
Fri 2020-05-29 17:45:13
Fri 2020-05-29 17:45:13
Fri 2020-05-29 17:45:14
Fri 2020-05-29 17:45:14
Fri 2020-05-29 17:45:15
Fri 2020-05-29 17:45:15
Fri 2020-05-29 17:45:15
Fri 2020-05-29 17:45:16
Fri 2020-05-29 17:45:16
Fri 2020-05-29 17:45:16
Fri 2020-05-29 17:45:17
Fri 2020-05-29 17:45:17
Fri 2020-05-29 17:45:18

**Keepalived version**
The latest snapshot.

**Additional context**
Add any other context about the feature request here.

**Comment by Mint-M** [comment]
BTW, would you like to add %dist to 'Release' keepalived.spec.in, which fits RH rpm package naming convention more?

**Comment by pqarmitage** [comment]
@Mint-M The most important issue here is that if keepalived child processes are terminating abnormally, then the details of that problem, along with stack backtraces from the coredump, need to be reported as an issue so that we can resolve the underlying problem. The key point is that **keepalived processes should NEVER segfault.**

So, can you please report the details causing the segfault so that we can fix the real problem.

I have thought about this issue of a delay before restarting the child process, but there is this conundrum. If the child process is terminating abnormally soon after startup, there is no point in attempting to run it at all since the child is not going to achieve anything before the child terminates again. It might be better in this circumstance to run keepalived with the `-D` switch, so that it doesn't respawn a child process that is just going to die anyway, and keepalived stops on the basis that it can't run properly.

By the way, stating "The lastest snapshot" does not help us, since we can't know which that was - for example it may have been the latest when you fetched the code but further commits may have been made since, or by the time we get to the day after you reported this, we will only be able to see the day of the report and not have any indication of the time, and if there were several commits that day we wouldn't know which one you were referring to. Please always provide the git commit number.

**Comment by Mint-M** [comment]
@pqarmitage The problem which causes segfault has already been fixed by https://github.com/acassen/keepalived/commit/8048c91d2841ebca5d34542a8633a52c8e3e26ea.
In that case, keepalived continuously restarted child processes. However, problem other than keepalived it self might cause segfault such as hardware problem(tainted memory) or other applications.

Since it is more a "feature requested" issue than a "bug report" issue, I just want to state that keepalived hasn't implemented this function yet by stating "The lastest snapshot". I know that precise version of the code should be provided if you need to locate where the program goes wrong.

**Comment by pqarmitage** [comment]
@Mint-M Many thanks for your response, and it is good to know that the segfault has been fixed.

Commit d2aff20 implements rate limiting of respawning child processes. The first time a child process dies, it is immediately respawned. The next time there is a 1 second delay, and each subsequent time is doubled up to a limit of 60 seconds.

If the child process runs for 1 minute or more, it is considered not to have a hard fault, and the reload delay is reset to 0.
