### ISSUE TITLE
Duplicate IPs when adding a new vip

### ISSUE THREAD

**Issue by achevalet** [acassen/keepalived#1603]
**Describe the bug**
Hi, I've just updated from 1.3 to 2.0 and I'm facing a weird (dummy?) issue. I've a basic vrrp_instance configuration running with 2 VIPs. I want to add a new VIP. I update the config on the standby node first, and restart or reload keepalived (before doing the same on the active node). The problem is that, when restating keepalived on standby node, all 3 VIPs mount on this node (the 2 existing VIPs plus the new one) and the 2 existing VIPs remains UP on the active node, which creates duplicate IPs problems.

**To Reproduce**
- Setup a 2 nodes cluster with a vrrp_instance
- Add a new vip on one node only and restart or reload keepalived

**Expected behavior**
- Nothing change. The 2 existing VIPs stay UP on the active node. The new VIP stay DOWN because of configuration mismatch between the 2 nodes. This is the behavior of 1.3, with meaningful logs: 
```
Jun  2 10:40:51 node2 Keepalived_vrrp[4179]: (haproxy-vip): received an invalid ip number count 2, expected 3!
Jun  2 10:40:51 node2 Keepalived_vrrp[4179]: bogus VRRP packet received on eth0 !!!
Jun  2 10:40:51 node2 Keepalived_vrrp[4179]: VRRP_Instance(haproxy-vip) ignoring received advertisment...
```

**Keepalived version**
- keepalived-2.0.20-1.x86_64

**Distro (please complete the following information):**
- CentOS Linux release 7.8.2003 x86_64

**Configuration file:**
I've tested different configuration - MASTER-BACKUP, BACKUP-BACKUP, same or different prio - and always get same behavior.

node1:
```
vrrp_instance haproxy-vip {
  interface                 eth0
  state                     BACKUP
  virtual_router_id         51
  priority                  101
  advert_int                1
  garp_master_delay         5

  virtual_ipaddress {
    1.2.3.201 dev eth0
    1.2.3.202 dev eth0
  }
}
```

node2:
```
vrrp_instance haproxy-vip {
  interface                 eth0
  state                     BACKUP
  virtual_router_id         51
  priority                  101
  advert_int                1
  garp_master_delay         5

  virtual_ipaddress {
    1.2.3.201 dev eth0
    1.2.3.202 dev eth0
    1.2.3.203 dev eth0
  }
}
```

**System Log entries**
node2 after restart:
```
Jun  2 11:11:00 node2 Keepalived[14381]: Starting Keepalived v2.0.20 (01/22,2020)
Jun  2 11:11:00 node2 Keepalived[14381]: Running on Linux 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 (built for Linux 3.10.0)
Jun  2 11:11:00 node2 Keepalived[14381]: Command line: '/usr/sbin/keepalived' '-D'
Jun  2 11:11:00 node2 Keepalived[14381]: Opening file '/etc/keepalived/keepalived.conf'.
Jun  2 11:11:00 node2 Keepalived[14382]: Starting VRRP child process, pid=14383
Jun  2 11:11:00 node2 Keepalived_vrrp[14383]: Registering Kernel netlink reflector
Jun  2 11:11:00 node2 Keepalived_vrrp[14383]: Registering Kernel netlink command channel
Jun  2 11:11:00 node2 Keepalived_vrrp[14383]: Opening file '/etc/keepalived/keepalived.conf'.
Jun  2 11:11:00 node2 Keepalived_vrrp[14383]: Assigned address 1.2.3.135 for interface eth0
Jun  2 11:11:00 node2 Keepalived_vrrp[14383]: Assigned address fe80::546f:c4ff:fe69:102 for interface eth0
Jun  2 11:11:00 node2 Keepalived_vrrp[14383]: Registering gratuitous ARP shared channel
Jun  2 11:11:00 node2 Keepalived_vrrp[14383]: (haproxy-vip) removing VIPs.
Jun  2 11:11:00 node2 Keepalived_vrrp[14383]: (haproxy-vip) Entering BACKUP STATE (init)
Jun  2 11:11:00 node2 Keepalived_vrrp[14383]: VRRP sockpool: [ifindex(2), family(IPv4), proto(112), unicast(0), fd(11,12)]
Jun  2 11:11:00 node2 Keepalived_vrrp[14383]: (haproxy-vip) received an unexpected ip number count 2, expected 3!
Jun  2 11:11:01 node2 Keepalived_vrrp[14383]: (haproxy-vip) received an unexpected ip number count 2, expected 3!
Jun  2 11:11:02 node2 Keepalived_vrrp[14383]: (haproxy-vip) received an unexpected ip number count 2, expected 3!
Jun  2 11:11:03 node2 Keepalived_vrrp[14383]: (haproxy-vip) received an unexpected ip number count 2, expected 3!
Jun  2 11:11:03 node2 Keepalived_vrrp[14383]: (haproxy-vip) Receive advertisement timeout
Jun  2 11:11:03 node2 Keepalived_vrrp[14383]: (haproxy-vip) Entering MASTER STATE
Jun  2 11:11:03 node2 Keepalived_vrrp[14383]: (haproxy-vip) setting VIPs.
Jun  2 11:11:03 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.201
Jun  2 11:11:03 node2 Keepalived_vrrp[14383]: (haproxy-vip) Sending/queueing gratuitous ARPs on eth0 for 1.2.3.201
Jun  2 11:11:03 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.202
Jun  2 11:11:03 node2 Keepalived_vrrp[14383]: (haproxy-vip) Sending/queueing gratuitous ARPs on eth0 for 1.2.3.202
Jun  2 11:11:03 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.203
Jun  2 11:11:03 node2 Keepalived_vrrp[14383]: (haproxy-vip) Sending/queueing gratuitous ARPs on eth0 for 1.2.3.203
Jun  2 11:11:03 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.201
Jun  2 11:11:03 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.202
Jun  2 11:11:03 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.203
Jun  2 11:11:03 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.201
Jun  2 11:11:03 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.202
Jun  2 11:11:03 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.203
Jun  2 11:11:03 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.201
Jun  2 11:11:03 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.202
Jun  2 11:11:03 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.203
Jun  2 11:11:03 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.201
Jun  2 11:11:03 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.202
Jun  2 11:11:03 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.203
Jun  2 11:11:08 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.201
Jun  2 11:11:08 node2 Keepalived_vrrp[14383]: (haproxy-vip) Sending/queueing gratuitous ARPs on eth0 for 1.2.3.201
Jun  2 11:11:08 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.202
Jun  2 11:11:08 node2 Keepalived_vrrp[14383]: (haproxy-vip) Sending/queueing gratuitous ARPs on eth0 for 1.2.3.202
Jun  2 11:11:08 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.203
Jun  2 11:11:08 node2 Keepalived_vrrp[14383]: (haproxy-vip) Sending/queueing gratuitous ARPs on eth0 for 1.2.3.203
Jun  2 11:11:08 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.201
Jun  2 11:11:08 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.202
Jun  2 11:11:08 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.203
Jun  2 11:11:08 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.201
Jun  2 11:11:08 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.202
Jun  2 11:11:08 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.203
Jun  2 11:11:08 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.201
Jun  2 11:11:08 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.202
Jun  2 11:11:08 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.203
Jun  2 11:11:08 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.201
Jun  2 11:11:08 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.202
Jun  2 11:11:08 node2 Keepalived_vrrp[14383]: Sending gratuitous ARP on eth0 for 1.2.3.203
Jun  2 11:11:08 node2 Keepalived_vrrp[14383]: (haproxy-vip) received an unexpected ip number count 2, expected 3!
Jun  2 11:11:09 node2 Keepalived_vrrp[14383]: (haproxy-vip) received an unexpected ip number count 2, expected 3!
Jun  2 11:11:10 node2 Keepalived_vrrp[14383]: (haproxy-vip) received an unexpected ip number count 2, expected 3!
```

node1:
```
Jun  2 11:11:03 node1 Keepalived_vrrp[4835]: (haproxy-vip) received an unexpected ip number count 3, expected 2!
Jun  2 11:11:04 node1 Keepalived_vrrp[4835]: (haproxy-vip) received an unexpected ip number count 3, expected 2!
Jun  2 11:11:05 node1 Keepalived_vrrp[4835]: (haproxy-vip) received an unexpected ip number count 3, expected 2!
```

**Did keepalived coredump?**
No.

**Additional context**

**Comment by pqarmitage** [comment]
The problem is that after the reload the standby node is seeing the adverts from the active node as invalid, since they contain the incorrect number of adverts, and so it discards the adverts. Since after 3 * advert interval + a bit it hasn't received a (valid from its point of view) the standby node transitions to master.

As RFC5798 says, when an advert is received:
```
      - MAY verify that "Count IPvX Addrs" and the list of IPvX
      address(es) match the IPvX Address(es) configured for the VRID.
```
and we do this by default.

There are a couple of ways to handle this:
1. Set `skip_check_adv_addr` in the vrrp_instance config (or `vrrp_skip_check_adv_addr` in global_defs). I am not sure whether this will work after a reload since it only skips the check if the advert is received from the same master as the previous advert. If it doesn't work reloading the standby first, it should work if the active node is reloaded first.
2. Use reload_time_file to reload the active and standby nodes at the same time (this may be a post 2.0.20 feature).
3. Manually ensure that the active and standby nodes are reloaded at the same time, or within a couple of advert intervals of each other.

It might be that we add a further option to `skip_check_adv_addr` to always skip the advert checks, but this is not a very safe way to run keepalived.

**Comment by achevalet** [comment]
Thanks for the quick reply. 
I've tested `skip_check_adv_addr` and it works (only) with a reload on the active node first. A restart on the active node or a reload or restart on the standby node creates the duplicate IPs mess. Options 2 and 3 might be hard to implement in my puppet managed environments with hundred of keepalived instances. 
I find this default behavior very unsafe. As both nodes are able to communicate with each other, it's weird that both nodes are able to mount the same IP address.. I'm now wondering what was the reason to change this behavior from 1.x (which is really safer imho) ;-)

**Comment by pqarmitage** [comment]
I think saying that the _default behaviour is very unsafe_ is very much a matter of opinion. From my point of view not checking the contents of an advert to ensure that it matches what is expected, i.e. to ensure that it is not a rogue advert, is _extremely_ unsafe, and the issue of an occasional reload that can be managed around is of somewhat lesser significance. 

What you are seeking to do is to run two vrrp instances with mismatched configurations, and that is not something that should be expected to work and as I quoted from the RFC above, it is perfectly valid to verify the received address count and addresses and to discard the advert if it doesn't match. A logical extension of what you are saying is that any advert should be accepted as valid, regardless of how many fields are wrong in it!

The point is that you want to do something that is unsupported and does not comply with the VRRP protocol. I believe that the correct way to reload mismatched configurations is to reload all instances at the same time. An alternative is to take down all the backup instances, reload the master, and then start up the backup instances with the new configuration. Either of these options ensures that you are not running with inconsistent configurations between your various VRRP instances at any time.

The timed reload feature was added in commit 6a4f372, which was the third commit after v2.0.20, and the patch should apply cleanly to v2.0.20 if you wanted to update to as close as possible to a released version and use timed reload, which was implemented precisely for this purpose.

You ask what has changed between v1.3.x and v2.0.x. Unfortunately I cannot remember exactly since there have been 2000 non-merge commits between v1.3.9 and v2.0.20 over the last 2 1/2 years, but I suspect it relates to adding more security by ensuring that the received advert matches what is expected to be received before accepting the advert.

We work very hard to attempt to ensure backward compatibility with all the changes we make, but occasionally when fixing incorrect or unsafe behaviour that simply is not possible.
