### ISSUE TITLE
Advert_int ping interval is not expected

### ISSUE THREAD

**Issue by Howard-Chang** [acassen/keepalived#1615]
**Describe the issue**
A clear and concise description of what the issue is.
When I set the advert_int to 0.5, and watch the tcpdump information.
like `tcpdump -i ens3 -nn 'vrrp' `
the output:
```
18:11:57.125350 IP 192.168.124.200 > 224.0.0.18: VRRPv2, Advertisement, vrid 51, prio 120, authtype simple, intvl 1s, length 20
18:11:58.126418 IP 192.168.124.200 > 224.0.0.18: VRRPv2, Advertisement, vrid 51, prio 120, authtype simple, intvl 1s, length 20
18:11:59.127615 IP 192.168.124.200 > 224.0.0.18: VRRPv2, Advertisement, vrid 51, prio 120, authtype simple, intvl 1s, length 20
18:12:00.128923 IP 192.168.124.200 > 224.0.0.18: VRRPv2, Advertisement, vrid 51, prio 120, authtype simple, intvl 1s, length 20
18:12:01.130152 IP 192.168.124.200 > 224.0.0.18: VRRPv2, Advertisement, vrid 51, prio 120, authtype simple, intvl 1s, length 20
```
It seems the ping interval not 0.5s. 
When I set the advert_int to 0.4s and watch the tcpdump information.
the output:
```
18:14:57.657457 IP 192.168.124.201 > 224.0.0.18: VRRPv2, Advertisement, vrid 51, prio 100, authtype simple, intvl 0s, length 20
18:14:57.657535 IP 192.168.124.201 > 224.0.0.18: VRRPv2, Advertisement, vrid 51, prio 100, authtype simple, intvl 0s, length 20
18:14:57.657632 IP 192.168.124.201 > 224.0.0.18: VRRPv2, Advertisement, vrid 51, prio 100, authtype simple, intvl 0s, length 20
18:14:57.657710 IP 192.168.124.201 > 224.0.0.18: VRRPv2, Advertisement, vrid 51, prio 100, authtype simple, intvl 0s, length 20
```

**To Reproduce**
Any steps necessary to reproduce the behaviour:
just set the `advert_int` to 0.4 or 0.5 and watch the tcpdump information `tcpdump -i ens3 -nn 'vrrp' `

**Expected behavior**
I think if I set the `advert_int` to 0.5, then keepalived backup should ping keepalived primary at intervals of 0.5s. However, it seems the frequency is at intervals of 1s
**Keepalived version**
Output of `keepalived -v`
`Keepalived v1.2.24`
**Distro (please complete the following information):**
 - Name [e.g. Fedora, Ubuntu] Ubuntu
 - Version [e.g. 29] 16.04
 - Architecture [e.g. x86_64] x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details
keepalived is running in qemu VM
**Configuration file:**
A full copy of the configuration file, obfuscated if necessary to protect passwords and IP addresses

**Notify and track scripts**
If any notify or track scripts are in use, please provide copies of them
```
vrrp_instance VI_1 {

    state BACKUP # Tag 為 BACKUP
    interface ens3
    virtual_router_id 51
    priority 100  # 權重要低於 MASTER
    nopreempt  #设置为不抢夺VIP
    advert_int 0.4
    mcast_src_ip 192.168.124.201 # vrrp 實體主機 IP

    authentication {
        auth_type PASS
        auth_pass 1111
    }

    virtual_routes {
        0.0.0.0/0 gw 192.168.124.4 # 0.0.0.0/0 gw 192.168.124.4
    }

    # VIP
    virtual_ipaddress {
        192.168.124.205 #192.168.124.205 # 提供的 VIP
    }

    notify_master "/root/haproxy/trans.sh MASTER"
    notify_backup "/root/haproxy/drop.sh BACKUP"

}
```

**System Log entries**
Full keepalived system log entries from when keepalived started
no
**Did keepalived coredump?**
If so, can you please provide a stacktrace from the coredump, using gdb.
no 
**Additional context**
no

**Comment by pqarmitage** [comment]
You should see a message in your system logs like:
`VRRPv2 advertisement interval 0.400000s must be an integer. rounding`
which explains what is happening.

With VRRP version 2 (VRRPv2), which is the default and also the version the you have to use if you want to use authentication, the advertisement interval has to be a whole number of seconds. If the advert interval is specified with fractions of a second it is rounded to the nearest second. In version 1.2.24 it doesn't check for rounding down to 0, and so specifying 0.4 will mean that keepalived is continuously sending adverts. In commit 043bbe5 (16 March 2017) I added a check to ensure that the interval could not be 0, and set the interval to 1 if it had been rounded to 0.

If you want to use an advert interval with fractions of a second, you will have to use VRRPv3. This means that you will have to stop using authentication, since it was removed from VRRPv3.

keepalived v1.2.24 is very old and there have been many enhancements, bug fixes and performance enhancements since the version; it is **strongly recommended** that you upgrade to version v2.0.20. If you do encounter any problems with keepalived v1.2.24, our response will wither be to upgrade to the latest version, or we will fix the issue in the current version; either way you would need to upgrade to the current version.

**Comment by Howard-Chang** [comment]
Hi @pqarmitage, I have update keepalived to `v2.1.2`, but  VRRP version is still 2(VRRPv2)
How could I update the VRRP to (VRRPv3)   

thanks a lot !

**Comment by pqarmitage** [comment]
@Howard-Chang The best way to find the answer to questions like this is to look at the man page - `man keepalived.conf`.

The answer to you question though is either specify `version 3` in the `vrrp_instance` block to make just that instance VRRPv3, or to specify `vrrp_version 3` in the `global_defs` block to make all vrrp_instances default to VRRPv3.

**Comment by Howard-Chang** [comment]
@pqarmitage thanks !
It can work correctly now.
