### ISSUE TITLE
Use configured interface for VRRP messages

### ISSUE THREAD

**Issue by leonshaw** [acassen/keepalived#1685]
**Is your feature request to resolve a problem or provide enhanced functionality? Please describe.**
When configuring VRRP on a macvlan interface `A` with `use_vmac` and `vmac_xmit_base` enabled, keepalived creates another macvlan interface `B` for data traffic and uses the main interface for VRRP. And if the main interface is in another netns, VRRP messages are sent via `B` instead.
The expected behavior is to send VRRP messages via configured interface `A`.

**Describe the solution you would like**
Add an option like `vmac_xmit_configured`, and use `configured_ifp` for VRRP.

**Describe alternatives you have considered**
Change the behavior of `vmac_xmit_base` as above.

**Would the feature request be of benefit only to you, or is it more generally applicable?**
I believe most of time people would want to use configured interface. The word "base" is a bit confusing.

**Keepalived version**
```
Keepalived v2.0.20 (01/22,2020)

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.3.1
Running on Linux 5.7.4-arch1-1 #1 SMP PREEMPT Thu, 18 Jun 2020 16:01:07 +0000

configure options: --prefix=/usr --sysconfdir=/etc --sbindir=/usr/bin --localstatedir=/var --runstatedir=/run CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now CPPFLAGS=-D_FORTIFY_SOURCE=2

Config options:  NFTABLES LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RESET_ON_FORK
```

**Comment by pqarmitage** [comment]
`use_vmac` tells keepalived to create a macvlan interface on the interface specified in the vrrp instance. `vmac_xmit_base` means that keepalived will send adverts on the base interface, i.e. the interface on which the macvlan has been created.

When a macvlan A is created and the base interface B specified is itself a macvlan with base interface C, the new macvlan is created on the base interface C of the specified macvlan B and not on the macvlan B specified (you can verify this using the `ip link add` command). With this in mind, if `use_vmac` is specified, and the `interface` configured is a macvlan B with base interface C, keepalived directly creates its macvlan on the base interface C of the specified interface. So although keepalived changes the interface it creates its macvlan on from B to C, it is merely doing what the kernel will do anyway.

You state `The expected behavior is to send VRRP messages via configured interface A`, but this is not the case if `vmac_xmit_base` is configured; it precisely means not to send the VRRP messages on interface A.

If the base interface C is in a different namespace from the one in which keepalived is running, keepalived cannot specify interface C as the base interface of its macvlan A, and has to specify B as the base interface, although the kernel will create the macvlan A with C as the base interface. Since keepalived has no access to interface C, `vmac_xmit_base` makes keepalived send adverts via interface B.

I am not entirely clear what you mean by `Add an option like vmac_xmit_configured, and use configured_ifp for VRRP.` Do you mean that `vmac_xmit_configured` should be a synonym for `vmac_xmit_base`?

We cannot change the behaviour of `vmac_xmit_base` since we cannot change the way existing configurations are working.

Would it help if the description of `vmac_xmit_base` were improved in the keepalived.conf(5) man page?

**Comment by leonshaw** [comment]
@pqarmitage The current behavior is that, if C is in a different namespace, packets are sent via interface A (not B).
I mean by adding `vmac_xmit_configured` option, packets will be send via the configured interface B (as specified by `interface B`), regardless of its type or whether it's the base interface of A.

**Comment by pqarmitage** [comment]
The reason for that is that interface B is not the base interface of interface C, and that keepalived cannot access the base interface of interface A, since interface C is in a different namespace (keepalived doesn't do network namespace hopping).

I will have a look at the feasibility of adding `vmac_xmit_configured` to send packets on interface B.

As a matter of interest, can you please explain why you want the adverts to be sent on interface B rather than on interface A.

**Comment by leonshaw** [comment]
@pqarmitage VRRP sent via A may cause VMAC flapping between two ports in the MAC address table of a switch.

**Comment by pqarmitage** [comment]
@leonshaw I have now tested this with keepalived v2.1.5 and for IPv4 it behaves as you have requested and so no change is needed to the code.

There are some issues in the current code with IPv6 and also what happens when addresses are added to and deleted from interfaces, and I am working on resolutions for those now.

**Comment by leonshaw** [comment]
@pqarmitage Cool. Verified on my testbed.
