### ISSUE TITLE
Running keepalived VRRP traffic on a separate network, vrrp_sync_group and track script

### ISSUE THREAD

**Issue by szahri** [acassen/keepalived#1703]
Hi there,
I have a requirement for Keepalived running VRRP on 2 load balancers (NGINX)  with 2 interfaces - eth0 (external) and eth1 (internal).
I am trying to configure a setup where all VRRP traffic (preferably unicast) is run via the dedicated internal eth1 interface, to reduce the risk of a split brain situation. However, the floating IP address (VRRP IP) will be on eth0 (external) network.

I was looking at [https://github.com/acassen/keepalived/issues/637] and trying to do something similar.  My config is below :

````
global_defs {
   notification_email_from myadmin@myserver
   smtp_server localhost
   smtp_connect_timeout 30
   router_id LVS_DEVEL
}

vrrp_script check_nginx {
    script "/usr/libexec/keepalived/check_nginx.sh"
    interval 3
}

vrrp_sync_group link_instances {
    group {
        real
        stop_duplicate
    }
}

vrrp_instance real {
    state BACKUP
    interface eth0
    virtual_router_id 1
    priority 250               # This will be a lower value on the other router
    version 3                  # not necessary, but you may as well use the current protocol
    advert_int 1
    nopreempt

    track_interface {
        eth1
    }

    track_script {
        check_nginx
    }

    unicast_src_ip 115.197.1.166
    unicast_peer {
    115.197.1.167
    }

     virtual_ipaddress {
          115.197.1.170/32 dev eth0
    }
}

vrrp_instance stop_duplicate {
    state BACKUP
    interface eth1
    virtual_router_id 1
    priority 255             
    version 3
    advert_int 1
    nopreempt

    unicast_src_ip 192.168.0.3
    unicast_peer {
    192.168.0.4
    }

    virtual_ipaddress {
        192.168.0.5/29         
  }
}
````

The problems I have with this setup so far:
1) On the master, I forcefully brought down eth1 (internal interface). This subsequently triggered a failover of keepalived and the state transitioned to fault. Not really a behaviour I was expecting, because I thought the idea is for it to "use" the external eth0 in this case to communicate (which is still up and running external VRRP), so this would provide resiliency. Is it possible, when eth1 is detected as down, for the failover NOT to be triggered, and instead wait for eth1 to also fail, in order for it to fail over?

2) I got the warning that my track_script `check_nginx` is  not used. Is the use of `track_scripts` still not allowed within `vrrp_sync_group`? Because I still need this to work in the event of NGINX failure scenario.

3) Could I use preempt within `vrrc_sync_group`? Because I would like to prevent failback once it moves across.

3) Is there a better way of doing this? What I want to achieve is:
a. Ensure that the VRRP traffic is used on internal (dedicated) interface `eth1` and the floating VRRP IP to reside on `eth0`. This is so we dont need to depend on external network for heartbeat. 
b. In the event of failure of eth0, DONT fail over to the BACKUP node,  if  eth1 is still alive. Only failover if that one is also down (as it should).  
c. If `check_nginx` fails however, this will trigger a failover.
d. Once it fails over, it will not fail back - unless the same failure scenarios happen to it (eg NGINX being down)

Wondering if what I'm trying to achieve is possible or not??

Thanks
J

**Comment by pqarmitage** [comment]
Additional information provided on keepalived-users@groups.io

Result of keepalived –v for your reference:

[root]# keepalived -v
Keepalived v2.1.2 (06/14,2020)

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 3.10.0
Running on Linux 3.10.0-1127.el7.x86_64 #1 SMP Tue Feb 18 16:39:12 EST 2020

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-nftables --disable-iptables --with-init=systemd build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic LDFLAGS=-Wl,-z,relro

Config options:  LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV6_ADVANCED_API RTA_ENCAP RTA_EXPIRES RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTA_VIA FRA_OIFNAME IFA_FLAGS IP_MULTICAST_ALL NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION VRRP_VMAC IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE SO_MARK SCHED_RESET_ON_FORK

**Comment by pqarmitage** [comment]
>  I am trying to configure a setup where all VRRP traffic (preferably unicast) is run via the dedicated internal eth1 interface, to reduce the risk of a split brain situation.

I am not clear why using the internal interface reduces the risk of a split brain situation, but there is no problem doing this. However, your configuration is running VRRP over eth0 (external) for vrrp_instance real. The `interface` keyword specifies the interface that is used for VRRP traffic.
> 1.  On the master, I forcefully brought down eth1 (internal interface). This subsequently triggered a failover of keepalived and the state transitioned to fault. Not really a behaviour I was expecting, because I thought the idea is for it to "use" the external eth0 in this case to communicate (which is still up and running external VRRP), so this would provide resiliency. Is it possible, when eth1 is detected as down, for the failover NOT to be triggered, and instead wait for eth1 to also fail, in order for it to fail over?

Let's call the system with the higher priority (priority 250) System A, and the other system System B.

The stop_duplicate vrrp_instance is running over eth1, and so if eth1 is taken down on System A, the VRRP instance will transition to fault state. If it didn't transition to fault state, then in normal circumstances you would end up with System A remaining in master state, but System B would also transition to master state, since it would no longer see adverts from System A due to System A's eth1 being down. Since you have both the real and the stop_duplicate instances in a sync group, then if with one of the vrrp instances goes to fault state, the other will as well.

There is a `dont_track_primary` keyword that would mean that the vrrp instance would not go to fault state if eth1 goes down, and this might achieve what you say you want. However, if eth1 is down on System A, the system would not be able for forward any traffic internally, so would you really want it to remain as master for the real vrrp_instance?

> 2. I got the warning that my track_script check_nginx is not used. Is the use of track_scripts still not allowed within vrrp_sync_group? Because I still need this to work in the event of NGINX failure scenario.

The track_script should be configured in the sync group and not in the vrrp_instance. I need to look into why there is no message about why it is not being used on the vrrp instance.

> 3. Could I use preempt within vrrc_sync_group? Because I would like to prevent failback once it moves across.

Although `preempt` is a valid keyword in a vrrp instance, it does nothing since it is the default. `preempt` or `nopreempt` are not valid keywords in a vrrp_sync_group - see the keepalived.conf(5) man page for what is valid configuration. Specifying `nopreempt` on the vrrp instances will achieve want you want.

> 4. Is there a better way of doing this? What I want to achieve is:
    a. Ensure that the VRRP traffic is used on internal (dedicated) interface eth1 and the floating VRRP IP to reside on eth0. This is so we dont need to depend on external network for heartbeat.
    b. In the event of failure of eth0, DONT fail over to the BACKUP node, if eth1 is still alive. Only failover if that one is also down (as it should).
    c. If check_nginx fails however, this will trigger a failover.
    d. Once it fails over, it will not fail back - unless the same failure scenarios happen to it (eg NGINX being down)

I don't understand requirement b). If eth0 is down on the master, the VIP 115.197.1.170 will not be able to work, and under normal circumstances that is precisely when you would want the other system to take over as master. I''m wondering if you have eth0 and eth1 the wrong way round here, which would be consistent with what you describe under point 1. If that is the case, then the answer is NO, since the VRRP instances cannot communicate with each other; the only way to achieve that is to use eth0 for the VRRP traffic.

The following configuration meets the requirements of 4 above, excluding b), which is not possible:
```
global_defs {
   notification_email_from myadmin@myserver
   smtp_server localhost
   smtp_connect_timeout 30
   router_id LVS_DEVEL
}

vrrp_script check_nginx {
    script "/usr/libexec/keepalived/check_nginx.sh"
    interval 3
}

vrrp_instance real {
    state BACKUP
    interface eth1
    virtual_router_id 1
@A   priority 250               # This will be a lower value on the other router
@B   priority 240
    version 3                  # not necessary, but you may as well use the current protocol
    advert_int 1
    nopreempt

    track_script {
        check_nginx
    }

@A    unicast_src_ip 192.168.0.3
@B    unicast_src_ip 192.168.0.4
    unicast_peer {
@A    192.168.0.4
@B    192.168.0.3
    }

     virtual_ipaddress {
          115.197.1.170/32 dev eth0
    }
}
```
If you don't want the vrrp instance to go to fault state if eth1 is down, then you will have to change the configuration to use `interface eth0`, and change the unicast addresses accordingly (or just let it use multicast, in accordance with the standard).

There are other possible configurations, depending on what you really want to achieve. 

BTW you really should upgrade to keepalived v2.1.5 since there were some issues with earlier v2.1.x versions.

**Comment by pqarmitage** [comment]
@szahri Commit 459fc2b restores being able to configure track scripts on vrrp instances which are part of a sync group.

**Comment by szahri** [comment]
@pqarmitage thanks very much for your comments. Really appreciate the helpful hints and efforts you put into helping everyone.

What you had outlined above all made sense (and yes I did swap the eth0 and eth1 around...sorry!). I tried the suggested config and it all worked the way you described it would. Hurray!

I am dissapointed that it is not possible to "move" the heartbeat interface when the default one (eth1) fails or unable to be contacted by its peer. So just to confirm, there is no concept of a "backup" heartbeat interface that it can possibly ping before it fails over?

I will download v2.1.5 and give it a go. Thanks again, J

**Comment by pqarmitage** [comment]
@szahri There is a feature that you might be able to use to fall back to using eth0 for adverts if eth1 fails but it depends on your network configuration and routing setup.

When using unicast, it is no longer necessary to specify the interface for the VRRP instance, and in that case the adverts will be sent on the interface as determined by the routing table. If you created a dummy address on the lo interface on each system, let's say 192.168.255.0/32 on A and 192.168.255.1/32 on B, and then add routing entries on A to route to 192.168.255.1/32 via both eth1 and eth0, with the higher priority route being via eth1, and likewise on B, then so long as the systems can detect that the route via eth1 has gone down, then the adverts will be sent via eth0.

The challenge will be to make the systems switch to using the route via eth0 if eth1 is down; you could try using a dynamic routing protocol such as OSPF.

**Comment by Jexbat** [comment]
@pqarmitage This is really good, but there is still a problem, what if I want vmac in eth0. If I configure `use_vmac` in `vrrp_instance real` the vmac will be on the eth1. How to use the vmac on eth0 and send VRRP traffic on eth1?
