### ISSUE TITLE
notify fifo script terminates abruptly

### ISSUE THREAD

**Issue by VasumathyJ** [acassen/keepalived#1712]
Hello
I am using VRRP. For the state change notification I am using the notify_fifo script
I have these in my global defs 
vrrp_notify_fifo /tmp/vrrp_notify_fifo
vrrp_notify_fifo_script /etc/keepalived/scripts/sample_notify_fifo.sh

I am using the same example from the doc/samples/sample_notify_fifo.sh

The script is abruptly stopping here as seen in keepalived_vrrp.log
Tue Aug  4 19:42:03 2020: Printing VRRP as json for process(16833) on signal
Tue Aug  4 19:42:03 2020: vrrp notify fifo script terminated

Always I see it stops after the JSON signal seems to be sent to the process.
what is missing in the script ?
I am using a replica of the sample script doc/samples/sample_notify_fifo.sh

**Comment by pqarmitage** [comment]
@VasumathyJ Unfortunately due to the lack of information you have provided all I can say is that the notify script does not terminate for me after sending the JSON signal to the keepalived process. Consequently there is nothing more that I can investigate at the moment.

We have templates for reporting issues, which specify what information is needed in order for us to investigate an issue; however you appear to have ignored the templates and hence not provided the necessary information.

I have set out below the information that we request for a bug report, and if you provide that we will then be able to investigate further.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Any steps necessary to reproduce the behaviour:

**Expected behavior**
A clear and concise description of what you expected to happen.

**Keepalived version**
Output of `keepalived -v`

**Distro (please complete the following information):**
 - Name [e.g. Fedora, Ubuntu]
 - Version [e.g. 29]
 - Architecture [e.g. x86_64]

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details

**Configuration file:**
A full copy of the configuration file, obfuscated if necessary to protect passwords and IP addresses

**Notify and track scripts**
If any notify or track scripts are in use, please provide copies of them

**System Log entries**
Full keepalived system log entries from when keepalived started

**Did keepalived coredump?**
If so, can you please provide a stacktrace from the coredump, using gdb.

**Additional context**
Add any other context about the problem here.

**Comment by pqarmitage** [comment]
Closing due to no response for over 1 week. If you are still experiencing the issue and can provide the information requested above, please do so and we can reopen this issue.

**Comment by VasumathyJ** [comment]
Hello, I was also not able to figure out what is causing the script to terminate abruptly on my system. 
I have keepalive 2.0.19 version.
For now what I am doing is patching the keepalived source code in my environment to directly call my custom code anytime there is a state change.
send_instance_notifies - here i added my custom code to take the action I require
That source code patch seems to be working for me for now, so I am proceeding with this approach.

**Comment by pqarmitage** [comment]
@VasumathyJ Can you provide a copy of your patch; it might be something we would like to incorporate into keepalived.

**Comment by VasumathyJ** [comment]
I wasnt able to update the ticket anymore as it says it is resolved now. The code change is nothing much, I just patched it to call my custom code here 
1 Index: keepalived-2.0.19/keepalived/vrrp/vrrp_notify.c    2 ===================================================================    3 --- keepalived-2.0.19.orig/keepalived/vrrp/vrrp_notify.c    4 +++ keepalived-2.0.19/keepalived/vrrp/vrrp_notify.c    5 @@ -262,6 +262,9 @@ send_instance_notifies(vrrp_t *vrrp)    6         notify_script_t *script = get_iscript(vrrp);    7         notify_script_t *gscript = get_igscript(vrrp);    8      9 +        log_message(LOG_INFO, "send_instance_notifies to my custom process when any state change");             10 +        send_vrrp_state_change_to_my_process(vrrp);       21 void send_vrrp_state_change_to_my_process(vrrp_t *vrrp)    22 +{    23 +       24 +       25 +    26 +   switch(vrrp->state)    27 +   {    28 +     case VRRP_STATE_MAST:    29 +         //My custom code for Master event    30 +         break;    31 +     32 +     case VRRP_STATE_BACK:    33 +          //My custom code for Backup event    34 +          break;    35 +    36 +     case VRRP_STATE_FAULT:    37 +          //My custom code for Fault event    38 +          break;    39 +   }    40 +}      

    On Tuesday, 1 September 2020, 16:19:29 GMT+5:30, Quentin Armitage <notifications@github.com> wrote:  
 
 


@VasumathyJ Can you provide a copy of your patch; it might be something we would like to incorporate into keepalived.
