### ISSUE TITLE
Missing error check of function setrlimit()

### ISSUE THREAD

**Issue by lc3412** [acassen/keepalived#1713]
Hi,

Function setrlimit() controls maximum resource consumption and returns -1 to indicate the error. However, as shown in the following code,  the return value of function setrlimit() (line 203, line 207) is not checked. 

https://github.com/acassen/keepalived/blob/02b9cb9989dd7d115fe0d1c9694286e145de24aa/lib/process.c#L202-L209

===================================================================================

Furthermore, I find the return value of this call has been checked in the other call sites. For example, see the following code from the same source file:

https://github.com/acassen/keepalived/blob/02b9cb9989dd7d115fe0d1c9694286e145de24aa/lib/process.c#L142-L143
https://github.com/acassen/keepalived/blob/02b9cb9989dd7d115fe0d1c9694286e145de24aa/lib/process.c#L184-L185
https://github.com/acassen/keepalived/blob/02b9cb9989dd7d115fe0d1c9694286e145de24aa/lib/process.c#L339-L340

**Comment by pqarmitage** [comment]
@lc3412 Many thanks for reporting this, and yes, on the face of it it does look wrong.

The reason that the return values of setrlimit() at lines 203 and 207 are not checked is because the values that are being set in these cases are the original values that the keepalived process started with, and therefore they should be valid values. Looking at the possible errors returned according to the setrlimit man page:
- **EFAULT** That would be a coding error, and since the `orig_fd_limit` and `core` structures have already been written to by a previous `getrlimit()` call, this error cannot occur.
- **EINVAL** Again, since the values being set are previous values, this error cannot occur.
- **EPERM** keepalived is a privileged process and so the first EPERM reason cannot occur
- **EPERM** In theory this could occur if /proc/sys/fs/nr_open had been decreased since keepalived started and originally read this value
- **EPERM** The third EPERM reason only applies to prlimit()
- **ESRCH** This only applies to prlimit()

The question would then be, what action should keepalived take if an error is returned? It could log it, but would that really be useful? The times when reset_process_priorities() is called is i) when keepalived is reloading and ii) when keepalived runs another process for notifies or a check script and I think in these cases, the reload or executing the process/script should continue regardless of whether the `setrlimit()` failed.

Do you agree with the above, or do you think keepalived should take some specific action in the event of `setrlimit()` failing? I am happy to add a comment explaining why the return value from the setrlimit() calls is not checked if you think that would help.

**Comment by lc3412** [comment]
Thank you very much for your patience in explaining the context.  I am still considering about the possible consequences of the function setrlimit() failure.  What kind of actions should keepalived take if function failure happens?   Furthermore, I totally agree with your opinion that error log helps, but it cannot solve the problem essentially.

**Comment by pqarmitage** [comment]
Closing due to no update for over 1 month. If you have any further issues with this, please add a further comment and this issue can be reopened.
