### ISSUE TITLE
Missing error check of function setpriority()

### ISSUE THREAD

**Issue by lc3412** [acassen/keepalived#1714]
Hi,

Function setpriority() sets the priority for the process and returns -1 on error.  However, as shown in the following code,  the return value of function setpriority() is not checked. 

https://github.com/acassen/keepalived/blob/02b9cb9989dd7d115fe0d1c9694286e145de24aa/lib/notify.c#L84

=================================================================================

Furthermore, the return value of function setpriority() from other call sites are both checked.  See the following code, such as,

https://github.com/acassen/keepalived/blob/02b9cb9989dd7d115fe0d1c9694286e145de24aa/lib/process.c#L90-L93
https://github.com/acassen/keepalived/blob/02b9cb9989dd7d115fe0d1c9694286e145de24aa/lib/process.c#L102-L105

**Comment by pqarmitage** [comment]
@lc3412 Again, many thanks for reporting this issue.

I think largely the same answer as issue #1713 applies. To set the scene, the `set_privileges()` function is called before keepalived calls another script or process.

I think it is impossible for the `setprioriy()` call to fail. The following errors are listed on the man page:
- **EINVAL** which is PRIO_PROCESS, and so this error cannot occur
- **ESRCH** who is 0, meaning the calling process, and so this error can't occur
- **EACCES** This error can only occur if setting a lower nice value, whereas this call to `setpriority()` can only set a higher nice value
- **EPERM** This error cannot occur, since the effective UID and real UID must match since it is changing the priority of itself, but also keepalived is privileged which also means that the error cannot occur.

Again, if you think the above is not sufficient, or you think a comment in the code would help, or you have any other thoughts about it, please add them to this issue.

**Comment by pqarmitage** [comment]
Not only was the code above never called, but also it is completely superfluous since the process privilege was already being reset in reset_process_priority(). Commit e85dfd7 removes the redundant code.

Many thanks for raising this issue - it has resulted in a significant cleanup of the code handling running scripts.
