### ISSUE TITLE
1.2.18 - ipv6 BACKUP fails with "Invalid VRRPv2 checksum"

### ISSUE THREAD

**Issue by SjonHortensius** [acassen/keepalived#172]
I've just upgraded 2 clusters of native_ipv6 keepalived machines to 1.2.18 and both of them have the same issue. My configuration is still the same as posted in https://github.com/acassen/keepalived/issues/70#issue-26595061.

The MASTER comes up fine and broadcasts without problems. The backup however, says:

```
Jul 03 07:27:28 host Keepalived[9094]: Starting Keepalived v1.2.18 (07/01,2015)
Jul 03 07:27:28 host Keepalived[9094]: Starting Healthcheck child process, pid=9095
Jul 03 07:27:28 host Keepalived_healthcheckers[9095]: Initializing ipvs 2.6
Jul 03 07:27:28 host Keepalived_healthcheckers[9095]: Registering Kernel netlink reflector
Jul 03 07:27:28 host Keepalived_healthcheckers[9095]: Registering Kernel netlink command channel
Jul 03 07:27:28 host Keepalived_healthcheckers[9095]: Opening file '/etc/keepalived/keepalived.conf'.
Jul 03 07:27:28 host Keepalived_healthcheckers[9095]: Configuration is using : 11980 Bytes
Jul 03 07:27:28 host Keepalived_healthcheckers[9095]: Using LinkWatch kernel netlink reflector...
Jul 03 07:27:28 host Keepalived[9094]: Starting VRRP child process, pid=9096
Jul 03 07:27:28 host Keepalived_vrrp[9096]: Registering Kernel netlink reflector
Jul 03 07:27:28 host Keepalived_vrrp[9096]: Registering Kernel netlink command channel
Jul 03 07:27:28 host Keepalived_vrrp[9096]: Registering gratuitous ARP shared channel
Jul 03 07:27:28 host Keepalived_vrrp[9096]: Opening file '/etc/keepalived/keepalived.conf'.
Jul 03 07:27:28 host Keepalived_vrrp[9096]: Configuration is using : 70705 Bytes
Jul 03 07:27:28 host Keepalived_vrrp[9096]: Using LinkWatch kernel netlink reflector...
Jul 03 07:27:28 host Keepalived_vrrp[9096]: VRRP_Instance(VI_2) Entering BACKUP STATE
Jul 03 07:27:28 host Keepalived_vrrp[9096]: Remote SMTP server [x:x:x]:25 connected.
Jul 03 07:27:28 host Keepalived_vrrp[9096]: VRRP_Script(check_nginx) succeeded
Jul 03 07:27:28 host Keepalived_vrrp[9096]: SMTP alert successfully sent.
Jul 03 07:27:28 host Keepalived_vrrp[9096]: Invalid VRRPv2 checksum
Jul 03 07:27:28 host Keepalived_vrrp[9096]: bogus VRRP packet received on eth0 !!!
Jul 03 07:27:28 host Keepalived_vrrp[9096]: VRRP_Instance(VI_2) ignoring received advertisment...
Jul 03 07:27:29 host Keepalived_vrrp[9096]: Invalid VRRPv2 checksum
Jul 03 07:27:29 host Keepalived_vrrp[9096]: bogus VRRP packet received on eth0 !!!
Jul 03 07:27:29 host Keepalived_vrrp[9096]: VRRP_Instance(VI_2) ignoring received advertisment...
Jul 03 07:27:30 host Keepalived_vrrp[9096]: Invalid VRRPv2 checksum
Jul 03 07:27:30 host Keepalived_vrrp[9096]: bogus VRRP packet received on eth0 !!!
Jul 03 07:27:30 host Keepalived_vrrp[9096]: VRRP_Instance(VI_2) ignoring received advertisment...
```

Another cluster that uses ipv4 exclusively seems to work fine

**Comment by acassen** [comment]
code merged on this part broke stuff. Will provide a patch to fix this...

**Comment by SjonHortensius** [comment]
thanks for the update, I've held back the upgrade

**Comment by acassen** [comment]
just commited the fix. Please give it a try and report.

**Comment by SjonHortensius** [comment]
@acassen It works fine, thanks for the quick fix. Will you release a new version? Also, could you elaborate on the "compliant" method of using vrrp on native ipv6 mentioned in the commit?

**Comment by acassen** [comment]
I will push a new release this week (today maybe). My point on the "compliant" is really not an issue at all, just a side effect of current implementation. The point is: VRRPv2 and v3 are not computing VRRP checksum the same way. VRRPv2 will expect a checksum over VRRPv2 header only while VRRPv3 will expect checksum over VRRPv3 header + pseudo header (rfc5798.5.2.8). Current Keepalived code is using IPV6_CHECKSUM socket option on all IPv6 sockets in order to offload VRRP checksum field computation to kernel, but this option will compute checksum as specified in rfc5798.5.2.8 (which is the way protocol in v6 world should use cksum). So if you are running VRRPv2 on top of IPv6 this checksum will include inconditionnally IPv6 pseudo header while VRRPv2 is not expecting it that way. My point here is : this is just a tiny side effect.

workaroung or say better way is to use VRRPv3 when you are using VRRP on top of IPv6. In other words in vrrp_instance when using "native_ipv6" use also "version 3"

regs,

**Comment by SjonHortensius** [comment]
Thanks for your explanation. I'll have a look at native_ipv6 + version3; I didn't realize I wasn't using that while it is available.

**Comment by acassen** [comment]
vrrp_instance VI_1 {
    interface eth0
    state MASTER
    native_ipv6
    version 3                   <<<<==== "space between version and 3"
    virtual_router_id 50
    priority 100
    virtual_ipaddress {
        192.168.0.105
    }
}
