### ISSUE TITLE
send VRRP traffic on eth0 and use vmac on eth1

### ISSUE THREAD

**Issue by JesseGuoX** [acassen/keepalived#1743]
Hi there,
I have a requirement for send  VRRP traffic on eth0 and use vmac on eth1. If I configure `use_vmac` in `vrrp_instance`, the vmac will on the ethx which is the interface value configured in `vrrp_instance`. Is there any other way to config for this requirement? 
Thank you.
#1703

**Comment by pqarmitage** [comment]
@Jexbat Can you confirm that your configuration looks something like:

```
vrrp_instance XXXX {
   ...
   interface eth0
   use_vmac
   ...
   virtual_ipaddress {
        a.b.c.d dev eth1
   }
   ...
}
```
and in particular where eth0 and eth1 are specified.

Since the only purpose of using VMACs is to ensure that the virtual IP addresses reside on interfaces with 00:00:5e:00:01:nn MAC addresses (assuming IPv4), it seems to me that if `use_vmac` is specified, then a VMAC should be created on all the interfaces on which virtual IP addresses are configured. For example:
```
vrrp_instance XXXX {
   interface eth0
   use_vmac
   virtual_ipaddress {
       a.b.c.d dev eth3
       e.f.g.h dev eth5
   }
```
should create VMACs on both eth3 and eth5, but there is no benefit in creating a VMAC on eth0, except that the VRRP RFC states that adverts should be send using the virtual MAC address. However, I don't want to change the way keepalived works with current configurations, so I think we should do as follows.

My thoughts with this are to add a keyword `use_vmac_addr`, which means use VMACs on each interface on which a VIP is configured, and leave `use_vmac` to work as it does now, in other words to create a VMAC on the configured interface. So using the above sample configuration, `use_vmac` would create a VMAC on eth0, `use_vmac_addr` would create VMACs on eth3 and eth5, and specifying both `use_vmac` and `use_vmac_addr` would create VMACs on eth0, eth3 and eth5.

I'm not sure that this is a trivial change, but I think it is the right thing to do.

Could you please confirm that what I have outlined above would meet your needs, and also whether it seems sensible to you or not.

**Comment by Jexbat** [comment]
@pqarmitage  Thank you for your reply. This is exactly what I need, and `use_vmac_addr ` could be a good idea.

**Comment by acassen** [comment]
Hello, use_vmac_addr is great option, or we could consider using `use_vmac` per vip definition ? Something like : 

```
vrrp_instance XXXX {
   interface eth0
   virtual_ipaddress {
       a.b.c.d dev eth3 use_vmac
       e.f.g.h dev eth5
   }
```

that way you could have the choice to only use VRRP VMAC for a specific VIP leaving others with regular behaviour.

**Comment by Jexbat** [comment]
Good idea, but it should ignore the `eth0`  interface use VMACs  if configured like:
```
vrrp_instance XXXX {
   interface eth0
   use_vmac
   virtual_ipaddress {
       a.b.c.d dev eth3 use_vmac
       e.f.g.h dev eth5 use_vmac
   }
```

**Comment by pqarmitage** [comment]
I think I will implement both ideas, If there are multiple VIPs then specifying `use_vmac` against each VIP would be a bit tedious, and just specifying `use_vmac_addr` against the VRRP instance would be simpler (the only difference in the code will be at config parsing time).

Regarding @Jexbat's last comment, I think
```
vrrp_instance XXXX {
   interface eth0
   use_vmac
   virtual_ipaddress {
       a.b.c.d dev eth3 use_vmac
       e.f.g.h dev eth5 use_vmac
   }
```
should create and use a VMAC on eth0, whereas
```
vrrp_instance XXXX {
   interface eth0
   virtual_ipaddress {
       a.b.c.d dev eth3 use_vmac
       e.f.g.h dev eth5 use_vmac
   }
```
should not use a VMAC on eth0. We need to allow either option, and I think this is the way of doing it.

Now the complication with allowing `use_vmac` against each MAC address. What does
```
vrrp_instance XXXX {
   interface eth0
   virtual_ipaddress {
       a.b.c.d dev eth3 use_vmac
       e.f.g.h dev eth3
   }
```
mean? I think that can work to mean a.b.c.d uses the VMAC but e.f.g.h doesn't. Is it sensible? or can we not think of a use case for it now, but someone might have one in the future?

Do we need to allow specifying a VMAC interface name after `use_vmac` on a VIP, or even with `use_vmac_addr`? The latter could only work if all the VIPs (and eVIPs) were on the same interface. The trouble with allowing `use_vmac` on a VIP to specify an interface name is:
```
vrrp_instance XXXX {
   interface eth0
   virtual_ipaddress {
       a.b.c.d dev eth3 use_vmac vrrp3.0
       e.f.g.h dev eth3 use_vmac vrrp3.1
   }
```
cannot work. For a given interface we must use the same VMAC interface name.

Perhaps `use_vmac_addr` should specify a template for the VMAC interface name, such as
```
    use_vmac_addr vrrp.${_IF}.${_VRID}
```
where ${_IF} means the interface of the VIP, etc.

Or do we just say _blow this for a lark_ this is just getting too complicated, and let keepalived decided the interface names as it does so now if no name is specified. I think if we do that, then we need to add a global def `vmac_name_template` keyword; this would be straightforward, since the current template name "vrrp" is hard coded in vrrp_complete_instance(). The reason for adding a template is that if more than one keepalived instance is running in the same network namespace, it enables avoiding the risk of interface name conflicts. It may be that for kernels v5.5 onwards we can make use of the altname link property which allows alternative link name up to 127 characters long.

**Comment by pqarmitage** [comment]
I have just been reading RFC5798, for another reason, and have come across the following in Paragraph 2.4:
> If the virtual router MAC address is never used as the source address in a
   link-level frame, then the station location is never learned,
   resulting in flooding of all packets sent to the virtual router.  To
   improve the efficiency in this environment, the protocol should:
   1\) use the virtual router MAC address as the source in a packet sent
   by the Master to trigger station learning; 2\) trigger a message
   immediately after transitioning to the Master to update the station
   learning; and 3\) trigger periodic messages from the Master to
   maintain the station learning cache.

1\) and 2\) are fine, but currently the default configuration means that 3\) is only done for the interface of the VRRP instance, which is implemented by sending the VRRP adverts with the source MAC address of the virtual router.

When we implement VMACs for VIPs on different interfaces, we will need to ensure that periodic gratuitous ARPs/NDs are sent to fulfil the requirement. This can be configured using `vrrp_garp_master_refresh_repeat`, but we will need to ensure that it is enabled automatically for VIPs using VMACs on interfaces on which the VRRP adverts are not being sent. I think we only need to do it automatically for one VIP per VMAC, since it is the station learning cache that we are wanting to refresh (it could be that it cycles through the VIPs per VMAC).

This is really a '_note to self_' as a reminder for when implementing this. However, as usual, any thoughts on this would be welcome.

**Comment by acassen** [comment]
Mixing `use_vmac` and not using it into the same virtual_ipaddress block could be usefull for some reasons we just dont think about right now :) but most of the time users are thinking and using it in a way I just would never has been though about. Just reading this morning the post, highlight it would be maybe more generic that way... But anyway if this just introduce too much complicated design we can consider then `use_vmac_addr` is best, while reading the VMAC part it is certainly much more simple to implement `use_vmac_addr`.

**Comment by pqarmitage** [comment]
Commit 3dcd13c adds the ability to specify using VMACs for addresses not on the VRRP instance's interface.

1. `use_vmac_addr` can be specified on a `vrrp_instance` so that all VIPs/eVIPs not on the VRRP instance's interface are on VMACs.
1. `use_vmac` can be specfied per VIP/eVIP to achieve the same result for individual addresses.
1. `vmac_prefix` allows the default prefix of VMAC names for a primary VMAC
1. `vmac_addr_prefix` allows specifying the default VMAC name prefix for VIPs/eVIPs on other interfaces
1. Global `vrrp_garp_extra_if [all]` and per VRRP instance `garp_extra_if [all]` enable sending periodic GARP/NA messages for VIPs/eVIPs not on a VRRP instance's primary interface (more details below).

Re point 5. above, if a VIP/eVIP is configured on a VMAC on a different interface from the primary VRRP interface, no traffic will normally be sent with the source MAC address of the VMAC interface, since VRRP adverts will be sent on the primary VRRP interface. This means that any network switches that cache MAC addresses will expire the VMAC's MAC address, typically after 300 seconds (note: this is (was) also a problem when using `vmac_xmit_base`). Sending periodic GARP/NA messages on those interfaces will refresh the MAC caches in switches, and avoid any packets sent to the VMAC's MAC address flooding the whole layer 2 network. The only instance where packets will normally be sent using the VMAC's MAC address is when using IPVS with NAT forwarding. If `all` is not specified, GARP/NA messages will only be sent on each VMAC configured; specifying `all` will also send the GARP/NA messages for VIPs on other interfaces that are not using VMACs.

The one feature that has not yet been implemented is detecting if the address based VMACs are deleted, and subsequently recreating them (this is done for a primary VMAC interface but not yet for the address based ones).

**Comment by nightguide** [comment]
@pqarmitage @acassen Hi!

I would like to share another non-standard keepalived configuration. Perhaps you can guide me on the right path.

We use nginx as an edge load balancer. For high availability, we use the **Keepalived**.
\
**Version Keepalived:**

```
Keepalived v2.2.7 (01/16,2022)

Copyright(C) 2001-2022 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 3.10.0
Running on Linux 5.4.252-1.el7.elrepo.x86_64 #1 SMP Tue Aug 8 21:29:35 EDT 2023
Distro: CentOS Linux 7 (Core)

configure options: --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info

Config options:  LIBIPSET_DYNAMIC NFTABLES LVS VRRP VRRP_AUTH VRRP_VMAC OLD_CHKSUM_COMPAT INIT=systemd SYSTEMD_NOTIFY

System options:  VSYSLOG LIBKMOD LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTA_VIA IFA_FLAGS IPTABLES NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IFLA_LINK_NETNSID GLOB_BRACE GLOB_ALTDIRFUNC INET6_ADDR_GEN_MODE SO_MARK
```
\
**Version Kernel:**

```
Linux keepalived-02 5.4.252-1.el7.elrepo.x86_64 #1 SMP Tue Aug 8 21:29:35 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux
```
\
I want to note that I **masked my public IP addresses** in the configurations and command output (for security purposes)

**My Config Keepalived:**

**LB1:** 
```
global_defs {
  notification_email {
    root@localhost.localdomain
  }
  notification_email_from root@localhost.localdomain
  smtp_server 127.0.0.1
  smtp_connect_timeout 30

  script_user admin
  enable_script_security

  vrrp_version 3
  vrrp_garp_master_delay 10
  vrrp_garp_extra_if all 100
  vrrp_garp_master_repeat 1
  vrrp_garp_lower_prio_delay 10
  vrrp_garp_lower_prio_repeat 1
  vrrp_garp_master_refresh 60
  vrrp_garp_master_refresh_repeat 2
  vrrp_garp_interval 0.001
  vrrp_gna_interval 0.000001
  max_auto_priority -1


}

vrrp_script chk_script {
  script "/usr/sbin/pidof nginx"
  weight 2
  interval 1
}

vrrp_instance VI_1 {
  interface ens160
  state MASTER
  priority 101
  virtual_router_id 67
  advert_int                 1

  use_vmac
  use_vmac_addr
  vmac_xmit_base


  unicast_src_ip 10.68.184.9
  unicast_peer {
    10.68.184.10
  }

  virtual_ipaddress {
    10.68.184.1 dev ens160 <- VIP address for access from private network 
    XX.XX.XX.XX dev ens224    <- VIP address for access from public network 
  }

  track_script {
    chk_script
  }

}
```



**LB2:**
```
global_defs {
  notification_email {
    root@localhost.localdomain
  }
  notification_email_from root@localhost.localdomain
  smtp_server 127.0.0.1
  smtp_connect_timeout 30

  script_user admin
  enable_script_security

  vrrp_version 3
  vrrp_garp_master_delay 10
  vrrp_garp_extra_if all 100
  vrrp_garp_master_repeat 1
  vrrp_garp_lower_prio_delay 10
  vrrp_garp_lower_prio_repeat 1
  vrrp_garp_master_refresh 60
  vrrp_garp_master_refresh_repeat 2
  vrrp_garp_interval 0.001
  vrrp_gna_interval 0.000001
  max_auto_priority -1


}

vrrp_script chk_script {
  script "/usr/sbin/pidof nginx"
  weight 2
  interval 1
}

vrrp_instance VI_1 {
  interface ens160
  state BACKUP
  priority 100
  virtual_router_id 67
  advert_int                 1

  use_vmac_addr
  use_vmac
  vmac_xmit_base


  unicast_src_ip 10.68.184.10
  unicast_peer {
    10.68.184.9
  }

  virtual_ipaddress {
     10.68.184.1 dev ens160  <- VIP address for access from private network 
     XX.XX.XX.XX dev ens224  <- VIP address for access from public network 
  }

}
```

We have two network interfaces on our load balancers.

**ens160** - internal interface (for access from private network)
**ens224** - external interface (for access from public network)

**LB1:**
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:b5:b8:18 brd ff:ff:ff:ff:ff:ff
    inet 10.68.184.9/24 brd 10.68.184.255 scope global ens160
       valid_lft forever preferred_lft forever
3: ens224: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:b5:ed:40 brd ff:ff:ff:ff:ff:ff
23: vrrp.67@ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:00:5e:00:01:43 brd ff:ff:ff:ff:ff:ff
    inet 10.68.184.1/32 scope global vrrp.67
       valid_lft forever preferred_lft forever
24: vrrp1.67@ens224: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:00:5e:00:01:43 brd ff:ff:ff:ff:ff:ff
    inet XX.XX.XX.XX/32 scope global vrrp1.67
       valid_lft forever preferred_lft forever
``` 

**LB2:**
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:b5:a3:c2 brd ff:ff:ff:ff:ff:ff
    inet 10.68.184.10/24 brd 10.68.184.255 scope global ens160
       valid_lft forever preferred_lft forever
3: ens224: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:b5:f0:6a brd ff:ff:ff:ff:ff:ff
6: vrrp.67@ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:00:5e:00:01:43 brd ff:ff:ff:ff:ff:ff
7: vrrp1.67@ens224: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:00:5e:00:01:43 brd ff:ff:ff:ff:ff:ff
```
\
Considering that our balancers are connected to the Cisco ACI fabric, we want to use VMAC to ensure high availability and correct operation of VIP addresses during failover.

I want you to pay attention to my virtual mac address on vrrp interfaces **vrrp.67@ens160** and **vrrp1.67@ens224** - `00:00:5e:00:01:43`

They are identical and that worries me. When I make requests for VIP addresses, I experience strange behavior.

Randomly I get status from them - `Recv failure: Connection reset by peer`

```
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  000 - Recv failure: Connection reset by peer
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  000 - Recv failure: Connection reset by peer
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  000 - Recv failure: Connection reset by peer
http://XX.XX.XX.XX-  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  000 - Recv failure: Connection reset by peer
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  000 - Recv failure: Connection reset by peer
http://XX.XX.XX.XX -  000 - Recv failure: Connection reset by peer
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  000 - Recv failure: Connection reset by peer
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  000 - Recv failure: Connection reset by peer
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  000 - Recv failure: Connection reset by peer
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX-  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  200 -
```

As far as I understand, the MAC address for the VRRP interface is generated based on the VRID, and in order to ensure its uniqueness, it is necessary to split my configuration with keepalived into two separate VRRP instances for each physical. interface (ens160 and ens224).

If I make this configuration, then everything works correctly.

```
vrrp_instance VI_1 {
  interface ens160
  state MASTER
  priority 100
  virtual_router_id 67
  advert_int                 1

  use_vmac
  vmac_xmit_base


  unicast_src_ip 10.68.184.9
  unicast_peer {
    10.68.184.10
  }

  virtual_ipaddress {
    10.68.184.1 dev ens160
  }

  track_script {
    chk_script
  }

}

vrrp_instance VI_2 {
  interface ens224
  state MASTER
  priority 100
  virtual_router_id 68
  advert_int                 1

  use_vmac
  vmac_xmit_base

  unicast_src_ip XX.XX.XX.XX
  unicast_peer {
    XX.XX.XX.XX
  }

  virtual_ipaddress {
     XX.XX.XX.XX dev ens224
  }


}
```

And now pay attention to the fact that now the virtual mac addresses for my **vrrp.67@ens160** and **vrrp.68@ens224** interfaces are not identical

vrrp.67@ens160 - `00:00:5e:00:01:43`
vrrp.68@ens224 - `00:00:5e:00:01:44`

```
[root@keepalived-01 ~]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:b5:b8:18 brd ff:ff:ff:ff:ff:ff
    inet 10.68.184.9/24 brd 10.68.184.255 scope global ens160
       valid_lft forever preferred_lft forever
3: ens224: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:b5:ed:40 brd ff:ff:ff:ff:ff:ff
    inet XX.XX.XX.XX/24 scope global ens224
       valid_lft forever preferred_lft forever
33: vrrp.67@ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:00:5e:00:01:43 brd ff:ff:ff:ff:ff:ff
    inet 10.68.184.1/32 scope global vrrp.67
       valid_lft forever preferred_lft forever
34: vrrp.68@ens224: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:00:5e:00:01:44 brd ff:ff:ff:ff:ff:ff
    inet XX.XX.XX.XX/32 scope global vrrp.68
       valid_lft forever preferred_lft forever
```

However, when I make requests for these VIP addresses, everything works correctly.

```
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX-  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  200 -
```

In this regard, I have a reasonable question.

I don't want to complicate my keepalived configuration and set up another separate VRRP instance that will run on the external interface (ens224). Are there any possible workarounds to solve this problem?

It looks like in order to work correctly within one VRRP instance, we must provide a unique mac address for VRRP interfaces.

It would be nice if you could set the option vmac_hwaddr in the virtual_ipaddress section.

Or keepalived should somehow understand itself, if the VIP address is up a different vrrp interface, then use a different MAC address. 

**For example:**

```
vrrp_instance VI_1 {
  interface ens160
  state MASTER
  priority 101
  virtual_router_id 67
  advert_int                 1
  garp_extra_if all 100

  use_vmac_addr
  use_vmac
  vmac_xmit_base


  unicast_src_ip 10.68.184.10
  unicast_peer {
    10.68.184.9
  }

  virtual_ipaddress {
     10.68.184.1 dev ens160 vmac_hwaddr AA:AA:AA:AA:AA:AA
     XX.XX.XX.XX dev ens224 vmac_hwaddr BB:BB:BB:BB:BB:BB
  }

}
```

**Comment by pqarmitage** [comment]
@nightguide It **should** not cause any problem using the same MAC address on different interfaces; this regularly occurs when using Vlans for example. It is possible that other devices in your network have a problem seeing the same MAC address on different sub-nets, but I think it is unlikely and it would be a bug in those devices.

It would be interesting if you tested your 2 VRRP instance configuration, but with both VRRP instances using the same VRID (virtual_router_id) and see if you then experience the problem.

You say that you don't want to complicate your configuration by having a separate VRRP instance on ens224, but it appears to me that that is precisely what you need to do. Suppose that on LB1 the link between ens224 and the switch it is connected to fails (e.g. a cable failure), then the VRRP instance on LB1 will continue to be the VRRP master, but no traffic will be able to pass. It really isn't a complication to run two separate VRRP instances, especially where, as in this case, you need to. The one thing that you should add is a _sync_group_, so that if one of the VRRP instances goes into fault state, the other instance will do so as well. To do so, add the following configuration block:
```
vrrp_sync_group GROUP_NAME {
    group {
        VI_1
        VI_2
    }
}
```
(GROUP_NAME is whatever you want to call the group).

As a separate matter, I would recommend not using the vrrp_script that you have configured, but rather use a _track_process_ which can be configured either in the _vrrp_sync_group_ or on one of the vrrp_instances. This is much more efficient that using a track_script, and also is much faster, since keepalived receives a notification from the kernel when nginx stops or starts, and so the transition to/from fault state is instantaneous.

I note that you have built your own kernel but have not updated the kernel headers against which keepalived is built. If you update your kernel headers on your build system then keepalived will be able to use kernel functionality that has been added between 3.10 and 5.4.252.

**Comment by nightguide** [comment]
@pqarmitage 

I set the same VRID for both VRRP instances and the problem reoccurs.

Current configuration:

```
global_defs {
  notification_email {
    root@localhost.localdomain
  }
  notification_email_from root@localhost.localdomain
  smtp_server 127.0.0.1
  smtp_connect_timeout 30

  script_user admin
  enable_script_security
}

vrrp_script chk_script {
  script "/usr/sbin/pidof nginx"
  weight 2
  interval 1
}

vrrp_instance VI_1 {
  interface ens160
  state BACKUP
  priority 100
  virtual_router_id 67
  advert_int                 1

  use_vmac
  vmac_xmit_base


  unicast_src_ip 10.68.184.9
  unicast_peer {
    10.68.184.10
  }

  virtual_ipaddress {
    10.68.184.1 dev ens160
  }

  track_script {
    chk_script
  }

}

vrrp_instance VI_2 {
  interface ens224
  state BACKUP
  priority 100
  virtual_router_id 67
  advert_int                 1

  use_vmac
  vmac_xmit_base


  unicast_src_ip XX.XX.XX.XX
  unicast_peer {
    XX.XX.XX.XX
  }

  virtual_ipaddress {
     XX.XX.XX.XX dev ens224
  }

  track_script {
    chk_script
  }
}
```

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:b5:b8:18 brd ff:ff:ff:ff:ff:ff
    inet 10.68.184.9/24 brd 10.68.184.255 scope global ens160
       valid_lft forever preferred_lft forever
3: ens224: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:b5:ed:40 brd ff:ff:ff:ff:ff:ff
    inet XX.XX.XX.XX/24 scope global ens224
       valid_lft forever preferred_lft forever
61: vrrp.67@ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:00:5e:00:01:43 brd ff:ff:ff:ff:ff:ff
    inet 10.68.184.1/32 scope global vrrp.67
       valid_lft forever preferred_lft forever
62: vrrp1.67@ens224: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:00:5e:00:01:43 brd ff:ff:ff:ff:ff:ff
    inet XX.XX.XX.XX/32 scope global vrrp1.67
       valid_lft forever preferred_lft forever
```       


See my output from my test script:

```
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  000 - Recv failure: Connection reset by peer
http://XX.XX.XX.XX -  000 - Recv failure: Connection reset by peer
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  000 - Recv failure: Connection reset by peer
http://10.68.184.1 -  000 - Recv failure: Connection reset by peer
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX-  000 - Recv failure: Connection reset by peer
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  000 - Recv failure: Connection reset by peer
http://10.68.184.1 -  000 - Recv failure: Connection reset by peer
http://XX.XX.XX.XX -  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  000 - Recv failure: Connection reset by peer
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX-  200 -
http://10.68.184.1 -  200 -
http://XX.XX.XX.XX -  200 -
```

**Comment by nightguide** [comment]
@pqarmitage 

It looks like it's really my fault.

I'm testing this configuration within the same VLAN but on different subnets.

Talked to our network administrators today and they confirmed this behavior.

I will try to separate the VLANs and write back about the result of my tests.

**Comment by nightguide** [comment]
@pqarmitage 

I seprated the subnets into different vlans and it worked. No more errors

Thank you for your help.
