### ISSUE TITLE
build warning using --disable-vrrp

### ISSUE THREAD

**Issue by wangxp006** [acassen/keepalived#1748]
**Describe the bug**
build warning using --disable-vrrp

**To Reproduce**
1. download keepalived in keepalived-master
2. ./build_setup
3 ./configure --disable-vrrp
4. make -j20

**Expected behavior**
Build success  without warning 

**Keepalived version**
keepalived master in github

[root@randywang keepalived]# autoconf --version
autoconf (GNU Autoconf) 2.69

[root@randywang keepalived]# gcc --version
gcc (GCC) 7.3.0

** Build Log **
[root@randywang keepalived]# make -j20
Making all in lib
make[1]: Entering directory '/root/build/keepalived/lib'
make  all-am
make[2]: Entering directory '/root/build/keepalived/lib'
  CC       vector.o
  CC       html.o
  CC       parser.o
  CC       signals.o
  CC       logger.o
  CC       list_head.o
  CC       rbtree.o
  CC       process.o
  CC       json_writer.o
  CC       memory.o
  CC       utils.o
  CC       notify.o
  CC       timer.o
  CC       scheduler.o
  AR       liblib.a
make[2]: Leaving directory '/root/build/keepalived/lib'
make[1]: Leaving directory '/root/build/keepalived/lib'
Making all in keepalived
make[1]: Entering directory '/root/build/keepalived/keepalived'
Making all in core
make[2]: Entering directory '/root/build/keepalived/keepalived/core'
  CC       main.o
  CC       daemon.o
  CC       pidfile.o
  CC       layer4.o
  CC       smtp.o
  CC       global_data.o
  CC       global_parser.o
  CC       keepalived_netlink.o
  CC       namespaces.o
  CC       reload_monitor.o
main.c: In function ‘sigend’:
 main.c:1089:6: warning: assuming signed overflow does not occur when simplifying conditional to constant [-Wstrict-overflow]
   if (wait_count) { 
      ^
  AR       libcore.a
make[2]: Leaving directory '/root/build/keepalived/keepalived/core'
Making all in check
make[2]: Entering directory '/root/build/keepalived/keepalived/check'
  CC       check_daemon.o
  CC       check_data.o
  CC       check_parser.o
  CC       check_api.o
  CC       check_tcp.o
  CC       check_http.o
  CC       check_ssl.o
  CC       check_smtp.o
  CC       check_misc.o
  CC       check_dns.o
  CC       check_print.o
  CC       ipwrapper.o
  CC       ipvswrapper.o
  CC       libipvs.o
  CC       check_udp.o
  CC       check_ping.o
  CC       check_file.o
  AR       libcheck.a
make[2]: Leaving directory '/root/build/keepalived/keepalived/check'
Making all in trackers
make[2]: Entering directory '/root/build/keepalived/keepalived/trackers'
  CC       track_file.o
  AR       libtracker.a
make[2]: Leaving directory '/root/build/keepalived/keepalived/trackers'
Making all in etc
make[2]: Entering directory '/root/build/keepalived/keepalived/etc'
Making all in init
make[3]: Entering directory '/root/build/keepalived/keepalived/etc/init'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/root/build/keepalived/keepalived/etc/init'
Making all in init.d
make[3]: Entering directory '/root/build/keepalived/keepalived/etc/init.d'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/root/build/keepalived/keepalived/etc/init.d'
Making all in keepalived
make[3]: Entering directory '/root/build/keepalived/keepalived/etc/keepalived'
  CP       keepalived.conf
make[3]: Leaving directory '/root/build/keepalived/keepalived/etc/keepalived'
make[3]: Entering directory '/root/build/keepalived/keepalived/etc'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/root/build/keepalived/keepalived/etc'
make[2]: Leaving directory '/root/build/keepalived/keepalived/etc'
make[2]: Entering directory '/root/build/keepalived/keepalived'
  CC       main.o
  EDIT     keepalived.service
  CCLD     keepalived
make[2]: Leaving directory '/root/build/keepalived/keepalived'
make[1]: Leaving directory '/root/build/keepalived/keepalived'
Making all in doc
make[1]: Entering directory '/root/build/keepalived/doc'
Making all in man/man8
make[2]: Entering directory '/root/build/keepalived/doc/man/man8'
  EDIT     keepalived.8
make[2]: Leaving directory '/root/build/keepalived/doc/man/man8'
make[2]: Entering directory '/root/build/keepalived/doc'
make[2]: Nothing to be done for 'all-am'.
make[2]: Leaving directory '/root/build/keepalived/doc'
make[1]: Leaving directory '/root/build/keepalived/doc'
Making all in genhash
make[1]: Entering directory '/root/build/keepalived/genhash'
  CC       main.o
  CC       sock.o
  CC       layer4.o
  CC       http.o
  CC       ssl.o
  CCLD     genhash
make[1]: Leaving directory '/root/build/keepalived/genhash'
Making all in bin_install
make[1]: Entering directory '/root/build/keepalived/bin_install'
make[1]: Leaving directory '/root/build/keepalived/bin_install'
make[1]: Entering directory '/root/build/keepalived'
  EDIT     README
make[1]: Leaving directory '/root/build/keepalived'

**Comment by wangxp006** [comment]
My fix is here #1749

**Comment by pqarmitage** [comment]
This warning is not produced with gcc versions 9.3.1, 4.8.5, 8.3.1 or 10.2.1, so I suspect it is not a valid warning.

We quite often find that older versions of gcc can produce warnings that are not produced by later versions, and I tend to take the view it is better to rely on later versions that earlier ones, albeit I will generally insect the code to check the validity of the warning.

The change that you have made in pull request #1749, which I presume stops the warning, does suggest that this is a compiler/optimiser problem rather than a problem with the keepalived code, since changing wait_count to unsigned does not alter the validity of the code.

The warning that is produced: `assuming signed overflow does not occur when simplifying conditional to constant ` looks quite worrying in terms of what code the compiler might produce. If it thinks that it can replace `if (wait_count)` with a constant then it will produce incorrect code. If it is relying on wait_count being non-zero due to `while (wait_count) {` at line 1016, then it is failing to take account of lines 1066 and 1084 which can alter the value of `wait_count`. I think if I were you I would be inclined to check the generated code to make sure that it is checking the value of wait_count at line 1089, and if it is not you many need to look for a different versions of gcc.

Based on the above I think it is not appropriate to apply pull request #1749, but many thanks for reporting this issue.

**Comment by wangxp006** [comment]
@pqarmitage I see. Thank you for your patient and meticulous reply.
