### ISSUE TITLE
build Error using --enable-debug --disable-vrrp

### ISSUE THREAD

**Issue by wangxp006** [acassen/keepalived#1750]
Describe the bug
build warning using --disable-vrrp

To Reproduce

download keepalived in keepalived-master
./build_setup
3 ./configure --enable-debug --disable-vrrp 
make -j20
Expected behavior
Build success  

Keepalived version
keepalived master in github

[root@randywang keepalived]# autoconf --version
autoconf (GNU Autoconf) 2.69

[root@randywang keepalived]# gcc --version
gcc (GCC) 7.3.0

 **Build Log** 
[root@localhost keepalived]# make -j20
Making all in lib
make[1]: Entering directory '/root/opensource/keepalived/keepalived/lib'
make  all-am
make[2]: Entering directory '/root/opensource/keepalived/keepalived/lib'
  CC       assert.o
  CC       memory.o
  CC       utils.o
  CC       notify.o
  CC       timer.o
  CC       vector.o
  CC       html.o
  CC       parser.o
  CC       signals.o
  CC       logger.o
  CC       list_head.o
  CC       rbtree.o
  CC       process.o
  CC       json_writer.o
  CC       scheduler.o
  AR       liblib.a
make[2]: Leaving directory '/root/opensource/keepalived/keepalived/lib'
make[1]: Leaving directory '/root/opensource/keepalived/keepalived/lib'
Making all in keepalived
make[1]: Entering directory '/root/opensource/keepalived/keepalived/keepalived'
Making all in core
make[2]: Entering directory '/root/opensource/keepalived/keepalived/keepalived/core'
  CC       main.o
  CC       daemon.o
  CC       pidfile.o
  CC       layer4.o
  CC       smtp.o
  CC       global_data.o
  CC       global_parser.o
  CC       keepalived_netlink.o
  CC       namespaces.o
  CC       reload_monitor.o
In file included from ../../keepalived/include/vrrp_track.h:35:0,
                 from ../../keepalived/include/vrrp_scheduler.h:34,
                 from main.c:103:
../../keepalived/include/vrrp.h:139:3: error: conflicting types for ‘vrrp_sgroup_t’
 } vrrp_sgroup_t;
   ^~~~~~~~~~~~~
In file included from main.c:94:0:
../../keepalived/include/smtp.h:125:14: note: previous declaration of ‘vrrp_sgroup_t’ was here
 typedef void vrrp_sgroup_t;
              ^~~~~~~~~~~~~
In file included from ../../keepalived/include/vrrp_track.h:35:0,
                 from ../../keepalived/include/vrrp_scheduler.h:34,
                 from main.c:103:
../../keepalived/include/vrrp.h:378:3: error: conflicting types for ‘vrrp_t’
 } vrrp_t;
   ^~~~~~
In file included from main.c:94:0:
../../keepalived/include/smtp.h:124:14: note: previous declaration of ‘vrrp_t’ was here
 typedef void vrrp_t;
              ^~~~~~
make[2]: *** [Makefile:395: main.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/root/opensource/keepalived/keepalived/keepalived/core'
make[1]: *** [Makefile:575: all-recursive] Error 1
make[1]: Leaving directory '/root/opensource/keepalived/keepalived/keepalived'
make: *** [Makefile:435: all-recursive] Error 1
[root@localhost keepalived]#

**Comment by wangxp006** [comment]
My fix is here #1751

**Comment by pqarmitage** [comment]
@wangxp006 Whilst I can see that your commit #1751 stops the build errors, moving the `enable_script_debug` line to only be enabled if vrrp is enabled doesn't resolve the real problem but just hides it. I do agree that moving `enable_recvmsg_debug` is the correct solution though, however there should also be an AC_MSG_ERROR added if `--enable-recvmsg-debug` is specified along with `--disable-vrrp` - see commit c4e2e29.

Although at the moment enabling script debug only enables code in the vrrp process, it is also intended to enable script checking code in the checker process (MISC_CHECK) at such time as it is needed and implemented, and hence `do_script_debug` is in `lib/scheduler.h` rather than `keepalived/include/vrrp_scheduler.h`. So the first error is in keepalived/core/main.c which includes `vrrp_scheduler.h` if _SCRIPT_DEBUG_ is defined rather than `lib/scheduler.h` - see commit 63fbed3.

The next question then must be _why are we getting the duplicate definitions of `vrrp_t` and `vrrp_sgroup_t`. It turns out that the definitions in `keepalived/include/smtp.h` are completely unnecessary, so we can just remove them - see commit c6376ee.
