### ISSUE TITLE
support to config not to listening on 0.0.0.0 for security

### ISSUE THREAD

**Issue by flymoondust** [acassen/keepalived#1759]
For security concerns, I have a request,that I want keepalived to support config weather or not listening on 0.0.0.0.
Please reply ASAP.

**Comment by pqarmitage** [comment]
@flymoondust I am not clear what it is you want to achieve, or what the problem is that you are having.

Is it that you don't like keepalived opening sockets with the local address being 0.0.0.0 or :: for IPv6? These are the sockets used for sending VRRP adverts, and there is a BPF filter set on each of those sockets to ensure that no packets are received on them.

Providing multicasting is used, the receive sockets are bound to 224.0.0.18 or ::1; this is so that the sockets do not receive any unicast traffic, and they only receive packets to the multicast addresses that they have register to listen on. For unicast, the receive sockets are bound to an address on the interface specified, or if no interface is specified to the configured unicast_src address.

I may have completely misunderstood what it is you are asking about, so if the above does not answer your concerns please do not hesitate to provide additional details.

**Comment by flymoondust** [comment]
I  don't like keepalived opening sockets with the local address being 0.0.0.0 or :: for IPv6.

**Comment by acassen** [comment]
That is the way multicast is working, and at the ingress there is a bound_to_device socketoption used as quentin said and at egress there is BPF filter to make it send-only socket. This is a good security practice, and this is not because your are using unicast bound to a specific socket that the setup is more secure (even you are filtering per IPs), because using multicast you will benefit good protection of using TTL=255 that ensure traffic is received and isolated at the same ethernet segment and not potentially originated from a forged remote host.
