### ISSUE TITLE
The code for handling the vrrp_garp_interval does not work properly 

### ISSUE THREAD

**Issue by ziginet** [acassen/keepalived#1760]
**Describe the bug**
If I set vrrp_garp_interval to a value greater than 0.001, then Keepalived does not send the expected number of GARP messages. With the configuration below, Keepalived sends only **2** GARP messages per VIP address although it should send **5** (viz vrrp_garp_master_repeat 5).

Quentin Armitage:
> I have looked at the code and the code for handling the vrrp_garp_interval does not work properly.
> 
> When the GARP messages are being sent, the code checks to see if vrrp_garp_interval has elapsed since the previous GARP message on the relevant interface has been sent. If it has not, the address gets marked as needing to send a GARP message, and a timer is set up. However, if multiple GARPs need to be sent for an address, that information is lost and only one more GARP will be sent.
> 
> The reason it appears to work properly when you set vrrp_garp_interval to 0.001 is that when the code is sending the second, third etc garp message, that time has elapsed since the previous GARP message was sent on the same interface, and so it is sent straight away.
> 
> The code for handling this is quite horrible and does not scale well to large configurations (since I wrote the code I can criticise it!).

**Expected behavior**
Keepalived will send the configured/required number of GARP messages.

**Keepalived version**
keepalived-1.3.5-16.el7.x86_64

Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2

Copyright(C) 2001-2017 Alexandre Cassen, <acassen@gmail.com>

Build options:  PIPE2 LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_PREF FRA_OIFNAME FRA_SUPPRESS_PREFIXLEN FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK LIBIPTC LIBIPSET_DYNAMIC LVS LIBIPVS_NETLINK VRRP VRRP_AUTH VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC FIB_ROUTING INET6_ADDR_GEN_MODE SNMP_V3_FOR_V2 SNMP SNMP_KEEPALIVED SNMP_CHECKER SNMP_RFC SNMP_RFCV2 SNMP_RFCV3 SO_MARK

**Distro**
 - Name: CentOS
 - Version: 7.8.2003
 - Architecture: x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
virtual machine on VMware ESXi

**Configuration file:**
```
global_defs {
       router_id fw-1 / fw-2

       vrrp_garp_master_delay 5
       vrrp_garp_master_repeat 5

       vrrp_garp_lower_prio_delay 5
       vrrp_garp_lower_prio_repeat 5

       vrrp_garp_master_refresh 120
       vrrp_garp_master_refresh_repeat 2

       vrrp_garp_interval 0.2
       vrrp_gna_interval 0.2`
}

vrrp_instance VI_11 {
       priority 100 / priority 50
       state MASTER / state BACKUP

       interface int0
       virtual_router_id 11

       advert_int 1

       track_interface {
               net0
               dmz0
               int0
               ic0
       }

       virtual_ipaddress {
               10.1.1.1/24 dev net0
               10.2.2.1/24 dev dmz0
               10.3.3.1/24 dev int0
               10.4.4.1/24 dev ic0
        }

       include local.conf.d/VI_11_vroutes.conf

       smtp_alert
}
```

**Additional context**
viz https://groups.io/g/keepalived-users/message/313

**Comment by pqarmitage** [comment]
I have now reworked the code so that better use if timer threads is made. This resolves the problem of insufficient GARP messages being sent. The primary commit to resolve this was [b1d9e37](https://github.com/acassen/keepalived/pull/2482/commits/b1d9e3758db34a1152b339b27c583294904ffe19), but commits [d7aeabb](https://github.com/acassen/keepalived/pull/2482/commits/d7aeabbedd722b83ddda2a19cb6b44eca6b1b091), [1d695bd](https://github.com/acassen/keepalived/pull/2482/commits/1d695bd2d0fd207194fe0c10b28b91fa3abe72f8), [5661fad](https://github.com/acassen/keepalived/pull/2482/commits/5661fadce21cf20fd8d99efe6faf5d744180378b), [360ec2a](https://github.com/acassen/keepalived/pull/2482/commits/360ec2a8603c6c51e50b38270a6470b27211f6f7) and [b0eed52](https://github.com/acassen/keepalived/pull/2482/commits/b0eed52abf58f2a99f6e474f7d6da0827aa55b80) also resulted from investigating this issue.
