### ISSUE TITLE
VRRP IPv6 mcast_src_ip not working

### ISSUE THREAD

**Issue by PaulSD** [acassen/keepalived#1770]
I'm using `Keepalived v1.3.9 (10/21,2017)` from Ubuntu 18.04 x86_64 (keepalived 1:1.3.9-1ubuntu0.18.04.2), running on a bare metal system.
I know this is a relatively old version of keepalived.  Unfortunately, I don't currently have an easy way to test a newer version, although I recognize that I will probably have to upgrade one way or another if I want a fix for this.

Some background:
If an IPv6 VRRP instance is configured in keepalived, then when keepalived starts it will look for a link-local IPv6 address on the interface to use as the source address for VRRP packets.  In most cases, keepalived will find the auto-assigned link-local IPv6 address, and all is good.  However, if link is down on the interface when keepalived starts, then the interface will not have an auto-assigned link-local IPv6 address configured, and keepalived will fail if there is no other link-local IPv6 address configured.
To prevent keepalived from failing if link is down, a static link-local IPv6 address can be assigned to the interface.
However, if both addresses are configured when keepalived starts, then depending on the order in which the auto-assigned and static link-local addresses were configured (depending on which the kernel considers to be the "primary" address), keepalived may inconsistently choose one or the other to use as a source address.  While that inconsistency is functionally OK in most cases, it causes problems when used with tightly-written firewall rules, and it can be confusing when troubleshooting.
So, I am trying to use mcast_src_ip configure keepalived to always use the statically assigned address, to eliminate that inconsistency.

Example config:
```
vrrp_instance int_IPv6 {
  interface eth0
  virtual_router_id 6
  mcast_src_ip fe80:1::2
  virtual_ipaddress {
    fe80:1::1/64
    <additional addresses here>
  }
}
```

If I comment out the `mcast_src_ip` line, then everything works as expected, and keepalived will use either fe80:1::2 or the auto-assigned link-local IPv6 address for VRRP packets (depending on the order that the addresses were configured on the interface).
If I uncomment the `mcast_src_ip` line, then there are no errors in the log, but keepalived doesn't send any packets at all.

Running `keepalived --log-detail ...` doesn't show anything interesting.  Unfortunately, keepalived 1.3.9 was before the `Assigned address ... for interface ...` log messages were added.

**Comment by pqarmitage** [comment]
I have tested this with v2.1.5 and keepalived works as you want it to, i.e.:
1. eth0 down
1. ip addr add fe80:1::2/64 dev eth0
1. ip link set eth0 up
1. keepalived transitions to backup state
1. keepalived transitions to master state and starts send multicast adverts from fe80:1::2

I don't think it is worth me testing this with keepalived v1.3.9 since you say it doesn't work. Unfortunately the only solution for you would seem to be to upgrade to a recent version of keepalived.

One problem on my system with this is that if `ip link set eth0 down` is executed, the address fe80:1::2/64 is removed, so you would need some configuration to reinstate the fe80:1::2 address in the event of eth0 going down and coming back up again. You could use a `notify_backup` script, something like:
```
#!/bin/bash

ip addr show eth0 | grep -q fe80:1::2
[[ $? -ne 0 ]] && ip addr add fe80:1::2/64 dev eth0
```

I think from a semantics point of view, the VIP should be fe80:1::1/128 rather than fe80:1::1/64; the network fe80:1::/64 already exists, since you have already added fe80:1::2/64, and when the VIP is added it is just adding the address rather than the network.
