### ISSUE TITLE
Connection not disconnect instantly when RS not functional

### ISSUE THREAD

**Issue by flymoondust** [acassen/keepalived#1781]
**Describe the bug**
UDP package, through keepalived to RealServer A,
then RealServer A run panic for some reason,
on this very moment, the heart beat test of RealServer A is failed and deleted from virtual table,
 but the connection between client and RealServer A didn't disconnect instantly, only disconnected when the connection timeout expired.
There is a problem here, when the connection exist, when udp packages from same client come, keepalive route them to RealServer A which not funcional, then these packages will be lost.

**Expected behavior**
I expect when heart beat test failed ,the connection can be disconnected as well instantly.

**Keepalived version**
Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2

**Distro (please complete the following information):**
 - Fedora
 - x86_64

**Configuration file:**
A full copy of the configuration file, obfuscated if necessary to protect passwords and IP addresses

**Comment by pqarmitage** [comment]
Please see the discussion at https://groups.io/g/keepalived-users/topic/76755617#277 which is the same issue.

ipvs maintains a connection tracking table so that packets on the same "connection" are sent to the same destination. This applies even after the real server is removed from the configuration (or possibly just if the weight of a real server is set to 0 - I can't remember which). The timeout of entries can be set using the keepalived `lvs_timeouts` keyword (see the ipvsadm(8) man page `--set` option for more details). Also, to override the behaviour of subsequent packets being sent to the same real server you can set the `ops` option in the virtual server configuration (see ipvsadm(8) man page `--ops` option for more details). I am not sure if `ops` works with the NAT forwarding method.
