### ISSUE TITLE
Stop IGMP/MLD messages being sent on VMAC interfaces - kernel setting

### ISSUE THREAD

**Issue by louis-oui** [acassen/keepalived#1792]
**Is your feature request to resolve a problem or provide enhanced functionality? Please describe.**
Current fix https://github.com/acassen/keepalived/pull/1403 implies compilation option and requires using filter.

**Describe the solution you would like**

There is a kernel option to not send IGMP join on local reserved range 224.0.0.0/24. Available on kernel > 4.13

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/networking/ip-sysctl.rst#n1590

igmp_link_local_mcast_reports - BOOLEAN
	Enable IGMP reports for link local multicast groups in the
	224.0.0.X range.

	Default TRUE

i.e. /proc/sys/net/ipv4/igmp_link_local_mcast_reports

http://lkml.iu.edu/hypermail/linux/kernel/1508.3/03066.html

Although the RFCs for the various version of IGMP (e.g.RFC 3376 for
v3) do not specify that the reserved addresses be excluded from
membership reports, it should do no harm in doing so. In particular
there should be no adverse effect in any IGMP snooping functionality
since 224.0.0.x is specifically excluded as per RFC 4541 (IGMP and MLD
Snooping Switches Considerations) section 2.1.2. Data Forwarding
Rules:

Suggestion is that keepalived sets up sysctl

A valid solution still needs to be found for MLD ipv6 case.

**Keepalived version**
Latest

**Additional context**
NA

**Comment by pqarmitage** [comment]
You state: Current fix #1403 implies compilation option and requires using filter.

The default option for keepalived is to include nftables support and it does not require a compilation/configuration option to be specified. If you have libnftnl-dev and libmnl-dev packages installed, then keepalived will be built with nftables support. This is the preferred way to to control the IGMP messages, and to ensure that they are not sent on the macvlan interface, but sent on the parent interface (in your case bond0). This functionality is automatically enabled unless iptables use is configured.

I think the easiest way to achieve what you are asking (other than using nftables) is to use the `startup_script` global_defs option, and for the script to set igmp_link_local_mcast_reports to 0. If you want to reset it when keepalived terminates, then you can use the `shutdown_script` option.

I will look further at whether it is sensible for keepalived to implement this, however it will not work for IPv6, since RFC4541 states `MLD is mandated for addresses with scope 2 (link-scope) or greater` and I can see no other option but to use nftables (or an eBPF filter) to achieve this, since the MLD message must be sent, but we want to send it on the parent (bond0) interface.

**Comment by louis-oui** [comment]
OK thank you for the feedback

**Comment by pqarmitage** [comment]
Commit d7b3bfa implements the above suggestion if global_def `disable_local_igmp` is configured.
