### ISSUE TITLE
NAT mod with iptables remapping port

### ISSUE THREAD

**Issue by flymoondust** [acassen/keepalived#1796]
**Describe the bug**
 now have a user case here:

RealServer use nat mode, and I use iptables to remap port in the meantime. I want to know if this is supported.

The result is confusing here:
Package from client ipA: 10.136.156.160 is remapped by iptables
But client ipB 10.137.117.116 is not remapped by iptables , directly handled by keepalived.

ipvsadm output:
[root@BeCloud-02 /usr/local/snbsudobin/RCLVSService/lvs_install/bin]# ./ipvsadm -lnc
IPVS connection entries
pro expire state       source             virtual            destination
UDP 134:51 UDP         10.136.156.160:55638 15.204.251.29:10162 15.204.251.22:10162
UDP 134:59 UDP         10.137.117.116:1621 15.204.251.29:162  15.204.251.25:162

iptables output:
[root@BeCloud-02 /usr/local/snbsudobin/RCLVSService/lvs_install/bin]# iptables -nvL -t nat
Chain PREROUTING (policy ACCEPT 908 packets, 46189 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  166 49266 DNAT       udp  --  *      *       0.0.0.0/0            15.204.251.29        udp dpt:162 to:15.204.251.29:10162

ipvsadm tables:

[root@BeCloud-02 /usr/local/snbsudobin/RCLVSService/lvs_install/bin]# ./ipvsadm -ln --stats
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port               Conns   InPkts  OutPkts  InBytes OutBytes
  -> RemoteAddress:Port
UDP  15.204.251.29:162                   1        5        5     1480     1620
  -> 15.204.251.22:162                   0        0        0        0        0
  -> 15.204.251.25:162                   1        5        5     1480     1620
UDP  15.204.251.29:10162                 0      785        0   319437        0
  -> 15.204.251.22:10162                 0      785        0   319437        0
  -> 15.204.251.25:10162                 0        0        0        0        0
  -> 15.204.251.28:10162                 0        0        0        0        0

**To Reproduce**
Any steps necessary to reproduce the behaviour:

**Expected behavior**

**Keepalived version**
Output of `keepalived -v`

**Distro (please complete the following information):**
 - Name [e.g. Fedora, Ubuntu]
 - Version [e.g. 29]
 - Architecture [e.g. x86_64]

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details

**Configuration file:**
A full copy of the configuration file, obfuscated if necessary to protect passwords and IP addresses

**Notify and track scripts**
If any notify or track scripts are in use, please provide copies of them

**System Log entries**
Full keepalived system log entries from when keepalived started

**Did keepalived coredump?**
If so, can you please provide a stacktrace from the coredump, using gdb.

**Additional context**

**Comment by pqarmitage** [comment]
This isn't a keepalived issue, but rather an IPVS issue.

You write `But client ipB 10.137.117.116 is not remapped by iptables , directly handled by keepalived.` This isn't actually the case; keepalived does not handle any packets regarding IPVS, keepalived just sets up the IPVS configuration (i.e. just as the ipvsadm command does) and it is the IPVS code in the kernel that handles the packets. You ask if using iptables NAT and IPVS NAT mode is supported; the simple answer is that keepalived will configure IPVS appropriately, and so keepalived supports it, but whether the IPVS code in the kernel supports it is another matter.

What it comes down to is what hooks and priorities IPVS uses to extract packets and reinject them (you may find that using nftables gives you more flexibility since the priority of chains can be specified).

I have in the past found that when IPVS forwards a packet to a real server, some of the iptables hooks are missed. I seem to remember that I couldn't use SNAT in iptables on a packet that IPVS had forwarded to a real server; I did manage to find a workaround by sending the packet to a different network namespace which simply returned it, and then the packet traversed the iptables chains again and the SNAT was then applied.

I think what you need to do is to set up your configuration, send some test packets and then look at the IPVS stats and connection tracking table with ipvsadm, and also look at the counters in iptables; that should tell you what is happening.

It would have been helpful if you had provided the information requested, especially your configuration and iptables setup, since then we could have tried it out ourselves.

**Comment by pqarmitage** [comment]
Closing due to no updates for a week. If you have further problems with this please update this issue and it can be re-opened if necessary.
