### ISSUE TITLE
Configuration Parse errors on v2.2

### ISSUE THREAD

**Issue by gregnetau** [acassen/keepalived#1831]
It seems there is a defect in version 2.2 with parsing configuration.

My configuration file (lines 650-670):

```
        real_server 10.200.7.62 443 {
                weight 80
                        TCP_CHECK {
                                connect_timeout 2
                                bindto 10.200.7.191
                        }
        }
}

virtual_server ipv6:addr:ess:000::1 443 {
    delay_loop 5
    lvs_sched wrr
    lvs_method DR
    persistence_timeout 300
    protocol TCP

```

Keepalived reports on startup:
(/etc/keepalived/keepalived.conf: Line 661) Unknown keyword 'delay_lbindto'
(/etc/keepalived/keepalived.conf: Line 663) Extra '}' found
(/etc/keepalived/keepalived.conf: Line 663) Unknown keyword '}'
(/etc/keepalived/keepalived.conf: Line 665) Unknown keyword 'real_server'
(/etc/keepalived/keepalived.conf: Line 665) Unexpected '{' - ignoring
(/etc/keepalived/keepalived.conf: Line 666) Unknown keyword 'weight'
(/etc/keepalived/keepalived.conf: Line 667) Unknown keyword 'TCP_CHECK'
(/etc/keepalived/keepalived.conf: Line 667) Unexpected '{' - ignoring
(/etc/keepalived/keepalived.conf: Line 668) Unknown keyword 'connect_timeout'
(/etc/keepalived/keepalived.conf: Line 669) Unknown keyword 'bindto'
(/etc/keepalived/keepalived.conf: Line 670) Unknown keyword '}'

**Comment by pqarmitage** [comment]
@gregnetau I have tried reproducing the problem with the above configuration snippet wrapped by minimal additional configuration to make it valid and I cannot reproduce the problem.

In order for us to investigate this further you will need to post your full configuration so that we can reproduce the problem.

**Comment by gregnetau** [comment]
Thanks @pqarmitage I have emailed you my config file.

**Comment by pqarmitage** [comment]
I had forgotten that file descriptors inherited via fork() are not independent of each other in that the file offset is the same for all of them, and reading from one moves the file offset as seen by the other processes. This meant that when the second block (4096 bytes) was read by the VRRP process, when the checker process next read via the file decriptor, it read the third block.

Commit ca03dc2 opens new file descriptors for the config file in each of the VRRP, checker and BFD processes so that they can be read independently of each other, and blocks are no longer skipped.
