### ISSUE TITLE
When run keepalived always start as backup then master even on the master which causes notify script to run twice.

### ISSUE THREAD

**Issue by rupesharora** [acassen/keepalived#1835]
As mentioned in #1804 after installing v2.2.0 which has all commits still facing the same issue.
Notify script runs twice which causes me problem.
Another thing that observed that script mentioned in vrrp_script{} run earlier than notify script why so?

**Comment by pqarmitage** [comment]
A VRRP instance will always start in backup state, and may subsequently transition to master state. How quickly it can transition to master state depends on the configuration, in particular whether the priority of the instance is 255 or not, and also whether `state MASTER` is configured or not. If the priority is 255 and `state MASTER` is specified, then the delay before transitioning to master state is `(advert interval) + skew_time; otherwise the delay is `3 * (advert_interval) + skew_time` where `skew_time` = `(256 - priority) / 256` seconds for VRRPv2 and `(256 = priority) / 256 * advert_interval)` for VRRPv3.

The reason for their being a delay of just over 1 advert interval when `state MASTER` is specified and priority=255 is a keepalived enhancement to handle the case if there were two matching VRRP instances both configured with priority 255. If a VRRP instance has priority 255 and it receives an advert with priority 255, it drops its own priority to 254, otherwise you would end up with 2 instances both acting as master. Some might claim that doing this is a violation of the VRRP protocol, however this acts precisely the same as though keepalived had been started 1 advert interval later, but it didn't have the delay, and so when view from outside the system, the behaviour is precisely the same, unless there has been a configuration error.

You have a choice when using notify scripts. You can either have `notify_master`/`notify_backup`/`notify_fault`, or you can just use `notify`. In the first case, different scripts must be specified, so that they know what the new state is (they could all call a common script afterwards, once the state is known). If using a `notify` script, a parameter is passed to the script which is the new state. Either way, it should not be a problem on startup to detect what is happening, since the new state of the VRRP instance is always known.

You also mention that the `vrrp_script` is run before a notify script. That is not a problem, since the `vrrp_script` can return a fault state that indicates that the VRRP instance should transition to fault state. In fact, it is better that the script does run before a VRRP instance can become master, so that it will stop a VRRP instance becoming master and then almost immediately transitioning to FAULT state if the `vrrp_script` indicates a fault.

You haven't provided a copy of your configuration, so it is not possible to know exactly why the things that you mention are occurring, or why it is a problem for you that a notify script runs twice.

Since keepalived is behaving as expected, I am closing this issue, but if you provide further information such as your configuration and scripts and why it is a problem that a notify script runs twice, we can still update the issue, or reopen it if appropriate.
