### ISSUE TITLE
Unable to set syslog facility with '--log-facility' - keepalived always uses 'user' facility

### ISSUE THREAD

**Issue by mengelmann** [acassen/keepalived#1836]
Hi!

I'm unable to set syslog logging facility with `--log-facility` to `local0`-`local7`. Keepalived always uses `user` facility.

I think this issue has been introduced by this commit https://github.com/acassen/keepalived/commit/db3bcf7b891881e8e70954424f0fe88ec7d37ce0.

This code https://github.com/acassen/keepalived/blob/db3bcf7b891881e8e70954424f0fe88ec7d37ce0/lib/logger.c#L202-L203 explicitly sets `user` facility, so `vsyslog()` / `syslog()` function uses it instead of default that is set when opening connection to syslog with `openlog()` here https://github.com/acassen/keepalived/blob/210e00e0605c3815ba08e88fbe2f688f90070b0b/keepalived/core/main.c#L2384 

More info about [Submitting Syslog Messages from GNU C Library](https://www.gnu.org/software/libc/manual/html_node/Submitting-Syslog-Messages.html).

**Keepalived version**
```
Keepalived v2.1.5 (07/13,2020)

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.19.160
Running on Linux 5.7.0-0.bpo.2-amd64 #1 SMP Debian 5.7.10-1~bpo10+1 (2020-07-30)

configure options: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --with-kernel-dir=debian/ --enable-snmp --enable-sha1 --enable-snmp-rfcv2 --enable-snmp-rfcv3 --enable-dbus --enable-json --enable-bfd --enable-regex build_alias=x86_64-linux-gnu CFLAGS=-g -O2 -fdebug-prefix-map=/srv/build/keepalived-2.1.5=. -fstack-protector-strong -Wformat -Werror=format-security LDFLAGS=-Wl,-z,relro CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2

Config options:  NFTABLES LVS REGEX VRRP VRRP_AUTH JSON BFD OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 DBUS

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RESET_ON_FORK
```

**Comment by mengelmann** [comment]
I can confirm, that reverting mentioned commit https://github.com/acassen/keepalived/commit/db3bcf7b891881e8e70954424f0fe88ec7d37ce0 brings back ability to specify log facility via `--log-facility`.

**Comment by pqarmitage** [comment]
@mengelmann Many thanks for the update. I am just working on this now.

With that commit reverted, despite the keepalived(8) man page stating that the default log level is LOG_DAEMON, it appears that the default log level for the parent process is indeed LOG_DAEMON, but for the BFD and VRRP processes it defaults to LOG_LOCAL2 and for the checker process it defaults to LOG_LOCAL1. I cannot see the reason for this, other than being able to configure syslog to log the different processes to different files, but that can be done based on the syslog identifier.

Since it has, as you say, been logging to facility LOG_USER, and no-one before you has raised it as an issue, I am inclined to make the code reflect what the kepalived(5) man page says, and log everything to LOG_DAEMON by default.

**Comment by mengelmann** [comment]
> log level for the parent process is indeed LOG_DAEMON, but for the BFD and VRRP processes it defaults to LOG_LOCAL2 and for the checker process it defaults to LOG_LOCAL1. I cannot see the reason for this

Right, I don't see reason why it is that way. Logging everything to facility LOG_DAEMON by default is good idea in my opinion.

I just would like to be able to change the default and set logging facility to `localX` as keepalived(8) man page states. 

The reason why it stopped working that way is because in line 202 https://github.com/acassen/keepalived/commit/db3bcf7b891881e8e70954424f0fe88ec7d37ce0#diff-4300374c82a4008ddcc5c3784fbba41e8f8582ff220cabb9ea8581445b9d95a3R202 `facility` is just priority (`LOG_INFO`, `LOG_DEBUG`, etc.) without facility part (`LOG_DAEMON`, `LOG_USER`, `LOG_LOCAL0`, etc.) and without setting facility (or passing it through from earlier code) testing value with `LOG_FACMASK` always makes the if statement unfulfilled.

There are two solutions
1. Line 202 mentioned above should probably use macro`LOG_MAKEPRI(LOG_FACILITY, LOG_PRIORITY)` as described here https://www.gnu.org/software/libc/manual/html_node/syslog_003b-vsyslog.html
2. Revert whole commit https://github.com/acassen/keepalived/commit/db3bcf7b891881e8e70954424f0fe88ec7d37ce0 - this one I tested and it works.

**Comment by pqarmitage** [comment]
I have now reverted db3bcf7. Commit c1477b3 makes the default facility LOG_DAEMON for all the keepalived processes, and commit d132c76 adds the option to specify `--log-facility=user`, `--log-facility=local{0-7}` and `--log-facility=daemon`. Being able to specify `user` is new, specifying `local{0-7}` duplicates existing functionality but is consistent in format with `user`, and specifying `daemon` is not really necessary since it is the default, but is allowed for consistency.

I don't think we need to use `LOG_MAKEPRI`, since when the log is opened only the facility is specified, and when a log entry is written only the priority is specified.

**Comment by mengelmann** [comment]
@pqarmitage thank you very much!
