### ISSUE TITLE
Failed with result 'protocol' and daemon is already running

### ISSUE THREAD

**Issue by Roxyrob** [acassen/keepalived#1845]
**Describe the bug**
Starting 
On CentOS 8 making rpm from source code, keepalived seem to start correctly (VIP is up), but fail as shown below: 

```
-- Unit keepalived.service has begun starting up.
Jan 31 02:17:12 host1 Keepalived[8243]: Starting Keepalived v2.2.1 (01/17,2021)
Jan 31 02:17:12 host1 Keepalived[8243]: Running on Linux 4.18.0-147.8.1.el8_1.x86_64 #1 SMP Thu Apr 9 13:49:54 UTC 2020 (built for Linux 4.18.0)
Jan 31 02:17:12 host1 Keepalived[8243]: Command line: '/usr/sbin/keepalived' '-D'
Jan 31 02:17:12 host1 Keepalived[8243]: Opening file '/etc/keepalived/keepalived.conf'.
Jan 31 02:17:12 host1 Keepalived[8243]: Configuration file /etc/keepalived/keepalived.conf
Jan 31 02:17:12 host1 systemd[1]: keepalived.service: Failed with result 'protocol'.
Jan 31 02:17:12 host1 systemd[1]: Failed to start LVS and VRRP High Availability Monitor.
-- Subject: **Unit keepalived.service has failed**
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- **Unit keepalived.service has failed.**
--
-- The result is RESULT.
Jan 31 02:17:13 host1 Keepalived[8245]: NOTICE: setting config option max_auto_priority should result in better keepalived performance
Jan 31 02:17:13 host1 Keepalived[8245]: Starting VRRP child process, pid=8246
Jan 31 02:17:13 host1 Keepalived_vrrp[8246]: Registering Kernel netlink reflector
Jan 31 02:17:13 host1 Keepalived_vrrp[8246]: Registering Kernel netlink command channel
Jan 31 02:17:13 host1 Keepalived_vrrp[8246]: Script /usr/local/bin/check_script.sh cannot be accessed - No such file or directory
Jan 31 02:17:13 host1 Keepalived_vrrp[8246]: Script /usr/local/bin/check_script.sh cannot be accessed - No such file or directory
Jan 31 02:17:13 host1 Keepalived_vrrp[8246]: Script /usr/local/bin/check_script.sh cannot be accessed - No such file or directory
Jan 31 02:17:13 host1 Keepalived_vrrp[8246]: Sync group vg1 has only 1 virtual router(s) - this probably isn't what you want - removing
Jan 31 02:17:13 host1 Keepalived_vrrp[8246]: Assigned address 192.168.30.18 for interface ens192
Jan 31 02:17:13 host1 Keepalived_vrrp[8246]: Assigned address fe80::150:52ff:fe87:2720 for interface ens192
Jan 31 02:17:13 host1 Keepalived_vrrp[8246]: Registering gratuitous ARP shared channel
Jan 31 02:17:13 host1 Keepalived_vrrp[8246]: (net_vip1) removing VIPs.
Jan 31 02:17:13 host1 Keepalived_vrrp[8246]: (net_vip1) Entering BACKUP STATE (init)
Jan 31 02:17:13 host1 Keepalived_vrrp[8246]: VRRP sockpool: [ifindex(  2), family(IPv4), proto(51), fd(14,15), unicast, address(192.168.30.18)]
Jan 31 02:17:13 host1 Keepalived_vrrp[8246]: Remote SMTP server [192.168.30.21]:25 connected.
Jan 31 02:17:13 host1 Keepalived_vrrp[8246]: SMTP alert successfully sent.
Jan 31 02:17:16 host1 Keepalived_vrrp[8246]: (net_vip1) Receive advertisement timeout
Jan 31 02:17:16 host1 Keepalived_vrrp[8246]: (net_vip1) Entering MASTER STATE
Jan 31 02:17:16 host1 Keepalived_vrrp[8246]: (net_vip1) setting VIPs.
Jan 31 02:17:16 host1 Keepalived_vrrp[8246]: (net_vip1) Sending/queueing gratuitous ARPs on ens192 for 192.168.30.21
Jan 31 02:17:16 host1 Keepalived_vrrp[8246]: Sending gratuitous ARP on ens192 for 192.168.30.21
Jan 31 02:17:16 host1 Keepalived_vrrp[8246]: Remote SMTP server [192.168.30.21]:25 connected.
Jan 31 02:17:16 host1 Keepalived_vrrp[8246]: Sending gratuitous ARP on ens192 for 192.168.30.21
Jan 31 02:17:16 host1 Keepalived_vrrp[8246]: SMTP alert successfully sent.
Jan 31 02:17:18 host1 Keepalived_vrrp[8246]: (net_vip1) Sending/queueing gratuitous ARPs on ens192 for 192.168.30.21
Jan 31 02:17:18 host1 Keepalived_vrrp[8246]: Sending gratuitous ARP on ens192 for 192.168.30.21
Jan 31 02:17:18 host1 Keepalived_vrrp[8246]: Sending gratuitous ARP on ens192 for 192.168.30.21
```

Restarting service (systemctl restart keepalived), returns "**daemon is already running**":

```
Jan 31 02:50:01 host1 systemd[1]: keepalived.service: Found left-over process 17777 (keepalived) in control group while starting unit. Ignoring.
Jan 31 02:50:01 host1 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 31 02:50:01 host1 systemd[1]: keepalived.service: Found left-over process 17778 (keepalived) in control group while starting unit. Ignoring.
Jan 31 02:50:01 host1 systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Jan 31 02:50:01 host1 systemd[1]: Starting LVS and VRRP High Availability Monitor...
-- Subject: Unit keepalived.service has begun start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- Unit keepalived.service has begun starting up.
Jan 31 02:50:01 host1 Keepalived[20666]: Starting Keepalived v2.2.1 (01/17,2021)
Jan 31 02:50:01 host1 Keepalived[20666]: Running on Linux 4.18.0-147.8.1.el8_1.x86_64 #1 SMP Thu Apr 9 13:49:54 UTC 2020 (built for Linux 4.18.0)
Jan 31 02:50:01 host1 Keepalived[20666]: Command line: '/usr/sbin/keepalived' '-D'
Jan 31 02:50:01 host1 Keepalived[20666]: Opening file '/etc/keepalived/keepalived.conf'.
Jan 31 02:50:01 host1 Keepalived[20666]: Configuration file /etc/keepalived/keepalived.conf
Jan 31 02:50:01 host1 Keepalived[20666]: daemon is already running
```

**Expected behavior**
Right keepalived start/restart

**Keepalived version**

```
Keepalived v2.2.1 (01/17,2021)

Copyright(C) 2001-2021 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.18.0
Running on Linux 4.18.0-147.8.1.el8_1.x86_64 #1 SMP Thu Apr 9 13:49:54 UTC 2020
Distro: CentOS Linux 8 (Core)

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-snmp --enable-snmp-rfc --enable-sha1 --enable-json --with-init=systemd --enable-regex build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection LDFLAGS=-Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld

Config options:  LIBIPSET_DYNAMIC NFTABLES SYSTEMD LVS REGEX VRRP VRRP_AUTH JSON OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 MEMFD_CREATE IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA IPTABLES NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE GLOB_ALTDIRFUNC INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RESET_ON_FORK
```

**Distro (please complete the following information):**

 - Name: CentOS
 - Version: 8
 - Architecture: x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
N/A

**Configuration file:**

**Notify and track scripts**
If any notify or track scripts are in use, please provide copies of them

**System Log entries**
See above

**Did keepalived coredump?**
NA

**Additional context**
NA

**Comment by pqarmitage** [comment]
I am using RHEL8.3, but I am assuming that it will behave exactly the same as CentOS 8.

I see that your keepalived is built with SYSTEMD support, which should be fine and certainly works on Fedora 31 with systemd version 243. However RHEL8.3 has systemd version 239. [systemd issue 9656](https://github.com/systemd/systemd/issues/9656) suggests that there are some problems with systemd v239 that can cause the `Failed with result 'protocol'` messages.

What is the value of `Type` in /lib/systemd/system/keepalived.service. I am assuming that it is `notify` since I can see the same problem when using notify. If you change the `Type` to `forking` (and then do `systemctl daemon-reload`), does it resolve the problem?

An alternative to try (i.e. leave it as `Type=notify`) is to change /etc/sysconfig/keepalived to add `-n` to `KEEPALVIED_OPTIONS`. That resolves the problem for me as well, and it is better to use Type=notify then Type=forking.

From the logs when the problem is experienced, and comparing it to using systemd version 243 which works without a problem, it appears that systemd v239 does not wait for the notify once the process has forked and the parent exited, whereas with version 243 it does wait for the notification after the fork/exec/exit of parent.

**Comment by Roxyrob** [comment]
Hi @pqarmitage, you are right, indee systemd loose control of the keepalived processes and one need to kill them manually. 

The solutions suggested work for me. Truly... last night, before file this issue I tried to set type=forking (as on centOS 7 and probably also on CentOS 8, yum install keepalived from AppStream yum repository set so in keepalived.service) but probably I was too tired and to me it seemed not to work... damn...

My apologies for wasting your time.
Thank you.

**Comment by Roxyrob** [comment]
Hi @pqarmitage,
there is some keepalived options not to assign IPv6 addresses ? Probably not so problematic, but it assign:

       Assigned address fe80::250:56ff:fe87:3720 for interface ens192

and we need control on that.

Also, we have been using keepalived on On-Prem  systems for a log time. On AWS we know DataLink layer is not an option as Public Cloud Providers like AWS change as Data Link works with own optimized and security solutions, so we use script using aws cli for monitoring peers and take over on subnets routing. Keepalived is garp based so should not be supported.

As per your experience is this right ? I read this section in INSTALL file "Running in an AWS container" about security group permission vor vrrp protocol, but Data Link layer lask of support is still present, right ?

**Comment by pqarmitage** [comment]
@Roxyrob I'm glad my suggestions have worked for you, and you certainly haven't wasted our time since we now know there is an issue using systemd notify with systemd v239. I have tested it with systemd v241 and that works, so from the above systemd issue linked above I think we can assume that it was v240 that fixed the problem (I don't have a system or VM that has v240 installed). I will now need to see if I can think of a way of detecting systemd version < 240 and whether there is a workaround I can implement.

I don't think you need to worry about the
`Assigned address fe80::250:56ff:fe87:3720 for interface ens192`
log entry. It simple means that keepalived has detected that that address is configured on ens192, it doesn't mean that keepalived is adding it to the interface (I agree that the log message is a bit confusing).

I have never used AWS, so I am not familiar with how it works. From comments other users have made keepalived can be used on AWS, but you need to use `unicast_src` and `unicast_peer` configuration options, so that multicast is not used. My understanding is that there is also an issue when 1 VM takes over an IP address from another VM, and it is necessary to run some aws cli command to notify the AWS environment that the IP address has moved to another VM, and this is achieved by configuration a `notify_master` script in order to execute the aws cli command There is a helpful looking page [keepalived with AWS](http://artemstar.com/2017/03/07/keepalived-failover-for-dns/) seems to have a fairly reasonable explanation. You particularly want to follow what it does with the `master.sh` script.

My understanding is that GARP not being used in AWS is not an issue, so long as the master.sh script is run. ARP is used so that the MAC address for an IP address can be discovered, but it seems to be done differently within an AWS environment.

**Comment by Roxyrob** [comment]
Hi @pqarmitage,
you are right again, keepalived tell "Assigned address..." but this is my test machine IPv6 address, not Assigned by Keepalived. 

In effect with aws cli commads it is possible to move ENI between EC2 (virtual network interfaces aka Elastic Network Interface - with all their properties - e.g. Layer2 managed by AWS correctly for others, so bypassing garp introduced to notify others), but this is not so quick operation for who is accustomed to keepalived failover efficiency... If this can be useful to someone, we find more quick aws like failover/failback to take over entire subnets (changing gateway for their  routes).

As said AWS (as many other Cloud Providers) have non-standard Layer2 behaviors that impose new solutions for "custom" load balancing).

Thank you for useful informations.

**Comment by darix** [comment]
ok we could trigger this bug as well. for us the solution was to pass `--dont-fork` in the /etc/sysconfig/keepalived. which brings us 2 questions 

1. can we ask maybe via libsystemd "are we running under systemd" and automatically assume "dont fork"
2. if 1 is not an option should we patch the service file that ships with the source code to always set `--dont-fork`?

**Comment by pqarmitage** [comment]
I believe that this problem is resolved by commit d875466, and was caused by incorrect signal handling. Commit e00141a8 improves on commit d875466 by using an event_fd rather than signals, and commit 7fee27a2 has some tidying up following those two commits.

If you are using SELinux you will either need a policy update or also add commit e8d12b05. The SELinux permissions I found were required were
```
allow keepalived_t sysctl_net_t:file write;
allow keepalived_t tmpfs_t:file { getattr open read write };
```

I did experiment with setting "dont fork" if keepalived is running under systemd with `type=notify` (this is ascertained by checking that keepalived's parent process has pid 1 and the process's COMM is `systemd` and for the presence of environment variable `NOTIFY_SOCKET` (see keepalived/core/systemd.c), and while it did appear to reduce the frequency with which the problem occurred, it did not resolve it.

The problem was that all the keepalived child processes were using the same signal to notify the parent keepalived process that they had finished reading the configuration file(s), and it isn't until the parent process has received all the notifications that it signals systemd that it has completed startup. Of course this was a completely flawed approach, since if two child processes both signal the parent process before the parent reaps the signals, one of the signals is "lost". It seems that my development system generally has sufficient free CPU cores/threads and is sufficiently idle that the parent process was never blocked from running to reap the child processes signals, which is why I didn't see the problem before I merged the code. What setting "dont fork" appears to do is to save the kernel having to tidy up a terminated process, and therefore the keepalived parent is more likely to be able to be scheduled to reap its child processes' signals (I was just doing `systemctl start keepalived` rather than enabling the keepalived service and rebooting the system; I think during a system boot, with multiple services starting simultaneously, the "dont fork" option is not likely to work at all).

Are you able to backport the patches I have listed above into your build of keepalived v2.2.1? If so, I think that should resolve the problem you are experiencing.

**Comment by darix** [comment]
i will look into the backports in a bit.

as a general note ... systemd prefers that services that use notify do not fork.

**Comment by pqarmitage** [comment]
I think my preference would be to set `--dont-fork` in KEEPALIVED_OPTIONS in the EnvironmentFile specified in the keepalived service file, rather than change the code to modify the forking behaviour if keepalived is being run by systemd with `Type=notify`.

Would that be acceptable to you?

**Comment by darix** [comment]
hmm from an user and distro standpoint this is bad imho. because then we would need to patch all the environment files during the package upgrade to append --dont-fork. if we already know "we want --dont-fork when running under systemd" then i would hardcode that in ExecStart

**Comment by pqarmitage** [comment]
OK, adding --dont-fork to ExecStart if setting `Type=notify` is straightforward.

**Comment by pqarmitage** [comment]
Commit 2661bae adds `--dont-fork` to ExecStart in the systemd keepalived.service file if keepalived is build with systemd notify support.

**Comment by pqarmitage** [comment]
@darix keepalived v2.2.2 was released yesterday.

**Comment by darix** [comment]
Thank you opensuse package is updated and on the way to tumbleweed.
