### ISSUE TITLE
Init file is not creating with manually RPM compiling

### ISSUE THREAD

**Issue by Cengizeren** [acassen/keepalived#1853]
Hi,

I am using Keepalived 2.2.1 on RHEL 6.10. In order to use this package, I built it manually with "rpmbuild", but if I use this way, Keepalived init file is not created automatically under /etc/init.d directory. I have to create it manually after the RPM installation. But I want to create an init file with the RPM building. How can I achieve that?  I applied the following steps to do this process:

 If building from tarball:
  1a. tar -xf TARFILE
  1b. cd into the directory

 If building from git clone:
  1. ./build_setup 

 For tarball and git
  2. ./configure
  3. make rpm

**Comment by pqarmitage** [comment]
@Cengizeren I am happy to investigate this and add installing the keepalived.init file to the keepalived.spec file. However, because RHEL6 has gone EOL, a week ago I merged a series of commits removing build and run time tests that were only needed to support RHEL6, in particular needed to support kernels back to 2.6.32. The oldest kernel that I could find of any distro that is currently not EOL is 3.10 (and the distro that uses it is RHEL7), and so that is the oldest kernel that keepalived now supports.

If I produce a patch to install the keepalived.init file, unfortunately you will need to backport it yourself rather than simply building from a tarball or git clone.

**Comment by Cengizeren** [comment]
@pqarmitage Thanks for your comment, i changed the standard keepalived.spec file for my purpose. Normally, the "/etc/init/keepalived.conf" file is being created. I removed this file and added /etc/init.d/keepalived init file from the source code. After these changes, I installed the new Keepalived rpm package to the system and  it seemed to be working properly

**Comment by pqarmitage** [comment]
@Cengizeren Thanks for you update.

I have pushed commit 958107a which adds installing the /etc/rc.d/init.d/keepalived file, and also updates the RedHat version to match the init file in the RHEL6 rpm. I you want to use the patch you will need to backport it to keepalived v2.2.1 (unfortunately there are some merge conflicts in configure.ac) since, as I mentioned above, from commit f07d3842 RHEL6 is no longer supported .

The commit following 958107a, commit f66dbd1, removes support for generating an RPM for RHEL6, since the support for RHEL6 has been removed elsewhere.

Thanks for reporting this since the addition of the etc/rc.d/init.d/keepalived file is now included in general in the RPM file when needed.
