### ISSUE TITLE
Keepalived lost some routers when reload 

### ISSUE THREAD

**Issue by qingfenghanghua** [acassen/keepalived#1877]
**Describe the bug**
We used ipvsadm -D to delete some routers while the configuration files remained unchanged. And then we reload keepalived,but the routers we deleted by ipvsadm -D were not loaded back.

**To Reproduce**
Use ipvsadm -D to delete some routers and reload keepalived.

**Expected behavior**
All the routers in configuration files  can be loaded when reload,no matter whether  some routers were deletet by ipvsadm -D.
**Keepalived version**
2.2.2
```

**Distro (please complete the following information):**
 - Name: Centos
 - Version: 7
 - Architecture: x86_64
 - GCC: 4.8.5

**Comment by pqarmitage** [comment]
The behaviour you are observing is the expected behaviour if you reload keepalived's configuration (I am assuming that by `reload` you mean sending SIGHUP to keepalived (or `systemctl reload keepalived`) so that keepalived reloads its configuration).

When keepalived reloads its configuration, it compares the new configuration to the configuration it was previously running, and implements any valid changes in the configuration. If you simply reload the configuration that was previously running, keepalived will not make any changes to the system since it detects that nothing has changed.

I can think of no valid reason to delete virtual servers that keepalived has configured; they are keepalived's virtual servers and only keepalived should alter their configuration. Altering the virtual/real servers setup can be achieved in several ways:
i) modify the keepalived configuration and initiate a reload
ii) Use checkers, e.g. CHECK_FILE, so that you can cause real servers to be disabled when you want to.

If you `restart` keepalived, i.e. stop keepalived and start it again, then although keepalived will log some errors when it stops due to trying to delete some of its real and virtual servers that you have already deleted, when keepalived starts again it will re-establish the original configuration.

**Comment by qingfenghanghua** [comment]
Thanks very much.As we guessed, it compares the new configuration to the configuration it was previously running. The reason why    
we ask the question is that we had tested it on the previous version(v 1.2.13),it seems to be no comparison  configuration.Would you confirm it?

**Comment by pqarmitage** [comment]
keepalived v1.2.13 was way before I became involved with keepalived. Commit 853cb97, which was added in v1.2.16, might have changed how virtual/real servers were handled on a reload, but I'm not sure it would have made the difference you are referring to.

If you currently feel you have a need to remove virtual servers, then I think you need to find a way of getting keepalived to do that, as I referred to above, since keepalived will not work properly if its virtual servers are removed by someone/something else.
