### ISSUE TITLE
Split Brain Scenario causes 2 masters in Cluster on return to Normalcy on adevrt, remaining MASTER doesn't send notification again

### ISSUE THREAD

**Issue by amolkavitkar** [acassen/keepalived#1884]
We have a 3 Node cluster, xx.xx.xx.2, xx.xx.xx.3 and xx.xx.xx.1 and vips as xx.xx.xx.4 and xx.xx.xx.5
when link between node-2 and node-3 goes down momentarily (due to link flip) we enter into network isolation stage for few seconds but in that time 2 also becomes MASTER while 3 is already in MASTER state. 

Now once network is back up which happens in few seconds only node-2 receives advert from node-3 and it goes back into BACKUP state.

**WE use notify script for logic depending on MASTER state and current master node IP is stored in DB but now as node-2 became master notify for it gets triggered and DB holds MASTER IP as node-2 and when node-2 receives advert and goes back into BACKUP node-3 doesn't re-announces itself as MASTER (like notfiy script for node-3 doesn't gets triggered) what is expected is node-3 should notify that he won the conflict and he is cluster MASTER now.**

Thu Mar 25 18:00:59 2021: (vip_xx.xx.xx.4) Entering MASTER STATE
Thu Mar 25 18:00:59 2021: (vip_xx.xx.xx.4) using locally configured advertisement interval (1000 milli-sec)
Thu Mar 25 18:00:59 2021: (vip_xx.xx.xx.4) setting VIPs.
Thu Mar 25 18:00:59 2021: Sending gratuitous ARP on enterprise for xx.xx.xx.4
Thu Mar 25 18:00:59 2021: (vip_xx.xx.xx.4) Sending/queueing gratuitous ARPs on enterprise for xx.xx.xx.4
Thu Mar 25 18:00:59 2021: Sending gratuitous ARP on enterprise for xx.xx.xx.4
Thu Mar 25 18:00:59 2021: Sending gratuitous ARP on enterprise for xx.xx.xx.4
Thu Mar 25 18:00:59 2021: Sending gratuitous ARP on enterprise for xx.xx.xx.4
Thu Mar 25 18:00:59 2021: Sending gratuitous ARP on enterprise for xx.xx.xx.4
Thu Mar 25 18:00:59 2021: VRRP_Group(ENTERPRISE) Syncing instances to MASTER state
Thu Mar 25 18:00:59 2021: (vip_xx.xx.xx.5) Entering MASTER STATE
Thu Mar 25 18:00:59 2021: (vip_xx.xx.xx.5) using locally configured advertisement interval (1000 milli-sec)
Thu Mar 25 18:00:59 2021: (vip_xx.xx.xx.5) setting VIPs.
Thu Mar 25 18:00:59 2021: Sending gratuitous ARP on enterprise for xx.xx.xx.5
Thu Mar 25 18:00:59 2021: (vip_xx.xx.xx.5) Sending/queueing gratuitous ARPs on enterprise for xx.xx.xx.5
Thu Mar 25 18:00:59 2021: Sending gratuitous ARP on enterprise for xx.xx.xx.5
Thu Mar 25 18:00:59 2021: Sending gratuitous ARP on enterprise for xx.xx.xx.5
Thu Mar 25 18:00:59 2021: Sending gratuitous ARP on enterprise for xx.xx.xx.5
Thu Mar 25 18:00:59 2021: Sending gratuitous ARP on enterprise for xx.xx.xx.5
**Thu Mar 25 18:01:25 2021: (vip_xx.xx.xx.4) Master received advert from xx.xx.xx.3 with same priority 100 but higher IP address than ours**
Thu Mar 25 18:01:25 2021: (vip_xx.xx.xx.4) Entering BACKUP STATE
Thu Mar 25 18:01:25 2021: (vip_xx.xx.xx.4) removing VIPs.
Thu Mar 25 18:01:25 2021: VRRP_Group(ENTERPRISE) Syncing instances to BACKUP state

**Ref Keepalived config file ( we can configure up-to 4 interfaces so conf file is bigger)**
global_defs {
vrrp_version 3
vrrp_iptables MAGLEV-KEEPALIVED-VIP
enable_script_security
script_user keepalived_script
vrrp_garp_master_delay 40
vrrp_garp_master_refresh 60
}

vrrp_script node_health_check {
script "/node_health_check.py"
interval 60 # check every 60 seconds
timeout 40 # Script Timeout of 40 seconds
fall 3 # require 3 failures for FAULT Transition
}

vrrp_instance vip_xx.xx.xx.234 {
state BACKUP
interface management
virtual_router_id 119
nopreempt
advert_int 1

track_interface {
management
}

virtual_ipaddress {
xx.xx.xx.234 dev management scope global
}

unicast_src_ip xx.xx.xx.231
unicast_peer {
xx.xx.xx.233
xx.xx.xx.232
}

track_script {
node_health_check
}

notify /keepalivednotify.py root
}

vrrp_instance vip_xx.xx.xx.234 {
state BACKUP
interface enterprise
virtual_router_id 44
nopreempt
advert_int 1

track_interface {
enterprise
}

virtual_ipaddress {
xx.xx.xx.234 dev enterprise scope global
}

unicast_src_ip xx.xx.xx.231
unicast_peer {
xx.xx.xx.233
xx.xx.xx.232
}

track_script {
node_health_check
}

notify /keepalivednotify.py root
}

vrrp_instance vip_xx.xx.xx.4 {
state BACKUP
interface cluster
virtual_router_id 41
nopreempt
advert_int 1

track_interface {
cluster
}

virtual_ipaddress {
xx.xx.xx.4 dev cluster scope global
}

unicast_src_ip xx.xx.xx.1
unicast_peer {
xx.xx.xx.3
xx.xx.xx.2
}

track_script {
node_health_check
}

notify /keepalivednotify.py root
}

**Comment by pqarmitage** [comment]
@amolkavitkar You don't indicate what version of keepalived you are using, so I am working on the basis that you are using the current version, v2.2.2.If you are not using an earlier version of keepalived and I suggest using a feature not included in that version you will need to upgrade to a later version.

There are clearly some significant differences between the configuration you are using and the configuration posted above, since the logs show a vrrp_sync_group but the configuration above does not have one configured. This makes diagnosing problems unreliable and difficult.

As I mention below it is bad practice to configure corresponding VRRP instances with the same priority. It would be much clearer to use different priorities on different systems; since you are using `nopreempt` a higher priority instance will not take over from a lower priority instance, but when there are multiple masters due to the situation you describe, you are using the source IP addresses to determine which system remains master, rather than using priorities.

You shouldn't be using notify_scripts if you want reliable notification; if two state transitions occur within a very short time interval, it cannot be determined what order the kernel will schedule the script processes to run. For reliable sequenced delivery of notifications, it is necessary to use a notify_fifo.

The issue you describe is a well known problem, and strictly isn't handled by the VRRP protocol; however, keepalived has some added functionality to allow this situation to be handled.

You have identified you have a split brain scenario, and in that situation it is inevitable that there will be 2 (or more) master VRRP instances. The issue is how do they recover once network connectivity is restored. I will describe the situation where there are only two systems running VRRP; the description can be extended to having 3 or more systems.

Let the two systems by A and B, with A having higher priority than B (or if the priorities are the same A has a higher IP adress than B). After network connectivity is restored there are three possibilities:
1. A receives an advert from B before B receives an advert from A
2. B receives an advert from A before B sends an advert
3. Both A and B receive adverts

1. When A receives a (lower priority) advert from B, it will immediately send an advert (provided `lower_prio_no_advert` is not configured). B then knows there is a higher priority master, and B will transition to backup. In this situation, if you have a `notify_fifo` configured, a message will be sent to the FIFO with `MASTER_RX_LOWER_PRI`; this is intended for exactly this situation so that the system remaining as master can take the necessary action, in your case update the database.

2. When B receives the first advert, it realises the other system has a higher priority, and so immediately transitions to backup and stops sending adverts. The problem here is that system A is not aware that B was also in master state. It was for this reason that I added the configuration option `higher_prio_send_advert`. If `higher_prio_send_advert` is configured, system B will send an advert (which will be lower priority than A) as it transitions to backup. A will receive the lower priority advert, and then act as 1. above, so that a `MASTER_RX_LOWER_PRI` message is sent on the FIFO.

3. This will probably cause two `MASTER_RX_LOWER_PRI` messages on the FIFO on system A, but that shouldn't be a problem. It should be straightforward to work out the sequence of events from 1. and 2. above.


You might be interested in the following issues I have noticed with your configuration:

1. I assume that xx.xx.xx is different for interface `cluster` and interface `management`, unless you are using a /25 or longer network mask. It is not helpful to show them as being the same if they are different.
2. Specifying a track interface for the interface that the VRRP instance is configured on is unnecessary.
3. It is unnecessary to specify `dev management` etc on the virtual ip addresses when the interface is the interface that the VRRP instance is configured on.
4. It is bad practice to put scripts in the root directory of the system (this is a general comment and applies not only to keepalived). If would be better to put them in /etc/keepalived, or create /etc/keepalived/scripts and put them there.
5. It is bad practice to configure the corresponding VRRP instances on different systems with the same priority. You are already using `nopreempt` so you should just specify different priorities on the different systems.
