### ISSUE TITLE
insertion point of iptables rules is different depending if ipset is in use or not

### ISSUE THREAD

**Issue by msoltyspl** [acassen/keepalived#1888]
**Describe the bug**
While it's obviously better to use custom chains for this (as one can control the exact moment of their traversal) - if keepalived is set to use standard chains - I noticed slighlty different behavior depending if ipsets were or weren't used.

Consider configuration that has:

- vrrp_ipsets w/o arguments under global_defs (which disables ipset use)
- no_accept is set

In such configuration, filter table rules look like (keepalived rules marked with *->):

```
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT ACCEPT
*-> -A INPUT -d 192.168.60.150/32 -j DROP
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
<other rules ....>
-A INPUT -p tcp -j REJECT --reject-with tcp-reset
-A INPUT -j REJECT --reject-with icmp-admin-prohibited
-A FORWARD -p tcp -j REJECT --reject-with tcp-reset
-A FORWARD -j REJECT --reject-with icmp-admin-prohibited
*-> -A OUTPUT -s 192.168.60.150/32 -j DROP
-A OUTPUT -j ACCEPT
*-> -A OUTPUT -o float60 -p igmp -j DROP
```

Note the no_accept related filtering are **inserted before** existing rules.

If we remove vrrp_ipsets from the configuration (thus making keepalived rely on defaults w.r.t. ipsets), then the rules will look like:

```
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
<othter rules ....>
-A INPUT -p tcp -j REJECT --reject-with tcp-reset
-A INPUT -j REJECT --reject-with icmp-admin-prohibited
*-> -A INPUT -m set --match-set keepalived dst -j DROP
-A FORWARD -p tcp -j REJECT --reject-with tcp-reset
-A FORWARD -j REJECT --reject-with icmp-admin-prohibited
-A OUTPUT -j ACCEPT
*-> -A OUTPUT -p igmp -m set --match-set keepalived_igmp dst,dst -j DROP
*-> -A OUTPUT -m set --match-set keepalived src -j DROP
```
Note the no_accept related filtering are **added after** existing rules.

**To Reproduce**
Use the included config, comment out vrrp_ipsets to see difference in the behavior.

**Expected behavior**
Rule placement should probably be the same - regardless if keepalived relies on ipsets or not.

**Keepalived version**
```
Keepalived v2.2.2 (03/05,2021)

Copyright(C) 2001-2021 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.10.13
Running on Linux 5.11.11-arch1-1 #1 SMP PREEMPT Tue, 30 Mar 2021 14:10:17 +0000
Distro: Arch Linux

configure options: --prefix=/usr --sysconfdir=/etc --sbindir=/usr/bin --localstatedir=/var --runstatedir=/run CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now CPPFLAGS=-D_FORTIFY_SOURCE=2

Config options:  LIBIPSET_DYNAMIC NFTABLES LVS VRRP VRRP_AUTH VRRP_VMAC OLD_CHKSUM_COMPAT INIT=systemd SYSTEMD_NOTIFY

System options:  VSYSLOG MEMFD_CREATE IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA IPTABLES NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE VRRP_IPVLAN IFLA_LINK_NETNSID GLOB_BRACE GLOB_ALTDIRFUNC INET6_ADDR_GEN_MODE VRF SO_MARK
```

**Distro (please complete the following information):**
 - Name: Arch
 - Version: n/a, rolling release distro
 - Architecture: x86_64

**Configuration file:**
```
global_defs {
 vrrp_version          3
 vrrp_iptables
 vrrp_ipsets
}

vrrp_instance test {
 interface               qeth60
 promote_secondaries
 use_vmac                float60
 state                   MASTER
 virtual_router_id       1
 priority                100
 no_accept

 virtual_ipaddress {
   192.168.60.150/24 noprefixroute
 }

```

**Comment by pqarmitage** [comment]
@msoltyspl I started replying to your message to keepalived-users@groups.io, but since you have now raised this as an issue I will respond here.

I have had a look at the code and can see why this is happening as you describe. In keepalived/vrrp/vrrp_iptables.c in function add_del_vip_rules(), which is used when using ipsets, the third parameter of the calls to ip4_tables_add_rules() is APPEND_RULE (likewise for ip6_tables_add_rules()). In handle_iptable_rule_to_vip(), which is used when not using ipsets, the third parameter to iptables_entry() is 0, which means that the rule is inserted at the beginning of the chain; however the IGMP rule as added using APPEND_RULE. I agree this is not sensible, and was presumably an oversight when I implemented it.

I don't think I can change the behaviour now since some users will be using ipsets and some will not, and they have presumably configured everything so that it works for them; changing the behaviour now would therefore break the configuration for some.

I am not particularly concerned about this, since it should only be a problem if the INPUT and OUTPUT chains are used, and it is not sensible to do so; as you say, custom chains should be used. Adding rules at the end of INPUT doesn't work with your configuration, and I would want RELATED,ESTABLISHED early, before the keepalived rules, so neither adding rules at the beginning or end of the INPUT chain really works. Basically, using INPUT/OUTPUT is bad practice.

Nowadays, ideally users will not use iptables/ipsets, but use nftables instead. It is much easier to handle, keepalived creates its own chains with the relevant hooks, and changes are much quicker to process.

There is a further problem with using iptables. If the iptables command is a link to iptables-nft, then executing an iptables command to create chains and add rules to call those chains will actually add nftables configuration. If keepalived were then to add iptables configuration (which it does directly to the kernel), then whatever it added would not be used. As a solution to this problem (which could be caused when a user upgrades their installation), keepalived checks whether the iptables command is actually iptables-nft, and if it is it uses nftables instead of iptables, even if vrrp_iptables has been specified. Essentially use of iptables/nftables is an internal matter for keepalived, but because of the need for the user to specify the iptables chains to be used it had to have a configuration option for it.

I have updated the keepalived.conf(5) man page to add the following:
```
    # Note: although the default chains that are used are INPUT and OUTPUT,
    # since those are the only chains that will always exist, it is not safe
    # or sensible to use those chains and specific chains should be created
    # and called from appropriate points in the iptables configuration. The
    # chains used for keepalived should not be used for any other purpose, and
    # should have no rules configured, other than the rules that keepalived
    # manages.
    # A startup_script (see above) can be used to create the chains and to
    # add rules to call them. A shutdown_script can be used to remove the
    # iptables configuration added by the startup_script.
    # Note2: If using ipsets, the iptables VIP rules are appended to the end
    # of the specified chains; if not using ipsets, the VIP rules are inserted
    # at the beginning of the chains. Any IGMP rules are always appended to
    # the end of the chains.
```
This will be commit 2d3476a once I have merged it.
