### ISSUE TITLE
Didn't clean up default route after remove it in from virtual_routes

### ISSUE THREAD

**Issue by lucheng0127** [acassen/keepalived#1900]
**How to reproduce**
1. Add a default route into virtual_routes and restart keepalived
2. Use ip r show route tables default route add succeed
3. Remove default route that added before from config
4. Except the route added before will clean up, but it still here

```
# Keepalived config file after add default static route
    virtual_routes {
        0.0.0.0/0 via 172.16.10.1 dev qg-a771c9fc-78
        0.0.0.0/0 via 192.168.101.13
    }
# Keepalived config file after delete default static route
    virtual_routes {
        0.0.0.0/0 via 172.16.10.1 dev qg-a771c9fc-78
    }
    
# Routes of qrouter namespace after add and delete default static route
[root@node-6 ~]# ip netns exec qrouter-59a3f6de-5a17-4e79-ba7c-dda143b674ea ip rf
default via 192.168.101.13 dev qr-15f4fecb-71
default via 172.16.10.1 dev qg-a771c9fc-78
169.254.0.0/24 dev ha-55f8d429-75 proto kernel scope link src 169.254.0.2
169.254.192.0/18 dev ha-55f8d429-75 proto kernel scope link src 169.254.192.3
172.16.10.0/24 dev qg-a771c9fc-78 proto kernel scope link src 172.16.10.130
192.168.101.0/24 dev qr-15f4fecb-71 proto kernel scope link src 192.168.101.1
```

**Expected behavior**
The default route has been clean up

**Keepalived version**
```
[root@node-6 ~]# keepalived -v
Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2

Copyright(C) 2001-2017 Alexandre Cassen, <acassen@gmail.com>

Build options:  PIPE2 LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_PREF FRA_OIFNAME FRA_SUPPRESS_PREFIXLEN FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK LIBIPTC LIBIPSET_DYNAMIC LVS LIBIPVS_NETLINK VRRP VRRP_AUTH VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC FIB_ROUTING INET6_ADDR_GEN_MODE SNMP_V3_FOR_V2 SNMP SNMP_KEEPALIVED SNMP_CHECKER SNMP_RFC SNMP_RFCV2 SNMP_RFCV3 SO_MARK
```

**Distro (please complete the following information):**
 - Name: Centos
 - Kernel Version: 4.18.0
 - Architecture: x86_64

**Comment by pqarmitage** [comment]
The same problem occurs with keepalived v2.2.2.

I need to understand what is happening here. If I execute the commands:
```
ip route add 0.0.0.0/0 via 172.16.10.1 dev qg-a771c9fc-78
ip route add 0.0.0.0/0 via 192.168.101.13
```
then the second command returns:
`RTNETLINK answers: File exists`

However, keepalived succeeds in adding the two routes.

So the question I need to resolve first is: is keepalived doing something wrong that is allowing both routes to be added.

There is a comment in vrrp_iproute.c that says `/* The kernel's key to a route is (to, tos, preference, table) */`, and that is what keepalived checks to see if a route in the new configuration matches a route in the old configuration. With the two routes you are using the match is positive, and therefore keepalived does not detect that it needs to delete the removed route. My recollection is that I added the comment after testing with the `ip route` command to see what caused `RTNETLINK answers: File exists` to be returned; clearly that is insufficient and I need to explore further.

**Comment by lucheng0127** [comment]
Yep, if use iproute2 command to add default it will raise error RTNETLINK answers: File exists
but if there is a default route in virtual_routes, keepalived will add this route succeed

**Comment by pqarmitage** [comment]
I have discovered that if you use the (undocumented) command `ip route prepend 0.0.0.0/0 via 192.168.101.13` instead of `ip route add 0.0.0.0/0 via 192.168.101.13` then it succeeds. The difference between `add` and `prepend` is that `prepend` does not set the `NLM_F_EXCL` flag (i.e. exclusive), and also keepalived does not set the `NLM_F_EXCL` flag.

Since we don't set the NLM_F_EXCL flag, there are further checks that need to be made for a match. In the kernel source  file net/ipv4/fib_trie.c in function fib_table_insert() it states `Find exact match for type, scope, fib_info to avoid duplicate routes`, and later it states `Error if we find a perfect match which uses the same scope, type, and nexthop information`.

We therefore need to add checks for scope, type and nexthop details to the existing checks to see if a route matches.

**Comment by lucheng0127** [comment]
Maybe we should use NLM_F_REPLACE falg, when we try to add a duplicate route we should replace the old one

**Comment by pqarmitage** [comment]
I don't think using NLM_F_REPLACE is the right approach, since then the routes that had been configured in keepalived would not all be added to the kernel.

Commit 4c0a6b4 should resolve the issue. However, you will need to upgrade to the latest version of the code, since the commit certainly will not backport to v1.3.5.
