### ISSUE TITLE
Add a custom string to virtualhostst

### ISSUE THREAD

**Issue by igroost** [acassen/keepalived#1910]
I want to add a string value of the form virtualhost "VIP-NAME (10.10.10.10) port 80"to the configuration in the virtualhost parameter. For the purposes of escaping the () characters, I use double quotes. And it seems to work, in snmp I get the desired output
```
#snmpwalk-Oafn-v 2c-c ipvs 10.1.57.20 .1.3.6.1.4.1.9586.100.5.3.3.1.12.2
.1.3.6.1.4.1.9586.100.5.3.3.1.12.2 = STRING: "RUTUBE-FH (10.9.200.7) port 80"
```
However, with this configuration, several VIPs for some reason do not work, there are no errors in the configuration, only the VIP address is issued in the output of ipvsadm-ln, as if the RS checks do not pass, although in fact the RS are available and respond as they should. An arbitrary number of keepalived restarts allows you to put a certain number of similar VIPs into operation, but not all of them. I tried in the configuration to escape the value through single quotes, but this does not lead to the desired effect. Tell me, what could be the reason for this behavior, can not keepalived rest on the restriction of some variables or other mechanisms?

The software we use

```
$ keepalived -v
Keepalived v2.1.5 (11/25,2020), git commit v2.1.5-210-gedd68ac

Copyright(C) 2001-2020 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.19.78
Running on Linux 4.19.78-3.1.x86_64 #1 SMP Thu Jan 9 15:47:22 UTC 2020
Distro: CentOS Linux 7 (Core)

configure options: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --enable-snmp --enable-snmp-rfc --enable-vrrp --disable-lvs-syncd --disable-vrrp-auth --disable-iptables --with-init=systemd --enable-regex --enable-regex-timers --enable-checker-debug --enable-regex-debug --enable-log-file build_alias=x86_64-redhat-linux-gnu host_alias=x86_64-redhat-linux-gnu PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic LDFLAGS=-Wl,-z,relro 

Config options:  LVS REGEX REGEX_DEBUG VRRP OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 FILE_LOGGING LOG_FILE_APPEND CHECKER_DEBUG

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION LIBIPTC_LINUX_NET_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RESET_ON_FORK

$ uname -r
4.19.78-3.1.x86_64
```

In our keepalived configuration, there are currently about 119 VIPs configured

An example of the standard VIP configuration we use

```
virtual_server 10.10.10.10 8080   {
virtualhost "TEST-NAME (10.10.10.10) port 8080"
        delay_loop 10
        alpha 1
        omega 1
        lvs_sched rr
        lvs_method TUN
        smtp_alert on
        retry 3
        delay_before_retry 3
        protocol TCP

    quorum 1

        quorum_up "/sbin/ip -4 addr add 10.10.10.10/32 dev lo"
        quorum_down "/sbin/ip -4 addr del 10.10.10.10/32 dev lo"


real_server 10.10.108.22 8080 {
        weight 1
        TCP_CHECK {
            connect_timeout 3
                   }
                            }


real_server 10.19.2.22 8080 {
        weight 1
        TCP_CHECK {
            connect_timeout 3
                   }
                            }
                                   }
```

**Comment by pqarmitage** [comment]
@igroost 

The purpose of the `virtualhost` keyword is to specify the virtual host in HTTP requests sent by HTTP_GET and SSL_GET checkers. The `virtualhost` name that you are configuring is not a valid DNS name, and so it should not be relied upon to work (the reason you need the `"`s is to escape the spaces, not the brackets). I am not clear why you are configuring `virtualhost` since you do not appear to be using HTTP_GET or SSL_GET checkers. Have you tried configuring a valid virtual host such as `www.example.com` to see if that makes any difference?

VIPs are used with VRRP, which you have not mentioned here. I am guessing that you are referring to the IP addresses you add using quorum_up.

I am not clear how your configuration is working, and whether or not you have 2 or more systems running keepalived with this configuration. It appears to me that if you do have 2 or more systems running this configuration, then you will potentially have addresses such as 10.10.10.10 configured on both of them. If you only have one server running this configuration, then I cannot see the purpose of dynamically adding and removing the addresses.

I have run the configuration snippet you have provided above, and 10.10.10.10 is added to the lo interface, so the configuration snippet is not showing the problem. Can you please provide the following information so that we can investigate this:
1. A copy of your full keepalived configuration
2. The full keepalived logs from the time keepalived starts (ideally running keepalived with the `-D` command line option)
3. The output of `ip addr show`
4. The output of `ipvsadm -Ln`
4. Identification of what addresses are causing a problem.

I think you state that the output of `ipvsadm -ln` shows some of the virtual servers with no real servers configured, and as you state that implies that the TCP_CHECKs have not been successful. This would imply that the quorum has not been achieved, and consequently the quorum_up script will not have run and hence the IP addresses will not have been added to the lo interface.

Is this problem really that some of the TCP_CHECKs are not succeeding?

**Comment by igroost** [comment]
@pqarmitage 

We do not use VRRP. We have two separate keepalived servers installed in different data centers that run the same configuration that I send in the attachment.

When configuring the text description in the virtualhost line, there was a problem with three virtual_servers 10.9.200.4, 10.9.200.14, 10.9.200.63. As you can see in the ipvsadm output, they are there, but there are no real servers behind them, but I can guarantee that checks for them pass because everything works on the production keepalived server, the only difference is that there are values for each virtual_server in virtualhost in the configuration for the example address 10.9.200.63

On the example of the address 10.9.200.63
If in the configuration we have specified so
```
virtual_server 10.9.200.63 80  {
virtualhost 10.9.200.63:80
```
then everything works.

If this is specified in the configuration, then we get a problem with at least three VIPs.
```
virtual_server 10.9.200.63 80  {
virtualhost "SB-STORAGE (10.9.200.63) port 80"
```
We do all this to take not only the IP virtual_server but also the description over snmp.

[keepalived.log](https://github.com/acassen/keepalived/files/6539997/keepalived.log)
[show_ipvsadm.txt](https://github.com/acassen/keepalived/files/6539998/show_ipvsadm.txt)
[ip_aadr_show.txt](https://github.com/acassen/keepalived/files/6539999/ip_aadr_show.txt)

**Comment by pqarmitage** [comment]
@igroost Many thanks for the above details. Unfortunately the keepalived.log is truncated so I cannot see what is logged when keepalived starts running the configuration. Could you also please provide a full copy of your configuration so that I can try and reproduce the problem.

**Comment by igroost** [comment]
@pqarmitage Yes, I forgot to attach the config file last time.

[keepalived.conf.txt](https://github.com/acassen/keepalived/files/6546564/keepalived.conf.txt)

**Comment by igroost** [comment]
@pqarmitage 
How correctly I understand the documentation and will this option work:

In the virtualhost directive of the virtual_server section, we specify an arbitrary string value, but in order for the HTTP \ SSL_CHECK checks to work normally, we already specify the required virtualhost at their level. Judging by the documentation, if virtualhost is not specified at the level of HTTP \ SSL_CHECK checks, then it is taken from a similar directive in the virtual_server section. Do I understand everything correctly, or will it not work like this?

**Comment by pqarmitage** [comment]
If `virtualhost` is specified in the HTTP_CHECK/SSL_CHECK, then that is used. If it is not specified there, the `virtualhost` setting configured in the read_server section is used, and if that is not specified then the `virtualhost` setting for the virtual server is used. This is all as specified in the keepalived.cof(5) man page.

@igroost Could you please provide the full keepalived.log; what you have provided above is only the beginning of the log.

**Comment by igroost** [comment]
@pqarmitage 
>If virtualhost is specified in the HTTP_CHECK/SSL_CHECK, then that is used. If it is not specified there, the virtualhost >setting configured in the read_server section is used, and if that is not specified then the virtualhost setting for the virtual >server is used. This is all as specified in the keepalived.cof(5) man page.

Yes, I read the documentation, I just clarify what I understood correctly. It turns out that we can specify the necessary virtualhost at the verification level so that it passes correctly, and at the virtualserver level we can specify the virtual_host already with a description that we will pick up via snmp i.e. in this configuration, these two virtual_hosts will not interfere with each other.

I ran keepalived again and attach the log again. I do not know for what reason, but the records of the execution of checks are indicated there in very small quantities, although as you can see at the beginning of the log keypalived is launched with the debug option. I waited a while after launch, but no new messages appeared in the log.
[keepalived.log](https://github.com/acassen/keepalived/files/6553844/keepalived.log)

**Comment by pqarmitage** [comment]
Unfortunately due to you using the `-d` keepalived option, it appears that the logger process rate limits keepalived logging and so log entries are discarded from part way through logging the configuration details until several minutes later. This means that it is not possible to determine what happened in the intervening period. It would be better to run keepalived without the `-d` option and if you want to see the status of keepalived with its current configuration, then send SIGHUP to the parent process which will cause keepalived to write /tmp/keepalived_check.data with the same details as appears in the log.

You appear to always run a version of keepalived built for a newer kernel than the system is running, e.g.
`WARNING - keepalived was built for newer Linux 5.4.40, running on Linux 4.19.78-3.1.x86_64 #1 SMP Thu Jan 9 15:47:22 UTC 2020`
This is not supported, and it means that keepalived may attempt to use kernel features that do not exist in the kernel you are running on.

You state above that the RSs for VSs 10.9.200.63, 10.0.200.14 and 10.9.200.4 are missing. Could that relate to the following log entries:
```
May 25 01:03:02 ipvs-test-102 Keepalived_healthcheckers[19752]: Removing Virtual Server [10.9.200.63]:tcp:80
May 25 01:03:02 ipvs-test-102 Keepalived_healthcheckers[19752]: Removing Virtual Server [10.9.200.14]:tcp:6379
May 25 01:03:02 ipvs-test-102 Keepalived_healthcheckers[19752]: Removing Virtual Server [10.9.200.4]:tcp:80
May 25 01:03:02 ipvs-test-102 Keepalived_healthcheckers[19752]: Removing Virtual Server [10.9.200.4]:tcp:8500
```
There are similar log entries at May 25 08:37:07.

I think the problems may relate to the HTTP_GET/SSL_GET checkers. You are specifying a `virtualhost`, and that is then used in the `Host` field of the HTTP GET request. Since what you are specifying in the `virtualhost` field is not a valid DNS hostname, the web servers should respond with an error, or worse still they may become confused and not respond properly at all.

I have run your configuration and I cannot reproduce the problem you are experiencing, albeit I have changed some of the checkers and I am not using HTTP_GET or SSL_GET checkers (to reproduce any problems with those checkers would also require web servers identical to yours).

If we are to be able to investigate this problem any further we will need the following:
1. Run a version of keepalived built for the running kernel or an earlier version of the kernel
2. The keepalived configuration in use at the time
3. The full keepalived log from when keepalived started to after the problem occurred, without using the `-d` option
4. The /tmp/keepalived_check.data file produced by executing `kill -USR1 KEEPALIVED_PARENT_PID`
5. The output of `ipvsadm -Ln`
6. The output of `ip addr show lo`

Whilst it would be good to resolve whatever the issue is here, it might be possible to find an alternative solution to using `virtualhost` in an invalid way. Can you please describe what it is you are wanting to achieve by using the `virtualhost` entries in the way that you are.

**Comment by igroost** [comment]
@pqarmitage 
I will try to gather the necessary conclusions for a detailed diagnosis.

As for the task that we want to solve by specifying non-standard entries in virtualhost - so we wanted to get not only the IP VSs through snmp, but also the description.

**Comment by igroost** [comment]
@pqarmitage 
Looks like I figured out what the problem was. 
Due to the fact that the testing was not performed on a combat vehicle, there was an error in the HC-REDIS-PING-PONG-A-B verification file, which always returned a non-null code. I also corrected the RSS configuration for Vs 10.9.200.4 by adding the IP addresses of Vs to HTTP_CHECK. Now the test machine with the specified custom virtualhost in VSs processes the same number of VSs as without custom values.

In order to have more messages in the log, it was really necessary to disable the-d option. Do I understand correctly that the-d option just prints the configuration to the log? I.e. with the-d option enabled, you can understand from the log what configuration was used in the work? And if, for example, there is an error in the configuration, and the-d option is not enabled, the error will still be reported in the log? 

At this point, I think we can close the ticket, it looks like we can do what we need.

**Comment by pqarmitage** [comment]
@igroost I am glad that you have found the problem and that the issue is resolved for you.

You are correct about the `-d` option; it just writes the configuration to the log file. The problem with large configurations is that the syslog utility can decide that the process is logging to much too quickly, and so it then discards log entries for a while until the process has calmed down. If you want to see the configuration that keepalived is running, you can send signal SIGUSR1 to the parent keepalived process, and the checker process will write its configuration to /tmp/keepalived_check.log (the parent, VRRP and BFD processes will also write their configurations to other /tmp/keepalived_*.log files), and then there is no issue with the syslog utility discarding log entries.

Any errors in the configuration should be logged regardless of whether the `-d` option is used or not; if any error is not logged I would treat that as a bug and produce a fix if the problem were reported.

I have one concern about what how you are using `virtualhost`. As I mentioned before, this is used to populate the `host` field in the HTTP request, and what you are specifying is not a valid hostname; this could cause a web server to respond inappropriately, or perhaps even appropriately, by rejecting the HTTP GET due to an invalid hostname. It seems to me that what you want is the SNMP output to include a string that you can use to identify the virtual_server. What we could do is add an extra field, e.g. snmp_name, that could be included in the SNMP output as a separate identifier (OID), so that you get the string you want included (e.g. "RUTUBE-FH (10.9.200.7) port 80"), but you are then not misusing a field which causes the HTTP_GET checker to send an invalid HTTP GET request (it would mean that your approach could also work if the web server is configured to use virtual hosts).

Would you like me to add an "snmp_name" field to the configuration that is included in the SNMP output, but is not the virtualhost field (which would still be included in the SNMP output, but could then be used solely for its proper purpose)? My concern is that what you are doing may at some point break in the future, for example of your web servers are upgraded and start rejecting requests based on the invalid host name.

**Comment by igroost** [comment]
@pqarmitage 
Thanks for the detailed answers.
Isn't there any information somewhere, what other signals can be sent to the keepalived process to get some information in the same way as it is done with the configuration output, maybe we could use some of them?

Regarding the main problem, if it is possible to add a field like snmp_name I think that would be the best solution! How difficult it will be to add the snmp_name field for both VSs and RSS is not sure, but maybe in the future we will need to collect names and RSS.

Regarding the current configuration, I did so, and judging by tcpdump, the call goes with the correct virtualhost, but I agree that this is a crutch solution. the virtualhost option was invented for another and we may encounter special effects.

`virtual_server 10.9.200.4 80       {
virtualhost "CONSUL-GATE (10.9.200.4) port 80"
        delay_loop 5
        alpha 1
        omega 1
        lvs_sched rr
        lvs_method TUN
        smtp_alert on
        retry 3
        delay_before_retry 3
        protocol TCP

#mediaid-routes-consul-101.
real_server 10.1.110.180 80 {
        HTTP_GET {
             url    {
             path /
             status_code 401
             virtualhost 10.9.200.4
                     }
                  }
                             }

#mediaid-routes-consul-201.
real_server 10.2.110.180 80 {
        HTTP_GET {
             url    {
             path /
             status_code 401
             virtualhost 10.9.200.4
                     }
                  }
                             }

#mediaid-routes-consul-301.
real_server 10.10.110.180 80 {
        HTTP_GET {
             url    {
             path /
             status_code 401
             virtualhost 10.9.200.4
                     }
                  }
                              }
                                    }`

**Comment by pqarmitage** [comment]
Commit 282154c adds virtual_server and real_server `snmp_name` configuration options. These are reported in SNMP output as virtualServerName and realServerName.
