### ISSUE TITLE
Keepalived with backup freeze

### ISSUE THREAD

**Issue by azlux** [acassen/keepalived#1927]
**Describe the bug**
Keepalived on HA1 don't send GARP (or bradcast arp) after the slave (HA2) have become master, then slave again.... during a backup task.
We think the backup freeze the device while creating a snapshot (during few second). So the HA1 don't know the HA2 have been master for the VRRP.
Result : the router think the HA2 have the vrrp IP, send the traffic during 4H until the arp entry is cleared

**To Reproduce**
- Install a master (HA1)/slave(HA2) keepalived on two VM (VMWARE)
- Schedule a Veeam backup (Veeam software) every days
- Wait... a lot (append 2 times during one entire year). Very strenuous to reproduce, this append by accident during on backup task.

**Expected behavior**
- When the HA2 become slave, the HA1 should send a arp broadcast (and garp)

**Keepalived version**
```
Keepalived v2.0.10 (11/12,2018)

Copyright(C) 2001-2018 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.18.20
Running on Linux 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28)

configure options: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --with-kernel-dir=debian/ --enable-snmp --enable-sha1 --enable-snmp-rfcv2 --enable-snmp-rfcv3 --enable-dbus --enable-dbus-create-instance --enable-json --enable-bfd build_alias=x86_64-linux-gnu CFLAGS=-g -O2 -fdebug-prefix-map=/build/keepalived-8agDac/keepalived-2.0.10=. -fstack-protector-strong -Wformat -Werror=format-security LDFLAGS=-Wl,-z,relro CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2

Config options:  LIBIPSET_DYNAMIC LVS VRRP VRRP_AUTH JSON BFD OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 DBUS DBUS_CREATE_INSTANCE

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA LIBIPTC LIBIPSET_PRE_V7 LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK

```

**Distro (please complete the following information):**
 - Name:  Debian 10.7
 - Architecture: x86_64
- Uname : `Linux ******-rp2 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux`

**Configuration file:**
```
global_defs {
  script_user root
  enable_script_security
}

vrrp_script chk_haproxy {
   script "/usr/bin/systemctl status haproxy" # verify le status haproxy
   interval 2                            # check every 2 seconds
   weight 2                                  # add 2 points of prio if OK

}
vrrp_instance ********-rproxy {
    state BACKUP
    interface ens192
    virtual_router_id 51
    priority 100
    advert_int 1
    track_script {
      chk_haproxy
    }
    authentication {
      auth_type PASS
      auth_pass *********
    }
    virtual_ipaddress {
      10.16.20.65/28
    }
}
```

**System Log entries**
There are logs on the HA2 only. The HA1 do produce any logs during the bug.
![image](https://user-images.githubusercontent.com/11210117/124150059-7bf99780-da91-11eb-9ef4-47516580f42a.png)

**Additional context**
After manual and additionnal configuration analysis, we think we think to add three options to avoid our issue, by adding some delay, and vrrp_higher_prio_send_advert  to send another advert :
- vrrp_garp_master_delay 15 
- vrrp_garp_lower_prio_delay  15
- vrrp_higher_prio_send_advert  true

Can you confirm me if theses parameters are a good config to add ?

Best regards
Azlux

**Comment by pqarmitage** [comment]
`vrrp_garp_master_delay` and `vrrp_garp_lower_prio_delay` should not be necessary, and I don't think they will make any difference in your situation. They just cause _additional_ GARP messages to be sent after the delay interval, and you really want to make sure that the first GARP messages are sufficient.

There are two scenarios that you need to cover after the backup on HA1 completes and keepalived starts running again:
1. HA1 sends an advert before HA2
1. HA2 sends an advert before HA1

In the second case you should not have a problem because HA1, when it sees a lower priority advert, will immediately send its own (higher priority advert) followed by one or more GARP messages (unless you have specified `strict_mode`).

The first case means that, by default, HA2 will revert to backup state, and HA1 will never know that HA2 had been master. To handle this situation, specifying `vrrp_higher_prio_send_advert true` is the correct thing to do. This causes HA2 to send 1 more advert before it reverts to backup, and this will make HA1 send GARP messages (as well as another advert).

I added `vrrp_higher_prio_send_advert` for this very situation, but since it is not specified by the VRRP RFCs, and strictly is not compliant with the RFCs, it is not enabled by default.
