### ISSUE TITLE
Optimization of memcp_constant_time causes annocheck failure

### ISSUE THREAD

**Issue by rohara** [acassen/keepalived#1948]
In lib/utils.c we have memcmp_constant_time function that has reduced optimization:

```
/*                                                                                                  
 * memcmp time constant variant.                                                                    
 * Need to ensure compiler doesnt get too smart by optimizing generated asm code.                   
 */
__attribute__((optimize("O0"))) int
memcmp_constant_time(const void *s1, const void *s2, size_t n)
{
        const unsigned char *a, *b;
        unsigned char ret = 0;
        size_t i;

        for (i = 0, a = s1, b = s2; i < n; i++)
                ret |= (*a++ ^ *b++);

        return ret;
}

```

While this is fine, I am wonder if there isn't a better way to accomplish this aside from explicitly reducing optimization. The reason is that the resulting binary will always fail an annocheck [1] due to the binary not being completely optimized. This is a real issue for me as a package maintainer.

I mentioned this problem to a few colleagues and some suggested that perhaps a better alternative would be to replace
```
__attribute__((optimize("O0"))
```
 with
```
__attribute__((noinline, noclone))
```
but this is definitely something I am not familiar with. Please advise.

[1] https://developers.redhat.com/blog/2019/02/04/annocheck-examining-the-contents-of-binary-files#

**Comment by pqarmitage** [comment]
The problem here relates to Link Time Optimisation.

Without LTO, and since the calls of `memcmp_constant_time()` are from a separate compilation unit, `memcmp_constant_time()` can neither have any knowledge of the `s1` and `s2` data, nor any knowledge of how the returned value is used. Consequently memcmp_constant_time() must process all `n` bytes of `s1` and `s2`, and hence will be close to constant time (this depends on whether the xor instruction is faster if, for example, one of the operands is 0).

In fact, it seems that forcing no optimisation of the code is not necessary, since, being in a separate compilation unit, there is no possibility of short-circuiting the loop.

This is to counter code such as:
```
int
memcmp(const void *s1, const void *s2, size_t n)
{
        const unsigned char *a, *b;
        size_t i;

        for (i = 0, a = s1, b = s2, i < n; i++) {
                if (*a++ != *b++)
                        return 1;
        }

        return 0;
}
```
where the time of execution will give a hint as to how many of the leading bytes of `s1` and `s2` matched.

When using LTO, optimisation of the `memcmp_constant_time()` function can be done in the context of the calling function. The two calls of `memcmp_constant_time()` are in keepalived/vrrp/vrrp.c. Both calls of memcmp_constant_time() pass `s1` as data received from in a VRRP advert packet, and so there can be no optimisation based on knowledge of the s1 data. Likewise, `s2` is runtime variable data. This would appear to stop function clone occurring.

The other optimisation that could be done with LTO is that the optimiser could detect that the return value is only checked for non-zero values. It could therefore bail out of the loop and return once it detects that `ret` is non-zero, but to do this it would need to recognise that `ret` can only have additional bits sets as the loop proceeds, and bits can never be cleared. Even if no optimiser does this now, there is no guarantee that it wouldn't in the future.

So to ensure the constant time properties of `memcmp_constant_time()`, it is necessary to stop there being a local copy of the function generated, and the combination of noinline and noclone should be sufficient to do that (I think the noclone is unnecessary while it can only clone for constant parameters, but it can't do any harm).

I have tested with noinline with and without noclone, and using gcc `memcmp_constant_time()` remains as a separately called function, and there is no variation in the number of loop iterations or the instructions executed within each loop. Consequently I am happy to change the `memcpy_constant_time()` function attributes to remove O0 and add noinline and noclone.

**Comment by pqarmitage** [comment]
Commit 11587e1 changes the `memcmp_constant_time()` function attribute to pure, noinline, noclone.
