### ISSUE TITLE
segfault at 0 ip 00007f2cb65a617b sp 00007fff8557a990 error 4 in libc-2.17.so[7f2cb6490000+1c4000]

### ISSUE THREAD

**Issue by lzx1993111740** [acassen/keepalived#1950]
**Describe the bug**
localhost.localdomain kernel: keepalived[9524]: segfault at 0 ip 00007f2cb65a617b sp 00007fff8557a990 error 4 in libc-2.17.so[7f2cb6490000+1c4000]
localhost.localdomain Keepalived[9524]: Starting Keepalived v2.2.0 (01/09,2021)
localhost.localdomain Keepalived[9524]: Running on Linux 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 (built for Linux 3.10.0)
localhost.localdomain Keepalived[9524]: Command line: '/usr/local/keepalived/sbin/keepalived' '-D'
localhost.localdomain Keepalived[9524]: memfd_create error 21 - Is a directory
localhost.localdomain Keepalived[9524]: Opening file '/etc/keepalived/keepalived.conf'.
localhost.localdomain systemd[1]: keepalived.service: control process exited, code=killed status=11
localhost.localdomain systemd[1]: Failed to start LVS and VRRP High Availability Monitor.

**To Reproduce**
service  keepalived  start

**Expected behavior**
Hope to start successfully

**Keepalived version**

keepalived-2.2.0

Keepalived configuration
------------------------
Keepalived version       : 2.2.0
Compiler                 : gcc gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Preprocessor flags       : -D_GNU_SOURCE -I/usr/include/libnl3
Compiler flags           : -g -g -O2 -Wall -Wextra -Wunused -Wstrict-prototypes -Wbad-function-cast -Wcast-align -Wcast-qual -Wdisabled-optimization -Wdouble-promotion -Wfloat-equal -Wformat-security -Wframe-larger-than=5120 -Winit-self -Winline -Wjump-misses-init -Wlogical-op -Wmissing-declarations -Wmissing-field-initializers -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Woverlength-strings -Wpointer-arith -Wredundant-decls -Wshadow -Wstack-protector -Wstrict-overflow=4 -Wstrict-prototypes -Wsuggest-attribute=const -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wsuggest-attribute=pure -Wsync-nand -Wtrampolines -Wundef -Wuninitialized -Wunknown-pragmas -Wunsuffixed-float-constants -Wunused-macros -Wvariadic-macros -Wwrite-strings -fPIE -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -O2
Linker flags             : -pie -Wl,-z,relro -Wl,-z,now
Extra Lib                : -lm -lcrypto -lssl -lnl-3 -lnl-genl-3
Use IPVS Framework       : Yes
IPVS use libnl           : Yes
IPVS syncd attributes    : No
IPVS 64 bit stats        : No
HTTP_GET regex support   : No
fwmark socket support    : Yes
Use VRRP Framework       : Yes
Use VRRP VMAC            : Yes
Use VRRP authentication  : Yes
With ip rules/routes     : Yes
With track_process       : Yes
With linkbeat            : Yes
Use BFD Framework        : No
SNMP vrrp support        : No
SNMP checker support     : No
SNMP RFCv2 support       : No
SNMP RFCv3 support       : No
DBUS support             : No
SHA1 support             : No
Use JSON output          : No
libnl version            : 3
Use IPv4 devconf         : No
Use iptables             : No
Use nftables             : No
systemd integration      : No
init type                : systemd
Strict config checks     : No
Build genhash            : Yes
Build documentation      : No

**Comment by pqarmitage** [comment]
Can you please post the following:

1. Your keepalived configuration file
2. The options specified to configure when building keepalived
3. lib/config.h from the source tree where you built keepalived
4. The output of running configure
5. Was any corefile created by the segfault? If so can you use gdb to create a stack backtrace and post it too.

**Comment by pqarmitage** [comment]
I'm currently focusing on the log entry `memfd_create error 21 - Is a directory` and why that occurred. Even though the memfd_create syscall wasn't added until Linux v3.17, it appears that it is supported in the RHEL 7 3.10 kernel, so RedHat must have backported it.

While EISDIR makes no sense for an errno returned from memfd_create it can be returned from open(), although it shouldn't be if O_TMPFILE is set in flags. However O_TMPFILE is another feature that RedHat appears to have backported to their 3.10 kernel at some point.

Can you please provide the output of the following on the system on which you built keepalived:
1. uname -a
2. rpm -q kernel-headers
3. rpm -q glibc-headers

Your kernel is quite an old RHEL7 kernel, and so there may be some issues around the point Linux 3.10 features being backported.

**Comment by pqarmitage** [comment]
That is an extremely old kernel you are running, built 2015-03-06, and this is the basic cause of the problem.

The problem is caused by building keepalived against kernel headers for a kernel later than 3.10.0-229 and then running keepalived on 3.10.0-229 (and possibly later glibc headers on the build system than the glibc version on the runtime system).

RHEL 7 kernel 3.10.0-229 did not support `memfd_create`, nor `open( ..., O_TMPFILE, ...)`, whereas at some point in the RHEL 3.10 kernel series these two features where backported, and were certainly in RHEL 7 3.10.0-1160.

While I don't know precisely what version of the kernel headers you used for building keepalived, certainly the open O_TMPFILE flag was supported, and `memfd_create` syscall probably was not supported. The error logged was `memfd_create error 21 - Is a directory` (error 21 == EISDIR), which cannot be returned by `memfd_create()` but it can be returned by `open(name, O_TMPFILE, ...)` if name is a directory and O_TMPFILE is not supported (the error message is wrong in implying that it was memfd_create that failed, it could have been open()).

While the current version of keepalived will build and run on any kernel from Linux 3.10 (we recently dropped support from Linux v2.6.32 onward when RHEL6 went EOL), what keepalived does is it uses the features that it determines are available based on the header files against which keepalived is built. At runtime it then uses those features. If keepalived is run on an older kernel than the headers against which it was built, keepalived will attempt to use system calls that aren't supported by the kernel, and consequently it fails to work.

This problem, or at least identifying it, is made worse by the RHEL policy of backporting later kernel feature into their older kernels. For example the `memfd_create` syscall was first included in mainstream kernel 3.17. However RedHat have backported the `memfd_create` syscall into their 3.10 kernel, and it is included in some 3.10 versions, e.g. 3.10.0-1160, but not in other versions, e.g. 3.10.0-229. Normally we can say, ah - that's kernel 3.16 and so that doesn't support memfd_create, but that doesn't work with RHEL. So for example the line `Running on Linux 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 (built for Linux 3.10.0)` should tell me what is supported on the runtime kernel (it does if I look at the RHEL specifics), but the `built for Linux 3.10.0` doesn't tell me what is and is not supported by the headers keepalived was built agains, whereas with most distros it does, since they don't get backported kernel features.

The solution to your problem is to build keepalived using -devel packages whose versions match the runtime package versions on the system on which you want to run keepalived. If the -devel pacakges are older versions that the runtime versions, then that isn't a problem; what is a problem is if the -devel packages are newer versions than the runtime versions.

@lzx1993111740 I would be very interested in your feedback on this and confirmation of what kernel and glibc -devel versions where used for building keepalived and the glibc version on the runtime system.

**Comment by lzx1993111740** [comment]
Thank you. I changed keepavlied version 1.2.17 and it can start successfully

**Comment by pqarmitage** [comment]
Keepalived version 1.2.17 is extremely old and many bugs have been resolved since then. You would be far better off building a current version of keepalived, but making sure that the kernel headers used for the build are the correct ones for the target system.
