### ISSUE TITLE
when use lvs_sync_daemon feature,when master recover,how to get conn info form backup?

### ISSUE THREAD

**Issue by CallMeKangSir** [acassen/keepalived#1966]
**when use lvs_sync_daemon feature,when master recover,how to get conn info form backup?**
when use lvs_sync_daemon feature,  i configed  "lvs_sync_daemon team0 VI_1". The backup can receive conn info from mater, but when master machine reboot, master can't get the conn info.

**I want the master auto get the conn info from backup after reboot or recover**

**Keepalived version**
Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2.

**Distro (please complete the following information):**
 - Name CentOS
 - Version  CentOS Linux release 7.9.2009 (Core)
 - Architecture 3.10.0-1160.6.1.el7.x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
keepalived run on device machine.

**Configuration file:**
[admin@BJCA-device ~]$ cat /etc/keepalived/keepalived.conf
#This keepalived config file is generate by friday
#Please not modify it!!!

global_defs {
   router_id LVS_DEVEL
   lvs_sync_daemon team0 VI_1
   lvs_flush true
}

vrrp_script check_role {
    script "/etc/keepalived/bypass_ipvs.sh team0 192.168.136.246 192.168.136.114"
    interval 3
}

vrrp_instance VI_1 {
    state BACKUP
    interface team0
    virtual_router_id 2
    priority 90
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass bjca
    }

    virtual_ipaddress {
        192.168.136.246/24
    }

    track_script {
        check_role
    }
    notify_master "/etc/keepalived/notify.sh master"
    notify_backup "/etc/keepalived/notify.sh backup"
    notify_fault "/etc/keepalived/notify.sh fault"
    notify_stop "/etc/keepalived/bypass_ipvs.sh team0 192.168.136.246 192.168.136.114 stop"
}

virtual_server 192.168.136.246 8000 {
    delay_loop 3
    lb_algo wrr
    lb_kind TUN
    persistence_timeout 0
    protocol TCP

    
    real_server 192.168.136.114 8000 {
        weight 1
        TCP_CHECK {
            connect_timeout 1
            nb_get_retry 1
            delay_before_retry 1
            connect_port 8000
            bindto 192.168.136.114
        }
    }
    
}

[admin@BJCA-device ~]$ cat /etc/keepalived/notify.sh 
#!/bin/bash
#
logs="/var/log/keepaliveNotify.log"
case $1 in
master)
    echo "`date`==master" >>$logs
    ;;
backup)
    echo "`date`==backup" >>$logs
    ;;
fault)
    systemctl restart keepalived
    echo "`date`==fault" >>$logs
    ;;
*)
    echo "`date`==Usage:$(basename $0) {master|backup|fault}"
    echo "`date`==$1" >>$logs
    exit 1
    ;;
esac

**Comment by pqarmitage** [comment]
Although I don't think this fully addresses your issue, commit ef3bbd6 allows both the master and backup IPVS sync daemons to run simultaneously; this is necessary for syncing IPVS connections when two ore more systems can both have active IPVS connections. This is achieved with keepalived if there are master VRRP instances on two or more systems and there are virtual servers configured using VIPs from the different VRRP instances. However, if you were to use that commit you would need to upgrade keepalived to a much more recent version than v1.3.5.

My understanding of your problem is that after the system you want to be the VRRP master is rebooted, the IPVS connection table is not synchronised after the reboot, and that when the rebooted system takes over asVRRP  master, the IPVS connection table on that system does not have the entries that were on the previous master, now backup, system.

One option is you could configure `nopreempt` on the VRRP instances. That would mean that the system that is normally the VRRP backup would remain VRRP master until keepalived stops running on that system. This would stop the usual master taking over as VRRP master after a reboot, and so you would not lose the IPVS connection information.

The remaining options are not supported in v1.3.5, and to use them you would need to upgrade to a recent version of keepalived.

The IPVS sync daemon does not appear to periodically sends updates including information about previously opened connections, and so the sync entries on the IPVS backup sync daemon only remain for the times given in the output of `ipvsadm -L --timeout`, which default to 900 seconds (TCP), 120 seconds (TCPFIN) and 300 seconds (UDP). If you are using the default timeouts, then waiting for 15 minutes (900 seconds) after starting the backup sync daemon, then the backup will have all the entries that it would have had had the system not been rebooted.

With the above in mind, you could configure on any relevant VRRP instance `preempt_delay 900` which means that the higher priority VRRP instance will delay 900 seconds before taking over as master, thereby allowing the sync'd IPVS connection data to be as up-to-date as possible.

Another possibility is to configure `global_defs` `vrrp_startup_delay 900` which will delay the VRRP code from starting up for 900 seconds, again allowing time for the IPVS connection table to be brought up-to-date.

Something I will look at is whether we can add functionality to keepalived to read the connection data and multicast it itself to bring any IPVS sync daemon backups up-to-date. This will take some time to implement however.

**Comment by CallMeKangSir** [comment]
@pqarmitage thanks fro your answer, i will has a test on the recent version, i think the remain option that you commited can resolve my pronlem.
