### ISSUE TITLE
vrrp dns dependency

### ISSUE THREAD

**Issue by tbsky** [acassen/keepalived#199]
hi:
    I am testing keepalived vrrp on openwrt box. I notice sometimes vrrp will take about 3-5 minutes to startup. after debugging, I found when keepalived starts, it will do a name resolve of hostname. if the name resolve system is trying hard to do the work and can not give out result, then keepalived will just wait there for minutes,until the resolve failed.
   
  if I put  my hostname to /etc/hosts then the situation is solved. but I am curious why keepalived try to resolve the hostname when start, is it necessary?

**Comment by pqarmitage** [comment]
keepalived does a name resolve of hostname in get_local_name(). It gets the local name from the nodename returned by uname(). In case this name is not a FQDN, or in case it is an alias, it calls getaddrinfo() to resolve this into a non-alias FQDN for the host.

keepalived called get_local_name() several times at startup if certain defaults are being used. For each of the vrrp process and checker process it would call get_local_name() once to get the router_id, and once to set the default email_from name for sending SMTP messages. It would also call get_local_name() every time it sent an email, to get the name to use in the HELO message.

Since this clearly calling get_local_name() more often than necessary, and so commit 9d028ac reduces the total number of calls to one per thread (saving the name for subsequent use in HELO messages). The commit also introduces an addition global configuration parameter, smtp_helo_name, and so if that, router_id and notification_email_from are all set in the global configuration, and if an smtp server is specified by IP address rather than host name, then keepalived shouldn't make and DNS queries at start up.
