### ISSUE TITLE
VRRPv3 IPv6 use_vmac: send advert error 22 (Invalid argument)

### ISSUE THREAD

**Issue by louis-oui** [acassen/keepalived#2026]
Same issue as https://github.com/acassen/keepalived/issues/1865 on last commit a7c928b2.
Same procedure to reproduce the issue. You can even reproduce the issue with member 1 only.

Same logs:
`Oct 29 11:33:10 ubuntu Keepalived_vrrp[1663]: (vrrp): send advert error 22 (Invalid argument)
`

**Keepalived version**
```
Keepalived v2.2.4 (10/27,2021), git commit v2.2.4-151-ga7c928b2

Copyright(C) 2001-2021 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 4.15.18
Running on Linux 4.15.0-159-generic #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021
Distro: Ubuntu 18.04 LTS

configure options: CFLAGS=-g -O0 --prefix=/usr --sysconfdir=/etc --with-extra-cflags=-I/usr/include/libnl3 --with-extra-ldflags= --disable-lvs --with-init=systemd --host=x86_64-linux-gnu hou

Config options:  VRRP VRRP_AUTH VRRP_VMAC OLD_CHKSUM_COMPAT INIT=systemd SYSTEMD_NOTIFY

System options:  VSYSLOG MEMFD_CREATE IPV4_DEVCONF RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SK

```

**Comment by pqarmitage** [comment]
The reason for the error 22 is as follows:

If the netlink message both sets addrgenmode to none and sets the interface up, the interface is set up before addrgenmode is set to none, and so an eui64 address is configured on the interface before addrgenmode is set to none. When keepalived is reloaded turning off `vmac_xmit_base`, keepalived is aware that there is a link local address on the interface, and does not attempt to add one itself (keepalived uses the link local address of the parent interface). However, when it sends the adverts, it specifies as the source IPv6 address the address that it should have added, and since the address does not exist on the interface the socket is bound to, sendmsg() returns error 22.

If you down and up the parent interface, then you stop getting the error 22s because keepalived sorts out the link local addresses on the macvlan interface.

Why I wasn't getting these errors on my development system I don't know.

**Comment by louis-oui** [comment]
@pqarmitage Thank you for the merge and the explainations
