### ISSUE TITLE
keepalived_modprobe

### ISSUE THREAD

**Issue by levin1** [acassen/keepalived#2040]
```
	if (!WIFEXITED(status) || WEXITSTATUS(status)) {
		return true;
	}

	return false;
```
it should be `WIFEXITED(status) && !WEXITSTATUS(status)`.

> WIFEXITED(status)
> returns true if the child terminated normally, that is, by calling exit(3) or _exit(2), or by returning from main().
> WEXITSTATUS(status)
> returns the exit status of the child. This consists of the least significant 8 bits of the status argument that the child specified in a call to exit(3) or _exit(2) or as the argument for a return statement in main(). This macro should only be employed if WIFEXITED returned true.

**Comment by pqarmitage** [comment]
keepalived_modprobe() returns true on error, false on success, in common with many functions which return 0 on success and non-zero on error. I therefore think the existing code is correct (I have just tested starting keepalived without the ip_vs module loaded and keepalived loaded the module and did not log an error).

You state `This macro [WEXITSTATUS] should only be employed if WIFEXITED returned true.` Indeed that is how it is being used since `WEXITSTATUS(status)` is only evaluated if `!WIFEXITED(status)` if false, i.e. `WIFEXITED(status)` is true.

The whole of the code quoted above could simply be replaced with:
   `return !WIFEXITED(status) || WEXITSTATUS(status);`
or even
   `return !(WIFEXITED(status) && !WEXITSTATUS(status));`
I would probably use the first of the two options nowadays rather than how the code is currently written; I certainly would not use the second of the above alternatives since I think it is harder to read (too many `!`s).

Many thanks for raising this issue; it is always helpful to have second opinions on the code.

**Comment by levin1** [comment]
Usually boolean functions return true on success, and false otherwise, and interger functions return 0 on success and negative otherwise, you use strange style, but ok.

**Comment by levin1** [comment]
> I have just tested starting keepalived without the ip_vs module loaded and keepalived loaded the module and did not log an error

What about xt_set? I get global using_ipset flag dropped because of failure to load xt_set, but it gets loaded.

**Comment by pqarmitage** [comment]
@levin1 I am not sure I agree that usually boolean functions return true on success and false otherwise. For example `getsockopt()` is a boolean function (it can return one of two values), and it returns 0 (equivalent to false) for success, but I suppose some may consider this a matter of interpretation.

Re global_data->using_ipsets being cleared, can you please provide:
- the output of `keepalived -v`
- a copy of your configuration
- the output of `iptables -V`
and I will look into that.

**Comment by levin1** [comment]
> For example getsockopt() is a boolean function

no, it declared as `int getsockopt`, so it is integer function, and as I wrote it returns negative on error and zero for success.

**Comment by levin1** [comment]
My modprobe doesn't support -s option, that's the problem. But if I prevent global_data->using_ipsets being cleared, xt_set gets loaded. Well, it's not keepalived issue.

**Comment by pqarmitage** [comment]
What is the source of your modprobe, and what distro are you running on? The modprobes I have are from the kmod package from https://git.kernel.org/pub/scm/utils/kernel/kmod/kmod.git .

The man page for modprobe states:
```
-s, --syslog
   This option causes any error messages to go through the syslog mechanism (as LOG_DAEMON with level LOG_NOTICE) rather than to standard error. This is also
   automatically enabled when stderr is unavailable.
```
so I will test if the `-s` option can be removed and modprobe still logs to syslog.

**Comment by pqarmitage** [comment]
Does your system have `/proc/sys/kernel/modprobe` and if so, what are its contents? 

@levin1On my systems, `cat /proc/sys/kernel/modprobe` outputs
/usr/sbin/modprobe
   or
/sbin/modprobe

This means that modprobe is invoked without the `-s` option, so it should be safe to remove the `-s` option.

**Comment by pqarmitage** [comment]
Commit 8b2226a makes keepalived try calling modprobe without the '-s' option if it fails with the '-s' option (it also makes `keepalived_modprobe()` return true for success and false for failure).

Commit fc10deb makes keepalived use libkmod for installing modules if it is available. This is faster and more secure than executing another program.
