### ISSUE TITLE
A possible race issue on the dbus_startup_completed

### ISSUE THREAD

**Issue by ryancaicse** [acassen/keepalived#2043]
Dear maintainers, for this commit #2036 , I have a suggestion that the lock `cond_mutex` should guard `dbus_startup_completed` to make the write operation atomic. 

https://github.com/acassen/keepalived/blob/7245f452fe33de7a026f92279fc9499529c3ffeb/keepalived/vrrp/vrrp_dbus.c#L643-L655

https://github.com/acassen/keepalived/blob/7245f452fe33de7a026f92279fc9499529c3ffeb/keepalived/vrrp/vrrp_dbus.c#L999-L1006

**Comment by pqarmitage** [comment]
@ryancaicse Many thanks for reporting this.

I'm not sure that the setting of `dbus_startup_completed` needs to be protected by the mutex, since `dbus_startup_completed` is set false before the dbus thread is started. However, `pthread_cond_signal()` must be called while the main thread is in `pthread_cond_wait()` and since `pthread_cond_wait()` can return following spurious wakeups, `pthread_cond_signal()` must be called while the thread has the `cond_mutex`.

Notwithstanding the above, I have therefore moved both setting `dbus_startup_completed` to true and the `pthread_cond_signal()` call to be done while the `cond_mutex` is held (see commit 99cdee6).
