### ISSUE TITLE
Transitioning to backup state if software failure occurs on server

### ISSUE THREAD

**Issue by MuhammadMunir12** [acassen/keepalived#2097]
**Describe the bug**
I have a question regarding the transitioning to backup state if the master server's OS get crashed, RAM usage becomes high, CPU failure occurs or any similar anomaly occurs that is not in scope for keepalived, how can we trigger keepalived to move to backup server based on above mentioned failures. 
Is this even possible to extend keepalived scope or link it with some script?? 

**Expected behavior**
Based on failure of given components on master server, backup server should take over the master. 

**Keepalived version**
```
Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2

```

**Distro (please complete the following information):**
 - Name: RHEL 
 - Version: 7.9
 - Architecture:  x86_64

Any help/guidance would be really appreciated.

**Comment by dfrEak** [comment]
I think you can use the vrrp_script to check the failure condition every n mins
and if it is failure it will go to FAULT state and the BACKUP will be MASTER

I found this example when he tried to check whether he can ping to google dns or not
https://www.redhat.com/sysadmin/advanced-keepalived

**Comment by pqarmitage** [comment]
@MuhammadMunir12 Yes, @dfrEak is correct that using a vrrp_script is the (traditional) way to do it.

For the situations you describe:
1. **Master server's OS get crashed**
If the OS (Linux) crashes on the master server, all processes that were on the master server will cease to exist, and so the master server will stop sending VRRP adverts. Consequently a backup server will take over as master without any further intervention.

2. **RAM usage becomes high**
This is detectable from a script/process, provided the script/process has not, itself, been swapped out. If the process sets itself to be not swappable, then you would avoid the problem of the process being swapped out; however all libraries that it uses would also need to be non-swappable.

3. **CPU failure occurs**
If your system has more that 1 CPU then this should be detectable; if it doesn't have more than 1 CPU then 1. above would apply.

4. **Any similar anomaly occurs**
This depends on what you can detect in a script/process.

Rather than using a vrrp_script, which has to be run periodically, you could run an external script/process and use `track_file` in your keepalived configuration. Using track_file is more efficient than using a vrrp_script, and keepalived will react as soon as the track_file is written to (by default writing a non-zero value to the track file will make the monitoring vrrp instance(s) transition to fault state). The external script/process could be initiated from a `startup_script` if the script then forks/execs another process to periodically make the necessary checks of the system, writing to the track_file once it detects that the vrrp_instance(s) should transition to fault state.

I am fairly certain, however, that keepalived v1.3.5 doesn't support `track_file` or `startup_script`; you would need to upgrade keepalived to a more recent version, which you ought to do anyway since v1.3.5 is extremely old.
