### ISSUE TITLE
Keepalived: Transitioning to backup node not happening when check script on master server finds service is down for an applicaiton

### ISSUE THREAD

**Issue by MuhammadMunir12** [acassen/keepalived#2103]
**Describe the bug**
I am trying to configure keepalived in such a way that if any application or service running on master node fails, keepalived should consider it as fault and backup node should act as master and take over the floating IP from master node.

I have written a script to check if service X on master server goes down, then it should transition to backup node.

**To Reproduce**
**My keepalived conf on master node:**
```
global_defs {
enable_script_security
}
vrrp_script keepalived_check {
script "/root/new/check.sh"
interval 1
timeout 1
rise 2
fall 2
weight 0 reverse
}
vrrp_instance V1_11 {
state MASTER
interface ens3
virtual_router_id 51
priority 101
advert_int 1
unicast_src_ip 192.168.10.129
unicast_peer {
    192.168.10.130
}
authentication {
    auth_type PASS
    auth_pass 1122
}
virtual_ipaddress {
    192.168.10.231/24
}
track_script {
    keepalived_check
}
}
```

**The Script that checks the service status:**

```
#!/bin/bash
var="$(systemctl is-active myservice.service)"

if [ $var == "active" ]
then
    echo 0
else
    echo 5
fi
```
I manually stopped the "myservice" using
```
systemctl stop myservice.service
```

**Expected behavior**
Keepalived transition to backup server. 

**Keepalived version**
```
version 2.2.7
```

**Distro (please complete the following information):**
 - Name: RHEL
 - Version: 7.9
 - Architecture: x86_64

The output for script is "5" as expected. But with above mentioned configurations, master node remains as primary node and it doesn't shift ownership to backup node. Is there any particular config that I have missed then kindly help me find that?

**Comment by pqarmitage** [comment]
keepalived does not read stdout from the check_scripts that it executes; it reads the exit status. I would change your script to:
```
#!/bin/bash
var="$(systemctl is-active myservice.service)"

if [ $var == "active" ]
then
    exit 0
else
    exit 5
fi
```
or
```
#!/bin/bash
var="$(systemctl is-active myservice.service)"

[[ $var == "active" ]] && exit 0 || exit 5
```
or even
```
#!/bin/bash
[[ $(systemctl is-active myservice.service) == "active" ]] && exit 0 || exit 5
```

The script is exiting success (exit code 0) if the service is running and failure (exit code != 0) if the service is not running. This is the normal case for track_scripts, and so you do not want `reverse` for the `weight`. As you have configured the vrrp_script block, when your `/root/new/check.sh` is modified to use `exit` rather than `echo`, if the service is running, the vrrp instance will be down, and vice versa. I suggest you simply delete the `weight 0` line, since (without the `reverse`) that is the default.

keepalived actually has a `track_process` feature which is designed for what you are doing. You can replace the `track_script` configuration with:
```
vrrp_track_process MY_SERVICE {
    process my_service_process_name
    terminate_delay 1
}
```
and in the vrrp_block, add `track_process MY_SERVICE`. There are other configuration options for `vrrp_track_process` - see keepalived.conf(5) man page for details.

Another option you might like to consider is using weights. If the vrrp `priority` on your backup server is 90, then specify `weight -15`. This means that in the event that the service is down, the priority on the master instance will reduce to 86 (101 - 15), and since this will lower than the priority on the backup server, the backup will take over as master. If the service then fails on the backup, its priority will reduce to 75, and the master server will take over as master again. This means that you will always have a master keepalived instance, but the backup will take over as master if the service stops on the master but is running on the backup.
