### ISSUE TITLE
configure with --prefix option does not apply to systemd service file

### ISSUE THREAD

**Issue by rohara** [acassen/keepalived#2113]
**Describe the bug**
When the configure script is run with the --prefix=PATH option, the resulting install ignores PREFIX for the systemd service file and installs (or attempts to install) the service file to '/usr/lib/systemd/system/keepalived.service'. In other words, regardless of PREFIX, the systemd service file is always installed to the same location.

**To Reproduce**
Run the configure script with --prefix set. I like to set this to '/tmp/root/' but anywhere should work.
```
./configure --prefix=/tmp/root/
make
make install
```
If you perform the above steps as root user, there will not be an error since root can install anywhere. Everything will be installed to appropriate directories with PREFIX except for the systemd service file, which will go to the normal location. However, if you run this as a non-root user (as I am in this example), that user most likely can't write to the systemd service directory and the install will fail. Here is a snippet of output when a non-root user attempts to install to a PREFIX location that said user does have write privileges to, but does not have privileges to "/usr/lib/systemd/system/".
```
make[4]: Entering directory '/home/rohara/tmp/keepalived-2.2.7/keepalived'
/usr/bin/mkdir -p //home/rohara/tmp/root/bin
make[4]: Leaving directory '/home/rohara/tmp/keepalived-2.2.7/keepalived'
 /usr/bin/mkdir -p '/usr/lib/systemd/system'
 /usr/bin/install -c -m 644 keepalived.service '/usr/lib/systemd/system'
/usr/bin/install: cannot create regular file '/usr/lib/systemd/system/keepalived.service': Permission denied
make[3]: *** [Makefile:536: install-systemdsystemunitDATA] Error 1
make[3]: Leaving directory '/home/rohara/tmp/keepalived-2.2.7/keepalived'
make[2]: *** [Makefile:727: install-am] Error 2
make[2]: Leaving directory '/home/rohara/tmp/keepalived-2.2.7/keepalived'
make[1]: *** [Makefile:563: install-recursive] Error 1
make[1]: Leaving directory '/home/rohara/tmp/keepalived-2.2.7/keepalived'
make: *** [Makefile:447: install-recursive] Error 1
```

As you can see, the systemd service file installation ignore PREFIX.

**Expected behavior**
I would expect that the systemd service file would be installed to "/home/rohara/tmp/root/usr/lib/systemd/service/keepalived.service".

**Keepalived version**
```
Keepalived v2.2.7 (01/16,2022)

Copyright(C) 2001-2022 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.15.4
Running on Linux 5.15.4-201.fc35.x86_64 #1 SMP Tue Nov 23 18:54:50 UTC 2021
Distro: Fedora Linux 35 (Thirty Five)

configure options: --enable-debug --enable-profile --enable-snmp --enable-snmp-rfc --enable-nftables --disable-iptables --enable-sha1 --with-default-config-file=./doc/samples/keepalived.conf.sample --prefix=/home/rohara/tmp/root/

Config options:  NFTABLES LVS VRRP VRRP_AUTH VRRP_VMAC OLD_CHKSUM_COMPAT SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 TIMER_CHECK NETLINK_TIMERS SMTP_ALERT_DEBUG EPOLL_DEBUG EPOLL_THREAD_DUMP TSM_DEBUG VRRP_FD_DEBUG NETWORK_TIMESTAMP ASSERT PROFILING FILE_LOGGING LOG_FILE_APPEND RECVMSG_DEBUG EINTR_DEBUG SCRIPT_DEBUG TRACK_PROCESS_DEBUG PARSER_DEBUG CHECKSUM_DEBUG CHECKER_DEBUG SMTP_CONNECT_DEBUG DUMP_KEYWORDS INIT=systemd SYSTEMD_NOTIFY DEFAULT_CONFIG_FILE=$(sysconfdir)/keepalived/./doc/samples/keepalived.conf.sample

System options:  VSYSLOG MEMFD_CREATE IPV6_MULTICAST_ALL IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE VRRP_IPVLAN IFLA_LINK_NETNSID GLOB_BRACE GLOB_ALTDIRFUNC INET6_ADDR_GEN_MODE VRF SO_MARK
```

**Additional context**
Again, there will be no error reported if this is done as root user. Running the configure, make and make install as non-root really uncovers the problem. Either way, the installation of the systemd service file should be relative to PREFIX.

**Comment by pqarmitage** [comment]
I think the issue here is what do we want to happen by default. What I believe is certainly wanted is that if I execute `./configure; make; sudo make install`, then I should get an installation that works. Since the default value of prefix is `/usr/local`, and I want/need the systemd service to be installed in `/usr/lib/systemd/system` (or more strictly the output of `pkg-config  --variable=systemdsystemunitdir systemd`), then installing the systemd config files relative to PREFIX would be wrong. I think if you want to override the location of the systemd config files, then the `--with-systemdsystemunitdir` configure option should be used.

I have found https://stackoverflow.com/questions/58017453/install-systemd-service-using-autotools which is quite interesting reading. In particular, jww writes
>The problem is due to limitations in the Coding Standards and Autotools. It is not equipped to handle both System and User Installed software.

However, that article also says:
> At the build installation time (e.g. make install during package build), packages are recommended to install their systemd unit files in the directory returned by pkg-config systemd --variable=systemdsystemunitdir (for system services) ...

and this is what keepalived does.

The above is, of course, looking at it from a user's perspective rather than a packagers perspective.

If doing a build for packaging, I think the following is the correct approach: `./configure --prefix= ; make; make DESTDIR=/tmp/root install`. The `--prefix` specified to configure sets up how to build the package (and for example in this case the default config file location will be set to `/etc/keepalived/keepalived.conf` rather than `/usr/local/etc/keepalived/keepalived.conf`, i.e. relative to whatever PREFIX is, and the DESTDIR option to `make install` handles the staged install.

I note that RedHat uses `--prefix=/usr` for building RPMs, but there is then some _trickery_ in /usr/share/config.site to adjust `sysconfdir`, `sharedstatedir` and `localstatedir`. I presume that this is so that executables are installed into `/usr/bin`/`usr/sbin` rather than `/bin` and `/sbin`.

So far as I can see I think keepalived is doing the right thing here, but I would appreciate any further comments if you believe it is not correct.

**Comment by pqarmitage** [comment]
Closing due to no response for over 6 weeks.
