### ISSUE TITLE
Add a notify when leaving the MASTER_RX_LOWER_PRI pseudo-state 

### ISSUE THREAD

**Issue by louis-6wind** [acassen/keepalived#2122]
**Is your feature request to resolve a problem or provide enhanced functionality? Please describe.**
We have a daemon that is running on two nodes. Only one instance must run at a time. We use VRRP to control and notify-fifo to control whether the daemon should deal with the traffic: basically when the state is master.

We face sometimes a problematic double master situation caused by a unidirectional link: the traffic is only operational from the lower priority member to the higher priority one. The higher priority one notifies MASTER_RX_LOWER_PRI to FIFO. Since the low priority member cannot know that is not the legitimate master, we would prefer to consider MASTER_RX_LOWER_PRI as a backup state. However, there is no notify to say that we are leaving the MASTER_RX_LOWER_PRI pseudo-state. The VRRP member would not leave the backup until a double transition happens.

Note that the topology cannot avoid temporal unidirectional link situation. All the VRRP packets are carried over a single VxLAN tunnel. When routing protocols converge, there is a temporal unidirectional link situation.

**Describe the solution you would like**
Add a notify when leaving the MASTER_RX_LOWER_PRI pseudo-state.

**Describe alternatives you have considered**

-

**Would the feature request be of benefit only to you, or is it more generally applicable?**

-
**Keepalived version**

-

**Additional context**

-

**Comment by pqarmitage** [comment]
@louis-6wind I understand your issue, but I think there is a problem implementing your request. MASTER_RX_LOWER_PRI is not a state but an event. The event is logged, and also the higher priority master immediately sends another advert, to try and make the other (lower priority) VRRP instance aware that there is a higher priority master.

Whilst we could output a MASTER_RX_LOWER_PRI message to the notify FIFO whenever a lower priority advert is received, you would need to run a timer whose expiry would indicate that the VRRP instance had stopped receiving lower priority adverts since, as indicated above, MASTER_RX_LOWER_PRI is not a state but an event caused by receiving the advert.

Would you be happy running your own timer so that you can determine when keepalived stops receiving lower priority adverts, otherwise I don't see that implementing this request would have any benefit.

**Comment by louis-6wind** [comment]
Thank you for your response @pqarmitage. We have finally decided to keep MASTER_RX_LOWER_PRI as master and to modify the topology to avoid double master.
