### ISSUE TITLE
possible null dereference in parser

### ISSUE THREAD

**Issue by zouyonghao** [acassen/keepalived#2131]
**Describe the bug**
In "read_line" function of parser.c, the "PMALLOC" and "STRDUP" may fail and return null, but we do not consider that in current code, which may cause null pointer dereference.

https://github.com/acassen/keepalived/blob/e7c9e7f16535a31ccf61154011519ff9c97d52a3/lib/parser.c#L2627-L2634

**Expected behavior**
Add error handling code.

**Keepalived version**
```
2.2.7
```

**Comment by pqarmitage** [comment]
The are many places in keepalived where the return value of malloc() is not checked, not only the example above and `vector_alloc_slot()` then you reported in issue #2128.

I am going to close this issue now, since **if** the discussions in issue #2128 relating to whether the return code of malloc() needs to be checked determine that it does, then the check will need to be made for all malloc()s, and so the changes can be handled via that issue. Fortunately, we almost always use definitions for MALLOC(), REALLOC(), STRDUP() etc, and so the check (and termination of keepalived) could be handled just in those definitions, especially if it also produced a stack trace. However let's wait an see whether it is felt to be worthwhile adding the overhead of a check for each malloc() call.
