### ISSUE TITLE
Can MASTER goes FAULT only when all the tracked interfaces goes down ?

### ISSUE THREAD

**Issue by woosonchan** [acassen/keepalived#2156]
I tested keepalived on my machines.

I found my MASTER node goes to FAULT status and the BACKUP node transitioned to MASTER role when **one of** the tracked interface went down.

But, I want my MASTER goes FAULT only when **all the tracked interfaces goes down**.

Can I achieve this goal ?

**Comment by pqarmitage** [comment]
There is no direct facility in keepalived to only go to fault state only when all tracked interfaces are down.

It would be interesting to know your scenario for wanting this functionality.

I can think of one or two possible solutions:

1. Have a track script which only returns failure when all the interfaces are down.
2. Use weights with track_interface so that the priority of the VRRP instance drops below the priority of the backup instance only when all interfaces are down.
3. Have a process that monitors the state of the interfaces that has a forked child unless all the interfaces are down. If you specify a quorum of 2 for the vrrp_track_process, then the instance will go down if the child is killed.
