### ISSUE TITLE
set a long timeout

### ISSUE THREAD

**Issue by cathaysia** [acassen/keepalived#2179]
Hello, I am running keepalived on a network with high load and high packet loss rate, I now receive a vrrp packet in an average of 4-5 seconds, which causes my backup machine to keep preempting the master. Can I extend the detection event of the backup machine? I want to extend it to 20s.

Any changes from the config file or code are fine, I'm using a custom version of keepalived now, here's the config file I'm using:

```
! Configuration File for keepalived

global_defs {
   router_id LVS_DEVEL
   vrrp_skip_check_adv_addr
   vrrp_strict
   vrrp_garp_interval 0.01
   vrrp_gna_interval 0.01
   preempt_delay 20
}


vrrp_instance VI_1 {
    state BACKUP
    interface ens3
    virtual_router_id 51
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        192.168.200.13
    }
}
```

master and salve use the same configuration file.

**Comment by pqarmitage** [comment]
@cathaysia You say that master and slave use the same configuration file. They should at least differ by having different priorities for the vrrp isntances.

You have closed this without saying why, so I will respond to your original post in case anyone else is interested.

The VRRP RFCs specify that the timeout for transitioning to master is `3 * advert interval + skew time` where skew time is a fraction of advert interval (VRRPv3) or 1 second (VRRP v2), and the higher the priority the lower the skew time. As a consequence of the RFCs being so specific about `3 *` it is hardcoded into keepalived.

It was 1 year less 3 days ago that I added the keyword `down_timer_adverts` for situations like this with the following commit:
```
commit 33385c6aa0563c482b99719f129806d3ce3b90d5
Author: Quentin Armitage <quentin@armitage.org.uk>
Date:   Fri Aug 13 18:56:18 2021 +0100

    vrrp: Add down_timer_adverts configuration option
    
    The VRRP RFCs state that the master down timer is 3 advert intervals
    plus a skew timer. There are some users who, due to network problems,
    would like to have more advert intervals, and there are others who
    would like to have fewer advert intervals in order to achieve a
    faster take over time by a backup instance.
    
    Using this feature is absolutely non-conformant with the RFCs, but
    it does add some flexibility for certain users.
```

This is probably what you want to use, although I am not sure that, as you say `with a high packet loss rate` you will be able to get keepalived to act reliably.

An alternative (and conformant) approach to increasing the takeover time to about 20s would be to set the advert interval to be about 6 or 7 seconds; however 3 missed adverts will still cause the backup to take over as master.

Probably the best solution is to keep the advert interval low (I see you are using VRRPv2 so it cannot be less than 1 second), and set the `down_timer_adverts` high. If you move to VRRPv3 (you will have to stop using authentication since that was dropped from VRRPv3 since it was not seen as being of any benefit) you will be able to specify the advert interval in 0.01s units down to 0.01s. You could then have a high down_timer_adverts and a low advert interval and maintain a relatively fast take over in the event of a failure of the master.

By the way, how do you manage to operate with a high packet loss? That in itself must be having bad effects on throughput and also itself be causing an increase in the network load.

**Comment by cathaysia** [comment]
I'm so sorry I closed  this whiout any replay. This is because I found a [post](https://blog.csdn.net/hitcompass1/article/details/104054934) that might be able to solve this problem, I thought it was a duplicate post.

Yes, the second is what I want, because advert_int is useless in my case.  Can I directly set vrrp->ms_down_timer to 20 s to achieve this? Because this simpler for me.

Yes, I'm on a network with high packet loss and loads at times, but I'm more inclined to be an OS and hardware issue at this point, but I don't know anything about that, so changing the software is the easier way . Although enabling keepalived will cause high network load, it is fine as long as the software can run normally, because this is not a performance-sensitive scenario

**Comment by cathaysia** [comment]
> You say that master and slave use the same configuration file. They should at least differ by having different priorities for the vrrp isntances.

In my system, keepalived is mainly used as the message component of the master-standby switch. I use other methods to let the backup machine exit so as not to affect the function of the master machine, so it is feasible for me to use the same configuration file.

**Comment by pqarmitage** [comment]
There are a number of potential issues and resolutions, depending on the cause of the problem.

1. _An OS problem, e.g. CPU load is high_
      You can make keepalived run with a high scheduling priority, and also realtime scheduling, which is even better. This can mean that keepalived has priority over (almost) all other processes.

2. _High packet loss_
      The only way around this really is to reduce the advert interval and allow more advert intervals before a backup times out.

I don't think changing the down timer to 20s on its own is the best way resolve the problem. The issue is that due to the high packet loss the likelihood of not receiving 3 successive adverts is relatively high. You therefore need to ensure that significantly more than 3 adverts are sent in the timeframe before the backup times out. If you have an advert interval of 1 second, and set `down_timer_adverts` to 20, then the backup would have to miss all 20 adverts in that interval before it becomes master (and you won't have to alter the code to do this).

If you change to using VRRPv3, you could have a 1/10th second advert interval with `down_timer_adverts` set to 30, and then the backup would take over after 3 seconds (as I presume it does now), but 30 consecutive adverts would have to be missed by the backup.

If you have periods where effectively no adverts can get through for say 10 seconds (and there are other users who have experienced this), then keeping the advert interval at 1 and setting `down_timer_adverts` to 20 is probably the right sort of way to go.

**Comment by cathaysia** [comment]
I wrote a configuration file like this:

```
! Configuration File for keepalived

global_defs {
   router_id LVS_DEVEL
   vrrp_skip_check_adv_addr
   vrrp_strict
   vrrp_garp_interval 0.01
   vrrp_gna_interval 0.01
   preempt_delay 20
}


vrrp_instance VI_1 {
    state BACKUP
    interface ens3
    virtual_router_id 51
    priority 100
    advert_int 1
    vrrp_version 3
    down_timer_adverts 100000
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        192.168.200.13
    }
}
```

Then test it on a network with 3s latency and 80% packet loss. But the backup machine quickly becomes the master:

https://user-images.githubusercontent.com/42114817/184055481-54e41e01-c910-412f-b9ef-4baa0966b593.mp4

**Comment by cathaysia** [comment]
Thanks, I solved this problem by this configuration:

```
! Configuration File for keepalived

global_defs {{
   router_id LVS_DEVEL
   vrrp_skip_check_adv_addr
   vrrp_garp_interval 0.1
   vrrp_gna_interval 0.1
   vrrp_version 3
   vrrp_down_timer_adverts 20
   max_auto_priority 99
}}

vrrp_instance VI_1 {{
    state BACKUP
    interface ens3
    virtual_router_id 51
    priority 100
    advert_int 1
    virtual_ipaddress {{
        192.168.200.13
    }
}
```

Now, the backup machine will not become the master until 20 seconds after the master dies.

Thanks for your help. :)

**Comment by pqarmitage** [comment]
@cathaysia I note that the above config has some double '{'s. i.e. '{{'. This is certainly not intended to be supported and if it works now it may not in a future version, so it would be worth correcting that and changing all '{{'s and '}}'s to '{' and '}' respectively.

**Comment by cathaysia** [comment]
Sorry, the keepalived configuration file in my software is dynamically generated, the purpose of double curly braces is to escape. I deleted them below, but forgot to delete the above

The truly configuration for keepalived is:

```
! Configuration File for keepalived

global_defs {
   router_id LVS_DEVEL
   vrrp_skip_check_adv_addr
   vrrp_garp_interval 0.1
   vrrp_gna_interval 0.1
   vrrp_version 3
   vrrp_down_timer_adverts 20
   max_auto_priority 99
}

vrrp_instance VI_1 {
    state BACKUP
    interface ens3
    virtual_router_id 51
    priority 100
    advert_int 1
    virtual_ipaddress {
        192.168.200.13
    }
}
```
