### ISSUE TITLE
in my eviroment,Keepalived starts OK on both boxes but goes master on both boxes.the following is syslog.

### ISSUE THREAD

**Issue by s09816** [acassen/keepalived#218]
Jan  7 22:42:47 cvknode234 Keepalived_vrrp[24226]: Kernel is reporting: interface vswitch0 DOWN
Jan  7 22:42:47 cvknode234 Keepalived_vrrp[24226]: VRRP_Instance(VI_1) Entering FAULT STATE
Jan  7 22:42:47 cvknode234 Keepalived_vrrp[24226]: Netlink: error: Cannot assign requested address, type=(21), seq=1452175349, pid=0
Jan  7 22:42:47 cvknode234 Keepalived_vrrp[24226]: VRRP_Instance(VI_1) Now in FAULT state
Jan  7 22:42:48 cvknode234 ntpd[23317]: Deleting interface #8 vswitch0, 192.168.33.10#123, interface stats: received=0, sent=0, dropped=0, active_time=2380 secs
Jan  7 22:42:48 cvknode234 ntpd[23317]: Deleting interface #7 vswitch0, fe80::20c:29ff:fed7:74b2#123, interface stats: received=0, sent=0, dropped=0, active_time=2556 secs
Jan  7 22:42:48 cvknode234 ntpd[23317]: Deleting interface #3 vswitch0, 192.168.33.234#123, interface stats: received=0, sent=13

**Comment by s09816** [comment]
Jan 7 22:42:47 cvknode234 Keepalived_vrrp[24226]: Netlink: error: Cannot assign requested address, type=(21), seq=1452175349, pid=0

this log is the error information.

**Comment by pqarmitage** [comment]
Unfortunately the log entries you have provided do not show any VRRP instances becoming master. It appears that the vswitch0 interface went down  causing VRRP instance VI_1 to go to fault state, which keepalived reports, and also ntpd reports that it is dropping using that interface.

Are you able to provide the log files showing the two instances both becoming master, and possibly your also your config files? Do they always both become master, and is that within a few seconds of starting, or does it occur at some random time later?

There can be various reasons for two instances becoming master, and that often relates to keepalived not seeing the adverts from the other system. This can be caused by iptables configuration or, if vmacs are used, not having the correct configuration set on the vmac interface and the underlying interface.

If an iptables problem is suspected, issuing the following iptables commands will trace packet progression through iptables, and one can see in the log files if, and where, a packet is bring discarded (replace iptables with ip6tables for IPv6 issues):
iptables -t raw -A PREROUTING -p 112 -j TRACE       # for incoming VRRP packets
iptables -t raw -A OUTPUT -p 112 -j TRACE                # for outgoing packets

Don't forgot to remove these entries after testing, otherwise log files can fill up!

For configuration settings for vmac interfaces, commit 60217b6 added the functionality to set the necessary interface configuration. keepalived/vrrp/vrrp_if_config.c shows the configuration that needs to be set.
