### ISSUE TITLE
How to set virtual ip as primary ip?

### ISSUE THREAD

**Issue by cathaysia** [acassen/keepalived#2183]
Due to some limitations, I have to put virtual ip and real ip in one network segment. This causes the tcp client to still use the real ip when sending requests. Does keepalived have some kind of configuration item that makes it automatically set the virtual ip as the master ip when it enters master mode?

I found a [post](https://www.iteye.com/blog/zhangxugg-163-com-1669810) describes how to set the default ip for a multi-ip network card, but unfortunately, the command he uses will report an error on my computer

> ip route change default dev eth0 src 192.168.0.22
> RTNETLINK answers: No such file or directory

**Comment by pqarmitage** [comment]
It is quite normal for the virtual ip and real ip to be in the same network segment; indeed I think it would be unusual not to do so.

The purpose of the virtual IP addresses is for other devices to be able to access a working system via the virtual IP address. For any outgoing connections it doesn't make sense to use the virtual IP address. Suppose a VRRP instance were currently master (machine A) and its virtual IP address was used for an outgoing (TCP) connection. Another system (machine B) now starts up with a higher priority VRRP instance and so takes over as master. The TCP connection established by machine A would now no longer work since any returned packets would go to machine B.

So the answer to your question is no. keepalived has no mechanism to set a VIP as the primary address for an interface.

**Comment by cathaysia** [comment]
Yes, your point is in line with my intuition. I think the virtual ip only makes sense for the server, and the client should be able to connect to the server and work no matter which ip it uses.

Please let me elaborate on my situation:

Currently my machine's software physical addresses are 192.168.130.21-192.168.130.30 and virtual addresses are 31-40. When the server is bound to the virtual ip, it seems to no longer accept requests from clients in 21-30. No doubt this is a problem with the server software itself, but if there is good way to make the client use a virtual ip instead of a physical ip, please let me know. thanks
