### ISSUE TITLE
Will Advert_int support milliseconds

### ISSUE THREAD

**Issue by shwethakeepalived** [acassen/keepalived#2191]
**Describe the bug**
This is query. Can VRRP advertisement interval can be set in milliseconds.
Is there any performance issue during scale testing(64 instances) and is there any known issues?

And if we configure upto 64 vrrp instance and is there any known issue on same?

**Keepalived version**
v2.0.19

Distro (please complete the following information):

Name [Ubuntu]
Version
Architecture
4.14.67-yocto-standard

**Comment by pqarmitage** [comment]
If you use VRRP version 3 then you can set the advertisement interval in centi-seconds, e.g. `advert_int 0.01`, but the resolution of the advert timer doesn't go any finer than that. This is specified in RFC5798 and the advert interval (in centi-seconds) is included in the transmitted VRRP header.

There are users who run over 1000 vrrp instances, and so there should be no issue with running a mere 64. There are no known issue relating to the number of vrrp instances.

It shouldn't be necessary, but you might want to configure the vrrp process to use realtime scheduling, since that gives the vrrp process higher priority than most other processes.

I would recommend that you upgrade to a recent version of keepalived, e.g. 2.2.7 rather than using the old version you have specified.

**Comment by shwethakeepalived** [comment]
Thank you for the update
