### ISSUE TITLE
keepalived error

### ISSUE THREAD

**Issue by imrahuldevopser** [acassen/keepalived#2197]
cd /etc/keepalived/keepalived.conf 
keepalived.conf file will be removed automatically after rebooting the system. why?  Because my keepalived status will be running and then around 8hrs will be back to my system can be check status so failed?

**Comment by pqarmitage** [comment]
`/etc/keepalived/keepalived.conf` will normally be a file, and therefore `cd /etc/keepalived/keepalived.conf` will normally fail.

I have no idea why keepalived.conf is removed automatically after rebooting the system; that is certainly not normal keepalived behaviour.

keepalived does remove (unlink) certain files:
- any FIFOs specified in the keepalived configuration
- a configured reload_time_file
- PID files

So unless you have configured one of the above to be the keepalived.conf file then it won't be keepalived that is removing the configuration file.

I am not clear what is meant by "Because my keepalived status ...", and this doesn't appear to have any relation to keepalived.conf being removed.

**Comment by pqarmitage** [comment]
@imrahuldevopser Due you have an update for this issue, or can it be closed now?

**Comment by pqarmitage** [comment]
Since there have been no updates to this issue for 24 hours despite requests for an update and other issues being updated, I am assuming that this is no longer an issue.
