### ISSUE TITLE
Configure options wrongly seen as incompatible

### ISSUE THREAD

**Issue by rlebreton** [acassen/keepalived#2200]
**Describe the bug**
When trying to run the configure script for version 2.2.7 with a set of options that was previously used with version 1.4.5, I had some errors that seemed wrong. For instance, pairing the --disable-lvs option with the --disable-fwmark one raises the following error message:
 
```
./configure --disable-lvs --disable-fwmark
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
[...]
checking for ldd... ldd
checking for ar... ar
checking the archiver (ar) interface... ar
configure: error: enable-fwmark requires lvs
```

**Expected behavior**
I assumed that the fwmark functionality was disabled by design when the lvs one was disabled as well but those two options should not be seen as incompatible, especially when the error message mentions the enable equivalent of the specified option.

**Distro**
 - Name: Ubuntu
 - Version: 22.04
 - Architecture: x86_64

**Additional context**
When looking at the configure.ac file and its history, I found the f80b1197dc6b2fefef21c242ac0bd2545b5d7f7a commit which seems to have introduced this behavior that also seems to occur when some other option pairs are used (such as disable-lvs/disable-regex, disable-regex/disable-regex-timers and others).

**Comment by pqarmitage** [comment]
The idea behind this is that if LVS is disabled, then there is no fwmark functionality to enable or disable, and so the error (or inconsistency) is reported. Similarly, regex functionality requires LVS, and regex-timer functionality requires regex functionality.

The reason behind this was to try and help avoid user configuration errors; if a user intended to type `--disable-vrrp --disable-fwmark` but instead typed `--disable-lvs --disable-fwmark` the the latter reports an error because there is not point in adding `--disable-fwmark` and it is more likely to be an error. I could have implemented it as a warning, but experience has shown that generally people completely ignore warnings.

I agree that the error message `configure: error: enable-fwmark requires lvs` is not helpful, and it would be better to have `configure: error: disable-fwmark requires lvs`. I will look to see if I can improve this.

**Comment by rlebreton** [comment]
Thanks for your quick reply.

> The idea behind this is that if LVS is disabled, then there is no fwmark functionality to enable or disable, and so the error (or inconsistency) is reported. Similarly, regex functionality requires LVS, and regex-timer functionality requires regex functionality.
> 
> The reason behind this was to try and help avoid user configuration errors; if a user intended to type `--disable-vrrp --disable-fwmark` but instead typed `--disable-lvs --disable-fwmark` the the latter reports an error because there is not point in adding `--disable-fwmark` and it is more likely to be an error. I could have implemented it as a warning, but experience has shown that generally people completely ignore warnings.

I indeed had to look into it since I could not bypass this that easily. At least it made me look into my old configure line and allowed me to clean some redundant options.

> I agree that the error message `configure: error: enable-fwmark requires lvs` is not helpful, and it would be better to have `configure: error: disable-fwmark requires lvs`. I will look to see if I can improve this.

That would be great to have a more explicit message. I found it a bit hard to guess the interconnected configure options just from the scripts help message.

**Comment by pqarmitage** [comment]
Commit d70a585 updates the error message to report the error `configure: error: disable-fwmark requires lvs`. There were three other options where the error was reported for the wrong enable/disable, which are now fixed too.
