### ISSUE TITLE
(LB_VIP) WARNING - equal priority advert received from remote host with our IP address.

### ISSUE THREAD

**Issue by GentleRV** [acassen/keepalived#2216]
**Describe the bug**
2 Node configuration with Ubuntu 20.04.5
On the "MASTER" system no errors after starting the keepalived.service
With or without a working keepalived deamon on the MASTER I see on the Second system with systemctl status keepalived.service the messages (LB_VIP) WARNING - equal priority advert received from remote host with our IP address.
This about every 5 sec.

**To Reproduce**
Start on the the secondary machine the keepalived deamon

**Expected behavior**
No extra messages when asking the status with systemctl status keepalived.service

**Keepalived version**
```I see version deb keepalived (1:2.0.19-2ubuntu0.2)

Output of `keepalived -v`
Keepalived v2.0.19 (10/19,2019)

Copyright(C) 2001-2019 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.4.166
Running on Linux 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022

configure options: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --with-kernel-dir=debian/ --enable-snmp --enable-sha1 --enable-snmp-rfcv2 --enable-snmp-rfcv3 --enable-dbus --enable-json --enable-bfd --enable-regex build_alias=x86_64-linux-gnu CFLAGS=-g -O2 -fdebug-prefix-map=/build/keepalived-QKJBdn/keepalived-2.0.19=. -fstack-protector-strong -Wformat -Werror=format-security LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2

Config options:  NFTABLES LVS REGEX VRRP VRRP_AUTH JSON BFD OLD_CHKSUM_COMPAT FIB_ROUTING SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 DBUS

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RT SCHED_RESET_ON_FORK
```

**Distro (please complete the following information):**
 - Name: UBUNTU 20.04.5 FOCAL
 - Version: 5
 - Architecture: AMDX64

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details

**Configuration file:**
```/etc/keepalived/keepalived.conf

A full copy of the configuration file, obfuscated if necessary to protect passwords and IP addresses
```# Global Settings for notifications
global_defs {
    notification_email {
       user@mydomain.com  # Email address for notifications 
    }
    notification_email_from haproxy-slave@test.com	# The from address for the notifications
    smtp_server xxx.xxx.xxx.12  # SMTP server address
    smtp_connect_timeout 15
}
  
# Define the script used to check if haproxy is still working
vrrp_script chk_haproxy { 
    script "/usr/bin/killall -0 haproxy"
    interval 2 
    weight 2 
}
  
# Configuration for Virtual Interface
vrrp_instance LB_VIP {
    interface eth0
    state BACKUP        # set to BACKUP on the peer machine
    priority 99        # set to  99 on the peer machine
    virtual_router_id 51
  
    smtp_alert          # Enable Notifications Via Email
  
    authentication {
        auth_type PASS
        auth_pass myP@ssword	# Password for accessing vrrpd. Same on all devices
    }
    unicast_src_ip xxx.xxx.xxx.13 # Private IP address of master
    unicast_peer {
        xxx.xxx.xxx.14		# Private IP address of the backup haproxy
   }
  
    # The virtual ip address shared between the two loadbalancers
    virtual_ipaddress {
        xxx.xxx.xxx.11
    }
     
    # Use the Defined Script to Check whether to initiate a fail over
    track_script {
        chk_haproxy
    }
}

Ofcourse MASTER and BACKUP with the right priorities are set

**Notify and track scripts**
```
If any notify or track scripts are in use, please provide copies of them
```

**System Log entries**
```
Full keepalived system log entries from when keepalived started
many lines with this information
Keepalived_vrrp[94058]: (LB_VIP) WARNING - equal priority advert received from remote host with our IP address.

```

**Did keepalived coredump?**
```
If so, can you please provide a stacktrace from the coredump, using gdb.
```

**Additional context**
Add any other context about the problem here.

**Comment by pqarmitage** [comment]
Your configuration above states that the VRRP instance has priority 99 on both machines. This is why the backup, when it receives an advert with the same priority as it has configured, it logs it. It is a configuration error to to have two or more VRRP instances configured with the same priority. Since the backup does not send any adverts, the master does not receive any adverts and hence is not logging that it has received an advert with its priority.

Change the priority on one of the instances, and then you will not get the log messages.

By the way, it is much more efficient, and you will get a faster response time, if you use `track_process` rather than vrrp script chk_haproxy.

**Comment by GentleRV** [comment]
As mentioned that master and backup have diffrent priorities set is your answer not valid

Ofcourse MASTER and BACKUP with the right priorities are set.....

**Comment by pqarmitage** [comment]
The configuration you provide above states `priority 99        # set to  99 on the peer machine`. To me this says that the priorities are the same on both systems. Further, I can see nothing in the original issue report that states that the configured priorities are different. But hey-ho.

Looking at this further, I think you are saying that even if keepalived is not running on the master, then the second system is logging the warning messages. If this is the case, it suggests to me that the `unicast_src_ip` and `unicast_peer` addresses are the wrong way around, but that can only be a guess since insufficient information has been provided.

If we are to look at this further, can you please provide the following additional information:
1. Full keepalived configuration file from the master system.
2. Full keepalived configuration file from the second system.
3. The output of `ip addr show` on both systems.
4. The full keepalived syslog output on the second system from the time keepalived starts until the warning messages are logged.

**Comment by GentleRV** [comment]
all problems are solved with reinstalling NGINX with this script:
wget https://raw.githubusercontent.com/angristan/nginx-autoinstall/master/nginx-autoinstall.sh
chmod +x nginx-autoinstall.sh
./nginx-autoinstall.sh
