### ISSUE TITLE
notify_stop directive works intermittent 

### ISSUE THREAD

**Issue by atomus1990** [acassen/keepalived#2239]
**Describe the bug**

Script declared to be executed at notify_stop is not executed always, as expected.

**To Reproduce**
1. create and declare script for notify_stop
2. perform systemctl stop keepalived and check if script was executed accordingly
3. Script is executed only sometimes

**Keepalived version**

keepalived -v
Keepalived v2.0.19 (10/19,2019)

**Distro (please complete the following information):**
 - Name: Ubuntu
 - Version: 20.04 LTS
 - Architecture: x86_64

**Configuration file:**

global_defs {
   notification_email {
        xxx
   }
   notification_email_from root@user-pc
   smtp_server 127.0.0.1
   smtp_connect_timeout 8
   router_id user-pc
   garp_master_delay 0
   script_user root
   enable_script_security
}

vrrp_sync_group MS_GROUP {   # must be before vrrp_instance declaration
  group {
    WAN_INTERFACE
    ENS4
  }
  notify_stop "/etc/test.sh"
  #notify_master "/etc/conntrackd/primary-backup.sh primary"
  #notify_backup "/etc/conntrackd/primary-backup.sh backup"
  #notify_fault "/etc/conntrackd/primary-backup.sh fault"
  #notify /etc/keepalived/keepalivednotify.sh
  #smtp_alert
}

vrrp_instance WAN_INTERFACE {
    interface ens3
    state BACKUP
    virtual_router_id 1
    priority 60
    advert_int 1
    authentication {
      auth_type PASS
      auth_pass hello123
    }
    unicast_src_ip X.X.X.X
    unicast_peer {
         X.X.X.X
    }
    virtual_ipaddress {
        X.X.X.X
    }
}

vrrp_instance ENS4 {
    interface ens4
    state BACKUP
    virtual_router_id 2
    priority 60
    advert_int 1
    authentication {
      auth_type PASS
      auth_pass hello123
    }
    unicast_src_ip X.X.X.X
    unicast_peer {
         X.X.X.X
    }
    virtual_ipaddress {
        X.X.X.X
    }
}

**Notify and track scripts**

cat /etc/test.sh
#!/bin/bash -xv

/usr/bin/echo "test123" > /etc/test123

**System Log entries**

Jan 12 05:03:49 user-pc Keepalived[361833]: Starting Keepalived v2.0.19 (10/19,2019)
Jan 12 05:03:49 user-pc Keepalived[361833]: WARNING - keepalived was build for newer Linux 5.4.166, running on Linux 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020
Jan 12 05:03:49 user-pc Keepalived[361833]: Command line: '/usr/sbin/keepalived' '--dont-fork'
Jan 12 05:03:49 user-pc Keepalived[361833]: Opening file '/etc/keepalived/keepalived.conf'.
Jan 12 05:03:49 user-pc Keepalived[361833]: (Line 9) Unknown keyword 'garp_master_delay'
Jan 12 05:03:49 user-pc Keepalived[361833]: Starting VRRP child process, pid=361844
Jan 12 05:03:49 user-pc Keepalived_vrrp[361844]: Registering Kernel netlink reflector
Jan 12 05:03:49 user-pc Keepalived_vrrp[361844]: Registering Kernel netlink command channel
Jan 12 05:03:49 user-pc Keepalived_vrrp[361844]: Opening file '/etc/keepalived/keepalived.conf'.
Jan 12 05:03:49 user-pc Keepalived_vrrp[361844]: Registering gratuitous ARP shared channel
Jan 12 05:03:49 user-pc Keepalived_vrrp[361844]: (WAN_INTERFACE) Entering BACKUP STATE (init)
Jan 12 05:03:49 user-pc Keepalived_vrrp[361844]: (ENS4) Entering BACKUP STATE (init)
Jan 12 05:03:52 user-pc Keepalived_vrrp[361844]: (ENS4) Entering MASTER STATE
Jan 12 05:03:52 user-pc Keepalived_vrrp[361844]: VRRP_Group(MS_GROUP) Syncing instances to MASTER state
Jan 12 05:03:52 user-pc Keepalived_vrrp[361844]: (WAN_INTERFACE) Entering MASTER STATE

**Comment by pqarmitage** [comment]
This is not relevant to your issue, but I note the log message `(Line 9) Unknown keyword 'garp_master_delay'`. In global_defs, the keyword is `vrrp_garp_master_delay`.

notify scripts are "fire and forget" so far as keepalived is concerned. In order not to leave zombie processes, keepalived also sets PDEATHSIG to SIGTERM for all child processes (including scripts) that it creates. This means that the notify script will be sent SIGTERM if the keepalived_vrrp process exists before /etc/test.sh completes. Unless the script handles/traps SIGTERM, the script will terminate before it completes. If you add a handler for SIGTERM to /etc/test.sh, then it should be able to consistently run to completion.

There are issue with notify scripts due to the fire and forget nature of them. For example, if a vrrp instance transitions to master state, and then almost immediately transitions back to backup, keepalived will (if appropriately configured) fire two notify scripts, one for the master transition and one for the backup transition. The problem is that there is no guarantee of the order in which the scripts will execute, and so this makes it very difficult to know if the vrrp instance ends up in master or backup state. It was for this reason that I added the notify_fifos where the order of messages sent to the fifo(s) is guaranteed to be correct. You may find it easier/better to use a notify fifo rather than notify scripts. There is a sampe_notify_fifo.sh script that demonstrates how the fifos can be used.

**Comment by atomus1990** [comment]
Thank you for your response :). It helped me a lot.
