### ISSUE TITLE
multiple interface for vrrp binding

### ISSUE THREAD

**Issue by SimonLiuhd** [acassen/keepalived#2290]
Want to use multiple interfaces in the **interface** item which is in the vrrp_instance block, such as followings, there are 2 interface names (eth0 and eth1):

rp_instance <STRING> {  
           ...
           interface **eth0 eth1**
           ...
}

Can we support the above, or we have already had a workaround way?

Thanks a lot.
Simon

**Comment by pqarmitage** [comment]
I don't understand why you want to do this or how you would want it to work.

Can you please provide a detailed description of what you want to achieve, an example configuration, and a description of your network setup for this.

**Comment by sever-sever** [comment]
> Want to get a HA network between the master and backup servers, we want to use 2 direct connection via 2 interface. For example, the eth0 fails, the commutation between the vrrp instances of 2 servers can use the eth1.
> 
> Thanks. Simon

Why not use bonding?

**Comment by pqarmitage** [comment]
I think @sever-sever has the best solution, i.e. create a bond interface and use that.

If we had 
   interface **eth0** **eth1**
which interface would keepalived configure the virtual IP addresses on?

Alternatively, you might be able to use unicast peers, providing the are reachable on both eth0 and eth1.

I don't see that there is anything sensible that we can do with keepalived to support this request.

**Comment by SimonLiuhd** [comment]
@sever-sever @pqarmitage 
Firstly, thanks for your suggestion, we use the bond solution.

We use eno5 and eno6 to the bond0 by mode1:  but during testing, when we **ifdown eno5**, and after 20 seconds,  **ifup eno5**, the backup server will **Receive advertisement timeout** and enters the MASTER STATE (the advert_int is configured as 1).

Could you guys help?

Thanks in advances.
Simon

**Comment by sever-sever** [comment]
> bond0 by mode1

I never used it for VRRP, so why not use LACP?
I haven't heard any negative reviews for this case (LACP)

**Comment by SimonLiuhd** [comment]
@sever-sever 
Thanks a lot for your quick reply.
We will try it.

**Comment by GigabyteProductions** [comment]
Hello, I'd like to re-open this issue for discussion on use cases where bonding is not an option.

The use case I am investigating may create a condition where the network used for VRRP is failing because there are two keepalived masters, and there are two keepalived masters because the network used for VRRP is failing. Such an issue may be solved by talking VRRP on an second/independent network. However, such a configuration causes keepalived to take down the main network when the second network fails for unrelated reasons.

If I can run VRRP on both networks, the two keepalived instances will continue to communicate over the primary network while the secondary network is down, and vice versa.

**Comment by pqarmitage** [comment]
@GigabyteProductions i really don't understand what you are wanting to acheive here. You need to provide a much more detailed description of what your issue is and what you are wanting to achieve.

**Comment by GigabyteProductions** [comment]
I am investigating the use of keepalived in the context of failover for redundant transparent firewalls between two network segments. The configuration is effectively what Cisco calls a "VLAN bridge". Having more than one bridge between two VLANs creates a switching loop that isn't exactly correctable by IEEE 802.1D STP alone. If interested, please see: https://www.cisco.com/c/en/us/support/docs/lan-switching/spanning-tree-protocol/11072-inter-vlan-11072.html

Where Cisco's failover solution involves configuring the VLAN bridges to run a multicast-based STP implementation separately from the underlying network's IEEE 802.1D STP, I am looking to instead use keepalived as something I can utilize on Linux today.

My concern is that, if the physical network becomes temporarily segmented, both instances of the VLAN bridge will enter master state, then when the segments come back together, a broadcast storm immediately occurs, creating too much network congestion for the two keepalived instances to communicate. I am concerned that the network can get "stuck" in this condition (network is failing because there are two masters, and there are two masters because the network is failing).

I'm considering an independent link between the keepalived instances, but I don't want a switching loop to occur on the main network because of an unrelated and undetected failure of the independent link.
