### ISSUE TITLE
Keepalived.service got notification from from PID 3977, but reception only permitted for main PID 3976

### ISSUE THREAD

**Issue by kunal-2309** [acassen/keepalived#2301]

**Comment by pqarmitage** [comment]
Please provide some details. What is PID 3977, and PID 3976? What is the contents of your keepalived.service file? what version of keepalived are you using? What kernel and systemd versions are you using? What distro and version are you running on? Please provide all log entries pertaining to keepalived since keepalived started.

**Comment by pqarmitage** [comment]
Duplicated in issue #2302, but with a little bit of information.
