### ISSUE TITLE
The VRRP script is invalid in special configurations

### ISSUE THREAD

**Issue by lbo874** [acassen/keepalived#2304]
**Describe the bug**
We have two VRRP scripts as follows:
1.The first script fails during startup, and all subsequent scripts succeed. The execution interval is 5 seconds；
2.The execution of the second script takes more than ten seconds.
After Keepalived is enabled, VRRP cannot take effect even if two VRRP scripts are successfully executed.
**To Reproduce**
The first script is as follows:
``` #!/bin/bash
if [[ ! -a /tmp/test111 ]]; then
    touch /tmp/test111
    exit 1
else
    exit 0
fi
``` 
The second script is as follows:
```
 #!/bin/bash
sleep 20
exit 0
```
The configuration file is as follows:
```
 vrrp_script aaa {
    script "/etc/keepalived/a.sh"
    interval 5
}

vrrp_script bbb {
    script "/etc/keepalived/b.sh"
    interval 60
}

vrrp_instance VI_1 {
    state BACKUP
    nopreempt
    interface enp3s0
    virtual_router_id 173
    priority 100
    advert_int 1
    virtual_ipaddress {
        8.82.225.200
    }
    track_script {
        aaa
        bbb
    }
}
```
**Expected behavior**

**Keepalived version**
```
2.2.4
```

**Distro (please complete the following information):**
 - Name:Euleros
 - Version: r12
 - Architecture: arm64

**System Log entries**
```
Full keepalived system log entries from when keepalived started
```

**Did keepalived coredump?**
no

**Additional context**

**Comment by pqarmitage** [comment]
Assuming that initially /tmp/test111 does not exist, when `/etc/keepalived/a.sh` first runs, it creates /tmp/test111 and exits with exit code 1 (i.e. failure). When `/etc/keepalived/a.sh` subsequently runs, since /tmp/test111 already exists, it exits with exit code 0 (i.e. success).

So keepalived is working as expected, i.e. a script returning a non-zero exit code is treated as a failure, and returning a 0 exit code is treated as success.
