### ISSUE TITLE
error: Non-existent interface specified in configuration

### ISSUE THREAD

**Issue by fantastic2085** [acassen/keepalived#2308]
_Support requests should be sent via_ https://groups.io/g/keepalived-users

**Describe why you are unable to send the support request to the above email list**
Understanding why you cannot use the email list should help us improve it.

**Describe what you need help/support for**
A clear and concise description of what you need help with.
An error occurred while deploying keepalived
![image](https://github.com/acassen/keepalived/assets/4116773/91656609-f001-44ea-acfd-f786a58ac146)

keepalived is deployed in container mode

Keepalived image from the docker.io/arcts/keepalived download

**Details of what you would like to do with keepalived**
Describe in details what you would like to achieve with keepalived

**Keepalived version**
Output of `keepalived -v` (a later version of keepalived might be needed).
![image](https://github.com/acassen/keepalived/assets/4116773/0cfe9987-ee9b-4ab5-afeb-38424d47905c)

**Distro (please complete the following information):**
 - Name [e.g. Fedora, Ubuntu] Ubuntu 20.04.6 LTS (Focal Fossa)
 - Version [e.g. 29] 5.4.0-144-generic
 - Architecture [e.g. x86_64] x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details 
Here is the command to run the keepalived container using podman:
/usr/bin/podman run --rm --ipc=host --stop-signal=SIGTERM --net=host --init --name ceph-c252ba5c-f5e9-11ed-a21b-851e9c041338-keepalived-rgw-lb-http-dmp-hci01-jdxzgw --cap-add=NET_ADMIN --cap-add=NET_RAW -d --log-driver journald --conmon-pidfile /run/ceph-c252ba5c-f5e9-11ed-a21b-851e9c041338@keepalived.rgw.lb.http.dmp-hci01.jdxzgw.service-pid --cidfile /run/ceph-c252ba5c-f5e9-11ed-a21b-851e9c041338@keepalived.rgw.lb.http.dmp-hci01.jdxzgw.service-cid --cgroups=split -e CONTAINER_IMAGE=172.18.210.68:4000/amd/ceph16/keepalived:v2.0.5-amd64 -e NODE_NAME=dmp-hci01 -e CEPH_USE_RANDOM_NONCE=1 -e KEEPALIVED_AUTOCONF=false -e KEEPALIVED_CONF=/etc/keepalived/keepalived.conf -e 'KEEPALIVED_CMD=/usr/sbin/keepalived -n -l -f /etc/keepalived/keepalived.conf' -e KEEPALIVED_DEBUG=false -v /var/lib/ceph/c252ba5c-f5e9-11ed-a21b-851e9c041338/keepalived.rgw.lb.http.dmp-hci01.jdxzgw/keepalived.conf:/etc/keepalived/keepalived.conf 172.18.210.68:4000/amd/ceph16/keepalived:v2.0.5-amd64

**Configuration file:**
Full copy of your configuration file, obfuscated if necessary to protect passwords and IP addresses

**Notify and track scripts**
If any notify or track scripts are in use, please provide copies of them

**System Log entries**
Full keepalived system log entries from when keepalived started, if applicable

**Additional context**

**Comment by pqarmitage** [comment]
I can only assume that `/etc/keepalived/keepalived.conf`specifies interface bond1.1102 but that interface does not exist on your system.

Since you have not provided a copy of your configuration, nor a listing of the interfaces on your system, we cannot investigate any further.

If you can provide the necessary information, then we can investigate further.

I note that the version of keepalived you are running is extremely old. You would be far better off using an up-to-date version, e.g. v2.2.8 or v2.2.7. I don't know what git commit 8fc23ec3d0 in the `keepalived -v` output is; there is no such commit in the keepalived git tree.

I might be simplest to initially run keepalived natively on your system (i.e. not using a docker image), and get  that working, and then move to using a docker image.
