### ISSUE TITLE
why ping_check uses a global seq number shared by all ping checker thread?

### ISSUE THREAD

**Issue by roykingz** [acassen/keepalived#2311]
I noticed that in [ping_it](https://github.com/acassen/keepalived/blob/master/keepalived/check/check_ping.c#L194) function, a global seq number shared by all ping checker is used. 
1. can we use a local seq number in ping_it or just a fixed seq number (like 1) all the time ?
2. should we convert the byte order like `icmp_hdr->un.echo.sequence = htons(seq_no++)` ?

**Comment by pqarmitage** [comment]
I agree that it doesn't make sense using a global seq number across all ping checkers, and also agree that `htons()` should also be used.

I have been looking at the code, and also at the ICMP packets being sent, with Wireshark. Currently, each ping packet is sent with a different id value (in fact it is incremented by 1 each time a ping packet is sent). Because the code uses a SOCK_DGRAM with protocol IPPROTO_ICMP/ICMPV6 the id value is filled in by the kernel, and the kernel increments the id value every time such a socket is opened (the alternative is to use SOCK_RAW when the application can fill in the id value, but there is then a problem of ensuring uniqueness of the id if other applications are also sending ICMP packets).

Since the id value is changing each time a ping packet is sent, it would be logical to just use a seq number of 1. However, I prefer the idea of the seq number being incremented, but this means that the socket needs to be kept open to keep the same id value, rather than opening the socket and subsequently closing it each time a ping packet is sent and received.

**Comment by pqarmitage** [comment]
Commit [2cdab40](https://github.com/acassen/keepalived/pull/2315/commits/2cdab40bbb0325b5358dc9c37149d7b5359ef2f0) now keeps the socket open for each ping check so the ICMP id field remains constant, the sequence number is maintained per ping checker, and the sequence number is now sent in big endian order.

Many thanks for raising this issue.
