### ISSUE TITLE
VRRP_Instance(VI_1) trunc to the first 20 VIPs

### ISSUE THREAD

**Issue by opencmit2** [acassen/keepalived#2327]
The keepalived component prompts "VRRP_Instance(VI_1) trunc to the first 20 VIPs" how to solve

**Comment by pqarmitage** [comment]
I suspect that you are using a fairly old version of keepalived. Prior to commit b46dec5 (January 2016) there was a hard coded limit of 20 VIPs. Commit b46dec5 relaxed this restriction and limits the number of VIPs to how many can fit in a VRRP advert packet.

I am unable to find the error message that you have quoted above. Prior to commit b46dec5 the error message was
```
VRRP_Instance(VI_1) more than 20 VIPs: extra added the excluded vip block.
 => Declare extra VIPs into the excluded vip block
```

The solution to the problem you appear to be experiencing is either to move any VIPs in excess of the limit of 20 from the `virtual_ipaddress` block to the `virtual_ipaddress_excluded` block, or to upgrade to a recent version of keepalived (which is a good idea in any case since there have been a large number of fixes and enhancements over the last 7+ years).
