### ISSUE TITLE
Keepalived load balancing not working on  fedora 38 - 2 nodes (VMs) setup.

### ISSUE THREAD

**Issue by ghevge** [acassen/keepalived#2330]
I'm trying to set up keepalived load balancing functionality on a 2  nodes(VMs) Fedora 38 environment. 
I was able to configure keepalive VIP and failover functionality, but so far, had no luck in making load balancing working.

My keepalived.conf for node 1 is :

```
vrrp_instance VI_1 {
  state MASTER
  interface ens18
  virtual_router_id 55
  priority 150
  advert_int 1
  unicast_src_ip 192.168.1.199
  unicast_peer {
    192.168.1.84
  }

  authentication {
    auth_type PASS
    auth_pass ***
  }

  virtual_ipaddress {
    192.168.1.100/24
  }
}
virtual_server 192.168.1.100 80 {
  delay_loop 6
  lb_algo rr
  lb_kind NAT
  protocol TCP

  real_server 192.168.1.199 80 {
    TCP_CHECK {
      connect_timeout 10
    }
  }
  real_server 192.168.1.84 80 {
    TCP_CHECK {
      connect_timeout 10
    }
  }
} 
```

My keepalived.conf for node 2 is :

```
vrrp_instance VI_1 {
  state BACKUP
  interface ens18
  virtual_router_id 55
  priority 100
  advert_int 1
  unicast_src_ip 192.168.1.84
  unicast_peer {
    192.168.1.199
  }

  authentication {
    auth_type PASS
    auth_pass ***
  }

  virtual_ipaddress {
    192.168.1.100/24
  }
}
virtual_server 192.168.1.100 80 {
  delay_loop 6
  lb_algo rr
  lb_kind NAT
  protocol TCP

  real_server 192.168.1.199 80 {
    TCP_CHECK {
      connect_timeout 10
    }
  }
  real_server 192.168.1.84 80 {
    TCP_CHECK {
      connect_timeout 10
    }
  }
}
```

I've aslo tried the instructions provided here: http://kb.linuxvirtualserver.org/wiki/Building_Two-Node_Directors/Real_Servers_using_LVS_and_Keepalived but in vain.

Any idea what might be wrong? Is the keepalive load balancing even possible on my setup?

Thanks

**Comment by pqarmitage** [comment]
When using NAT, IPVS rewrites the destination IP address and port (although port 80 is replaced with port 80 in your case), but does not rewrite the source IP address (see http://linuxvirtualserver.org/VS-NAT.html). This means that, for example, after 192.168.1.199 receives a packet and decides to forward it to real server 192.168.1.84, when 192.168.1.84 sends the reply packet, it will not be sent via 192.168.1.199 to reverse the NAT, but directly back to the client, who won't understand the packet since it won't have a conntrack entry for a connection to 192.168.1.84:80 but will have the original entry to 192.168.1.199:80.

There are a number of ways around this:

1. Use nftables/iptables to do source NAT when 192.168.1.199 forwards a packet to 192.168.1.84, and when 192.168.1.84 forwards a packet to 192.168.1.199.
2. You could try using TUN or DR, but I think there are complications with that. The VIP, i.e. 192.168.1.100 would have to be permanently configured on both nodes on a non ARP interface (e.g. a loopback interface), but this could do horrible things to your routing since all the addresses are on the same subnet (IPVS is designed for the real servers to be on different servers from the virtual servers and IPVS routes between an external network (with the virtual servers) and and internal network (with the real servers)).
3. You might be able to do something using network namespaces, but that could be quite difficult to set up.
4. If the web server addresses are resolved via DNS, and suppose the web server name is www.a.b.c, then update the DNS so that it has two A records, 192.168.1.100 and 192.168.1.101, and then you can stop using IPVS at all. You configurations could look something like:
for Node 1:
```
vrrp_instance VI_1 {
  interface ens18
  virtual_router_id 55
  priority 150
  advert_int 1
  unicast_src_ip 192.168.1.199
  unicast_peer {
    192.168.1.84
  }

  authentication {
    auth_type PASS
    auth_pass ***
  }

  virtual_ipaddress {
    192.168.1.100/24
  }
}

vrrp_instance VI_2 {
  interface ens18
  virtual_router_id 56
  priority 100
  advert_int 1
  unicast_src_ip 192.168.1.199
  unicast_peer {
    192.168.1.84
  }

  authentication {
    auth_type PASS
    auth_pass ***
  }

  virtual_ipaddress {
    192.168.1.101/24
  }
}
```

and for node 2:
```
vrrp_instance VI_1 {
  interface ens18
  virtual_router_id 55
  priority 100
  advert_int 1
  unicast_src_ip 192.168.1.84
  unicast_peer {
    192.168.1.199
  }

  authentication {
    auth_type PASS
    auth_pass ***
  }

  virtual_ipaddress {
    192.168.1.100/24
  }
}

vrrp_instance VI_2 {
  interface ens18
  virtual_router_id 56
  priority 150
  advert_int 1
  unicast_src_ip 192.168.1.84
  unicast_peer {
    192.168.1.199
  }

  authentication {
    auth_type PASS
    auth_pass ***
  }

  virtual_ipaddress {
    192.168.1.101/24
  }
}
```

Normally node 1 will be master for VI_1 (192.168.1.100) and node 2 will be master for VI_2 (192.168.1.101). DNS will effectively provide the load balancing, but in the event of a node failure, the other node will take over both IP addresses.

A combination of these ideas might provide an even better solution.

**Comment by pqarmitage** [comment]
@ghevge The whole purpose of VRRP is to have VIPs on one node at a time, which move to another node in the event that the first node fails. It you want to have the same VIPs on multiple nodes at the same time then VRRP is not the right protocol for you.

**Comment by ghevge** [comment]
@pqarmitage  then is there a way to force VIP to move to the backup node if the upstream on the master node is not available/accessible ?

**Comment by ghevge** [comment]
@pqarmitage thanks for the info!  Today when we move into the containers world, is there a way to track a container status or a service within a container, other than trying to build a track script ?

**Comment by pqarmitage** [comment]
keepalived has no direct way to track the status of a container, so the only way to do it would be to use a track script.

**Comment by ghevge** [comment]
@pqarmitage I've tried to set the VIP as a static ip in the backup node, like this:

static_ipaddress {
  192.168.1.100 dev enp0s3 scope global
}

Once I restart the backup node the static VIP gets assigned to it, but when I restart the Master node, the static ip gets removed from the backup node... :( . So not even the static ips get persisted across the nodes

**Comment by ghevge** [comment]
OK i think I've found a way to set a persisting static ip. I have to use a different ip than the VIP one. That way the static ip will be kept accross nodes plus I can access my app pinting to this new static IP: 

```
static_ipaddress {
192.168.1.101 dev enp0s3 scope global
}
```

**Comment by pqarmitage** [comment]
It will not work if the static_ipaddress is the same as a virtual_ipaddress. It looks as though you have found a solution by using a non VIP address for the static address.

**Comment by ghevge** [comment]
Partial solution, as the routing on static ip doesn't behave the same it does on the VIP.
