### ISSUE TITLE
SELinux AVC denial for setattr

### ISSUE THREAD

**Issue by szarkos** [acassen/keepalived#2333]
**Describe the bug**
On Fedora (and like) systems we can see an AVC denial with keepalived:
```
AVC avc:  denied  { setattr } for  pid=4374 comm="keepalived" name="script.sh" dev="nvme0n1p1" ino=9531038 scontext=system_u:system_r:keepalived_t:s0 tcontext=unconfined_u:object_r:keepalived_unconfined_script_exec_t:s0 tclass=file permissive=0
```

The AVC denial does not seem to keep keepalived from running normally, but it may trigger some alarms. The reason for this denial is because keepalived is calling utimensat() on any notify scripts (usually placed in /usr/libexec/keepalived/).

Some time ago there was a RedHat bug report and attempted fix in the selinux-policy repo, but the Red Hat devs were unable to determine where the utimensat() call was coming from and weren't willing to enable setattr permissions, so the bug was closed: https://bugzilla.redhat.com/show_bug.cgi?id=1997148

However, a quick trace shows utimensat() is actually being called from libmagick, in particular `ka_magic_open() -> magic_open()` in lib/keepalived_magic.h. Systems that build without libmagick will not see this issue, but the Fedora keepalived spec file includes a build requirement for `file-devel`.

One solution is to remove the MAGIC_PRESERVE_ATIME parameter in the call to magic_open(), although I'd like to hear if this parameter is necessary for some reason?

`magic_t magic = magic_open(MAGIC_ERROR | MAGIC_NO_CHECK_CDF | MAGIC_NO_CHECK_COMPRESS);`

instead of 

`magic_t magic = magic_open(MAGIC_PRESERVE_ATIME | MAGIC_ERROR | MAGIC_NO_CHECK_CDF | MAGIC_NO_CHECK_COMPRESS);`

**To Reproduce**
 - Start with any basic keepalived.conf that configures some scripts.
 - Start the keepalived service and view then review the audit logs (`ausearch -m avc -i`)
   - Alternatively, you can try to run keepalived manually with the correct context:
   - `runcon system_u:object_r:keepalived_exec_t:s0 /usr/sbin/keepalived --dont-fork -D -l`
 - Run strace and search for the call to utimensat() (after the above code change it should not occur):
    `strace -kf /usr/local/sbin/keepalived --dont-fork -D -l 2>&1 | less`

**Expected behavior**
Keepalived happily runs with no AVC denials in the audit log.

**Keepalived version**
keepalived-2.2.8

**Distro (please complete the following information):**
 - Name: Fedora 38 (although earlier should also repro)
 - Version: 38
 - Architecture: x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
N/A

**Configuration file:**
Any trivial configuration with something like the following:
```
vrrp_script check_nginx {
    script "/usr/libexec/keepalived/check_script.sh"
    interval 2
}
vrrp_instance VI_1 {
    ... snip ...

    # Health check
    track_script {
        check_nginx
    }
```

**Notify and track scripts**
The contents of the scripts don't matter.

**System Log entries**
See audit log above.

**Did keepalived coredump?**
No

**Comment by pqarmitage** [comment]
@szarkos Many thanks for your detailed analysis. I have updated https://bugzilla.redhat.com/show_bug.cgi?id=1997148 to identify how utimensat() is being called.

It seems wrong to modify a program to stop SELinux errors; it should be that the SELinux policy is updated to reflect what the program needs to do (unless of course the SELinux report identifies that the program is doing something that it shouldn't be doing). In this case however, i think that, especially given the magic code below, there is an argument for modifying keepalived as you suggest.

The magic code has an interesting comment in close_and_restore() (which is where the MAGIC_PRESERVE_ATIME functionality is):
```
        if ((ms->flags & MAGIC_PRESERVE_ATIME) != 0) {
                /*
                 * Try to restore access, modification times if read it.
                 * This is really *bad* because it will modify the status
                 * time of the file... And of course this will affect
                 * backup programs
                 */
```
so based on this, it would seem sensible to remove MAGIC_PRESERVE_ATIME (I think where the comment refers to "status time" it means "change time").

The question is: _What is the impact of no longer setting MAGIC_PRESERVE_ATIME_? The answer is, I think, nothing (well almost). Once the script is executed, the atime of the script will be updated anyway, so there is no point in preserving it.

Regarding preserving atime doing nothing is not quite correct. For some reason, file's magic.c does not preserve the atime and mtime properly; even if utimes() is available, magic.c does not restore the tv_usec value for atime and mtime, and so even with MAGIC_PRESERVE_ATIME, the mtime and atime are modified by having the fractions of a second part set to 0. It seems to me that magic.c should be using utimensat() directly and setting the tv_nsec thereby ensuring that the mtime and atime remain precisely the same.

My inclination therefore is to remove MAGIC_PRESERVE_ATIME, and then the mtime and ctime fields will not be modified, and although the atime field will be (it is anyway at the moment because the tv_nsec field is set to 0), it will be modified each time the script is run, and so there is no real impact.

**Comment by szarkos** [comment]
@pqarmitage - thank you for the quick response! I agree in most cases this sort of thing should be fixed in selinux-policy, but since the RH bugzilla and PR was rejected I figured I'd see if it was fixable here.

Would you prefer that I submit a PR for this?

**Comment by pqarmitage** [comment]
My reading of the RedHat Bugzilla was that they wouldn't fix the problem because they couldn't identify where utimensat() was being called. Since we have now identified that and the BZ is updated accordingly, they make take some action on it.

I don't need a pull request for this, I'll push a fix later.

**Comment by pqarmitage** [comment]
Commit b2b6539 removes MAGIC_PRESERVE_ATIME.
