### ISSUE TITLE
The keepalived log shows SMTP status code = 553 when sending mail

### ISSUE THREAD

**Issue by wmz1930** [acassen/keepalived#2334]
_Support requests should be sent via_ https://groups.io/g/keepalived-users

**Describe why you are unable to send the support request to the above email list**
I can't receive the registration verification email in my mailbox.

**Describe what you need help/support for**
A clear and concise description of what you need help with.

**Details of what you would like to do with keepalived**
When I configure smtp_server send mail, I can't find the configuration item where to configure the account and password to log in to the mail server. So, the keepalived log shows SMTP status code = 553 when sending mail, where can I configure the account and password of the mail server?

**Keepalived version**
Keepalived v2.2.8 (04/04,2023), git commit v2.2.7-154-g292b299e+

**Distro (please complete the following information):**
 - Name [e.g. Fedora, Ubuntu]
 - Version [e.g. 29]
 - Architecture [e.g. x86_64]

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details 

**Configuration file:**
  notification_email {
     xxxxxx@163.com
     xxxxx@qq.com
     xxxxx@qq.com
  }
  notification_email_from xxxxx@163.com
  smtp_server smtp.163.com
  smtp_connect_timeout 30

**Notify and track scripts**
If any notify or track scripts are in use, please provide copies of them

**System Log entries**
Full keepalived system log entries from when keepalived started, if applicable

**Additional context**

**Comment by pqarmitage** [comment]
keepalived does not support SMTP authentication, nor indeed TLS for SMTP; it is strictly an RFC821 implementation that uses HELO and does not use authentication.

According to https://en.wikipedia.org/wiki/List_of_SMTP_server_return_codes error code 553 means **553 Requested action not taken: mailbox name not allowed**, which seems to imply that either the MAIL FROM or the RCPT TO field is not acceptable. It may indeed be that this is because your email server requires authentication.

It you can provide a Wireshark trace of the SMTP exchange that fails with the 553 error, I will consider enhancing the SMTP functionality to support RFC2821 (EHLO etc), TLS and authentication, although this will not be an insignificant task.
