### ISSUE TITLE
vrrp mem leak when reload

### ISSUE THREAD

**Issue by lbo874** [acassen/keepalived#2336]
**Describe the bug**
When I started the  process and reloaded it every 30 seconds, it seemed like a memory leak happened.Every one to three reloads may cause 4 to 8 KB leak of the VRRP process.

**To Reproduce**
1. keepalived -D -p /var/run/keepalived.pid -r /var/run/vrrp_lvs.pid -c /var/run/checkers_lvs.pid
2. loop  kill -1 Parent Process  peer 30s
3. 
![image](https://github.com/acassen/keepalived/assets/128496832/f923897f-943d-4bb4-a8b3-9017b43de6c7)

**Expected behavior**

**Keepalived version**
```
 
Built with kernel headers for Linux 5.10.0
Running on Linux 5.10.0-60.18.0.50.oe2203.aarch64 #1 SMP Wed Mar 30 02:43:08 UTC 2022

configure options:

Config options:  NFTABLES LVS VRRP VRRP_AUTH OLD_CHKSUM_COMPAT FIB_ROUTING

System options:  PIPE2 SIGNALFD INOTIFY_INIT1 VSYSLOG EPOLL_CREATE1 IPV4_DEVCONF IPV6_ADVANCED_API LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_OIFNAME FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS IP_MULTICAST_ALL LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE VRRP_VMAC VRRP_IPVLAN IFLA_LINK_NETNSID CN_PROC SOCK_NONBLOCK SOCK_CLOEXEC O_PATH GLOB_BRACE INET6_ADDR_GEN_MODE VRF SO_MARK SCHED_RESET_ON_FORK
[root@openEuler keepalived]#

```

**Distro (please complete the following information):**
 - Name:
 - Version:
 - Architecture: x86

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details

**Configuration file:**
```
vrrp_instance LVS_HW {
    state BACKUP
    interface eth4
    virtual_router_id 1
    priority 1
    advert_int 1
    nopreempt
    virtual_ipaddress {
    }
    virtual_ipaddress_excluded {
    }
    unicast_src_ip 192.168.229.93
    unicast_peer {
    }
}
include vsconf/*.conf
```
(Other valid configurations also this problems)

**Notify and track scripts**
loop kill -1 Parent Process 

**System Log entries**
![image](https://github.com/acassen/keepalived/assets/128496832/ceacc74d-7560-4d9e-8aee-b911873b1992)

**Did keepalived coredump?**
NA

**Additional context**
v2.0.20

**Comment by pqarmitage** [comment]
If we are to test this, we will need the full configuration, i.e. all the vsconf/*.conf files and any files they also include.

v2.0.20 is very old - there have been over 1000 non merge commits since that version. Can you please upgrade to v2.2.8 and see if the problem still occurs.

keepalived has a build option for memory allocation diagnostics. If you run configure with the `--enable-mem-check` option, keepalived will create files /tmp/keepalived_mem.PID.log which contain details of all memory allocations, frees etc, and when keepalived terminates it will log if there are any remaining memory allocations. Using this option is really the only way to identify the source of any memory leak.

**Comment by pqarmitage** [comment]
Closing due to no response for over 5 months.
