### ISSUE TITLE
VRRP Json dump  readiness notifications

### ISSUE THREAD

**Issue by saikanuri** [acassen/keepalived#2343]
**Describe the issue**
VRRP json prints the configuration to "keepalived.json" on SIGJSON today.

Is there a way this can be dumped to file without using the signal but rather whenever there's a modification on the configuration?

Also, this creates temporary file & rename it to keepalived.json making it unusable with inotify as inode of the file gets changed. So any specific rationale to chose to rename than copy the content ? or any other means to ensure application integrating keepalived can be synchronised with this?

**To Reproduce**
VRRP json prints the configuration to "keepalived.json" on SIGJSON today.

Is there a way this can be dumped to file without using the signal but rather whenever there's a modification on the configuration?

Also, this creates temporary file & rename it to keepalived.json making it unusable with inotify as inode of the file gets changed. So any specific rationale to chose to rename than copy the content ? or any other means to ensure application integrating keepalived can be synchronised with this?

**Expected behavior**

**Keepalived version**
Output of `keepalived -v`

**Distro (please complete the following information):**
 - Name [e.g. Fedora, Ubuntu]
 - Version [e.g. 29]
 - Architecture [e.g. x86_64]

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details

**Configuration file:**
A full copy of the configuration file, obfuscated if necessary to protect passwords and IP addresses

**Notify and track scripts**
If any notify or track scripts are in use, please provide copies of them

**System Log entries**
Full keepalived system log entries from when keepalived started

**Did keepalived coredump?**
If so, can you please provide a stacktrace from the coredump, using gdb.

**Additional context**

**Comment by pqarmitage** [comment]
@saikanuri This all depends on what you mean by "whenever there's a modification on the configuration". My understanding of a modification to the configuration is that the configuration file is modified and SIGHUP is sent to keepalived to make it reload its configuration (1). If on the other hand you mean if, for example, a VRRP instance changes from master to backup state, then you would like the JSON dumped (2), then that is another matter.

Re (1), since some outside agent (script or person) has triggered the configuration reload, then that agent could also send SIGJSON, and so there is no need to modify keepalived. I you mean something like (2) above, then you will need to define what events should trigger a re-write of the JSON file. However, you can probably use a `notify_fifo` together with a `notify_fifo_script` to be notified of relevant events, and then send a SIGJSON from the script.

The explanation for why a temporary file is created and then renamed to keepalived.json is given in a long(ish) comment in fopen_safe() in lib/utils.c. You can still monitor what is happening using inotify if you monitor the directory (default /tmp) using inotify, rather than monitoring the keepalived.json file itself.

**Comment by pqarmitage** [comment]
Closing due to no response for over 4 months.
