### ISSUE TITLE
Question: Active-active Load balancing using ARP replies 

### ISSUE THREAD

**Issue by stampeed** [acassen/keepalived#2346]
https://techhub.hpe.com/eginfolib/networking/docs/routers/msrv5/cg/5200-2312_hi-avail-cg/content/459372981.htm
Attached is a screen capture of the relevant section of this link, if a PNG is better than clicking a link.

HP Enterprise has an article about VRRP where the Master can selectively reply to ARP requests with VMACs for the Backup nodes using some algorithm, in order for those other nodes be advertised. This creates an "active-active" operational mode.

Can Keepalived currently support this type of operation?
This is not necessarily a feature request, just a question about what is currently possible and if so, how?

![vrrp_load_balancing_with_arp](https://github.com/acassen/keepalived/assets/8228132/3395ef06-2701-4082-9115-0dcb1ad8138e)

**Comment by pqarmitage** [comment]
Simple answer: No.

What is described above, and on the linked page, is **NOT** VRRP. While they may use VRRP to determine which device is the active virtual forwarder (AVF) (using VRRP advertisements) HP have added additional, proprietary, VRRP message types (request, reply and release) in order to add this extra functionality.

If the protocol extensions were documented, this is something that we could consider implementing, although I think it is unlikely since this has never been raised before, and the solution is proprietary to HP. If HP (or anyone else) were to add this functionality to the VRRP RFC (currently under review), then we would certainly look to implement it.
