### ISSUE TITLE
Can the order of adding IPv6 to keepalived be controlled

### ISSUE THREAD

**Issue by smallemployees** [acassen/keepalived#2367]
**Describe the bug**
I expect the addition order of IPv6 to be before the default IPv6 address

**To Reproduce**
Any steps necessary to reproduce the behaviour:
![image](https://github.com/acassen/keepalived/assets/150658327/c2d0fa54-bad6-46c1-b963-7468127c1eb5)

**Expected behavior**
I expect the addition order of IPv6 to be before the default IPv6 address
**Keepalived version**
```
Output of `keepalived -v`
```
![image](https://github.com/acassen/keepalived/assets/150658327/5e4cc1f3-fede-4678-bfc9-0f74910cec04)

**Distro (please complete the following information):**
 - Name: [e.g. Fedora, Ubuntu]
 - Version: [e.g. 29]
 - Architecture: [e.g. x86_64]

**Details of any containerisation or hosted service (e.g. AWS)**
If keepalived is being run in a container or on a hosted service, provide full details

**Configuration file:**
```
A full copy of the configuration file, obfuscated if necessary to protect passwords and IP addresses
```

**Notify and track scripts**
```
If any notify or track scripts are in use, please provide copies of them
```

**System Log entries**
```
Full keepalived system log entries from when keepalived started
```

**Did keepalived coredump?**
```
If so, can you please provide a stacktrace from the coredump, using gdb.
```

**Additional context**

**Comment by pqarmitage** [comment]
It appears to be that the VRRP virtual_ipaddress is fd::192:168:0:122/64 (since it specifies _nodad_); I am not sure what you mean by the _default IPv6 address_, but I guess you are referring to fd::192:168:0:91/64 (which does not have _nodad_).

So far as I can tell, _ip addr show_ first lists IPv4 addresses and then lists IPv6 addresses; within an address family the addresses are listed in the order of being added, most recent first. On that basis it is not possible to modify the order in which addresses are listed, and as far as I can tell the order has no significance).

So far as I can determine, there is no such thing as a _default_ IPv6 address. At https://superuser.com/questions/1129366/proper-way-to-set-default-outbound-ipv6-address-on-linux-in-ifcfg-eth0 it states that "when no address is preferred over another, Linux chooses one at random".

If you are wanting to control which IPv6 address is used as the source address of outgoing connections, there are several ways that can be done, depending on whether you want the statically configured address to be used or a VIP to be used:
1. Specify _preferred_lft 0_ for any address you do not want to use as a source address
2. Specify "home" on an address you do want to be used as the source address (the article above says this it is really abusing the true purpose of home)
3. Modify your IPv6 routes to add _src IPv6_address_ to specify the source IP address to be used for outgoing connections.

Options 1 and 2 can be added to the IPv6 address specification in the _virtual_ipaddress_ section of the keepalived configuration. Option 3 can also be handled by keepalived by using _virtual_routes_ in the vrrp_instance block of your keepalived configuration (if you want to override an existing route, specify a lower metric for the virtual_route in the keepalived config).

It would be interesting to know why you are interested in the order that addresses are listed.
