### ISSUE TITLE
healthchecker runtime error on check_data.h

### ISSUE THREAD

**Issue by schoekek** [acassen/keepalived#2368]
**Describe the bug**
Each run of healthcker generate multiple messages in syslog:
Keepalived_healthcheckers[1227]: Unknown protocol 0 at protocol_to_index:285 in ../../keepalived/include/check_data.h

**Keepalived version**
```
Keepalived v2.2.7 (01/16,2022)

Copyright(C) 2001-2022 Alexandre Cassen, <acassen@gmail.com>

Built with kernel headers for Linux 5.19.11
Running on Linux 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30)
Distro: Debian GNU/Linux 12 (bookworm)

configure options: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --enable-snmp --enable-sha1 --enable-snmp-rfcv2 --enable-snmp-rfcv3 --enable-dbus --enable-json --enable-bfd --enable-regex --with-init=systemd build_alias=x86_64-linux-gnu CFLAGS=-g -O2 -ffile-prefix-map=/build/keepalived-m8ENAG/keepalived-2.2.7=. -fstack-protector-strong -Wformat -Werror=format-security LDFLAGS=-Wl,-z,relro CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2

Config options:  NFTABLES LVS REGEX VRRP VRRP_AUTH VRRP_VMAC JSON BFD OLD_CHKSUM_COMPAT SNMP_V3_FOR_V2 SNMP_VRRP SNMP_CHECKER SNMP_RFCV2 SNMP_RFCV3 DBUS INIT=systemd SYSTEMD_NOTIFY

System options:  VSYSLOG MEMFD_CREATE IPV6_MULTICAST_ALL IPV4_DEVCONF LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_NEWDST RTA_PREF FRA_SUPPRESS_PREFIXLEN FRA_SUPPRESS_IFGROUP FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK RTEXT_FILTER_SKIP_STATS FRA_L3MDEV FRA_UID_RANGE RTAX_FASTOPEN_NO_COOKIE RTA_VIA FRA_PROTOCOL FRA_IP_PROTO FRA_SPORT_RANGE FRA_DPORT_RANGE RTA_TTL_PROPAGATE IFA_FLAGS LWTUNNEL_ENCAP_MPLS LWTUNNEL_ENCAP_ILA NET_LINUX_IF_H_COLLISION LIBIPVS_NETLINK IPVS_DEST_ATTR_ADDR_FAMILY IPVS_SYNCD_ATTRIBUTES IPVS_64BIT_STATS IPVS_TUN_TYPE IPVS_TUN_CSUM IPVS_TUN_GRE VRRP_IPVLAN IFLA_LINK_NETNSID GLOB_BRACE GLOB_ALTDIRFUNC INET6_ADDR_GEN_MODE VRF SO_MARK
```

**Distro (please complete the following information):**
 - Name: Debian Bookworm
 - Version: 12.4
 - Architecture: x86_64

**Details of any containerisation or hosted service (e.g. AWS)**
No container, Vmware virtual maschine

**Configuration file:**
```
track_file acme {
  file     "/var/local/vrrp_track_file"
  weight      1
}
vrrp_instance lb_mapproxy_test_218 {
  interface                 ens192
  state                     MASTER
  virtual_router_id         218
  priority                  100
  advert_int                1
  garp_master_delay         5

  # notify scripts and alerts are optional
  #
  # filenames of scripts to run on transitions
  # can be unquoted (if just filename)
  # or quoted (if has parameters)
  # to MASTER transition
  notify_master "/usr/sbin/notify.sh del 10.xxx.xx.218 443"
  # to BACKUP transition
  notify_backup "/usr/sbin/notify.sh add 10.xxx.xx.218 443"
  # FAULT transition
  notify_fault "/usr/sbin/notify.sh add 10.xxx.xx.218 443"

  track_file {
    acme weight 1
  }

  virtual_ipaddress {
    10.xxx.xx.218/26 dev ens192
  }
}

virtual_server fwmark 218443 {

  lb_algo wlc
  lb_kind DR
  protocol TCP



  real_server 10.xxx.xx.211 443 {
    SSL_GET {
      connect_timeout 5
      delay_before_retry 5
      nb_get_retry 1

      url {
        digest e0aa021e21dddbd6d8cecec71e9cf564
        path /loadbalancer.html
      }
    }
  }
  real_server 10.xxx.xx.212 443 {
    SSL_GET {
      connect_timeout 5
      delay_before_retry 5
      nb_get_retry 1

      url {
        digest e0aa021e21dddbd6d8cecec71e9cf564
        path /loadbalancer.html
      }
    }
  }
  real_server 10.xxx.xx.213 443 {
    SSL_GET {
      connect_timeout 5
      delay_before_retry 5
      nb_get_retry 1

      url {
        digest e0aa021e21dddbd6d8cecec71e9cf564
        path /loadbalancer.html
      }
    }
  }
  real_server 10.xxx.xx.214 443 {
    SSL_GET {
      connect_timeout 5
      delay_before_retry 5
      nb_get_retry 1

      url {
        digest e0aa021e21dddbd6d8cecec71e9cf564
        path /loadbalancer.html
      }
    }
  }
  real_server 10.xxx.xx.215 443 {
    SSL_GET {
      connect_timeout 5
      delay_before_retry 5
      nb_get_retry 1

      url {
        digest e0aa021e21dddbd6d8cecec71e9cf564
        path /loadbalancer.html
      }
    }
  }
}

```

**System Log entries**
```
Keepalived_healthcheckers[1227]: Unknown protocol 0 at protocol_to_index:285 in ../../keepalived/include/check_data.h
```

**Comment by pqarmitage** [comment]
OK, I can see the likely reason for this. The virtual server is specified using **fwmark**, and therefore there is no specific protocol for the virtual server (the _protocol tcp_ configuration line is redundant, and a config warning is logged for this).

I will have a look at the code to work out what needs to be done, however I have tried running your configuration and cannot reproduce the problem. Can you please provide the full keepalived logs so that we can understand better what is happening.

I note that keepalived logs the following warnings:
```
Fri Jan 12 08:58:35.392867405 2024: WARNING - fwmark virtual server FWM 218443, real server [10.200.30.211]:none:443 has port specified - clearing
Fri Jan 12 08:58:35.392888078 2024: WARNING - fwmark virtual server FWM 218443, real server [10.200.30.212]:none:443 has port specified - clearing
Fri Jan 12 08:58:35.392899182 2024: WARNING - fwmark virtual server FWM 218443, real server [10.200.30.213]:none:443 has port specified - clearing
Fri Jan 12 08:58:35.392906306 2024: WARNING - fwmark virtual server FWM 218443, real server [10.200.30.214]:none:443 has port specified - clearing
Fri Jan 12 08:58:35.392913500 2024: WARNING - fwmark virtual server FWM 218443, real server [10.200.30.215]:none:443 has port specified - clearing
```
These warnings should be removed since the checkers use the port as the default port for the checker to connect to (for when _connect_port_ is not specified in the checker configuration).

**Comment by pqarmitage** [comment]
So far as I can see _protocol_to_index()_ is only called when virtual/real servers are added or removed, which isn't quite the same as every time a checker is called.

Are you able to provide some more details of what is happening.

**Comment by schoekek** [comment]
thx for the verry fast response.
In our installations fwmark message is not logged to syslog.
fwmark is used in the nftables mangle prerouting configuration.

**Comment by schoekek** [comment]
The log entries come approximately every minute and always exactly 78 of them.

**Comment by pqarmitage** [comment]
Since you are getting 78 messages each minute, I guess that you have not provided your full configuration. Can you please provide your full configuration and also the log entries, since at the moment I cannot see what could be causing the log entries to be generated.

P.S. I will be offline from now for the next 5 to 6 hours.

**Comment by schoekek** [comment]
Yes, the configuration is complete, only the IP addresses are adjusted.
In addition, I can also say that we do not receive these log messages on Debian 11 servers (Keepalived v2.1.5) with a similar configuration.

**Comment by pqarmitage** [comment]
The log messages that you are seeing were added in commit dd48e5e, which was designed to optimise the IPVS configuration for virtual server groups with a large number of addresses and a large number of real servers. Commit dd48e5e was first included in v2.2.2.

At the moment I cannot work out what is happening. Using your configuration I cannot make keepalived call _protocol_to_index()_, and consequently cannot reproduce your problem. This isn't helped by what _protocol_to_index_() logs, and so I have produced the following patch (which I will merge upstream later): [pti.patch](https://github.com/acassen/keepalived/files/13931328/pti.txt). Are you able to apply this patch and build a test version of keepalived? The log output should then give us a better idea of where _protocol_to_index()_ is being called from.

Also, your notify script _/usr/sbin/notify.sh_ may be contributing to the issue, so could you please post the contents of that file. I assume that the 10.xxx.xx.218 address is being added or removed by the script, but I need to see the full details.

Since you have a VRRP instance configured, I assume that you are running keepalived on more than one system. Can you please confirm this, and also provide the keepalived configuration for the other systems (or confirmation that they are all exactly the same, including the VRRP instance priority).

It really would help to see the logs that are being produced, so that I can see things like the relative timings of the log messages, whether the checkers are succeeding or failing etc; the full keepalived logs entries from when keepalived starts and for at least 4 minutes after the _Unknown protocol_ log messages start appearing are what I need.

**Comment by pqarmitage** [comment]
It would be very helpful if you could execute the following:
  kill -USR1 $(ps -ef | grep "keepalived " | sed -e "s/^[^ ]* *//" | sort -n | head -1 | sed -e "s/ .*//")
and post the /tmp/keepalived.data /tmp/keepalived_check.data files.

**Comment by schoekek** [comment]
[Downloads.zip](https://github.com/acassen/keepalived/files/13938573/Downloads.zip)

**Comment by pqarmitage** [comment]
I can generate the issue if I use SNMP with keepalived, e.g. by running snmpwalk. Are you using SNMP?

**Comment by schoekek** [comment]
Yes, we use SNMP for monitoring.

**Comment by pqarmitage** [comment]
Commit cabe011 should resolve this issue. keepalived was calling _protocol_to_index()_ from various places when it shouldn't have been doing so; protocol_to_index() should only be called for virtual servers using a virtual server group which is using auto fwmarks.

I am fairly certain that in your case it was being triggered by the use of SNMP.
