### ISSUE TITLE
Repeating "AgentX session to master agent attempted to be re-opened." Warnings

### ISSUE THREAD

**Issue by kylebrandt** [acassen/keepalived#238]
In my logs I'm getting the following repeated:

```
Feb  3 02:45:48 ny-lselastic01 Keepalived_healthcheckers[31140]: AgentX session to master agent attempted to be re-opened.
Feb  3 02:45:48 ny-lselastic01 Keepalived_vrrp[31141]: AgentX session to master agent attempted to be re-opened.
Feb  3 02:45:48 ny-lselastic01 Keepalived_vrrp[31141]: AgentX session to master agent attempted to be re-opened.
Feb  3 02:46:03 ny-lselastic01 Keepalived_healthcheckers[31140]: AgentX session to master agent attempted to be re-opened.
Feb  3 02:46:03 ny-lselastic01 Keepalived_vrrp[31141]: AgentX session to master agent attempted to be re-opened.
Feb  3 02:46:03 ny-lselastic01 Keepalived_vrrp[31141]: AgentX session to master agent attempted to be re-opened.
```

I'm not sure what do to fix this. I do have `master agentx` in the snmpd config. In the changelog I did notice the following:

> "By default the Agent X master server is listening for MIB registrations on a local TCP socket with a port number of 705."

I don't anything listening on that TCP socket. I do have the following unix socket on the device:
```
s -l /var/agentx/master
srwxr-xr-x 1 root root 0 Feb  2 19:05 /var/agentx/master
```

But maybe that isn't related. Any advice on how to proceed, or is there more information I can provide?

```
keepalived --version
Keepalived v1.2.19 (11/09,2015)
```

```
 snmpd --version
NET-SNMP version:  5.7.2

```

Error string comes from https://github.com/winlibs/net-snmp/blob/master/agent/mibgroup/agentx/subagent.c#L832

**Comment by pqarmitage** [comment]
There have been a large number of changes to the SNMP code in the last couple of weeks or so, so if you are able to build the latest version available in the git repository, then you may well find that your issues are resolved (I certainly found that keepalived would attempt to register the same OID more than once, which might cause your problem).

To build with the traditional SNMP implementation, you need to specify _--enable-snmp_ to configure. If you also want the new RFC compliant SNMP code, also specify _--enable-snmp-rfc_.

The snmpd.conf file I am using has the following contents:
**rocommunity public**
**rwcommunity private**
**master agentx**

**trapcommunity public**
**trap2sink localhost:162**

The last two lines are for traps, in which case you would need to run snmptrapd too (see below for source of more information).

There are new global keywords that enable SNMP in addition to the existing keyword _enable-traps_ so that '-x' no longer needs to be specified to keepalived when it is run.
The keywords are:
_enable-snmp-keepalived
enable-snmp-checker
enable-snmp
enable-snmp-rfcv2
enable-snmp-rfcv3
enable-snmp-rfc_

_enable-snmp_ enables keepalived and checker, and _enable-snmp-rfc_ enables rfcv2 and rfcv3, so if you want to match the previous functionality specify _enable-snmp_. Specifying -x on the keepalived command line enables all SNMP options built into keepalived.

By default, agentx master listens on udp port 161, and you can check that with  _netstat -anp | grep snmp_. By default, keepalived will use the same.

Some more details of a working test setup are at the top of the source file _keepalived/vrrp/vrrp_snmp.c_.

If you are still having problems, a copy of your config file, snmpd.conf file, and the git commit you have built the code from, along with the build options as output by configure would be helpful.
