### ISSUE TITLE
v2.2.8: nopreempt is configured, the notify_xxx method will not be triggered.

### ISSUE THREAD

**Issue by wangyusheng1985** [acassen/keepalived#2392]
As title

**Comment by pqarmitage** [comment]
Please provide some information about your issue - there is nothing we can do based on just the title of this issue.

We need the following:
- keepalived configuration file from each system involved
- a description of what happens that makes you expect something to happen
- what happens when the event occurs
- what you expect to happen when the event occurs

Once we have the details we will investigate what is happening.

**Comment by pqarmitage** [comment]
I have tested this and when a VRRP instance changes state, the relevant notify scripts are executed at the appropriate times.

Closing due to no response for over 2 weeks and tests have not been able to identify any fault.
