### ISSUE TITLE
Code analysis: Buffer overflow at memcpy v2.2.8 libipvs.c

### ISSUE THREAD

**Issue by Aruise** [acassen/keepalived#2420]
Pointer 'get->entrytable[0]' in memcpy at libipvs.c:1262 is referencing to a memory that consists of 104 bytes, but svc has a size parameter that equals 224 bytes, which can cause a buffer overflow
'sizeof(get->entrytable[0])' instead might fix that

![изображение](https://github.com/acassen/keepalived/assets/47882486/1378554a-0724-43cf-9f79-afd7c0a61888)

keepalived v2.2.8

**Comment by pqarmitage** [comment]
@Aruise  Many thanks for reporting this. That code has been like that for the last 13 years, and then I changed it only last month (see commit 3a8ea5f).

As you have identified, memcpy()s are dangerous things, and when I was changing the code in ipvs_get_service() I changed it to:
`*svc = get->user.entrytable[0];`
so we can now rely on the compiler's type checking.
I don't think the memcpy() in v2.2.8 can simply be changed to the line of code above though, since I made some changes to various structs at the same time as making the above change.

Commit 3a8ea5f was first included in release v2.3.0, although v2.3.1 has one extra commit which has an impact if you are using the configure `--prefix=` option.

Reports like this are always welcome, so if you find any more such issues, please do report them.
