### ISSUE TITLE
VRRP_Script(redis_check) timed out

### ISSUE THREAD

**Issue by Biaoshi** [acassen/keepalived#2509]
I use VRRP_Scrips to check redis health. There is a "VRRP_Script(redis_check) timed out" in Keepalived log. but my program is listening redis server. It's normal. No exception.

**it is so strange. 
why the script wiould be timed out? and why the log is not be written? how can I fix them?**

The Os system version: CentOS Linux release 7.9.2009 (Core)
The  Architecture : x86_64

```
Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2

Copyright(C) 2001-2017 Alexandre Cassen, <[acassen@gmail.com](mailto:acassen@gmail.com)>

Build options:  PIPE2 LIBNL3 RTA_ENCAP RTA_EXPIRES RTA_PREF RTA_VIA FRA_OIFNAME FRA_SUPPRESS_PREFIXLEN FRA_TUN_ID RTAX_CC_ALGO RTAX_QUICKACK LIBIPTC LIBIPSET_DYNAMIC LVS LIBIPVS_NETLINK VRRP VRRP_AUTH VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC FIB_ROUTING INET6_ADDR_GEN_MODE SNMP_V3_FOR_V2 SNMP SNMP_KEEPALIVED SNMP_CHECKER SNMP_RFC SNMP_RFCV2 SNMP_RFCV3 SO_MARK
```

```
! Configuration File for keepalived

global_defs {
   script_user root root
   enable_script_security
   router_id redis01
   vrrp_garp_master_refresh 10
}

vrrp_script redis_check {
    script "/root/scripts/redis_check.sh 127.0.0.1 6379"
    interval 2
}

vrrp_instance VI_1 {
    state BACKUP
    nopreempt
    interface ens224
    virtual_router_id 249
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }

    virtual_ipaddress {
        10.190.5.249/24 dev ens224  
    }

    track_script {
        redis_check
    }
    notify_master "/root/scripts/redis_master.sh 10.190.5.217 6379"
    notify_backup "/root/scripts/redis_backup.sh 10.190.5.217 6379"
}
```

**Notify and track scripts**

redis_check.sh
```
#!/bin/bash
REDIS_CLI="/usr/local/bin/redis-cli"

FAIL_COUNT_FILE="/root/scripts/keepalived_fail_count"

if [ ! -f "$FAIL_COUNT_FILE" ]; then
  echo 0 > "$FAIL_COUNT_FILE"
fi

LOG_FILE="/root/scripts/check.txt"

ALIVE="`$REDIS_CLI -h $1 -p $2 -a CRRC_ATO_2023 PING`"

FAIL_COUNT=$(cat "$FAIL_COUNT_FILE")

current_date="`date +%Y%m%d_%H:%M:%S`"

echo "$current_date - [check]" >> $LOG_FILE

if [[ ${ALIVE} == "PONG" ]];then
  current_date1="`date +%Y%m%d_%H:%M:%S`"
  echo "$current_date1 - Success: redis-cli -h $1 -p $2 PING $ALIVE" >> $LOG_FILE
  echo 0 > "$FAIL_COUNT_FILE"
else
  current_date2="`date +%Y%m%d_%H:%M:%S`"
  echo "$current_date2 - Failed:redis-cli -h $1 -p $2 PING $ALIVE" >> $LOG_FILE
  ((FAIL_COUNT++))
  echo $FAIL_COUNT > "$FAIL_COUNT_FILE"
#  killall keepalived
#  exit 1
fi

if [ "$FAIL_COUNT" -ge 2 ]; then
  exit 1
else
  exit 0
fi

find $LOG_FILE -mtime +7 -name "*.*" -exec rm -rf {} \;
```

**System Log entries**
```
Nov 17 14:40:37 centos avahi-daemon[924]: Registering new address record for fe80::8237:f37a:990b:cd82 on ens192.*.
Nov 17 14:40:37 centos avahi-daemon[924]: Registering new address record for 10.190.13.116 on ens192.IPv4.
Nov 17 14:40:37 centos avahi-daemon[924]: Registering HINFO record with values 'X86_64'/'LINUX'.
Nov 17 14:40:38 centos Keepalived_vrrp[23758]: VRRP_Script(redis_check) timed out
Nov 17 14:40:38 centos Keepalived_vrrp[23758]: /root/scripts/redis_check.sh 127.0.0.1 6379 exited due to signal 15
Nov 17 14:40:38 centos Keepalived_vrrp[23758]: VRRP_Instance(VI_1) Entering FAULT STATE
Nov 17 14:40:38 centos Keepalived_vrrp[23758]: VRRP_Instance(VI_1) removing protocol VIPs.
Nov 17 14:40:38 centos avahi-daemon[924]: Withdrawing address record for 10.190.5.249 on ens224.
Nov 17 14:40:38 centos Keepalived_vrrp[23758]: VRRP_Instance(VI_1) Now in FAULT state
Nov 17 14:40:39 centos Keepalived_vrrp[23758]: VRRP_Script(redis_check) succeeded
Nov 17 14:40:39 centos Keepalived_vrrp[23758]: VRRP_Instance(VI_1) Entering BACKUP STATE
```

**Additional context**
In my own check.txt, there aren't any log about 5 seconds.
```
20241117_14:40:34 - [check]
20241117_14:40:34 - Success: redis-cli -h 127.0.0.1 -p 6379 PING PONG
20241117_14:40:39 - [check]
20241117_14:40:39 - Success: redis-cli -h 127.0.0.1 -p 6379 PING PONG
```

**Comment by pqarmitage** [comment]
There appear to be a couple of problems with your script, though that should not effect this issue:
1. The first time redis-cli returns "PONG" after there have been two or more PING failures, the script will exit with exit code 1 (you need to set `FAIL_COUNT=0` in the `if [[ ${ALIVE} == "PONG" ]];then` block.
2. The `find $LOG_FILE -mtime +7 ...` will never do anything since the script has just written to $LOG_FILE.
3. You appear to have included your redis password in the script above.

What is the timeout for the redis PING command? If it is longer that the keepalived script timeout, then I would except to see `VRRP_Script(redis_check) timed out` messages. At 14:40:37 there appear to have been some address changes happening on your system. Is it possible that that might have caused the redis PING command to be delayed completing?

Your keepalived configuration shows that the `redis_check` script should run every 2 seconds, but the output of the check.txt shows that there was a 5 second delay between 2 consecutive runs. Well it doesn't show that actually since `echo "$current_date - [check]" >> $LOG_FILE` isn't executed until AFTER the `redis-cli PING` command completes, and if keepalived timed out the script and sent it a SIGTERM (signal 15), there will be no entry for that run of `redis-check.sh` in your log file.

All the evidence you have provided suggests that there was a delay in the `redis-cli PING` command completing, and keepalived killed the script due to its script timeout expiring.

I suggest you move the following two lines:
```
current_date="`date +%Y%m%d_%H:%M:%S`"

echo "$current_date - [check]" >> $LOG_FILE
```
to be before the
```
ALIVE="`$REDIS_CLI -h $1 -p $2 -a CRRC_ATO_2023 PING`"
```
line.

You probably also want to consider the keepalived script timeout and the redis-cli PING timeout, and make sure that the keepalived script timeout is longer that the PING timeout.

**Comment by Biaoshi** [comment]
Thanks for your answer. I will check my script.
Regarding the third point in your answer, can you change your answer to hide my redis password? 

like This. 
> ```
> ALIVE="`$REDIS_CLI -h $1 -p $2 -a **** PING`"
> ```

Thank you!

**Comment by pqarmitage** [comment]
@Biaoshi I have made the edit as reqested, but you really should consider the password as compromised now.

**Comment by Biaoshi** [comment]
> @Biaoshi I have made the edit as reqested, but you really should consider the password as compromised now.

@pqarmitage 
Thank you for reminding me. I want to know, if multiple hosts have the same host name, will it also trigger VRRP_Script execution timeout?

**Comment by pqarmitage** [comment]
@Biaoshi It might depend what type of hostname you mean; on the other hand I don't think keepalived uses any form of hostname. There might be some knock on consequences where having duplicate hostnames does something strange that then causes an indirect problem for keepalived, but I really can't think what that might be. However, in general I would avoid duplicate hostnames just to play safe.
