### ISSUE TITLE
gap and gna help

### ISSUE THREAD

**Issue by Mixlining** [acassen/keepalived#2510]
Hello, I am confused about the official configuration documents during using keepalived.
If my config is:
```conf
vrrp_instance VI_1 {
    state BACKUP
    interface eth0
    virtual_router_id 51
    priority 90
    advert_int 1

    virtual_ipaddress {
        192.168.1.100 dev eth1
    }
}
```
then I config items like "vrrp_garp_*" and "vrrp_gna_*" .
The gna and garp will send via eth0 or eth1 ?
Can I specify the network interface for GARP and GNA packets?

**Comment by pqarmitage** [comment]
The `varp_gna_` configuration is not relevant since you are not using IPv6.

The GARP packets should be sent on eth1, since that it the interface that the VIP is configured on. There is no point in sending the GARP packets on any other interface, and indeed it would be wrong to do so.

If you need any further help with this, you will need to provide the following and we can then reopen this issue:

1. the output of `keepalived -v`
2. your full keepalived configuration
3. separate tcpdump packet traces on both eth0 and eth1 showing VRRP adverts and GARP messages.
