### ISSUE TITLE
Which are the known "stupid switches" that triggered the fix in version 1.2.10?

### ISSUE THREAD

**Issue by diego-maravankin** [acassen/keepalived#289]
Hello,

I'd like to know if there is a list of the "stupid" switches which cause the issue with the multicast handling. We've experienced a network outage, and our customer describes it as a "network loop", but we believe it could've been the issue described there.

We are running Keepalived version 1.2.9 (from Debian repositories).

Thanks!

Diego

**Comment by pqarmitage** [comment]
@diego-maravankin I'm not clear what you mean by "stupid" switches; could you please explain. Also, you refer to "the issue described there". Could you please provide a link to the description of the issue, so that we can understand what the problem is.

Any further description of the problem, and copies of configurations, would be helpful.

Please note that the latest version of keepalived is 1.2.20, and there have been very many fixes (and enhancements) since 1.2.9, and so upgrading to 1.2.20 might resolve your issues anyway.

**Comment by diego-maravankin** [comment]
@pqarmitage I meant the "stupid switches" mentioned in the Changelog:

> There are some stupid switches which does a special processing
	  to 224.0.0.0/8 multicast packets which causes packets drop from
	  queue overflows in environments which creates 100 and more
	  multicast control plane packets a second.

Apparently the issue we had was an actual network loop and not an issue with keepalived anyway, sorry I did not get back to you guys. 

Thanks for the reply. I will close this issue now.
