### ISSUE TITLE
Centos 6.2 make error 

### ISSUE THREAD

**Issue by dhpark21** [acassen/keepalived#294]
In file included from /usr/src/linux/include/linux/netfilter/x_tables.h:3,
                 from /usr/include/xtables.h:17,
                 from vrrp_iptables_calls.c:23:
/usr/src/linux/include/linux/kernel.h:733:2: warning: #warning Attempt to use kernel headers from user space, see http:
In file included from vrrp_iptables_calls.c:26:
/usr/include/linux/netfilter/xt_set.h:17: error: expected specifier-qualifier-list before ‘ip_set_id_t’
/usr/include/linux/netfilter/xt_set.h:41: error: expected specifier-qualifier-list before ‘ip_set_id_t’
make[2]: *** [vrrp_iptables_calls.o] Error 1
make[2]: Leaving directory `/home/admin/data/utils/KEEPALIVED/keepalived-1.2.20/keepalived/vrrp'
make[1]: *** [all] Error 1
make[1]: Leaving directory `/home/admin/data/utils/KEEPALIVED/keepalived-1.2.20/keepalived'

**Comment by pqarmitage** [comment]
There appears to be two issues here.

1. The kernel source internal headers are included in your include path, which is causing the #warning Attempt to use kernel headers from user space message. This should be resolved if you remove /usr/src/linux from your include path.

2. With kernels prior to 3.4, the ipset headers could not be included in userspace applications. Commit f11f2de adds a configure check to ensure that the ipset headers can be included, otherwise it disables ipset support.
