### ISSUE TITLE
1.2.19 - (temporal) loss of connectivity causes permanent multi-master (masters have same prio)

### ISSUE THREAD

**Issue by SjonHortensius** [acassen/keepalived#342]
I'm experiencing a very weird issue in keepalived 1.2.19. I'm interested if this is a known issue which would be fixed by upgrading to 1.2.20/21.

The problem is that after a network-disconnect I've had 5 completely separate clusters end up in multi-master. The strange thing is that they never recovered, although I can see the network traffic arriving just fine, the keepalived process seems to ignore it.

My config is ipv6 only (master and slave have exactly the same config except for the instance-name and unicast address):
```
vrrp_instance VI_1 {
	state BACKUP
	nopreempt
	interface eth0
	virtual_router_id 1
	priority 100
	smtp_alert
	native_ipv6

	track_script {
		check_mysqld
	}

	unicast_peer {
		2a02:xxxx:951
	}

	virtual_ipaddress {
		2a02:xxxx:1/128 dev eth0
	}
}
```

**slave**
```
vrrp_instance VI_2 {
    ...
	unicast_peer {
		2a02:xxxx:228
	}
}
```

When the network disconnected, my slave logged this, with nothing else following that (master logged nothing)
```
VRRP_Instance(VI_2) Transition to MASTER STATE
VRRP_Instance(VI_2) Entering MASTER STATE
2a02:xxxx:1 has a prefix length of 128, setting preferred_lft to 0
````

Currently they are still both master; with tcpdump showing both machines broadcasting and strace confirming it:

```
11:15:15.211800 IP6 2a02:xxx:951 > 2a02:xxx:228: ip-proto-112 24
11:15:15.212066 IP6 2a02:xxx:228 > 2a02:xxx:951: ip-proto-112 24
```

strace shows something interesting (I've removed the *gettimeofday* calls):
```
sendmsg(11, {msg_name(28)={sa_family=AF_INET6, sin6_port=htons(0), inet_pton(AF_INET6, "2a02:xxx:228", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, msg_iov(1)=[{"!\1d\1\0\1\0\0*\2#\10\0\0\0\0\0\0\f\233\362\21\0\1", 24}], msg_controllen=0, msg_flags=0}, 0) = 24
select(1024, [4 6 10], [], [], {0, 999860}) = 1 (in [10], left {0, 0})
recvfrom(10, "!\1d\1\0\1k\326*\2#\10\0\0\0\0\0\0\f\233\362\21\0\1", 1024, 0, {sa_family=AF_INET6, sin6_port=htons(0), inet_pton(AF_INET6, "2a02:xxx:228", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, [28]) = 24
select(1024, [4 6 10], [], [], {0, 342333}) = 0 (Timeout)
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f367a35ea10) = 21948
select(1024, [4 6 10], [], [], {0, 656122}) = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=21948, si_uid=0, si_status=0, si_utime=0, si_stime=0} ---
write(5, "\21\0\0\0", 4)                = 4
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
read(4, "\21\0\0\0", 4)                 = 4
wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], WNOHANG, NULL) = 21948
wait4(-1, 0x7ffe7d19d044, WNOHANG, NULL) = -1 ECHILD (No child processes)
read(4, 0x7ffe7d19d064, 4)              = -1 EAGAIN (Resource temporarily unavailable)
select(1024, [4 6 10], [], [], {0, 615169}) = 1 (in [10], left {0, 526})
recvfrom(10, "!\1d\1\0\1k\326*\2#\10\0\0\0\0\0\0\f\233\362\21\0\1", 1024, 0, {sa_family=AF_INET6, sin6_port=htons(0), inet_pton(AF_INET6, "2a02:xxx:228", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, [28]) = 24
select(1024, [4 6 10], [], [], {0, 0})  = 0 (Timeout)
select(1024, [4 6 10], [], [], {0, 999588}) = 1 (in [10], left {0, 242})
recvfrom(10, "!\1d\1\0\1k\326*\2#\10\0\0\0\0\0\0\f\233\362\21\0\1", 1024, 0, {sa_family=AF_INET6, sin6_port=htons(0), inet_pton(AF_INET6, "2a02:xxx:228", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, [28]) = 24
select(1024, [4 6 10], [], [], {0, 0})  = 0 (Timeout)
```

Is this a known issue, or can I help debug this further somehow?

**Comment by pqarmitage** [comment]
You state that master and slave have exactly the same config except instance name and unicast address. I take it that means that both instances are configured to have priority 100.

If the priorities are configured to be the same, then it is less clear which is the master, and which the slave (it comes down to comparing addresses, but off-hand I can't remember which addresses).

Can you try configuring the "slave" system to have a lower priority than the master, and report what happens in that case.

I'll try and see if I can reproduce this behaviour later to understand better what is happening.

**Comment by SjonHortensius** [comment]
Yes, they have the exact same priority. It this inadvisable? When everything functions normally, each instance would correctly detect the other master and decide to enter BACKUP state correctly.

The reason they have equal priority is because I don't want instances becoming MASTER automatically without me first manually inspecting if the database is still in sync after a failure.

**Comment by pqarmitage** [comment]
RFC 5798 states that if a master instance receives an advert of equal priority, then it will compare IP addresses, and if the IP address of the sender is greater than the local IP address, then the instance will transition to backup. Therefore, setting equal priorities will not force a master instance to stay as master.

The way to stop an instance taking over from another as master is to use nopreempt, which you alreay have configured.

I would suggest trying the two instances with different priorities to see if that resolves your problem, and if it does, it will give us a good pointer for investigating the underlying issue further.

**Comment by SjonHortensius** [comment]
Right, so it seems we could differentiate the priorities.

However, the current multi-master still shouldn't happen unless comparison of IPs is somehow broken, which we previously experienced which was fixed in https://github.com/acassen/keepalived/commit/c2a02264529f1f52ec22cb23dfc8903c776ee0cc. Is it possible this code has since been removed? Looking at https://github.com/acassen/keepalived/commit/b78122b7a4e4e1050245bb68031af6a91a302ae8, it seems we could have expected a message **Received higher prio advert**; which we didn't get

**Comment by SjonHortensius** [comment]
I've had to restart these machines, making this non-reproducible.

**Comment by pqarmitage** [comment]
@SjonHortensius I've now been able to reproduce this problem. I'm running the latest version of keepalived from git, so it is v1.2.21+.

The way I have reproduced the problem is by entering the following commands on each machine:
iptables -I INPUT -p 112 -j DROP
ip6tables -I INPUT -p 112 -j DROP 

I have two IPv4 instances and two IPv6 instances. After I enter the above commands all 4 instances become masters, as expected. After I delete the iptables/ip6tables entries, the IPv4 instances sort themselves out, and drop back to backup in one of the systems, but with the IPv6 instances neither system drops back to backup.

If you can reopen this issue, then we can continue tracking the problem though here; othersize would you like to open a new issue report.

**Comment by SjonHortensius** [comment]
Wow, that's great news; I didn't expect it to be this easy. TIA, excited to see if you can find the bug as well

**Comment by pqarmitage** [comment]
Update: this isn't just an IPv6 issue.

Sometimes an instance with a lower address will drop back to backup mode, sometimes it won't. Sometimes everything works as expected, sometimes none of the instances will drop back into backup mode, sometimes some instances behave correctly and others don't. More often than not the problem is with IPv6, but it can also happen with IPv4, but this might relate to my system which has a higher priority address for IPv6 (and lower priority for IPv4) is significantly slower that the other system.

More investigation needed.

**Comment by pqarmitage** [comment]
The problem was that when a master received an advert, when it checked if the advert priority was less than the priority of the local instance, it didn't also check if the priorities were equal and then if so compare the addresses. This meant that if a master received an equal priority advert from a remote master with a lower address, it didn't detect a lower priority advert and then force a new election. For some reason, the higher priority master, although still thinking it was master, would also stop sending adverts, and so the other system would not see a higher priority (by virtue of address) and hence it too would still think it was master.

The problem all depended on timing; if the lower address system received an advert first, it would drop back to backup mode, but if the higher address system received the advert first it would behave as described above.

**Comment by acassen** [comment]
Well done !

Thanks
