### ISSUE TITLE
I configure the keepalived in preept

### ISSUE THREAD

**Issue by s09816** [acassen/keepalived#347]

**Comment by s09816** [comment]
I configure the keepalived in preept mode，the client connect VIP by iscsi。i restart the keepalived on master node, the VIP one master node always.But,the arp entry of the client show that the MAC address corresponding  to the VIP is the backup node's MAC address. So the client can not ping VIP.


the version of keepalived is 1.2.7

**Comment by pqarmitage** [comment]
Have you specified use_vmac on the vrrp instance? If not, the situation you describe will always occur, and either the entry in the ARP table will need to be manually deleted, or allowed to time out.

Using vmacs causes the vrrp instance to use a virtual mac address (as is specified in the RFCs), and that virtual mac address moves with the virtual ip address, so it is always on the master, and more importantly that is MAC address that the client will use. The virtual MAC address will be of the form 00:00:5e:00:01:nn where nn is the virtual router id.

By the way, the version of keepalived is very old (nearly 4 years), and there have been in excess of 800 commits to the code since then in the subsequent 14 versions. You might find it better to update your version of keepalived to the latest version (currently 1.2.21).

**Comment by s09816** [comment]
I do not specify use_vmac on the vrrp instacnce.Why the other node do not connet the VIP can ping the VIP, adn the arp entry show that the MAC addr corresponding to the VIP is the master's MAC addr.Why the arp table of the client can not update when conneting to the VIP.

**Comment by pqarmitage** [comment]
The client discovered the MAC address for the VIP when the backup node was acting as master. When the master node comes back up it takes over the VIP, but since you do not specify use_vmac, the MAC address used by the master node is it's own MAC address, which of course is different from the backup node's MAC address. The client has cached the backup node's MAC address for the VIP, and so it is sending packets to the VIP to the backup node's MAC address, but the backup node no longer has the VIP, and so it won't respond.

Until the ARP entry in the ARP cache on the client times out, or the address is manually deleted, the client will continue sending packets to the VIP to the backup node's MAC address.

**Comment by acassen** [comment]
Last merge fix preempt pending preempt issue.
