### ISSUE TITLE
how many vips i can config?

### ISSUE THREAD

**Issue by s09816** [acassen/keepalived#368]
when I config 32 vips which on the same interface,the system reporting the following error.

Jun 25 19:11:09 cvknode94 kernel: [32803.637849] chbk: chbk_tcp_connect 2326: could not bind to socket 0x5e6910ac: -99
Jun 25 19:11:09 cvknode94 kernel: [32803.637865] chbk: chbk_connect_init 2729: create socket and connect to server fail: -99
Jun 25 19:11:39 cvknode94 kernel: [32833.741639] chbk: chbk_tcp_connect 2326: could not bind to socket 0x5e6910ac: -99
Jun 25 19:11:39 cvknode94 kernel: [32833.741661] chbk: chbk_connect_init 2729: create socket and connect to server fail: -99

**Comment by s09816** [comment]
this is my config which have 32 vrrp_instance. I only list part of it 
global_defs {
	router_id cvknode94
}

vrrp_script chk_tgtd {
	script "killall -0 tgtd"
	interval 2
	weight -100
	fall 2
	rise 2
}

vrrp_instance VI_43 {
	state BACKUP
	interface eth0
	virtual_router_id 43
	priority 240
	advert_int 1
	authentication {
	auth_type PASS
	auth_pass 1111
	}
	track_script {
	chk_tgtd
	}
	virtual_ipaddress {
	172.16.56.2/24
	}
}

vrrp_instance VI_44 {
	state BACKUP
	interface eth0
	virtual_router_id 44
	priority 240
	advert_int 1
	authentication {
	auth_type PASS
	auth_pass 1111
	}
	track_script {
	chk_tgtd
	}
	virtual_ipaddress {
	172.16.56.3/24
	}
}

vrrp_instance VI_45 {
	state BACKUP
	interface eth0
	virtual_router_id 45
	priority 240
	advert_int 1
	authentication {
	auth_type PASS
	auth_pass 1111
	}
	track_script {
	chk_tgtd
	}
	virtual_ipaddress {
	172.16.56.4/24
	}
}

**Comment by pqarmitage** [comment]
Do you have any idea what chbk is? I can't find it in the kernel sources, and a search on google doesn't produce anything.

**Comment by s09816** [comment]
I config so many VIPS. I want to know if another application will use these vip to setup tcp conneticon.
in my environment, sometimes when I ping the other node on the node which own vip, the source ip is the vip

**Comment by s09816** [comment]
chbk is our code, the following error is not related to keepalived.
Jun 25 19:11:09 cvknode94 kernel: [32803.637849] chbk: chbk_tcp_connect 2326: could not bind to socket 0x5e6910ac: -99
Jun 25 19:11:09 cvknode94 kernel: [32803.637865] chbk: chbk_connect_init 2729: create socket and connect to server fail: -99

**Comment by pqarmitage** [comment]
If you specify your virtual_ip_addresses with a /32 netmask rather than a /24, then it should pick up the real ip address as the source address rather than using one of the VIPs.

Could you try this and confirm whether this is the case.

**Comment by s09816** [comment]
according your description,I config virtual_ip_addressed with 32 netmask will be more appropriate

How to specify appropriate netmask, what is the rule?

**Comment by s09816** [comment]
when i config 32 vips, node1 connect 5 vips according iscsi,   I encounter a problem

keepalived work on preempt mode 

node1    node2   node3


first： 
32 vips take effect on node3

then
ifdown the interface of node3 and node2
32 vips take effect on node1

then 
ifup the interface of node3 and node2
32 vips take effect on node3
but node1 can not ping one of the vip on node3, the arp entry show the mac is node2's mac
node2 can ping all vips on node3

**Comment by pqarmitage** [comment]
The approach I take when configuring virtual IPs is that if the network already exists on the system, then when the vrrp instance becomes master we only want to add individual addresses, and so use /32 (or /128 for IPv6) netmask. If we are adding a new sub-net to the system, then we need to specify the sub-net mask appropriately for the network we are adding (although I think this situation would be relatively rare).

Some time ago I found using /32 rather than /24 made a lot of problems I was having disappear.

**Comment by pqarmitage** [comment]
In your original report, you referred to error messages from chbk, but in comment 5 you state the errors don't relate to keepalived. Can we ignore those error messages, and that would then just leave us with how many VIPs can be configured?

It would be really helpful if you could provide the full configurations for all three nodes, since it will save me constructing them, but also enable me to see what differences there are, such as priority. If you could zip them up into one file and attach the zip file that would probably be best.

**Comment by pqarmitage** [comment]
@s09816 I have taken your configuration and extended it to 128 VIPs and I am not seeing any problems with a similar setup with 3 nodes. This is with keepalived version 1.2.22.

The issue you describe is that the arp entry on node 1 for one of the vips is node 2, whereas it should be node 3.

I think we need the answers to the following questions to be able to understand this any further:
1. Is this problem is consistent across several tests, and is it always the same VIP?
2. Is it only 1 of the 32 VIPs that this problem occurs for?
3. When you have the problem check what addresses are still configured on eth0 on each of the three nodes.
4. If you wait long enough (e.g. 15 minutes) does the problem resolve itself?
5. What version of keepalived you are running

If you could provide the answers to the above questions, and also which VIP address has the problem, and provide copies of the full configurations from all 3 nodes along with the outputs of the following commands at a time when you have the ping/arp problem, then we might be able to see what is happening. The commands are:
ip addr show dev eth0
ip -s neighbour list

**Comment by pqarmitage** [comment]
I should have said in my previous comment that keepalived should have no limit on the number of VIPs that can be configured, and any limitation, if there is one, is likely to be a hard or soft limit of the kernel, or the amount of available memory on the system.

**Comment by s09816** [comment]
this problem can not be reproduced, it appear several times
question 1: the vip which can not be pinged  are not the same vip
important  another application setup the tcp connection by the vip which can not be pinged

question2:yes, it is only one vip occurs this problem

question4:the problem always exist when wait enough time, because another application setup the tcp connection by the vip

my version is 1.2.7

**Comment by s09816** [comment]
172.16.56.2 is the vip which can not be pinged

on node1 by netstat i can see the following record

172.16.56.92:2003    172.16.56.2:39226     ESTABLISHED  7596/python


I want to know how to prevent other application setuping tcp conneting by the vip

the linux interface connect()   how to choose local address when setup a tcp connection with remote

**Comment by pqarmitage** [comment]
After the call of socket(), call bind() before calling connect(). Specify the local IP address you want to be the source address to bind().
