### ISSUE TITLE
failed real server never make it back into VS

### ISSUE THREAD

**Issue by markrechler** [acassen/keepalived#373]
Running keepalived master, it seems that a failed server never gets added back into the VS:
```
Error connecting server [127.0.0.1]:8000.
Error connecting server [127.0.0.1]:8000.
Error connecting server [127.0.0.1]:8000.
Error connecting server [127.0.0.1]:8000.
Check on service [127.0.0.1]:8000 failed after 3 retry.
Removing service [127.0.0.1]:8000 from VS [172.16.207.249]:80
```
The test was downing the server and waiting until removed, then turning the server back on. I am noticing the health check come through in the server logs after turning it back on despite it not being added back. Sending a `HUP` no longer seems to restart health checks as it does in `1.2.13`.

Config:
```
global_defs {
   notification_email {
     none
   }
   notification_email_from nobody
   router_id dev.bitly.org
}


vrrp_instance BITLY_FE {
    interface eth0
    virtual_router_id 249
    nopreempt
    state BACKUP
    priority 50
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass xxxx
    }
    virtual_ipaddress {
        172.16.207.249/32 brd 172.16.207.255
    }
}


# dev test
virtual_server 172.16.207.249 80 {
    delay_loop 6
    lb_algo sh
    lb_kind DR
    persistence_timeout 120
    protocol TCP
    quorum 0

    # 127.0.0.1
    real_server 127.0.0.1 80 {
        weight 1
        HTTP_GET {
            url {
                path /internal/lb.ping
            }
            connect_timeout 3
            nb_get_retry 3
            delay_before_retry 3
        }
    }
    real_server 127.0.0.1 8000 {
        weight 1
        HTTP_GET {
            url {
                path /test.txt
            }
            connect_timeout 3
            nb_get_retry 3
            delay_before_retry 3
        }
    }

}
```

**Comment by pqarmitage** [comment]
When I send a HUP to the keepalived parent process, if I run kepalived with the -D option, I get the following log message:
Jun 27 20:00:40 samson1 Keepalived_healthcheckers[23567]: Got SIGHUP, reloading checker configuration

Can you check if you are seeing the same.

I think it may be the case that since 1.2.13 the reloading code has been improved so that new configuration is added, and entries no longer configured are removed, but any configuration that remains the same is left untouched.

The real issue here is that the real_servers are not added back after they come back up. I'll have a look at that later, probably tomorrow now. I do seem to remember another issue report mentioning the same thing, but that issue has since been closed.

**Comment by markrechler** [comment]
Thanks @pqarmitage!

I do see:
```
Got SIGHUP, reloading checker configuration
...
Activating healthchecker for service [127.0.0.1]:80
Activating healthchecker for service [127.0.0.1]:8000
```
Let me know if I can help test anything on this end.

**Comment by pqarmitage** [comment]
I've found the problem, and am putting together a patch to resolve it.

As a temporary workaround, if you add `status_code 200` within the URL blocks in the config (assuming 200 is the HTTP status code returned), then it should add the real servers back into the IPVS config.

**Comment by markrechler** [comment]
Everything looks good, thanks @pqarmitage.
