### ISSUE TITLE
Slow IPv6 failover

### ISSUE THREAD

**Issue by mwpastore** [acassen/keepalived#375]
It takes 30-45 seconds for traffic to an IPv6 address to move between nodes:

```
$ ping6 2600:3c02::14:effd
PING 2600:3c02::14:effd(2600:3c02::14:effd) 56 data bytes
64 bytes from 2600:3c02::14:effd: icmp_seq=1 ttl=64 time=0.603 ms
64 bytes from 2600:3c02::14:effd: icmp_seq=2 ttl=64 time=0.608 ms
64 bytes from 2600:3c02::14:effd: icmp_seq=3 ttl=64 time=0.650 ms
64 bytes from 2600:3c02::14:effd: icmp_seq=45 ttl=64 time=1.34 ms
64 bytes from 2600:3c02::14:effd: icmp_seq=46 ttl=64 time=0.630 ms
64 bytes from 2600:3c02::14:effd: icmp_seq=47 ttl=64 time=0.678 ms
```

I see the unsolicited NA being sent so I'm not sure why the changeover takes so long. IPv4 failover is nearly instantaneous. Is this a limitation of my hosting provider or is there configuration option that will hasten the transition?

#### master -> backup

```
Jul 03 08:38:10 atl-edge-000 Keepalived_vrrp[3441]: VRRP_Script(haproxy) failed
Jul 03 08:38:11 atl-edge-000 Keepalived_vrrp[3441]: VRRP_Instance(VI_1) Entering FAULT STATE
Jul 03 08:38:11 atl-edge-000 Keepalived_vrrp[3441]: VRRP_Instance(VI_1) removing protocol VIPs.
Jul 03 08:38:11 atl-edge-000 Keepalived_vrrp[3441]: VRRP_Instance(VI_1) Now in FAULT state
```

#### backup -> master

```
Jul 03 08:38:11 atl-edge-001 Keepalived_vrrp[3423]: VRRP_Instance(VI_1) Transition to MASTER STATE
Jul 03 08:38:12 atl-edge-001 Keepalived_vrrp[3423]: VRRP_Instance(VI_1) Entering MASTER STATE
Jul 03 08:38:12 atl-edge-001 Keepalived_vrrp[3423]: VRRP_Instance(VI_1) setting protocol VIPs.
Jul 03 08:38:12 atl-edge-001 Keepalived_vrrp[3423]: VRRP_Instance(VI_1) Sending gratuitous ARPs on eth0 for 50.116.37.219
Jul 03 08:38:12 atl-edge-001 Keepalived_vrrp[3423]: VRRP_Instance(VI_1) Sending Unsolicited Neighbour Adverts on eth0 for 2600:3c02::14:effd
Jul 03 08:38:12 atl-edge-001 Keepalived_vrrp[3423]: Netlink reflector reports IP 2600:3c02::14:effd added
```

#### keepalived.conf

```
global_defs {
  router_id atl-edge-001-priv
}

vrrp_script haproxy {
  script "systemctl is-active haproxy.service"
  interval 2 # check every two seconds
  fall 2 # require two failures for KO
  rise 2 # require two successes for OK
}

vrrp_instance VI_1 {
  state MASTER
  interface eth0
  smtp_alert
  virtual_router_id 51
  priority 100
  advert_int 1
  authentication {
    auth_type PASS
    auth_pass xxxxxxxx
  }
  virtual_ipaddress {
    50.116.37.219/24 dev eth0 label eth0:1
    2600:3c02::14:effd/116 dev eth0 scope global
  }
  unicast_src_ip 192.168.129.234
  unicast_peer {
    192.168.204.58
  }
  track_script {
    haproxy
  }
}
```

(router_id is atl-edge-000-priv on the other node and the unicast addresses are reversed)

#### System

* Keepalived v1.2.19 (08/15,2015)
* Linux 4.5.5-x86_64
* Ubuntu Server 16.04 LTS (Xenial)

**Comment by pqarmitage** [comment]
It isn't valid to have a mixture of IPv4 and IPv6 addresses as virtual ip addresses. If using VRRPv3 either all addresses (including unicast and multicast addresses for source and destination address) must be IPv4 or all addresses must be IPv6; if using VRRPv2, all addresses must be IPv4. There is no way to indicate that one address is IPv4 and another is IPv6; the address type is determined by the IP packet type.

Up to v1.2.19, due to a bug in the code, received packets didn't get rejected for having an incorrect number of addresses, nor was there a check that there wasn't a mixture of addresses; addresses of the wrong family were silently dropped from the VRRP advertisements.

Version 1.2.20 corrected those issues, and it now rejects configuration with mixed IP address families. When making the changes to stop mixed address families, I didn't investigate fully the consequences of what might happen with mixed addresses, I just fixed the code, so I can't say if what you are seeing is caused by having mixed address families.

There are two ways you can alter your configuration to be compliant:
1) Configure the IPv6 address in a virtual_ipaddress_excluded block
2) Add a second vrrp_instance and move the IPv6 address into that, but you will also need IPv6 addresses for the unicast_src and unicast_peer items.

I would recommend upgrading to Keepalived v1.2.22 (or better still the latest version from the git repo) and testing again to see if the issues (i.e. this and #376) are resolved. There are a huge number of fixes and improvements that have been applied to the code since v1.2.19.

If you could upgrade to the latest version of keepalived and update your configuration, and then  confirm whether this and issue #376 are resolved or not, we will investigate further if the problems persist.

**Comment by mwpastore** [comment]
@pqarmitage Thanks! I moved the IPv6 address to a virtual_ipaddress_excluded block. Unfortunately, neither issue resolved after this change (but at least the current behavior was preserved). I then cloned the repo and built and installed master to /usr/local. This resolved issue #376, but it's still taking 30-45 seconds for the traffic to move over to the other node (which is the more urgent issue). Any other suggestions?

**Comment by pqarmitage** [comment]
Are the unicast_src_ip and unicast_peer addresses on different subnets, and if so, is there routing involved between the two hosts? If so, how is the routing updated for the virtual IPs?

A description of your architecture and the connectivity between your two systems would be helpful. Also, what are the subnet masks for the 192.168.129.234 and 192.168.204.58 addresses, and what interfaces on the systems do they belong to (e.g. eth0)?

**Comment by mwpastore** [comment]
They're both on the same subnet, 192.168.128.0/17, and as far as I know there's no routing in between them (traceroute shows a single hop). These are two virtual private servers in Linode's Atlanta datacenter, and I have a /116 pool of IPv6 addresses that routes to both servers. You can read more about it [here](https://www.linode.com/docs/networking/native-ipv6-networking/#ipv6-neighbor-discovery).

Let me clarify the problem a bit. The backup sees the state change and adds the IP address(es) right away, so the VRRP packet/frame is coming through without any issues. I see the unsolicited NA packet being sent out from the backup right away as well. It's just that traffic from a third server to the VIP is interrupted for 30-45 seconds after all this happens.

**Comment by pqarmitage** [comment]
This sounds to me as though the unsolicited NA packet isn't reaching your third server.

While the backup is taking over as master, and while pinging the virtual IPv6 address, could you also monitor the IPv6 neighbour table on the third server with something like `while [ 1 ]; do ip neigh show 2600:3c02::14:effd; sleep 1; done` and see if the ping starting to work again corresponds with the entry changing in the ip neighbour table. It might be that the Linode architecture doesn't forward the unsolicited NA to your other servers.

I note in the Linode document you provided a link to above, it says "In order to take advantage of neighbor discovery you must configure your Linode to be a router using net.ipv6.conf.default.forwarding." Can you check that that is set; if not it may be the cause of the unsolicited NA not reaching the third server.

A second thing to try would be to use vmacs so that there is a virtual mac address, and then the ip neighbour entry on the third server won't need to change. To use a vmac, add `use_vmac` to the vrrp_instance configuration on both servers, and remove the unicast_peer and unicast_src entries. Whether this will work or not depends on how Linode have configured their environment, and to what extent they allow multicasting.

**Comment by mwpastore** [comment]
Thank you so much for your help troubleshooting this. I know we're getting into territory where I should really be working with the Linode folks (and in fact I have a ticket open with them) but this is arming me with some great information. And I'm learning a ton in the process!

Here's the `ip neigh` output from the third server, with notes in brackets:

```
2600:3c02::14:effd dev eth0 lladdr f2:3c:91:9b:73:c1 router STALE [repeating inf; pinging]
<-- stop haproxy on MASTER
2600:3c02::14:effd dev eth0 lladdr f2:3c:91:9b:73:c1 router DELAY [repeating 5x; not pinging] 
2600:3c02::14:effd dev eth0 lladdr f2:3c:91:9b:73:c1 router REACHABLE [repeating 14x; not pinging]
2600:3c02::14:effd dev eth0 lladdr f2:3c:91:9b:73:c1 router DELAY [repeating 5x; not pinging]
2600:3c02::14:effd dev eth0 lladdr f2:3c:91:9b:73:c1 router PROBE [repeating 3x; not pinging]
2600:3c02::14:effd dev eth0  router FAILED [not repeating; not pinging]
2600:3c02::14:effd dev eth0 lladdr f2:3c:91:55:ae:92 router REACHABLE [repeating inf; pinging]
```

> It might be that the Linode architecture doesn't forward the unsolicited NA to your other servers.

This appears to be the case. 😞 

> I note in the Linode document you provided a link to above, it says "In order to take advantage of neighbor discovery you must configure your Linode to be a router using net.ipv6.conf.default.forwarding." 

I think that is specific to the /56 and /64 address pools, whereas I have a /116 address pool. Regardless, I tried setting `net.ipv6.conf.default.forwarding` (and `net.ipv6.conf.eth0.forwarding`) to `1` on all three servers and it had no affect on the above-documented behavior. 

I'll reconfigure for multicast and try a vmac...

**Comment by mwpastore** [comment]
Well, that was a bust. Here are the choice responses from Linode support:

> Our network is not set up to support multicast IPv6 from within an individual Linode

So much for that idea...

> Your Linode has a unique MAC address that is set when it's created. You wouldn't be able to change it, in most cases. However, if you are creating a virtual machine within your Linode, you may be able to set the MAC address as you would like. 

What?! Anyway, keepalived assigned an IP address from the pool to a virtual MAC but it never became reachable from any other servers, so it would appear that this is not supported within Linode.

> the delay that you're seeing is not entirely unexpected due to the way that the /116 is routed within our network

I'm probably stuck with the 30-45 second delay, then, unless Linode makes other changes to their infrastructure. Actually, the delay is much longer from outside of Linode's datacenter, rendering this solution basically unusable. At any rate, it's no fault of keepalived's. Thank you for the help!

**Comment by pqarmitage** [comment]
Here's another idea, but I don't know if this would work.

You could try using a vmac, but with unicast_src and unicast_peer. It's not something I've ever tried, but it might just work.

**Comment by mwpastore** [comment]
I definitely tried that yesterday, and again just now. There are two problems: Node B never seems to get the unicast packets from Node A (or vice-versa); in other words, both think they are MASTER. Secondly, even if I disable keepalived on one of the two nodes, the VIP bound to the VMAC is not reachable from any other hosts.
