### ISSUE TITLE
VIPs remain if removed from config and keepalived reloaded

### ISSUE THREAD

**Issue by DStape** [acassen/keepalived#382]
clear_diff_vrrp_vip_list() is the function that goes on to remove stale VIPs (VIPs that were present in the previous version of the config, but have since been removed). However, this function is never being called and as a result, stale VIPs remain configured on the interface. This is easy to reproduce, simply set up one vrrp group with 2 VIPs, then remove one of those VIPs and reload keepalived. The VIP that was removed will still be present on the interface.

clear_diff_vrrp_vip_list() is only ever called from within the clear_diff_vrrp_vip(0 function within vrrp.c:
```bash
$ git grep -n clear_diff_vrrp_vip_list                                                                                                             
keepalived/vrrp/vrrp.c:2478:clear_diff_vrrp_vip_list(vrrp_t *vrrp, struct ipt_handle* h, list l, list n)
keepalived/vrrp/vrrp.c:2510:            clear_diff_vrrp_vip_list(vrrp, h, old_vrrp->vip, vrrp->vip);
keepalived/vrrp/vrrp.c:2511:            clear_diff_vrrp_vip_list(vrrp, h, old_vrrp->evip, vrrp->evip);
```
However, before this gets called, there's a check for old_vrrp->iptable_rules_set. If this is not set, then clear_diff_vrrp_vip_list() never gets called.

As far as I can tell, iptable_rules_set will always be false:
```bash
$ git grep -n iptable_rules_set
keepalived/include/vrrp.h:198:  bool                    iptable_rules_set;      /* Iptable drop rules set to VIP list ? */
keepalived/vrrp/vrrp.c:134:             vrrp->iptable_rules_set = (cmd == IPADDRESS_ADD);
keepalived/vrrp/vrrp.c:2489:            vrrp->iptable_rules_set = false;
keepalived/vrrp/vrrp.c:2491:            vrrp->iptable_rules_set = true;
keepalived/vrrp/vrrp.c:2503:    if (!old_vrrp->iptable_rules_set)
```
It's value is only ever updated in 3 locations (all functions within vrrp.c):

vrrp_handle_accept_mode() - accept mode not configured so this function is never entered
clear_diff_vrrp_vip_list() (twice in here inside both if/else clauses) - the function we want to call but never do!

After removing the check for old_vrrp->iptable_rules_set, everything works as expected again:

```bash
diff --git a/keepalived/vrrp/vrrp.c b/keepalived/vrrp/vrrp.c
index f5fda3f..88f19a1 100644
--- a/keepalived/vrrp/vrrp.c
+++ b/keepalived/vrrp/vrrp.c
@@ -2500,9 +2500,9 @@ clear_diff_vrrp_vip(vrrp_t *old_vrrp, vrrp_t *vrrp)
 #endif
        struct ipt_handle *h = NULL;
-       if (!old_vrrp->iptable_rules_set)
-               return;
-
```
I'd put a PR out to remove this, but I don't fully understand why this was added. A git blame reveals that code was added in commit d3463c27, however the associated log message talks about adding the ability to use libiptc, so it's not clear to me why that check was added. Especially since removing it fixes the problem.

@pqarmitage , do you recall why this was added? Thanks.

**Comment by pqarmitage** [comment]
@DStape asks why the test `if (!old_vrrp->iptables_rules_set)` was added.

It looks to me as though it was retained from line 2054 of the code before the patch, as shown in commit d3463c2, but I agree that the test is wrong, since the VIPs are now removed after that test, whereas they were removed before it.

I think removing the test will not cause any problems, since in clear_diff_address() it checks whether an address is set prior to removing it. However, the comparison of the old and new lists of VIPs/eVIPs is order n^2, and so should be avoided if possible. A reasonable alternative test would be `if (!old_vrrp->vipset)` , since there will be no addresses to remove if the VIPs aren't set. @DStape do you agree with that, and if so are you in a position to test it?

You also state that you think iptables_rules_set will always be false. My understanding of the code is that `vrrp_handle_accept_mode()` is called regardless of whether accept_mode is configured or not, and that the function will only do anything if accept_mode is NOT configured on the specific VRRP instance (it might be better if the function were called `vrrp_handle_not_accept_mode()`). If accept_mode is not set, then iptables_rules_set will be set at line 134 (based on the grep output above) of vrrp.c if vrrp_handle_accept_mode() is called with cmd == IPADDRESS_ADD. Do you agree with this analysis? If not, then I will need to recheck the code to make sure it is doing what is needed.

While thinking about this issue, another problem has occurred to me. If an address is moved from being an eVIP to a VIP, then on reload keepalived will first attempt to add it since it is a new VIP, which will fail since it will already exist due to being an eVIP, but then it will be removed, since it will no longer exist in the eVIP list. The comparision of old and new addresses needs to consider the VIPs and eVIPs on a VRRP instance as a single list for this purpose.

I will test the change of `if (!old_vrrp->iptables_rules_set)` to `if (!old_vrrp->vipset)` this evening, and if it works, I'll submit a patch for it.

Another thought that has just occurred, and I'll need to look into this later, is does the code correctly handle accept_mode being changed on a vrrp instance when a reload occurs. This is also pertinent if accept_mode is changed via snmp.

**Comment by DStape** [comment]
@pqarmitage, thank you for making the PR. I will test out the code with your merged commit at some point today and will close this ticket if I can no longer reproduce. Thanks again.

**Comment by DStape** [comment]
Looks good to me, thanks @pqarmitage . Closing.
