### ISSUE TITLE
Add a parameter to test/check configuration file

### ISSUE THREAD

**Issue by kustodian** [acassen/keepalived#389]
Keepalived has many awesome features, but thing that is missing is the ability to check if the configuration file has a good syntax, before you reload the new configuration. Is there a reason why keepalived doesn't have a configuration test/check parameter?

**Comment by pqarmitage** [comment]
The commits in pull request #413 take a slightly different approach to that set out above.

The new script test/netns-test.sh will set up an environment that mirrors the main system configuration, but in a separate network namespace (default test). keepalived can then be run in that namespace and it will load and run the configuration, which will not only test the configuration file for valid syntax, but also ensure that it can be run (e.g. interfaces and addresses exist).

Execute `test/netns-test.sh -f CONFIG_FILE` to setup the test network namespace, and then run keepalived adding the option `-s test` to run keepalived in the test namespace (the netns-test.sh script outputs the details of how to run keepalived and how to delete the namespace).

Testing the configuration this way not only tests that the syntax is valid, but also that the configuration is runnable, e.g. specifying `interface eth00` for a vrrp instance would be correct syntax, but the configuration wouldn't work if it should be been eth0.

**Comment by pqarmitage** [comment]
Closing due to no reply for over 1 month.

**Comment by kustodian** [comment]
Sorry, but it's a little strange that you close an issue which isn't replied to, but it's also not resolved? It's fine to close it if you think that #413 solves this issue, but it doesn't make sense to close an issue because the reporter didn't respond in a month?

Even though #413 is awesome, it doesn't solves this issue, because what keepalived is missing is to tell you if some configuration parameter is wrong, missing, or whatever, or even what changed on reload. Currently you can write almost anything in the configuration file and if keepalived doesn't recognize it, it will silently ignore it. Currently the only way to see what keepalived actually parsed is to add `-d` parameter and read the log, or to test if what you set is currently working.

**Comment by pqarmitage** [comment]
I clearly misinterpreted what it was you wanted; I thought you wanted a way to run your configuration without it affecting a live environment, whereas I now realise that you asking for the parser to be fixed so that it reports all configuration errors.

It is well known that the keepalived parser will, so far as we know, correctly parse correct configuration, but it can fail to detect invalid configuration, and can segfault.

I think what you are after is the parser sorted out to report any error, and an option for keepalived to check a configuration and report any errors without loading the configuration. One complication is that the validity of a configuration depends in part on the configuration of the system itself, such as interfaces and addresses configured on the interfaces.

A number of us would like to improve the parser, but to do it properly is a very big job. I have a few ideas, in particular to try and make it more table driven rather than procedure driven, but I haven't completed the idea of quite how to do it in my mind.

What it really needs is a volunteer to work on sorting out the parser.

Commit be7ae80 (which was first included in v1.3.0) seeks to stop segfaults (or other random symptoms) occurring in the parser when a required parameter is omitted, and I hope this is a big step forward in improving the parser. Earlier commit 1807bcb started logging errors for unknown keywords, but was a bit over zealous, and this was resolved in commits 41fec00 and 584ff2b. So far as I am aware, the parser now correctly reports unknown keywords, and will not segfault if there are missing parameters etc. If you find specific examples of configuration that can cause parser problems in v1.3.0 onwards, then please do report them so that they can be invertigated. 

I do think that closing an issue one month after a potential solution has been offered and there has been no response for a month is reasonable. If we didn't do that, we'd have a very long list of open issues, most of which would no longer be relevant, and we wouldn't be able to see the wood for the trees.

**Comment by rohara** [comment]
I've been trying to find time to look more closely at the parser, too. There are a few things I'd like to fix:

1. Identify and report errors for configuration options and require value(s) but are absent. I think Quentin did some work on this recently.
2. Identify keywords that are out of context. Most keywords only make sense in a particular section of the config file, anywhere else should be an error.
3. Be a bit more relaxed about case-sensitivity (eg. "protocol TCP" should work as well as "protocol tcp").
4. Be consistent about when and where quotations are needed/required around strings.

Note that libmultipath (part of dm-multipath) has been using, and improving upon, the keepalived parser code for years. Might be worth a peek.

**Comment by k0ste** [comment]
Why this closed? Actually keepalived still not have "dry run" function.

**Comment by yakatz** [comment]
Here is an example of something that should be caught by a config test:
If you have two VRRP instances with the same VRID, right now the only way to know is to start the service and have it not start up.

> May 23 13:31:17 haproxy01 Keepalived[12259]: Starting Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2
> May 23 13:31:17 haproxy01 Keepalived[12259]: Opening file '/etc/keepalived/keepalived.conf'.
> May 23 13:31:17 haproxy01 Keepalived[12260]: Starting Healthcheck child process, pid=12261
> May 23 13:31:17 haproxy01 Keepalived[12260]: Starting VRRP child process, pid=12262
> May 23 13:31:17 haproxy01 Keepalived_vrrp[12262]: Registering Kernel netlink reflector
> May 23 13:31:17 haproxy01 Keepalived_vrrp[12262]: Registering Kernel netlink command channel
> May 23 13:31:17 haproxy01 Keepalived_vrrp[12262]: Registering gratuitous ARP shared channel
> May 23 13:31:17 haproxy01 Keepalived_vrrp[12262]: Opening file '/etc/keepalived/keepalived.conf'.
> May 23 13:31:17 haproxy01 Keepalived_vrrp[12262]: VRID 26 is duplicated on interface em1
> May 23 13:31:18 haproxy01 Keepalived_vrrp[12262]: Stopped
> May 23 13:31:18 haproxy01 Keepalived[12260]: Keepalived_vrrp exited with permanent error CONFIG. Terminating
> May 23 13:31:18 haproxy01 Keepalived[12260]: Stopping
> May 23 13:31:23 haproxy01 Keepalived[12260]: Stopped Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2

We manage our configuration using Puppet. Sometimes someone adds a duplicate VRID in Puppet which means next time Puppet runs, it takes down all our servers since it can't check to make sure the configuration is valid before it restarts `keepalived`.

**Comment by corywright** [comment]
I'd like to add my name to the list of people who would like to see this functionality available in keepalived. We don't want our configuration management system trying to reload/restart keepalived if the config file is invalid.

This is a [common feature of many daemons](http://www.configapp.com/post/2018/01/09/configuration-file-validation-check/).

**Comment by pqarmitage** [comment]
While it may be possible to partially implement this, it is not possible to know that a configuration is fully valid without actually loading it, since some configuration errors are detected by the kernel. e.g. when routes are added.

I do see that some validation is beneficial, but what sort of reaction will we get if a config test passes, but the configuration subsequently fails to load due to an error that can only be detected by attempting to install the configuration?

**Comment by yakatz** [comment]
While you do have to draw the line somewhere, anything that causes keepalived to exit by itself (like in my example: "VRID 26 is duplicated on interface em1") should definitely be detectable.

**Comment by corywright** [comment]
@pqarmitage I'm agree with @yakatz, we simply need something basic. 

For example, HAproxy's config check verifies the syntax and that options are used in the correct context (frontend vs backend, tcp vs http mode, etc), but it doesn't check if an IP that is bound to is available on the server. This is acceptable for us as we are more concerned about the validity of the config file, which is prone to human error.

**Comment by agustincastanio** [comment]
+1

**Comment by yakatz** [comment]
I think a return code change would be important. The same way you can't rely on users to read the config file (so you need to be able to validate it), you can't rely on users to check the logs.

The return code would also be important for tools like puppet that can roll back to the old configuration if the check command returns a non-zero value.

**Comment by k0ste** [comment]
Yes, return code should be non-zero, this is also important for Ansible template validation.

**Comment by kustodian** [comment]
Agreed, without a return code, it's hard to use this with configuration management tools.

**Comment by pqarmitage** [comment]
Keepalived now exits with exit code 1 if it would fail to run the configuration.

keepalived tries to work around configuration errors, and most errors cause warnings rather than cause keepalived not to run. If there are warnings but non-fatal errors, keepalived will exit with exit code 0, since it would execute the configuration.

**Comment by pqarmitage** [comment]
Closing since no adverse comments for a week (and two thumbs up!).

**Comment by pqarmitage** [comment]
@kustodian @iDemonix @bjhaid @sebschrader @zed-0xff @tshak @corywright @yakatz @sander85 @agustincastanio @fliphess You all indicated some interest in this issue. Issue #955 has raised further issues with the implementation of the '-t'/--config-test' option, in particular saying the output should be written to stderr, and that keepalived should exit with a non-zero exit code for any configuration error.

I am proposing the following changes to the `-t`/`--config-test` option:
1. Output is written by default to stderr, rather than /tmp/keepalived.conf-check. The output file can still be specified as an optional parameter to the `-t`/`--config-test` option.
2. When using the `-t`/`--config-test` keepalived will exit with status 0 if there are no configuration errors, 3 if the configuration is not loadabled, 4 if the configuration could be loaded but there are errors, and 5 if scripts are configured but script security is not enabled.

Does anyone have any concerns with these changes?
