### ISSUE TITLE
Curious about passing variable arguments in MISC_CHECK path

### ISSUE THREAD

**Issue by chines** [acassen/keepalived#407]
Hello,

The company I work for has recently began migrating several load balancers from ldirectord to keepalived and so far are very happy with it.  One of the things that's come up recently is if the MISC_CHECK script argument could have a variable argument placed on the command line that would represent the real_server IP address.  This would make maintaining the health checks a bit simpler.  

To illustrate:
# Current real_server block with MISC_CHECK

```
    real_server 10.1.18.98 443 {
            MISC_CHECK {
                    misc_path "/etc/keepalived/healthchecks/oasis_healthchk qflgnvwebu0 98"
                    misc_timeout 2
                    }
            }
```
# With desired updates -- real_server block with MISC_CHECK

```
    real_server 10.1.18.98 443 {
            MISC_CHECK {
                    misc_path "/etc/keepalived/healthchecks/oasis_healthchk $real_server $port"
                    misc_timeout 2
                    }
            }
```

I'm not very skilled at coding but would be willing to try making a patch if I had some guidance.  I looked at the source and it appears that the real_server ip is being added to the logs, so I'm curious if it would be difficult to search and replace it in the MISC_CHECK misc_path?

**Comment by pqarmitage** [comment]
I'm a bit confused by your example. From what you have provided, I would have expected
`misc_path "/etc/keepalived/healthchecks/oasis_healthchk $real_server $port"`
to become
`misc_path "/etc/keepalived/healthchecks/oasis_healthchk 10.1.18.98 443"`
I don't understand where `qflgnvwebu0` and `98` come from.

I think I would refer `$ip` rather than `$real_server`, since I think it is the IP address that you want to substitute first (keepalived uses ip addresses rather than hostnames, since it is working at too low a level and DNS lookups can cause delays).

The function where you would need to make the change is misc_path_handler() in keepalived/check/check_misc.c.

I think you would need to handle a special case of "$$" which get converted to "$", as well as the specific substitutions you need.

It would be good to generalise the change so that it could be used for other configuration lines as well. Perhaps have a function `replace_parameters()` which is not only passed CHECKER_VALUE_STRING(strvec) but also an array with the expansions, e.g.
```
misc_path_subst[] = {
    { "ip", rs->addr, format_addr },
    { "port", rs->addr, format_port}
};
```

where format_addr() and format_port() are functions that are passed rs->addr so they can replace the '$ip' in the string with the formatted ip address.

You would need a statement like
`virtual_server_t *rs = LIST_TAIL_DATA(LIST_TAIL_DATA(check_data->vs)->rs);`
to find the real_server data currently being configured.

The replace_parameters() function could then return a pointer to some MALLOC()'d memory that has the modified string.

**Comment by pqarmitage** [comment]
Closing since no response for over a year.

**Comment by pqarmitage** [comment]
@chines I have now implemented a more generic solution to what you suggested above for $real_server, etc, in the form of replaceable parameters.

What you suggested can now be implemented as:
```
$real_server=10.1.18.98
$port=443
    real_server $real_server $port {
            MISC_CHECK {
                    misc_path "/etc/keepalived/healthchecks/oasis_healthchk $real_server $port"
                    misc_timeout 2
                    }
            }
```

Using this approach means that we don't have to handle specific parameters for each type of configuration block.
