### ISSUE TITLE
Recommended "dev" packages to install before compilation

### ISSUE THREAD

**Issue by tersmitten** [acassen/keepalived#424]
Is there any reason why I want to compile `keepalived` with the following packages installed?

- libnl-3-dev
- libnl-genl-3-dev
- libnl-route-3-dev
- libnfnetlink-dev

Or maybe even more?

**Comment by pqarmitage** [comment]
libnl-3 is used to get information about the interfaces
netfilter netlink is used for creating vmac interfaces, adding and removing ip addresses, routes, rules etc.

If you want to see where they are called, you could uninstall the development libraries after running configure, and see where you get linker failures.

**Comment by tersmitten** [comment]
Thanks for the explanation, but are there any "dev" packages that I need for performance, stability or extra functionality (except snmp, debugging)?

**Comment by pqarmitage** [comment]
The libnl-3 libraries are to be preferred over libnl-1 since maintenance of libnl-1 is limited and most new functionality is not added to libnl-1.

libiptc and libipset will certainly give performance enhancements.

libglib2.0-dev will allow building with DBus support (this has only been added to github today).

The crypto library is needed for SHA1 support.

Other than that, most of the conditional compilation is based on what your kernel supports and what glibc supports.

**Comment by tersmitten** [comment]
Thanks
