### ISSUE TITLE
Keepalived_vrrp exited due to segmentation fault (SIGSEGV).

### ISSUE THREAD

**Issue by sosogh** [acassen/keepalived#428]
If i config "debug" in  vrrp_instance{} , keepalive will crash with these logs 
-------------------------------------------------------------------------------------

Sep 20 17:34:12 myserver kernel: [  852.791478] Core dump to |/usr/share/apport/apport 16503 11 0 16503 pipe failed
Sep 20 17:34:12 myserver kernel: [  852.831468] keepalived[16505]: segfault at 1000074 ip 00007f9f9e1d7467 sp 00007ffe33e0ecb0 error 4 in libc-2.19.so[7f9f9e19a000+1ba000]
Sep 20 17:34:12 myserver kernel: [  852.831510] Core dump to |/usr/share/apport/apport 16505 11 0 16505 pipe failed

Sep 20 17:34:13 myserver Keepalived[15979]: Starting VRRP child process, pid=16529
Sep 20 17:34:13 myserver kernel: [  853.295473] Core dump to |/usr/share/apport/apport 16529 11 0 16529 pipe failed
Sep 20 17:34:13 myserver Keepalived[15979]: pid 16529 exited due to segmentation fault (SIGSEGV).
Sep 20 17:34:13 myserver Keepalived[15979]:   Please report a bug at https://github.com/acassen/keepalived/issues
Sep 20 17:34:13 myserver Keepalived[15979]:   and include this log from when keepalived started, what happened
Sep 20 17:34:13 myserver Keepalived[15979]:   immediately before the crash, and your configuration file.
Sep 20 17:34:13 myserver Keepalived[15979]: VRRP child process(16529) died: Respawning

If I remove "debug" in  vrrp_instance{} , there are only a few logs:
---------------------------------------------------------------------------

Sep 20 17:41:48 myserver Keepalived[16724]: Starting Keepalived v1.2.24 (09/20,2016)
Sep 20 17:41:48 myserver Keepalived[16724]: Opening file '/etc/keepalived/keepalived.conf'.
Sep 20 17:41:48 myserver Keepalived[16725]: Starting Healthcheck child process, pid=16727
Sep 20 17:41:48 myserver Keepalived[16725]: Starting VRRP child process, pid=16728

and it seems that virtual_ipaddresses are config correctly , the virtual_ipaddresses  are pingable.

This is the config
------------------- 

> 

global_defs {
   notification_email {
    zha@a.com                     
   }
   notification_email_from FsOPSController@fs.myclouds.com       
   smtp_server 12.0.3.7
   smtp_connect_timeout 60                              
   router_id FSOPSCTL                           
}

vrrp_sync_group VG1 {
    group {
        ETH0
        ETH1
    }
}

vrrp_instance  ETH0 {
        state BACKUP
        interface eth0
        virtual_router_id 134
        priority 102
        smtp_alert
        nopreempt
        advert_int 1
        authentication {
                auth_type PASS
                auth_pass 1235
        }
        virtual_ipaddress {
                14.15.14.14/24 dev eth0 label eth0:ct_vip
                12.13.69.24/24 dev eth0 label eth0:cnc_vip
        }
}

vrrp_instance  ETH1 {
        state BACKUP
        interface br-eth1
        virtual_router_id 192
        priority 102
        smtp_alert
        nopreempt
        advert_int 1
        authentication {
                auth_type PASS
                auth_pass 1235
        }
        virtual_ipaddress {
                10.1.43.12/24 dev br-eth1 label br-eth1:int_vip
        }
}

system info
-----------------
ubuntu 14.04.5 amd64

root@myserver:/etc/keepalived# uname -a
Linux myserver.fs.myclouds.com 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

How I complie it is:
cd keepalived-1.2.24
./configure
make
make instal

**Comment by pqarmitage** [comment]
The debug option requires a level, in the range 0 to 4, which I assume you are not specifying. keepalived is well known for not checking the presence of expected parameters before attempting to parse them. and this often causes a segfault. If you add a number after the debug keyword, then it should stop segfaulting.

However, the debug option is not implemented, and so you may as well just leave it out. If you want more detail logged, then specify the `-D` option on the command line.

**Comment by sosogh** [comment]
>> If you add a number after the debug keyword, then it should stop segfaulting

yes, you are right.

In the older version of keepalived , if keepalived enter master or backup  state ,
there will be log "Enter Master / BACKUP state " .
But now I do not see them . 
That is why  I want to enable debug or  verbose log .
And I do not receive any email messages when the state of keepalived is changed  either.

It seems that virtual_ipaddresses are config correctly , the virtual_ipaddresses are pingable.
I am not sure whether keepalived is working well or not .

**Comment by pqarmitage** [comment]
I get the "Entering MASTER STATE" and "Entering BACKUP STATE" messages whether I run keepalived with the `-D` option or not.

I see you don't have any entries in the log you show for the idents "Keepalived_vrrp" and "Keepalived_healthercheckers". The master and backup state changes are logged with the "Keepalived_vrrp" ident.

**Comment by sosogh** [comment]
>> The master and backup state changes are logged with the "Keepalived_vrrp" ident.

I am sorry. I do not quite understand .
The log which I paste in the post is all the log after I start keepalived instance .

**Comment by sosogh** [comment]
and now my questions are 
1. I am not sure whether keepalived is working well or not ,cos I do not see any log about "state changing" and "email notification"
2. I do not receive any  "email notification" when keepalived state changing.

**Comment by pqarmitage** [comment]
For some reason, your log is not showing any entries from the vrrp and healthchecker child processes (PIDs 16727 and 16728 in your last log extract). These are logged with the strings `Keepalived_vrrp` and `Keepalived_healthcheckers`, rather than the string `Keepalived` that you have for PID 16725.

The email notifications are send by the vrrp child process, and so will be logged with the `Keepalived_vrrp` prefix. 

Until you can find where the Keepalived_vrrp and Keepalived_healthcheckers log entries are going, you won't find the log entries you want. Below is an example of the log entries I get:
Sep 20 11:48:46 samson1 Keepalived[26680]: Starting Keepalived v1.2.24 (09/19,2016), git commit show-100-g3a26ac3+
Sep 20 11:48:46 samson1 Keepalived[26680]: Opening file '/etc/keepalived//quick_high.conf'.
Sep 20 11:48:46 samson1 Keepalived[26681]: Starting Healthcheck child process, pid=26682
Sep 20 11:48:46 samson1 Keepalived_healthcheckers[26682]: Initializing ipvs
Sep 20 11:48:46 samson1 Keepalived[26681]: Starting VRRP child process, pid=26683
Sep 20 11:48:46 samson1 Keepalived_vrrp[26683]: Netlink reflector reports IP 141.1.0.1 added
Sep 20 11:48:46 samson1 Keepalived_vrrp[26683]: Netlink reflector reports IP 141.1.1.1 added
Sep 20 11:48:46 samson1 Keepalived_vrrp[26683]: Netlink reflector reports IP 141.1.2.1 added
Sep 20 11:48:46 samson1 Keepalived_vrrp[26683]: Netlink reflector reports IP 141.1.3.1 added
Sep 20 11:48:46 samson1 Keepalived_vrrp[26683]: Netlink reflector reports IP fe80::f8a6:43ff:feb7:aab4 added
Sep 20 11:48:46 samson1 Keepalived_vrrp[26683]: Netlink reflector reports IP fe80::3c02:77ff:fedf:a07f added
Sep 20 11:48:46 samson1 Keepalived_vrrp[26683]: Netlink reflector reports IP 2001:470:69dd:102::1 added
Sep 20 11:48:46 samson1 Keepalived_vrrp[26683]: Netlink reflector reports IP fe80::87d:8eff:fece:8cea added
Sep 20 11:48:46 samson1 Keepalived_vrrp[26683]: Netlink reflector reports IP 2001:470:69dd:103::1 added
Sep 20 11:48:46 samson1 Keepalived_vrrp[26683]: Netlink reflector reports IP fe80::bc45:14ff:fe01:5ffa added
Sep 20 11:48:46 samson1 Keepalived_vrrp[26683]: Registering Kernel netlink reflector
Sep 20 11:48:46 samson1 Keepalived_healthcheckers[26682]: Netlink reflector reports IP 141.1.0.1 added
Sep 20 11:48:46 samson1 Keepalived_healthcheckers[26682]: Netlink reflector reports IP 141.1.1.1 added
Sep 20 11:48:46 samson1 Keepalived_healthcheckers[26682]: Netlink reflector reports IP 141.1.2.1 added
Sep 20 11:48:46 samson1 Keepalived_healthcheckers[26682]: Netlink reflector reports IP 141.1.3.1 added
Sep 20 11:48:46 samson1 Keepalived_vrrp[26683]: Registering Kernel netlink command channel
Sep 20 11:48:46 samson1 Keepalived_healthcheckers[26682]: Netlink reflector reports IP fe80::f8a6:43ff:feb7:aab4 added
Sep 20 11:48:46 samson1 Keepalived_healthcheckers[26682]: Netlink reflector reports IP fe80::3c02:77ff:fedf:a07f added
Sep 20 11:48:46 samson1 Keepalived_healthcheckers[26682]: Netlink reflector reports IP 2001:470:69dd:102::1 added
Sep 20 11:48:46 samson1 Keepalived_healthcheckers[26682]: Netlink reflector reports IP fe80::87d:8eff:fece:8cea added
Sep 20 11:48:46 samson1 Keepalived_healthcheckers[26682]: Netlink reflector reports IP 2001:470:69dd:103::1 added
Sep 20 11:48:46 samson1 Keepalived_healthcheckers[26682]: Netlink reflector reports IP fe80::bc45:14ff:fe01:5ffa added
Sep 20 11:48:46 samson1 Keepalived_vrrp[26683]: Registering gratuitous ARP shared channel
Sep 20 11:48:46 samson1 Keepalived_healthcheckers[26682]: Registering Kernel netlink reflector
Sep 20 11:48:46 samson1 Keepalived_healthcheckers[26682]: Registering Kernel netlink command channel
Sep 20 11:48:46 samson1 Keepalived_healthcheckers[26682]: Opening file '/etc/keepalived//quick_high.conf'.
Sep 20 11:48:46 samson1 Keepalived_vrrp[26683]: Opening file '/etc/keepalived//quick_high.conf'.
Sep 20 11:48:46 samson1 Keepalived_vrrp[26683]: vmac: Success creating VMAC interface vrrp.1 for vrrp_instance VI_0
Sep 20 11:48:46 samson1 Keepalived_vrrp[26683]: Using LinkWatch kernel netlink reflector...
Sep 20 11:48:46 samson1 Keepalived_vrrp[26683]: VRRP_Instance(VI_0) Entering BACKUP STATE
Sep 20 11:48:46 samson1 Keepalived_vrrp[26683]: VRRP sockpool: [ifindex(5878), proto(112), unicast(0), fd(10,11)]
Sep 20 11:48:46 samson1 Keepalived_healthcheckers[26682]: Using LinkWatch kernel netlink reflector...
Sep 20 11:49:26 samson1 Keepalived_vrrp[26683]: VRRP_Instance(VI_0) Entering MASTER STATE
Sep 20 11:49:26 samson1 Keepalived_vrrp[26683]: VRRP_Instance(VI_0) using locally configured advertisement interval (12000 milli-sec)
Sep 20 11:49:26 samson1 Keepalived_vrrp[26683]: VRRP_Instance(VI_0) setting protocol iptable drop rule
Sep 20 11:49:26 samson1 Keepalived_vrrp[26683]: VRRP_Instance(VI_0) setting protocol VIPs.
Sep 20 11:49:26 samson1 Keepalived_vrrp[26683]: Sending gratuitous ARP on vrrp.1 for 141.1.0.254
Sep 20 11:49:26 samson1 Keepalived_vrrp[26683]: VRRP_Instance(VI_0) Sending/queueing gratuitous ARPs on vrrp.1 for 141.1.0.254
Sep 20 11:49:26 samson1 Keepalived_healthcheckers[26682]: Netlink reflector reports IP 141.1.0.254 added
Sep 20 11:49:31 samson1 Keepalived[26681]: Stopping
Sep 20 11:49:31 samson1 Keepalived_vrrp[26683]: VRRP_Instance(VI_0) sent 0 priority
Sep 20 11:49:31 samson1 Keepalived_vrrp[26683]: VRRP_Instance(VI_0) removing protocol VIPs.
Sep 20 11:49:31 samson1 Keepalived_healthcheckers[26682]: Stopped
Sep 20 11:49:31 samson1 Keepalived_vrrp[26683]: VRRP_Instance(VI_0) removing protocol iptable drop rule
Sep 20 11:49:32 samson1 Keepalived_vrrp[26683]: vmac: Success removing VMAC interface vrrp.1 for vrrp_instance VI_0
Sep 20 11:49:32 samson1 Keepalived_vrrp[26683]: Stopped
Sep 20 11:49:32 samson1 Keepalived[26681]: Stopped Keepalived v1.2.24 (09/19,2016), git commit show-100-g3a26ac3+

**Comment by sosogh** [comment]
It turns out the it is the matter of config of rsyslog.
After I reconfig rsyslog , I can see  the complete log now. 
@pqarmitage   Thank you for your help.

**Comment by okaprinarjaya** [comment]
I also just facing this error today. I am using Keepalived v1.3.x 
where's the solution? Please help me.

Thank you
