### ISSUE TITLE
Add travis-ci support

### ISSUE THREAD

**Issue by rik78** [acassen/keepalived#433]
How do you feel about travis-ci? It would be nice to have in my opinion. At least it will be easier to test if some build is breaking, and then we could add some basic tests to keep keepalived functionality checked at every commit.

**Comment by pqarmitage** [comment]
If this can do what we need it would be wonderful. The challenge regarding testing the building of keepalived is the number of different options that can be passed to configure, and the amount of conditional compilation that is based on availability of kernel and library features.

Currently there are approximately 25 different command line options that can be passed to configure (although some are suboptions of others), and this amounts to, at a rough calculation, some 891,648 different build combinations. I'm sure some analysis would show that some are completely independent of each other, and so this number of different build combinations should be able to be reduced significantly.

The more difficult issue is, I think, needing to support kernel versions from at least 2.6.32 (for Centos 6) through to the latest version (currently 4.7.5) (although I did add a patch for someone recently in order to allow keepalived to build on Linux 2.6.19, so we should probably say 2.6.19 through 4.7.5). There are approximately 50 different conditional defines based on kernel/library functionality, but these should be able to be put in a chronological order, so there should only be 50 or so options to test there.

Is there a way that travis-ci can support all this. If so, it would be really, really useful.

Is this something that travis-ci can do for us?

I've also noticed that travis VMs are 64 bit, whereas we also need to be able to support 32 bit systems.

**Comment by rik78** [comment]
I agree that testing all combinations of configuration would be very hard. Testing with different distros should be possible with the _matrix_ option. Unfortunately 32bit vm support is still missing.

**Comment by pqarmitage** [comment]
Are you in a position to create a travis.yml file and try something out as a test?

What I'm not clear about at the moment is advantages this gives us. Would we need to identify a number of options for testing different configure scenarios, a number of different kernel versions, and a number of different distros, and then see what travis-ci does with those.

**Comment by commodo** [comment]
#> ping @here
#> payload PR https://github.com/acassen/keepalived/pull/604

**Comment by commodo** [comment]
to add to this discussion

one reference i use, is this file from lldpd
https://github.com/vincentbernat/lldpd/blob/master/.travis.yml

it already provides a matrix of options;
to test building lldpd on Linux, OSX, gcc compiler, clang compiler, --with / --enable / --disable options

i admit i was lazy with my PR to do any of these ; but even as it is, it should be a starter to something like `lldpd` has

**Comment by commodo** [comment]
not to mention the `build passing` tag ; which is always a good sign to see in every github repo

**Comment by rik78** [comment]
Closing...

**Comment by pqarmitage** [comment]
Many thanks for this suggestion and the help in setting it up. Travis-CI building is now enabled for keepalived and the github page is now displaying the `build passing` tag.
