### ISSUE TITLE
keepalived exiting with code 256 on FAULT state in systemd when built from source

### ISSUE THREAD

**Issue by jslusher** [acassen/keepalived#438]
I’m having a little trouble getting keepalived to work using systemd when building from source. I copied the unit file from a package-installed keepalived available to centos 7, and it mostly works in that it does start and stop the keepalived process, but when keepalived goes into its FAULT state, systemd shows that it continually exits with the code 256. when installed from the package it shows the FAULT state properly. I’m not sure what the difference is between the two installations concerning systemd.

    [Unit]
    Description=LVS and VRRP High Availability Monitor
    After=syslog.target network.target

    [Service]
    Type=forking
    KillMode=process
    EnvironmentFile=-/etc/sysconfig/keepalived
    ExecStart=/usr/local/sbin/keepalived $KEEPALIVED_OPTIONS
    ExecReload=/bin/kill -HUP $MAINPID
    PIDFile=/var/run/keepalived.pid

    [Install]
    WantedBy=multi-user.target

The process starts and stops fine, but when a FAULT state is encountered, I get this:

    ● keepalived.service - LVS and VRRP High Availability Monitor
       Loaded: loaded (/etc/systemd/system/keepalived.service; enabled; vendor preset: disabled)
       Active: active (running) since Sat 2016-10-01 00:47:12 EDT; 2s ago
      Process: 30947 ExecStart=/usr/local/sbin/keepalived $KEEPALIVED_OPTIONS (code=exited, status=0/SUCCESS)
     Main PID: 30948 (keepalived)
       CGroup: /system.slice/keepalived.service
               ├─30948 /usr/local/sbin/keepalived -D
               ├─30949 /usr/local/sbin/keepalived -D
              └─30950 /usr/local/sbin/keepalived -D

    Oct 01 00:47:12 server.test.com Keepalived_vrrp[30950]: Registering gratuitous ARP shared channel
    Oct 01 00:47:12 server.test.com Keepalived_vrrp[30950]: Opening file '/etc/keepalived/keepalived.conf'.
    Oct 01 00:47:12 server.test.com Keepalived_vrrp[30950]: Truncating auth_pass to 8 characters
    Oct 01 00:47:12 server.test.com Keepalived_vrrp[30950]: VRRP_Instance(VPN) removing protocol VIPs.
    Oct 01 00:47:12 server.test.com Keepalived_vrrp[30950]: Using LinkWatch kernel netlink reflector...
    Oct 01 00:47:12 server.test.com Keepalived_vrrp[30950]: VRRP_Instance(VPN) Entering BACKUP STATE
    Oct 01 00:47:12 server.test.com Keepalived_vrrp[30950]: VRRP sockpool: [ifindex(3), proto(112), unicast(1), fd(10,11)]
    Oct 01 00:47:12 server.test.com Keepalived_vrrp[30950]: pid 30951 exited with status 256
    Oct 01 00:47:13 server.test.com Keepalived_vrrp[30950]: pid 30953 exited with status 256

When installed from the package I get this. (Same configuration AFAICT):

    Oct 01 02:07:07 server.test.com Keepalived_vrrp[5493]: Configuration is using : 66531 Bytes
    Oct 01 02:07:07 server.test.com Keepalived_vrrp[5493]: Using LinkWatch kernel netlink reflector...
    Oct 01 02:07:07 server.test.com Keepalived_vrrp[5493]: VRRP_Instance(VPN) Entering BACKUP STATE
    Oct 01 02:07:07 server.test.com Keepalived_vrrp[5493]: VRRP sockpool: [ifindex(3), proto(112), unicast(1), fd(10,11)]
    Oct 01 02:07:07 server.test.com systemd[1]: Started LVS and VRRP High Availability Monitor.
    Oct 01 02:07:11 server.test.com Keepalived_vrrp[5493]: VRRP_Instance(VPN) Now in FAULT state

**Comment by pqarmitage** [comment]
First of all, the exit status of processes 30951 and 30953 is in fact 1 (i.e. 256 >> 8); it is being misreported by keepalived, and I'll produce a patch to fix this.

The next thing is that processes 30951 and 30953 are not keepalived processes, since the PIDs of the keepalived processes are 30948, 30949 and 30950. 30951 and 30953 are probably notify_... scripts run by the keepalived vrrp process. It doesn't look as though the keepalvied processes are exiting when run under systemd.

Looking at
```
Process: 30947 ExecStart=/usr/local/sbin/keepalived $KEEPALIVED_OPTIONS (code=exited, status=0/SUCCESS)
 Main PID: 30948 (keepalived)
   CGroup: /system.slice/keepalived.service
           ├─30948 /usr/local/sbin/keepalived -D
           ├─30949 /usr/local/sbin/keepalived -D
          └─30950 /usr/local/sbin/keepalived -D
```
systemd is running /usr/local/sbin/keepalived, which has PID 30947. keepalived then forks (to detach itself from the controlling terminal if it is run from a command line, but isn't necessary when run by systemd), and the parent process then exits, which is why it reports that process 30947 has exited with status =0.

The child of PID 30947, which is PID 30948 then runs as the main keepalived process, and forks to create PIDs 30949 and 30950, which run as the Keepalived_vrrp and Keepalived_healthcheckers processes.

As I indicated above, PIDs 30951 and 30953 are probably the PIDs of notify_... scripts run by the Keepalived_vrrp process, but they might be iptables processes, depending on how keepalived is built, and the particular configuration you are running.

In order to investigate this further, it would be helpful to see the following:
1. The output of keepalived -v for both the version built from source, and for the version installed from the package
2. A copy of the keepalived config file: /etc/keepalived/keepalived.conf
3. A copy of the full logs when running keepalived in the two different ways described above.
4 A copy of /etc/sysconfig/keepalived

**Comment by jslusher** [comment]
keepalived -v from source:

    /usr/local/sbin/keepalived -v
    Keepalived v1.2.24 (09/30,2016)

    Copyright(C) 2001-2016 Alexandre Cassen, <acassen@gmail.com>

    Build options:  PIPE2 FRA_OIFNAME RTAX_QUICKACK LINUX_NET_IF_H_COLLISION LVS VRRP VRRP_AUTH VRRP_VMAC SOCK_NONBLOCK SOCK_CLOEXEC FIB_ROUTING SNMP SNMP_KEEPALIVED SNMP_CHECKER SO_MARK 

from package:

    /usr/sbin/keepalived -v
    Keepalived v1.2.13 (11/20,2015)

=============================

[keepalived.conf](https://gist.github.com/jslusher/2fd58d8023daa21f02a18e6665e545bb) 

============================

[/etc/sysconfig/keepalived](https://gist.github.com/jslusher/8b2d18725c168a8f4db6d0f2cb38794d)

============================

[startup logs from package](https://gist.github.com/jslusher/a219b2ee95350b3039a82419247c9352)

============================

[startup logs from source](https://gist.github.com/jslusher/65152ef78ffa5f33dafdddf7ca2d3689)

**Comment by pqarmitage** [comment]
The `pid ... exited with status 256` messages are caused by the following configuration:

vrrp_script chk_vpn {
script "echo hellow"
}
vrrp_instance VPN {
  track_script {
    chk_vpn
  }
}

Once per second the script "echo hellow" is run. When keepalived is run under systemd, it cannot find an echo command to execute. If you change
`script "echo hellow"` to `script "/bin/echo hellow"` (but do check you have a /bin/echo), then the error should stop.

The reason that the vrrp instance VPN is going into the fault state is that that there are 5 consecutive failures when executing the script (since it can't find echo), and so it puts the vrrp instance into the fault state.

**Comment by jslusher** [comment]
I forgot to update that config file after I was experimenting. 

    vrrp_script chk_vpn {
        script "/bin/killall -0 openvpn"
    }

The original chk_vpn script did not have the absolute path, but I tried using the absolute path and it still seems to [behave the same](https://gist.github.com/jslusher/6ced7d5f3e27a1f38f0d0be305b50496).

**Comment by pqarmitage** [comment]
I've merged an commit that will now make the log entries correctly report `pid ... exited with status 1` rather than status 256.

I've done some further tests, and I get exit status 1 if the process that killall is attempting to kill doesn't exist. This suggests that for some reason when you are running keepalived from systemd, it is unable to find the openvpn process to kill.

**Comment by jslusher** [comment]
I think there is some confusion still. Originally when I opened this issue, it was because I didn't think the keepalived process was actually going to a FAULT state. It appears that the process is going to a FAULT state, but also verbosely logging when the `vrrp_script` fails. The openvpn process isn't present on the server, so the FAULT state is to be expected. What is different now from the package install appears to be the verbose logging. What's the difference between the package and the build from source that makes it log verbosely?

**Comment by pqarmitage** [comment]
The version of keepalived from the package is v1.2.13, and the version you have built from source is v1.2.24 and there have been 680 or so commits between the two.

It appears that I added logging of child processes terminating with non 0 exit status in commit https://github.com/acassen/keepalived/commit/273af5ad and the first release version this appeared in was v1.2.20.

I hope that answers your issue.

**Comment by jslusher** [comment]
Ah thanks! Sorry to go the long way about asking. I appreciate your help.
