### ISSUE TITLE
IPAO priority is off by one

### ISSUE THREAD

**Issue by andempsey** [acassen/keepalived#455]
This code 
`if (new_prio < 1)
		new_prio = 1;
else if (new_prio >= VRRP_PRIO_OWNER)
		new_prio = VRRP_PRIO_OWNER - 1;`
in vrrp_scheduler.c vrrp_update_priority line 837 causes an off by one error when IPAO mode is active.
Our implementation is slightly different (in the new year we should hopefully have a refactor and be able to merge with your work here) and we have a boolean for if the group is an IP address owner. I've just added this code in our implementation.
`else if (new_prio >= VRRP_PRIO_OWNER && !vrrp->addr_owner)
                 new_prio = VRRP_PRIO_OWNER -1;
if (vrrp->addr_owner)
                 new_prio = VRRP_PRIO_OWNER`

Cheers,
Anthony

**Comment by pqarmitage** [comment]
Anthony,

Many thanks for this report.

I believe this was fixed in commit 7c677ea6 with a slightly different approach. If the vrrp instance is the address owner, then the effective priority will never be changed, so the commit stopped vrrp_update_priority() being called in that case.

Commit 7c677ea6 was the last commit included in v1.2.24. What version of the code is you code based on; in other words does your code include commit 7c677ea6? If it does, then I'll need to look further, but I haven't experienced a problem in this area.

Cheers,
Quentin

**Comment by andempsey** [comment]
Hmmm, our divergent code might've introduced this bug then. The divergent code is mostly to do with vmac interfaces and this code was for dynamically adding the address owner VIP. We definitely have that commit in our code base, I'll do some more digging on Monday and close this off until I can determine if it's outside our changes.
