### ISSUE TITLE
Default behaviour of adding iptables DROP rule?

### ISSUE THREAD

**Issue by Soprano74** [acassen/keepalived#474]
Not sure if this is a issue, I cant seem to find anything related to this, but when using the newer versions, 1.3.1 and 1.3.2, when I only define a virtual_ipaddress, once a instance activated the VIP, it adds an iptables DROP rule to this IP. This obviously drops all traffic, making it unreachable. 
I tried the default version on CentOS7, 1.2.13, which with the same config, does not have this behaviour. Most online examples of a simple VIP setup, do not work because of this. Flusing the rules using a notify_master script seems ugly to me.

Any hints?

**Comment by pqarmitage** [comment]
iptables entries should only be added if `strict` or `noaccept` is configured against the vrrp instance, or `vrrp_strict` is configured in global_defs. This is to comply with RFC5798 Accept_Mode, except that unless `strict` is specified, the default is to set Accept_Mode (i.e. allow packets to be received by the virtual IP address) whereas the RFC states that the default should be Accept_Mode is false.

You could try specifying `accept` against the vrrp instances, so see if that stops the iptables entries being added.

Could you post a copy of your keepalived config so that we can test it to make sure there isn't a problem with the logic in this area in keepalived. I have tested a minimal config without strict oro noaccept set, and it doesn't add iptables entries for me.

**Comment by pqarmitage** [comment]
Before altering the configuration, could you do
`kill -USR1 $(cat /var/run/kaapalived.pid)`
and then post the resulting /tmp/keepalived.data

It's possible that somehow the configuration is getting corrupted after being read.

**Comment by Soprano74** [comment]
I was sure I tested with only the very short configurations. But it seems in the global defs the vrrp_strict statement did cause the iptables input. Removing this stops the iptables rule form being inserted, and I do not even need to specify 'accept'. I guess working as intended. Thanks for the reply's.

**Comment by bharatlalgupta** [comment]
> I was sure I tested with only the very short configurations. But it seems in the global defs the vrrp_strict statement did cause the iptables input. Removing this stops the iptables rule form being inserted, and I do not even need to specify 'accept'. I guess working as intended. Thanks for the reply's.

commenting vrrp_strict worked for me; thanks a lot..!!
