### ISSUE TITLE
1.3.2 - Syslog spammed with "Netlink reflector reports IP xxx:xxx added" (SLAAC IP)

### ISSUE THREAD

**Issue by SjonHortensius** [acassen/keepalived#481]
Since upgrading 1.2.24 > 1.3.2 I frequently see these messages. I'm not sure why they suddenly appear but their frequency is currently an issue. The reported IP is not configured in keepalived in any way; it seems these are the machine's normal address which is configured via SLAAC

```
Dec 14 15:32:05 host Keepalived_healthcheckers[22503]: Netlink reflector reports IP 2a0s:xxx added
Dec 14 15:32:21 host Keepalived_healthcheckers[22503]: Netlink reflector reports IP 2a0s:xxx added
Dec 14 15:32:21 host Keepalived_vrrp[22504]: Netlink reflector reports IP 2a0s:xxx added
Dec 14 15:32:40 host Keepalived_healthcheckers[22503]: Netlink reflector reports IP 2a0s:xxx added
Dec 14 15:32:40 host Keepalived_vrrp[22504]: Netlink reflector reports IP 2a0s:xxx added
Dec 14 15:32:51 host Keepalived_healthcheckers[22503]: Netlink reflector reports IP 2a0s:xxx added
Dec 14 15:32:51 host Keepalived_vrrp[22504]: Netlink reflector reports IP 2a0s:xxx added
Dec 14 15:33:01 host Keepalived_healthcheckers[22503]: Netlink reflector reports IP 2a0s:xxx added
Dec 14 15:33:01 host Keepalived_vrrp[22504]: Netlink reflector reports IP 2a0s:xxx added
Dec 14 15:33:16 host Keepalived_vrrp[22504]: Netlink reflector reports IP 2a0s:xxx added
Dec 14 15:33:16 host Keepalived_healthcheckers[22503]: Netlink reflector reports IP 2a0s:xxx added
Dec 14 15:33:26 host Keepalived_vrrp[22504]: Netlink reflector reports IP 2a0s:xxx added
Dec 14 15:33:26 host Keepalived_healthcheckers[22503]: Netlink reflector reports IP 2a0s:xxx added
Dec 14 15:33:34 host Keepalived_vrrp[22504]: Netlink reflector reports IP 2a0s:xxx added
Dec 14 15:33:34 host Keepalived_healthcheckers[22503]: Netlink reflector reports IP 2a0s:xxx added
Dec 14 15:33:41 host Keepalived_vrrp[22504]: Netlink reflector reports IP 2a0s:xxx added
Dec 14 15:33:41 host Keepalived_healthcheckers[22503]: Netlink reflector reports IP 2a0s:xxx added
Dec 14 15:33:53 host Keepalived_healthcheckers[22503]: Netlink reflector reports IP 2a0s:xxx added
```

Is this in any way expected / configurable?

**Comment by pqarmitage** [comment]
The -D command line option to keepalived causes these messages to be output. Is that somehow now being passed on the keepalived command line?

What is strange here is that it is only reporting addresses being added, since the -D option should also report addresses being removed. Are the addresses all different, or is it the same address being reported repeatedly?

**Comment by SjonHortensius** [comment]
Yes; `-D` is passed; but these messages only appear since the upgrade.

The address reported is the current address of the machine; every entry lists the exact same address. Again; this keepalived instance is not configured to use ipv6 or do anything with the reported address.

**Comment by pqarmitage** [comment]
This is very strange. So far as I am aware it shouldn't be possible for netlink to repeatedly report an address being added, without it reporting the address being deleted.

Were any other packages upgraded at the same time as keepalived?

I can only think of two possibilities; either there is some sort of build problem with keepalived, or the system itself if doing something very strange. Have you checked the system logs to see if anything is being reported?

If it is a keepalived problem, then the only thing I could suggest is doing a git bisect to find out which commit caused the problem.

**Comment by acassen** [comment]
hmm, strange...

Could you try running : "ip monitor all"

this will register a direct display into netlink reflector. If you are observing the same behaviour here as in your syslog then there is some conf and/or on local system causing this issue.

In IPv6 env you must also take a special care of aging, some router via ND will discard regulary IP in order to submit the full process to refresh routing path (and/or adding a new different IPv6 address: for security considerations, your local pub v6 address could change over a session, in order to make life less easier for attacker to track your activity).

**Comment by SjonHortensius** [comment]
`ip monitor all` does confirm the same address gets added over and over; and keepalived simply reports this. I have no problem with this behaviour; but I wonder why previous keepalived versions never reported this. I'll see if I can pinpoint which commit enabled this behaviour.

I have not enabled IPv6PrivacyExtensions for this specific machine btw.

**Comment by acassen** [comment]
maybe previous version simply silently ignore this message. To be sure, run previous keepalived setup and run in // ip monitor all. If "ip monitor all" still report IP added with your previous setup... then...

**Comment by SjonHortensius** [comment]
I've already tested this; and keepalived-1.2.24 does not report this; while `ip monitor all` still does. Looking at [check_api.c#L272](https://github.com/acassen/keepalived/blame/5cc4c097913f6c833840c80a94a05e7c22cb7db7/keepalived/check/check_api.c#L272) it seems this check was always present in keepalived and this wasn't intentionally changed, right?

**Comment by pqarmitage** [comment]
I'm not aware of any intentional change regarding the logging of Netlink reflector messages. If you could identify which commit has caused the change for you that would be really helpful, since I'm not seeing any change in the logging of these messages between 1.2.24 and 1.3.2.

**Comment by SjonHortensius** [comment]
Update: okay this is not necessarily caused by keepalived; After bisecting I ended up with 1.2.24 throwing the same messages. It seems to be related to a dependency; my distro supplied 1.2.24-binary still does **not** throw them.
Fwiw this is Archlinux and I'll have a look at libnfnetlink / ipset / systemd versions next

**Comment by pqarmitage** [comment]
I saw this earlier today on a Centos 7 VM, but the same version of keepalived isn't causing it on other systems. When I have a moment I'll investigate it further, but any input is much appreciated.

**Comment by CoMPaTech** [comment]
Got this since last friday when installing (one of multiple) gateways at one of our customers. This box was 'just another scientific linux 7' the only difference is that this is behind a CPE modem and as such has IPv6 (where to others tend to ignore it, although same basic OS configuration, but on colocations). Also the 'significant other' isn't present yet (so it's a standalone box, waiting for the other to be build). If there is anything I can test, please let me know

**Comment by pqarmitage** [comment]
This appears to be a kernel issue.

In the next planned major release of keepalived by default keepalived will only log addresses that are of relevance to keepalived (unless the new -a option is specified), so this should stop the filling of logs with irrelevant messages.
