### ISSUE TITLE
How to tune down sensitivity to react to vrrp_adverts?

### ISSUE THREAD

**Issue by Cugar15** [acassen/keepalived#486]
Hi,

   I'm running two nodes in master/backup mode.
Each has one vrrp_instance defined with a very basic configuration.

advert_int 5 is defined. (5 seems to be less sensitive than 1)

Regularily, if running a backup on my Master node - means creating heavy IO, the Backup node seems to not getting the adverts from the Master node anymore and 'tries' to transition into Master mode - however, in the course of action, it assumes BACKUP state again before completing the transition.

'Completing' is defined that the notify script when 'transitioning' to MASTER state is actually exectued.

All happens within 1 second.

The log file looks like:
````
Dec 18 06:15:35 178 Keepalived_vrrp[61570]: VRRP_Instance(VI_1) Transition to MASTER STATE
Dec 18 06:15:36 178 Keepalived_vrrp[61570]: VRRP_Instance(VI_1) Received advert with higher priority 200, ours 100
Dec 18 06:15:36 178 Keepalived_vrrp[61570]: VRRP_Instance(VI_1) Entering BACKUP STATE
Dec 18 06:15:36 178 Keepalived_vrrp[61570]: Opening script file /etc/keepalived/action.sh
````

A sort of 'timeout' might be the cure to the problem - however, I was not able to find such a switch in the docu....

Any ideas? Thanks!!!

**Comment by pqarmitage** [comment]
Commit e1cb8f4 added global options to attempt to alleviate this problem, namely vrrp_priority and vrrp_no_swap (it also added checker_priority and checker_no_swap but it doesn't sound as though they are relevant here).

You could try setting vrrp_priority to a negative value (to increase its priority), and you might also need vrrp_no_swap if the keepalived processes are being swapped out. If you do need to use vrrp_no_swap,  then I will need to do some more work on working out what the right stack size is to pass to set_process_dont_swap(), since at the moment it is ridiculously small.

An alternative (or you could do both) would be to reduce the priority of the backup process, which is probably a good idea anyway.

**Comment by Cugar15** [comment]
Thanks for the fast answer.
OK, understand. I will try to play with these options.
I will update for your information based on what I'm finding.
For now, I close this ticket.
Cheers!

2016-12-19 9:46 GMT+01:00 pqarmitage <notifications@github.com>:
