### ISSUE TITLE
Keepalived Exit due to Segmentation Fault

### ISSUE THREAD

**Issue by vishal2332** [acassen/keepalived#495]
Hi,

We are running  Keepalived v1.2.20 on 2 of my HA Proxy Server's on CentOS 6.7 it worked quite well for a while  but  all of a sudden we are now  getting this Segmentation fault error after which the Secondary Ha Proxy becomes master but dont return back when the master server is up.

![image](https://cloud.githubusercontent.com/assets/20405168/21981526/e3a514c2-dc0d-11e6-98d0-bc373c9fe6c5.png)
![ha-proxy-error](https://cloud.githubusercontent.com/assets/20405168/21981643/71636480-dc0e-11e6-9a49-6e17ea8b18ee.PNG)

Can someone please help resolving this error.

**Comment by pqarmitage** [comment]
The log entry asking you to file this bug report also asks that you include a copy of the keepalived log from when keepalived started, a description of what is happening immediately before the crash, and also a copy of your configuration file. Without this information we have nothing to be able to determine what might be causing the crash.

It is also worth trying the latest version of keepalived (currently 1.3.2) so see if that resolves your issue, since there have been many fixes since 1.2.20.

**Comment by pqarmitage** [comment]
Closing due to no response for over 2 months.
