### ISSUE TITLE
Issues with ./configure ?

### ISSUE THREAD

**Issue by jllorente** [acassen/keepalived#496]
I'm tying to compile keepalived under Ubuntu 16.04. I have installed the following dependencies:
```
# apt-get install libssl-dev libipset-dev iptables-dev
```
Then, when I try to run the ./configure, I get the following summary:
```
$ ./configure --enable-libiptc --enable-libipset --disable-lvs --with-systemdsystemunitdir=/etc/systemd/system

Use libiptc              : No  
Use libipset             : No  
init type                : SYSV
```

Could you please indicate if I am doing something wrong? 
Thanks!

**Comment by pqarmitage** [comment]
First of all, `--enable-libiptc` and `--enable-libipset` aren't necessary, since they are the defaults, but it shouldn't matter including them.

The output of configure should tell you what test is failing. Looking in configure.ac, when checking the usability of libiptc it checks for the presence of `linux/netfilter/x_tables.h xtables.h libiptc/libip6tc.h libiptc/libiptc.h libiptc/libxtc.h` header files, and also whether it can link to the libiptc function iptc_init. The output I get relating to this when running configure is:
```
checking linux/netfilter/x_tables.h usability... yes
checking linux/netfilter/x_tables.h presence... yes
checking for linux/netfilter/x_tables.h... yes
checking xtables.h usability... yes
checking xtables.h presence... yes
checking for xtables.h... yes
checking libiptc/libip6tc.h usability... yes
checking libiptc/libip6tc.h presence... yes
checking for libiptc/libip6tc.h... yes
checking libiptc/libiptc.h usability... yes
checking libiptc/libiptc.h presence... yes
checking for libiptc/libiptc.h... yes
checking libiptc/libxtc.h usability... yes
checking libiptc/libxtc.h presence... yes
checking for libiptc/libxtc.h... yes
checking for iptc_init in -liptc... yes
```
If you get `no` for any of these, then that would explain why it is not using libiptc.

If configure determines that libiptc cannot be used, then it will not attempt to use libipset. However, if you resolve the libiptc issue and it is still not using libipset, then you can see from configure.ac what header files and library function it is checking to determine usability of libipset, and the output from configure should show you what test is failing.

To see how configure is checking what init type to use, look at configure.ac after the comment `Determine system init type` to see what tests it is making. If you can't see what is not working, then you can try running configure as:
`bash -x ./configure >/tmp/config.op 2>&1`
and after it has run look in the /tmp/config.op file to see what is happening when it is determining the init type.

**Comment by jllorente** [comment]
Thanks for the help! Turns out I was missing some dependency, I still don't know how I missed that before :)

I didn't know this one and it's quite handy
```
bash -x ./configure >/tmp/config.op 2>&1
```

**Comment by jllorente** [comment]
Actually I just noticed something, I get different init type if I run the configure with sudo.

```
./configure

Keepalived configuration
------------------------
Keepalived version       : 1.3.2
Compiler                 : gcc
Preprocessor flags       :
Compiler flags           : -Wall -Wunused -Wstrict-prototypes -Wextra -g -O2
Linker flags             :
Extra Lib                : -ldl -lssl -lcrypto  -lip4tc -lip6tc -lxtables
Use IPVS Framework       : Yes
IPVS use libnl           : No
IPVS syncd attributes    : Yes
IPVS 64 bit stats        : Yes
fwmark socket support    : Yes
Use VRRP Framework       : Yes
Use VRRP VMAC            : Yes
Use VRRP authentication  : Yes
With ip rules/routes     : Yes
SNMP vrrp support        : No
SNMP checker support     : No
SNMP RFCv2 support       : No
SNMP RFCv3 support       : No
DBUS support             : No
SHA1 support             : No
Use Debug flags          : No
Stacktrace support       : No
Memory alloc check       : No
libnl version            : None
Use IPv4 devconf         : No
Use libiptc              : Yes
Use libipset             : Yes
init type                : SYSV
Build genhash            : Yes
Build documentation      : No
```

```
sudo -E ./configure

Keepalived configuration
------------------------
Keepalived version       : 1.3.2
Compiler                 : gcc
Preprocessor flags       :
Compiler flags           : -Wall -Wunused -Wstrict-prototypes -Wextra -g -O2
Linker flags             :
Extra Lib                : -ldl -lssl -lcrypto  -lip4tc -lip6tc -lxtables
Use IPVS Framework       : Yes
IPVS use libnl           : No
IPVS syncd attributes    : Yes
IPVS 64 bit stats        : Yes
fwmark socket support    : Yes
Use VRRP Framework       : Yes
Use VRRP VMAC            : Yes
Use VRRP authentication  : Yes
With ip rules/routes     : Yes
SNMP vrrp support        : No
SNMP checker support     : No
SNMP RFCv2 support       : No
SNMP RFCv3 support       : No
DBUS support             : No
SHA1 support             : No
Use Debug flags          : No
Stacktrace support       : No
Memory alloc check       : No
libnl version            : None
Use IPv4 devconf         : No
Use libiptc              : Yes
Use libipset             : Yes
init type                : systemd
Build genhash            : Yes
Build documentation      : No
```

**Comment by pqarmitage** [comment]
One further note. You are not using libnl, so it would be worth installing libnl3-dev.

Thanks for the report regarding init type changes depending on whether configure is run as root or not. I will have a look into that.

**Comment by pqarmitage** [comment]
Apologies, the packages that need to be installed are: libnl-3-dev libnl-genl-3-dev libnl-route-3-dev

**Comment by pqarmitage** [comment]
I've installed a Ubuntu 16.04 VM, and when I run ./configure as a non-privileged user, I get init type systemd as I would expect, so we have some different behaviour between our systems.

Could you generate config.op files for running configure as root and non-root users, and see what differences there are around where systemctl is called. In configure.ac the relevant checks follow the comment `Determine system init type`.

**Comment by jllorente** [comment]
Hi @pqarmitage 
It seems the source of the problem is due to my LXC container environment. Both my VM and containers are running Ubuntu 16.04, but there seems to be some issue with the virtualization layer that makes the system init go to SYSV. 

I guess we could close this issue again as it is not related to the keepalived project :)

```
$systemctl
Failed to connect to bus: No such file or directory
```

PS: I installed the libnl libraries as you indicated ;)
