### ISSUE TITLE
Issues building/running under alpine linux

### ISSUE THREAD

**Issue by r0p0s3c** [acassen/keepalived#508]
The current build/code has a couple of issues when attempting to build and run under alpine linux (which uses the musl c library):

- minor issue: configure.ac doesn't handle an undetected init system (alpine uses openrc)
- major issue: musl doesn't really support/have a sane value for GETPW_R_SIZE_MAX/GETGR_R_SIZE_MAX which causes memory corruption when using script user/group, usually leading to a crash on startup

**Comment by pqarmitage** [comment]
Can you confirm what the return value of `sysconf(_SC_GETPW_R_SIZE_MAX)` is on your Alpine Linux system. I've noticed that sysconf() can return -1 if the queried option is not available, or there is no definite limit. If you are getting -1, then I think we should have code at run time to check for the return value -1, and if that is the case, set getpwnam_buf_len to 1024, and we don't need to worry about the configure time check and definition of _MISSING_GETPW_R_SIZE_MAX.

I'd also be interested to know what shell you are using that requires the addition of the "s around \`which systemctl\`, since I've not experienced a problem without them.

**Comment by r0p0s3c** [comment]
Hi,

looks like musl does indeed does set invalid/unavailable config variables to -1:
`
src/conf/sysconf.c:             [_SC_GETGR_R_SIZE_MAX] = -1,
src/conf/sysconf.c:             [_SC_GETPW_R_SIZE_MAX] = -1,
`
compile-time seemed like the best place but I don't think there should be any other issues with runtime checking of this and adjusting. As for the sh issue, looks like the default shell is based on ash.

Thanks

**Comment by pqarmitage** [comment]
I decided to implement the check for sysconf() returning -1 a runtime, since it is vaguely possible that keepalived may be built on a system that returns a sensible value, but if it run on another system, 01 could be returned.

Commits 849803b and a1e142b make the changes as outlined in your pull request #509, but with the change to make the check for sysconf() returning -1 at runtime.

**Comment by r0p0s3c** [comment]
Thanks
