### ISSUE TITLE
Keepalived version 1.3.2 compile error CentOS7

### ISSUE THREAD

**Issue by fenice2** [acassen/keepalived#513]
This seems to be the same problem mentioned in issue #480 and subsequently fix #482 was merged into the master branch. I've tried building this from the master branch on my CentOS7 server but I'm still encountering this issue.

cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core) 

make[2]: Leaving directory `/root/rpmbuild/BUILD/keepalived-1.3.2/keepalived/core'
Making all in vrrp
make[2]: Entering directory `/root/rpmbuild/BUILD/keepalived-1.3.2/keepalived/vrrp'
  CC       vrrp_daemon.o
In file included from ./../include/vrrp_iproute.h:32:0,
                 from vrrp_daemon.c:37:
/usr/include/linux/mpls.h:4:29: fatal error: uapi/linux/mpls.h: No such file or directory
 #include <uapi/linux/mpls.h>
                             ^
compilation terminated.
make[2]: *** [vrrp_daemon.o] Error 1
make[2]: Leaving directory `/root/rpmbuild/BUILD/keepalived-1.3.2/keepalived/vrrp'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/rpmbuild/BUILD/keepalived-1.3.2/keepalived'
make: *** [all-recursive] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.v1YSz8 (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.v1YSz8 (%build)

That was from running the following: rpmbuild -ba  keepalived.spec

I've checked the code as much as I can and, obviously, the fixes are all in there but still this problem. If I run a ./configure - make - make install it all seems to go OK but building the rpm fails. I'm not very experienced at building packages - is there anything obvious that I might have missed?

**Comment by pqarmitage** [comment]
First of all, it is not good practice to run rpmbuild as root - it should be run by a non privileged user. To do this, log in as a non-privileged used and execute `rpmdev-setuptree`. This will create a directory rpmbuild, with relevant sub-directories.

This issue with building the rpm probably relates to what version of the keepalived is in the tarball you are using. In order to pick up the changes made in commit #482, you need to create your own tarball from the git checkout you have. In the directory where you ran ./configure, run `make dist` and then copy keepalived-1.3.2.tar.gz to your rpmbuild/SOURCES directory. You should then be able to run `rpmbuild -bb keepalived.spec` (-ba also creates a source rpm file, which you probably don't need).

BTW, what keepalived.spec file are you using - the one from the keepalived distribution, or one taken from CentOS?
gzip

**Comment by fenice2** [comment]
Thanks for your quick reply. Yes, I know about not building as root and this is just a temporary test VM that I put up to try building keepalived.  I thought I'd created the tarball from the master branch and copied it to the correct directory. 

The keepalived.spec file is the one supplied in the master download. I'll go through this again a bit later today and make sure I'm following your procedure, I'll let you know what happens.

**Comment by fenice2** [comment]
All is now fixed, thanks to your comments. I was missing the 'make dist' step and also creating the tar file incorrectly - once they were fixed it all worked without problems apart from a minor hiccup. I was getting the following error when I did the make: 'aclocal-1.15' is missing on your system. - that was resolved by running this command "autoreconf -f -i" and after that it all ran smoothly

Thanks for your earlier post and I hope you have a good week-end. :)
