### ISSUE TITLE
Unable to build when configuring with --disable-vrrp

### ISSUE THREAD

**Issue by casantos** [acassen/keepalived#537]
```
$ ./configure --disable-vrrp
[...]
Keepalived configuration
------------------------
Keepalived version       : 1.3.4
Compiler                 : gcc
Preprocessor flags       : 
Compiler flags           : -Wall -Wunused -Wstrict-prototypes -Wextra -g -O2
Linker flags             : 
Extra Lib                : -ldl -lssl -lcrypto 
Use IPVS Framework       : No
fwmark socket support    : Yes
Use VRRP Framework       : Yes
Use VRRP VMAC            : Yes
Use VRRP authentication  : Yes
With ip rules/routes     : Yes
SNMP vrrp support        : No
SNMP checker support     : No
SNMP RFCv2 support       : No
SNMP RFCv3 support       : No
DBUS support             : No
SHA1 support             : No
Use Debug flags          : No
Stacktrace support       : No
Memory alloc check       : No
libnl version            : None
Use IPv4 devconf         : No
Use libiptc              : No
Use libipset             : No
init type                : systemd
Build genhash            : Yes
Build documentation      : No
$ make
[..]
  CCLD     keepalived
core/libcore.a(main.o): In function `keepalived_main':
/work/keepalived/keepalived/core/main.c:789: undefined reference to `netlink_set_recv_buf_size'
collect2: error: ld returned 1 exit status
Makefile:459: recipe for target 'keepalived' failed
```
The problem can be fixed by applying the attached patch.
[0001-Fix-build-when-configured-with-disable-vrrp-patch.txt](https://github.com/acassen/keepalived/files/806537/0001-Fix-build-when-configured-with-disable-vrrp-patch.txt)

**Comment by pqarmitage** [comment]
Many thanks for this report.

While your patch does indeed enable compilation of keepalived without vrrp, it has reminded my of an exchange I had with Alexandre about why the checker process needed netlink notifications. Alexandre explained that the reason was for when ha_suspend is configured on a virtual server. This means that if the IP address of the virtual server ceases to exist on the server, then the virtual server will be removed.

This will often be used to allow a virtual server to only be enabled if a VRRP virtual IP address is configured (i.e. the vrrp instance is master). However the documentation says that ha_suspend simply follows whether the IP address is configured on the server. This means that manual addition/deletion of the relevant IP address, or scripts or other processes adding/deleting the IP address should cause addition/deletion of the virtual server.

What we really need to do is permanently enable the netlink ip address monitoring functionality of the checker process, so that ha_suspend works with --disable-vrrp.

I'll have a look so see if I can produce a patch to resolve this.

**Comment by pqarmitage** [comment]
Commit b6ff7b4 resolves building with --disable-vrrp. A number of other patches have also been applied that improves building with --disable-vrrp and --disable-lvs, and also some optimisation about netlink monitoring of added/deleted addresses and improvements in the operation of ha_suspend.

Many thanks for the report - it has ended up with a much greater improvement in keepalived than originally anticipated!
