### ISSUE TITLE
not able to advertise 2 virtual IP's

### ISSUE THREAD

**Issue by swapniil** [acassen/keepalived#545]
Hi,

I need to have a setup where there will be 2 virtual IP's for 2 different network interfaces.  I have tried with the latest version of keepalived(v1.3.4) and it won't worked.

See the configuration file's as below
**For MASTER**:
_global_defs  # Block id
{
 lvs_flush
}
vrrp_sync_group VG_1 {
 group {
   Alef_platform_OPR_IPS
  Alef_platform_Data_IPS
 }
}

vrrp_instance Alef_platform_IPS{
 state MASTER 
  interface eth0
  track_interface {
   eth0
  }
 virtual_ipaddress {
  192.168.166.8/24 brd 192.168.166.255 dev eth0 
 }
 virtual_router_id 100
  priority 150
  advert_int 1 
  notify /etc/alef/watchdog/watchdog.d/common/alef_vrrp_data_notification.py
}

vrrp_instance Alef_platform_OPR_IPS {
 state MASTER
  interface eth3
  track_interface {
   eth3
  }
 virtual_ipaddress {
  192.168.166.20/24 brd 192.168.166.255 dev eth3
 }
 virtual_router_id 120
  priority 150
  advert_int 1 
  notify  /etc/alef/watchdog/watchdog.d/common/alef_vrrp_data_notification.py
}_

**For Backup**:
_global_defs  # Block id
{
 lvs_flush
}
vrrp_sync_group VG_1 {
 group {
  Alef_platform_OPR_IPS
  Alef_platform_Data_IPS
 }
}

vrrp_instance Alef_platform_IPS{
 state BACKUP 
 interface eth0
 track_interface {
  eth0
  eth3
 }
 virtual_ipaddress {
  192.168.166.8/24 brd 192.168.166.255 dev eth0 
 }
 virtual_router_id 100
 priority 100
 advert_int 1 
 notify /etc/alef/watchdog/watchdog.d/common/alef_vrrp_data_notification.py
}

vrrp_instance Alef_platform_OPR_IPS {
 state BACKUP
 interface eth3
 track_interface {
  eth3
 }
 virtual_ipaddress {
  192.168.166.20/24 brd 192.168.166.255 dev eth3
 }
 virtual_router_id 120
 priority 100
 advert_int 1 
 notify /etc/alef/watchdog/watchdog.d/common/alef_vrrp_opr_notification.py
}_

Observations:
for single vrrp_instance it works fine. When I configure 2 vrrp_instance's then for every 2nd instance in vrrp_sync_group on every machine it gets status as MASTER. 
I am not sure if I did any wrong configuration but as it works for 1 IP, I guess it is configured correctly.

**Comment by pqarmitage** [comment]
There are two issues that I can see here:
1. The sync group refers to vrrp instance `Alef_platform_Data_IPS` which doesn't exist; the vrrp instance is declared as `Alef_platform_IPS`.
2. You are configuring the 192.168.166.0/24 subnet on both eth0 and eth3. If you want to only add the addresses to existing subnets, then specify /32 rather than /24. What networks do you have configured on eth0 and eth3; you probably just want to be adding an addresses within the already configured networks.

Also,
3. Is it intentional that for vrrp instance `Alef_platform_IPS` the master only tracks eth0, whereas the backup tracks eth0 and eth3.
4. You don't need to specify tracking the interface that the vrrp instance is configure on, so except for the `Alef_platform_IPS` backup instance, the track_interface statements could be removed, and for `Alef_platform_IPS` on the backup instance you only need to specify tracking eth3.

**Comment by swapniil** [comment]
My bad on configuration. Thank you @pqarmitage for correcting me.
