### ISSUE TITLE
VRRP/CHECK not working if compiled with debug option

### ISSUE THREAD

**Issue by vel21ripn** [acassen/keepalived#582]
Version v1.3.5

Build with "--enable-debug" gives a completely inoperable vrrp and checker.
In the procedure vrrp_daemon.c:start_vrrp_child() because of conditional compilation "#ifndef _DEBUG_" the code "prog_type = PROG_TYPE_VRRP" is not executed, which later leads to fatal errors in kernel_netlink_init().
The procedure check_daemon.c:start_check_child() has a similar error.
IMHO The conditional compilation "#ifndef _DEBUG_" in these cases is only needed for fork() code.

**Comment by pqarmitage** [comment]
The complication with this, as you identified is in keepalived_netlink.c where it takes different actions depending whether it is running the vrrp functionality or the checker functionality, and generally this is determined by which process is running the code.

Unfortunately, with --enable-debug, everything runs in a single process, and so the approach used for non-debug mode doesn't work.

I've put together a patch (attached) that I think should resolve the problem you are experiencing, and I would be grateful if you could try it and report back whether it resolves the problem or not. The patch applies to the current head of the master branch, although with a slight tweak it can be applied to v1.3.5.  If the patch resolves your problem I will submit a pull request.
[debug.patch.txt](https://github.com/acassen/keepalived/files/944236/debug.patch.txt)

**Comment by vel21ripn** [comment]
Yours patch is not helped. Can't run working configuration.
While I'm using this patch [keepalived-1.3.5-debug.patch.txt](https://github.com/acassen/keepalived/files/952812/patch-keepalived-1.3.5-debug.patch.txt)
I don't use lvs. vrrp only.

**Comment by pqarmitage** [comment]
The patch was using the wrong conditional compilation variable, so unfortunately wasn't doing anything. Commit b5a1118 adds the patch, but with the correct conditional compilation tests.

Are you in a position to try the lastest code from github to see if it works?

**Comment by pqarmitage** [comment]
Commits f8b33e6 and 0ef48a0 enable keepalived to work again with `--enable-debug` option, but there are still issues around initialisation and termination that aren't resolved.

For example, some of the code in start_vrrp() and start_check() does the same thing, and should only be called once if using `--enable-debug` and in that case it should be called from start_keepalived() (e.g. init_global_data(), kernel_netlink_init()). Similarly some of the code in stop_vrrp() and stop_check() should only be called once. Further some of the signal handling would need to be changed so that the parent process adds events when it receives SIGHUP, SIGTERM, SIGINT, rather than sending signals to the child processes.

It is felt that making these changes would be unduly disruptive to the code and risks introducing bugs. Since `--enable-debug` now works at least to some extent, unless there is a strong need for further changes we will not take this any further.
