### ISSUE TITLE
v1.3.2 crashs if no router_id specified with snmp

### ISSUE THREAD

**Issue by levin1** [acassen/keepalived#588]
I saw line in man for config: "default: local host name", so no need to specify. But then it segfaults in strlen at vrrp_snmp.c:2458.

```
 global_defs {
	vrrp_iptables A B
	enable_traps
	enable_snmp_keepalived
	enable_snmp_checker
	enable_snmp_rfc
}
vrrp_instance x {
	state BACKUP
	interface eth1
	virtual_router_id 1
	use_vmac eth1x
	priority 100
	no_accept
	version 2
	advert_int 1
	mcast_src_ip 1.1.1.1
	virtual_ipaddress {
		1.1.1.2
	}
}
```

**Comment by pqarmitage** [comment]
I have tried the above configuration and it doesn't cause a problem for me.

I've had a look at the code, and I assume that global_data->router_id is NULL, which then causes the segfault when calling strlen(NULL) at vrrp_snmp.c:2458. The only cause of this, as far as I can see, is if there is a problem in get_local_name() in lib/utils.c. For get_local_name() not to return a valid name, then either uname() or getaddrinfo() is failing, or res->ai_canonname is NULL.

Could you try applying the attached patch which will add some logging to get_local_name() so that we can try and ascertain where the problem is. Once you've added the log output to this issue report we will have a better idea about where the problem is.

In the meantime, I'll see if I can work up a patch to handle the situation of global_data->router_id being NULL, but what we really want to do is sort out why it appears to be NULL.
         
[lib_utils.c.diff.txt](https://github.com/acassen/keepalived/files/1019438/lib_utils.c.diff.txt)
