### ISSUE TITLE
vrrp_script logic (bug or feature?)

### ISSUE THREAD

**Issue by GreyKat** [acassen/keepalived#601]
Hello everyone,

the question itself is at the very end, you can skip the full story.

I'm working on switching my current setup Keepalived v1.2.13 (10/08,2014) to latest stable release Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2

In "old" keepalived.conf I have
```
vrrp_script check_increase_priority {
	script "[ -f /etc/keepalived/increase_priority ]"
	interval 1
	weight 50
}
```
so when I "touch" that file on backup node, it get +50 weight and transit to master state.
 Since in version 1.3.0 "bashism" was eliminated, I changed check to:
```
vrrp_script change_weight {
    script "/usr/local/sbin/change_weight_50"
    interval 5
    weight 50
}
```
and script itself:
```
#!/bin/bash
FILE=/etc/keepalived/remove_me_to_get_normail_weight_back

if [ -f $FILE ]; then
    exit 0
else
    exit 1
fi
```
So the behaviour is the same, but I'm getting log entry every 5 sec:
```
Keepalived_vrrp[38768]: /usr/local/sbin/change_weight_50 exited with status 1
```
To to get rid of this annoying log entries every 5 sec I decided to reverse the logic: 
script returns 0 when file doesn't exist (and 1 when it does) but vrrp_script decrease weight by 50.

After I changed `weight 50` to `weight -50` and restarted keepalived its logic has also changed.
Now it applies `weight -50` when script returns 1

So the question is: 
is that by design, that  vrrp_script triggered on `exit 0` when weight change is positive value, and on `exit 1` when weight adjustment is negative value?

**Comment by pqarmitage** [comment]
See doc/keepalived.SYNOPSIS:
A positive weight means that <rise> successes will add <weight> to the priority of all
VRRP instances which monitor it. On the opposite, a negative weight will be subtracted
from the initial priority in case of <fall> failures.

So yes, the behaviour you describe is by design.

BTW, a forthcoming version of keepalived will only log script exit statuses when the status changed. It also adds track_files whose contents are read whenever they change, and the numeric value read from the file is added to the priority of the vrrp instance (negative numbers to decrease it and positive numbers to increase it).

**Comment by pqarmitage** [comment]
Need to sort out ability to configure `script "[ -f /etc/keepalived/increase_priority ]"`

**Comment by pqarmitage** [comment]
The vrrp_script and notify_scripts are intended to be executable files, not scripts themselves, so the approach taken above to change `script "[ -f /etc/keepalived/increase_priority ]"` to `script "/usr/local/sbin/change_weight_50"` is the correct way to do it.
