### ISSUE TITLE
Defect? Flapping Master/Backup with arbitrary "Entering BACKUP STATE -> Transition to MASTER STATE"

### ISSUE THREAD

**Issue by kbaegis** [acassen/keepalived#617]
Hi all,

Horribly confused. About 10% of the time, this behaves appropriately with the master taking on the VIP and the backup waiting for a fault or interface to fail and lower the weighted priority. 

The remaining majority of the time the backup node arbitrarily gobbles up the master role immediately after transitioning to backup (where it's supposed to remain). Is this a defect? The inconsistent behavior is one problem at least. 

It's basically like the backup node is ignoring the election with the higher priority, despite clearly seeing it in the logs. 

[node2.conf.txt](https://github.com/acassen/keepalived/files/1121981/node2.conf.txt)
[node1.conf.txt](https://github.com/acassen/keepalived/files/1121982/node1.conf.txt)
[messages.txt](https://github.com/acassen/keepalived/files/1121983/messages.txt)

**Comment by pqarmitage** [comment]
First of all it is showing in your log file that it is reporting `unknown keyword 'preempt'`. Can you please fix that (preempt is the default so just delete it) - issues shouldn't be raised when keepalived is reporting the configuration to be invalid, unless the issue is about why it is reporting an unknown keyword. Having said that, it won't make any difference to your problem.

I'm not sure why you need the virtual routes. I think adding the virtual_ipaddress when MASTER should add the route if it doesn't already exist.

Why are you specifying `dont_track_primary`? 
From the log it looks as though, although tine can receive vrrp packets when it is in MASTER mode, it cannot receive packets in BACKUP mode. Can you provide answers to the following questions:
1. What kernel version are you running
2. What distro are you using
3. When keepalived isn't running, what addresses are configured on the tine.lab interface - can you post the output of `ip addr show tine.lab`.
4. The output of `cat /proc/sys/net/ipv4/conf/all/rp_filter`
5. The output of `cat /proc/sys/net/ipv4/tine.lab/rp_filter`

The answers to these questions may help identify what is happening.

**Comment by kbaegis** [comment]
Amazing response time! :)

1) 4.8.0-rc3
2) gentoo
3) tine is 172.23.0.3, prong is 172.23.0.2
4) output is 1 on both
5) 1

I want to set the subnets primary router to the VIP (172.23.0.1)

put preempt in the appropriate block. 

tine.lab/prong.lab are both internal ports on ovs which are access ports for a trunk bond on the phy.

**Comment by pqarmitage** [comment]
Re 3, can you confirm the addresses are 172.23.0.3/16 and 172.23.0.2/16.

When keepalived is backup (or not running), what is the route to 172.23.0.0/16? 

I think the virtual route `172.23.0.0/16 dev tine.lab src 172.23.0.1` will merely set the source address of packets originating from tine to be 172.23.0.1, which is not what you want. If tine originates a connection to another system it should use it's own IP address, and not the virtual IP address. The idea of VRRP is that all devices on the 172.23.0.0/16 subnet are permanently configured with the relevant routes via 172.23.0.1, and then either prong or tine has that address depending on which is master.

I find it works better if the virtual address in configured as a /32 address, i.e. 172.23.0.1/32, so change the virtual address block to be
```
virtual_ipaddress {
    172.23.0.1
}
```
(you don't need the dev tine.lab since that is the default).

I would suggest trying without the virtual routes configured, with the /32 and dev tine.lab/prong.lab removed) and removing the dont_track_primary, and see if you can get something working with that. It that still doesn't work, remove as much config as possible to something like:
```
! Configuration File for keepalived

global_defs {
   router_id prong
   vrrp_version 3
}

vrrp_instance VI_LAB {
    state BACKUP
    interface prong.lab
    virtual_router_id 52
    priority 150
    advert_int 1
    virtual_ipaddress {
        172.23.0.1
    }
}
```
and see if that works, and if so, build it up from there a step at a time.

BTW I don't think the vrrp_script_default will achieve anything (I know the config doesn't use it). Since keepalived is running the script, pidof will always be successful. Your configuration just means that any interface using it will not be able to come up for 10 seconds.

**Comment by kbaegis** [comment]
Awesome! Thank you. It's working now. The failback is a little sticky (15 consecutive requests for master election), but it's working!
