### ISSUE TITLE
Should it be allowed to have different priorities in sync-group?

### ISSUE THREAD

**Issue by levin1** [acassen/keepalived#624]

**Comment by levin1** [comment]
Ok, there is a warning in configuration example. But maybe it is possible to do some protection: ignore such configuration or switch only when instance with highest priority goes backup? It seems better than continuous selection.

**Comment by pqarmitage** [comment]
I don't think we can ignore the configuration, since that is what the user has requested, and I don't think switching only when the highest priority goes backup, since other vrrp instances in the sync group may be low priority that other routers, and then both routers would think they should be master (unless no-preempt is set).

Consider the following scenario:

Router 1
=======
vrrp id: 1 prio: 20

Router 2 (2 instances in sync group)
=======
vrrp id: 1 prio: 30
vrrp id: 2 prio: 20

Router 3
=======
vrrp id: 2 prio: 30

If Router 3 is up, it will be master for id 2, causing Router 2 to sync all instances to backup, and then Router 1 will become master for id 1. If Router 3 is down, then Router 2 will be able to become master for id 2, and since it is eligible to become master for id 1, it will become master for both instances and Router 1 will become backup for id 1. To summarise, if Router 3 is up, Router 1 and Router 3 will be masters, if Router 3 is down, Router 2 will be master for both instances.

This seems to me to be a valid use (if somewhat unusual) for a sync group, and it uses different priorities for the instances in the sync group (yes, the configuration in this simple case could be changed so that the priorities are the same, but some other more complicated scenarios may require different priorities).

As is always the case, it is possible to misconfigure keepalived and although sometimes that can be identified and a warning given, in scenarios like this I don't think it is possible to identify invalid configuration when looking at just one configuration.

I am happy to update the documentation to include a warning that except in unusual circumstances the priorities of all instances in a sync group should normally be the same.
