### ISSUE TITLE
No IPv4/IPv6 mixing in virtual_ipaddress allowed, but in virtual_routes

### ISSUE THREAD

**Issue by robert-scheck** [acassen/keepalived#631]
Issue #341 says:

> Commit 1e433b9 removed the ability to configure a mixture of IPv4 and IPv6 addresses since a) it didn't work, and b) it is not valid as specified in RFC 5798 (see paragraphs 5 and 5.2.9 at https://tools.ietf.org/html/rfc5798).

However, mixing IPv4 and IPv6 in `virtual_routes` still works as per keepalived 1.3.5. Does this make sense? I would expect that if mixing in `virtual_ipaddress` is not allowed, mixing in `virtual_routes` shouldn't be allowed either.

**Comment by pqarmitage** [comment]
It isn't possible to mix IPv4 and IPv6 `virtual_ipaddress` since the VRRP protocol doesn't support it. You can however have a mixture in `virtual_ipaddress_excluded`, since that doesn't have any impact on what is sent in the VRRP packets, and there are certainly people who use this.

Likewise, `virtual_routes` don't have any impact on what is sent in VRRP packets, and there may be users who want to run VRRP with one address family but add routes of the other address family when the VRRP instance is master. It doesn't cause any problems, doesn't conflict with the VRRP protocol, so why not allow it:

**Comment by robert-scheck** [comment]
Okay, if mixing IPv4 and IPv6 addresses in `virtual_routes` doesn't cause conflicts, I'm fine with it.
