### ISSUE TITLE
[Documentation?] macvlan/vmac configuration example not complete

### ISSUE THREAD

**Issue by Rocco83** [acassen/keepalived#636]
I am facing to vmac configuration for the first time.
I need to setup in an environment that enforce the mac address usage.

I would expect a way to define:
- ip address for the macvlan interface
- mac address for the macvlan interface

Looking at https://github.com/acassen/keepalived/blob/master/doc/NOTE_vrrp_vmac.txt#L58, in the example provided there is no explicit way to say if an ip virtual_ipaddress will be added into the main interface or the macvlan one.
Nor there is a way to define the mac address of the macvlan interface.

On the IP address,
For sure https://github.com/acassen/keepalived/issues/507 has highlighted that there is an issue , 
Is correct to state that any virtual_ipaddress entry should be added into the macvtap interface?

On the mac address,
https://tools.ietf.org/html/rfc5798#page-28 in "Virtual Router MAC Address" chapter, define the mac address that should be used, the documentation does not describe this topic.
"IPv4 case: 00-00-5E-00-01-{VRID} (in hex, in Internet-standard bit-order)"
I do not know if another mac address is legal or not, i would say yes, thus i am not sure about it (ie if filtered out in the code).
Is correct to state that the mac address SHOULD be changed?

Of course, as pointed out in https://github.com/acassen/keepalived/issues/507 a script that bring up the interface may trigger all of this functionalities.

What of the above does make sense and what not?
I would like to fill some PR at least to fix documentations and clarity doubts to newcomers as me, but i need before to be sure of the expectations.

**Comment by pqarmitage** [comment]
```
I need to setup in an environment that enforce the mac address usage.

I would expect a way to define:

    ip address for the macvlan interface
    mac address for the macvlan interface
```
The VRRP RFC (rfc5798) specifies the MAC address to be used, and therefore there is no option to specify it. The IP addresses that are added to the interface when the vrrp instance is master are specified in the `virtual_ipaddress` and `virtual_ipaddress_excluded` blocks of the config.

```
Looking at https://github.com/acassen/keepalived/blob/master/doc/NOTE_vrrp_vmac.txt#L58, in the 
example provided there is no explicit way to say if an ip virtual_ipaddress will be added into the main 
interface or the macvlan one.
```
The virtual_ipaddress(es) will be added by default to the interface that the vrrp instance is operating over (the macvlan if `use_vmac` is specified, otherwise the interface specified in the `interface` option). One can add `dev IFNAME` to the virtual_ipaddress entry, but it needs to be an interface that exists when keepalived reads its configuration (and hence not a macvlan created by keepalived).
```
Nor there is a way to define the mac address of the macvlan interface.
```
Correct - see above.
```
On the IP address,
For sure #507 has highlighted that there is an issue ,
Is correct to state that any virtual_ipaddress entry should be added into the macvtap interface?
```
See the description above regarding what interface a virtual_ipaddress is added to.
```
On the mac address,
https://tools.ietf.org/html/rfc5798#page-28 in "Virtual Router MAC Address" chapter, define the mac address that should be used, the documentation does not describe this topic.
"IPv4 case: 00-00-5E-00-01-{VRID} (in hex, in Internet-standard bit-order)"
I do not know if another mac address is legal or not, i would say yes, thus i am not sure about it (ie if filtered out in the code).
```
Using a different MAC address would not conform to the VRRP specification. keepalived allows various things to be configured that do not conform to the specification (such as not using a macvlan in which case the MAC address used will be that of the interface the vrrp_instance is using). At the moment we are not aware of a need to use a non-standard MAC address on a macvlan.
```
Is correct to state that the mac address SHOULD be changed?
```
To conform to the RFC it is necessary to specify `use_vmac` so that the correct MAC address can be used. I'm not sure if this answers your question.
```
Of course, as pointed out in #507 a script that bring up the interface may trigger all of this functionalities.
```
If you have some unusual requirements of an interface (such as a non-standard MAC address), then you could manually create the interface before running keepalived, and then configure keepalived to use that interface and don't specify `use_vmac`. Any needed IP addresses could also be added.
```
What of the above does make sense and what not?
I would like to fill some PR at least to fix documentations and clarity doubts to newcomers as me, but i need before to be sure of the expectations.
```
If you would like to provide some updates to the documentation then they will be gratefully received.
