### ISSUE TITLE
[Documentation?] How to run keepalived on another interface

### ISSUE THREAD

**Issue by Rocco83** [acassen/keepalived#637]
Current setup:
- two server (virtual in my case, but not important)
- two nic, one is a vlan and the other one is the physical nic
- one nic is on the "public" lan, one nic is on the "private" lan

Goal:
- Avoid to run VRRP traffic on the public NIC.
even if secure, it is always less secure then run it on a private NIC.

Possible caveat:
- Clear that running VRRP on a separate nic is possibly resulting in a not consistent situation. But as this is a VLAN running on top, this is of course a mitigation.
For sure this is a trade-off between security and reliability.

Consideration:
- `vrrp_sync_group` and `track_interface` may be both useful.
Seems that the first one is the recommended solution.
- The above setup is considered mainly on VLAN, but this may have some sense also on 2 separate NIC.

Possible solution: 
- use "dev" keyword for ip address.
As specified in: http://louwrentius.com/configuring-attacking-and-securing-vrrp-on-linux.html but this is not recommended as by https://github.com/acassen/keepalived/issues/408

I have not found any other documentation on the topic.
Which is the best solution that may be provided on this topic?

Of course, willing to document it somehow, through a PR.
If also the section/file that should be edited, or the folder in case a new file has to be done, are more then welcome.

**Comment by pqarmitage** [comment]
I'm not clear what the security issues are regarding running VRRP on the "public" NIC. So long as you don't use unicast for the VRRP packets, with the check that the received TTL is 255, the packets can only have originated from the local network.

However, assuming that what you want to do is run VRRP over the private network, with virtual ipaddresses in the public network, what I think you want is as follows:
`vrrp_sync_group`s won't help you since you only need one vrrp instance. You need to configure the vrrp instances to use the private interface, and configure track_interface to track the public interfaces. For the vrrp_ipaddresses, you need to specify dev PUBLIC_IF.

Let's say that the public interface is `eth0` with address 192.0.2.10/24, and the private interface is `eth0.100` with address 198.51.100.20/24.
```
vrrp_instance VI_0 {
    interface eth0.100
    virtual_router_id 1
    priority 250               # This will be a different value on the other router(s)
    use_vmac
    version 3                  # not necessary, but you may as well use the current protocol

    track_interface {
         eth0
    }

    virtual_ipaddress {
          192.0.2.200/32 dev eth0
    }
}
```

The virtual_ipaddress has a netmask of /32 since the 192.0.2.0/24 network already exists, and you are only adding the single address. If, on the other hand, the network does not already exist, then you would want something like:
virtual_ipaddress {
        203.0.113.200/24 brd 203.0.113.255 dev eth0
}

As you have identified, this is a trade-off against reliability. If the vlan stops functioning properly, the two VRRP instances will cease to see each other, and both will become masters, meaning that the virtual ip address will be configured on both systems simultaneously.

An alternative could be to run a vrrp instance on the public interfaces as well, but it doesn't configure any "useful" addresses. If the two vrrp instances are in a sync group, then you won't get the duplicate ip addresses on the public interfaces unless the public interfaces also become isolated:
```
vrrp_sync_group link_instances {
    group {
        real
        stop_duplicate
    }
}

vrrp_instance real {
    interface eth0.100
    virtual_router_id 1
    priority 250               # This will be a lower value on the other router
    use_vmac
    version 3                  # not necessary, but you may as well use the current protocol

    track_interface {
         eth0
    }

    virtual_ipaddress {
          192.0.2.200/32 dev eth0
    }
}

vrrp_instance stop_duplicate {
    interface eth0
    virtual_router_id 1
    priority 255                # use priority 254 on the secondary router.
    use_vmac
    version 3

    virtual_ipaddress {
        10.0.0.1/32            # a dummy address that isn't used. Make sure it is a private IP address
    }
```
