### ISSUE TITLE
Track virtual_server ?

### ISSUE THREAD

**Issue by avinchakov** [acassen/keepalived#657]
Hi,
I have two Ubuntu 14.04 and keepalived 1.2.23. My config:
Master:
```
vrrp_instance VI_1 {
        state                                   BACKUP
        interface                               eth0
        virtual_router_id                       1
        unicast_src_ip                          192.168.3.140
        unicast_peer {
                                                192.168.3.196
        }
        priority                                150
        smtp_alert
        nopreempt
        advert_int                              1
        virtual_ipaddress {
                                                192.168.3.111
        }
}

virtual_server 192.168.3.111 80 {
        delay_loop                              5
        lvs_sched                               wrr
        lvs_method                              DR
        protocol                                TCP
        virtualhost                             192.168.3.111
        real_server 192.168.3.140 80 {
                weight                          2
                inhibit_on_failure
                TCP_CHECK {
                        retry                   2
                        delay_before_retry      3
                        connect_port            80
                        connect_timeout         5
                }
        }
}
```

BACKUP:
```
vrrp_instance VI_1 {
        state                                   BACKUP
        interface                               eth0
        virtual_router_id                       1
        unicast_src_ip                          192.168.3.196
        unicast_peer {
                                                192.168.3.140
        }
        priority                                149
        smtp_alert
        advert_int                              1
        virtual_ipaddress {
                                                192.168.3.111
        }
}

virtual_server 192.168.3.111 80 {
        delay_loop                              5
        lvs_sched                               wrr
        lvs_method                              DR
        protocol                                TCP
        virtualhost                             192.168.3.111

        real_server 192.168.3.196 80 {
                weight                          2
                inhibit_on_failure
                TCP_CHECK {
                        retry                   2
                        delay_before_retry      3
                        connect_port            80
                        connect_timeout         5
                }
        }
}
```
Is it correct that I want to use such config for detection of web server state? I don't like the solution like "pidof nginx". 
But my config don't work the way I want it. When I shutdown web server, master does not switch to another server(.
I have only logs:

> Keepalived_healthcheckers[29692]: TCP connection to [192.168.3.140]:80 failed.
> Keepalived_healthcheckers[29692]: TCP connection to [192.168.3.140]:80 failed.
> Keepalived_healthcheckers[29692]: TCP connection to [192.168.3.140]:80 failed.
> Keepalived_healthcheckers[29692]: Check on service [192.168.3.140]:80 failed after 2 retry.
> Keepalived_healthcheckers[29692]: Disabling service [192.168.3.140]:80 from VS [192.168.3.111]:80
> Keepalived_healthcheckers[29692]: Lost quorum 1-0=1 > 0 for VS [192.168.3.111]:80

**Comment by pqarmitage** [comment]
My understanding is that you would like the vrrp instance to cease to be master if the http server is not responding. Unfortunately keepalived does not have any functionality to reduce the priority of a vrrp instance in the event of a real_server becoming unavailable. Consequently I don't think the virtual_servers are achieving anything in your configurations.

A few thoughts are:
1. You could add a sorry_server to the virtual_servers, each pointing to the other server's real IP address, so that if the http server on the master fails, it will forward all http traffic to the other server. In the Master config, you would add `sorry_server 192.168.3.196 80` in the virtual_server block, and likewise `sorry_server 192.168.3.140 80` on the backup server.

2. You could stop using virtual servers altogether, and use a track_script without a weight configured on the vrrp instances. The script would need to attempt to connect to the local http server, and return a non zero exit code if the connection is unsuccessful. The script could be something like:
```
(echo >/dev/tcp/127.0.0.1/80) >/dev/null 2>&1
exit $?
```

I think option 2 is the simplest. This removes the need for virtual servers, and if the local http server ceases to accept connections, the vrrp instance will go into fail state. Once the http server is responding again, the vrrp instance will become backup, and then if it is the master machine will transition to master.

**Comment by avinchakov** [comment]
> Unfortunately keepalived does not have any functionality to reduce the priority of a vrrp instance in the event of a real_server becoming unavailable
very bad( Thanks for the advice. How to do through scripts I know.
