### ISSUE TITLE
Can keepalived enter backup state and remove VIP

### ISSUE THREAD

**Issue by chenzhiwei** [acassen/keepalived#672]
Hi, I am running keepalived inside container, when I run `docker rm` to remove the container, the VIP still on the interface.

This will cause some issues when I restart the keepalived container, since the MASTER maybe some one else. This will cause two nodes both have VIP.

My case:

1. Start Keepalived container on node1

    The node1 is MASTER and VIP will be assigned to node1.

2. Start keepalived container on node2

    The node2 is BACKUP.

3. Remove keepalived container on node1 and node2

    This will cause VIP still on node1.

4. Start keepalived container on node2

    The node2 is MASTER and VIP will be assigned to node2. **But meanwhile, the VIP is also on node1**.

5. Start keepalived container on node1

    The node1 is BACKUP and keepalived does not remove the VIP.

Is there a way to let keepalived remove VIP when it enters to BACKUP state? This will solve the following issue.

**Comment by pqarmitage** [comment]
The problem is that by running `docker rm` you are not allowing keepalived to terminate cleanly, which is when it does its cleanup. What you need to do before `docker rm` is `kill -TERM $(cat /var/run/keepalived.pid)` in the docker environment and then wait a couple of seconds to allow keepalived to complete its termination cleanup. Then it is safe to do `docker rm`.

I don't know if there is a way to set up a docker container so that on termination it executes some shutdown code. If there is, then it would be useful to configure the container to do the `kill -TERM`. If anyone knows, it would be very useful to hear how to do it.

**Comment by pqarmitage** [comment]
Depending on how your container is set up, if keepalived is PID 1 in the container, then executing
`docker stop CONTAINER_ID` will send a SIGTERM to keepalived which will cause keepalived to execute an orderly shutdown and remove any IP addresses that it added.
