### ISSUE TITLE
CentOS7 build fails because of unpackaged README

### ISSUE THREAD

**Issue by wonderg** [acassen/keepalived#675]
1.3.8 generates two README files 

./BUILDROOT/keepalived-1.3.8-2.x86_64/usr/share/doc/keepalived/README
./BUILDROOT/keepalived-1.3.8-2.x86_64/usr/share/doc/keepalived-1.3.8/README

and this turns to an error during rpmbuild execution:

```
Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/jenkins/workspace/RPM-Keepalived-Any-Branches/BUILDROOT/keepalived-1.3.8-2.x86_64
error: Installed (but unpackaged) file(s) found:
   /usr/share/doc/keepalived/README


RPM build errors:
    Installed (but unpackaged) file(s) found:
   /usr/share/doc/keepalived/README
```

I remove this additional README file within %install section and it works for me

```
%install
%{__rm} -rf %{buildroot}
%{__make} install DESTDIR=%{buildroot}
# Remove "samples", as we include them in %%doc
%{__rm} -rf %{buildroot}%{_sysconfdir}/keepalived/samples/
#The line below was added
%{__rm} -rf %{buildroot}/usr/share/doc/keepalived/README
```
But it would be better to fix that at Makefile level

**Comment by pqarmitage** [comment]
I've just run a make using the keepalived-1.3.8 tarball, and I'm not seeing the problem you describe.

Can you post the keepalived.spec file that you are using and I'll see if I can generate the problem, or is it the keepalived.spec file included in the package?

**Comment by pqarmitage** [comment]
There is a difference between Fedora 26 and CentOS7 which means that building the rpm package on Fedora works without a problem, but on CentOS7 it fails.

The difference is on Fedora 26:
`DOCDIR=/home/quentin/rpmbuild/BUILDROOT/keepalived-1.3.8-2.x86_64/usr/share/doc/keepalived`
whereas on CentOS 7
`DOCDIR=/home/quentin/rpmbuild/BUILDROOT/keepalived-1.3.8-2.x86_64/usr/share/doc/keepalived-1.3.8`

This means that on Fedora, `make install` and the `%doc AUTHOR ChangeLog CONTRIBUTORS COPYING README TODO` .spec file statement copy the README file to the same location, whereas on CentOS the two statements copy README to two different locations.

We don't want to modify the Makefile, since we want `make install` to install the README, especially if it is being executed outside an rpmbuild environment. But also, we can't add `%{__rm} -rf %{buildroot}/usr/share/doc/keepalived/README` to the rpm spec file, since that would break builds on Fedora amongst other systems.

Commit 3f72222 resolves the issue. It turns out that the fix to the .spec file suggested above is the best solution.
