### ISSUE TITLE
i met a mistake

### ISSUE THREAD

**Issue by altwei** [acassen/keepalived#678]
![image](https://user-images.githubusercontent.com/21077127/31760699-22298ac6-b4e8-11e7-856b-56914ba3f3cc.png)

![image](https://user-images.githubusercontent.com/21077127/31760753-51bb8f14-b4e8-11e7-870f-7f914471c1e5.png)

![image](https://user-images.githubusercontent.com/21077127/31760777-61912340-b4e8-11e7-95fd-eca3ca4df604.png)

I'm a newbie，the system is centos7；
Excuse me for my poor English；
Rely on dictionaries；

**Comment by altwei** [comment]
damn，I didn't configure email service. 
Delete email related code

**Comment by pqarmitage** [comment]
Can you provide the output of:
`keepalived -v`
`uname -a`
`getenforce`
`rpm -q selinux-policy`

Are you running keepalived directly on the host CentOS7 system, or is it being run in a container or a virtual machine?

Also, try running keepalived from the command line rather than using systemd to start it:
```
systemctl stop keepalived.service
keepalived -DRMmf /etc/keepalived/keepalived.conf
```
`-D` provides detailed logging
`-R` stops keepalived repeatedly respawning after SIGSEGV
`-m-` requests keepalived to produce a coredump if it terminates abnornally
`-M` updates /proc/sys/kernel/core_pattern
`-f` just specifies the config file

If keepalived produces a core file - it should be /core.PID, then run the following:
```
gdb keepalived /core.PID
bt
```
and post the output of the `bt` command in this issue.

There have been some recent problems with running keepalived on CentOS7, which are discussed in issue #654 (there is a summary of the issues near the end) and also issue #650. Usually ensuring the system is booted with the latest selinux-policy (if running selinux) and building a slightly later version of keepalived - from commit 47b5e44 or later resolves the problem.

**Comment by altwei** [comment]
@pqarmitage 
Thanks for your reply. 
I just got home and built the environment again.

![image](https://user-images.githubusercontent.com/21077127/31770836-30d41342-b50c-11e7-8cb8-794bc34d726d.png)

![image](https://user-images.githubusercontent.com/21077127/31770881-746ae676-b50c-11e7-830f-aaa3d3cb50a1.png)

![image](https://user-images.githubusercontent.com/21077127/31770891-7d9f4372-b50c-11e7-9351-1943b3f77b52.png)

Yes, I tested it on a virtual machine.
I am Chinese.  
I've been searching for a long time on the domestic search engine. 
Some pictures failed to upload.

**Comment by altwei** [comment]
Using your code seems to solve the problem.
But, Restarting service and error again (192.168.1.162).

![image](https://user-images.githubusercontent.com/21077127/31771649-7c869e10-b50f-11e7-8e27-a846abe41875.png)

![image](https://user-images.githubusercontent.com/21077127/31771657-88d870d0-b50f-11e7-8a64-a16768114ebe.png)
`abc`

**Comment by altwei** [comment]
Just as you say.
"try running keepalived from the command line rather than using systemd to start it:"
Your method can be successful.
Why ? 

```
systemctl stop keepalived.service
keepalived -DRMmf /etc/keepalived/keepalived.conf
```

**Comment by pqarmitage** [comment]
@altwei from a screenshot you sent me separately you have selinux-policy-3.13.1-102.el7 installed. You need to upgrade that to selinux-policy-3.13.1-166.el7_4.4 or later.

There can be some issues with keepalived-1.3.5 when running in a virtual machine. You will need to download a later version of the source code and build it yourself. You need at least commit 47b5e44 or alternatively you could just download version 1.3.8 and build that. There is further information in commit #654.

The purpose of running
`keepalived -DRMmf /etc/keepalived/keepalived.conf`
was to try to produce a core file which could then be analysed with gdb to see exactly where keepalived was segfaulting.
Starting keepalived via systemctl after running keepalived manually shouldn't have made any difference to whether keepalived worked or not.

**Comment by altwei** [comment]
@pqarmitage  Thanks, pqarmitage.  I'll try
