### ISSUE TITLE
LEDE/openwrt compilation error on libipvs.c netlink include not found

### ISSUE THREAD

**Issue by feckert** [acassen/keepalived#680]
I want to update the "keepalived" in the openwrt package feed to the current version 1.3.7
https://github.com/openwrt/packages/blob/master/net/keepalived/Makefile because the version is very old.
I have also update the configure options which are not supported anymore.
And removed the patches which do not apply anymore.
Every thing compiles and works as expected.

But if i remove the "--disable-lvs" configure option to get lvs support the build process complains the it does not find "netlink/netlink.h" in libipvs.c!
https://github.com/openwrt/packages/blob/9b9ef2375d46e5f2eefafe00cd188764287257c4/net/keepalived/Makefile#L47

Netlink support is already used and is compiling before i removed the --disable-lvs configure option.
There is nothing wrong on this lines https://github.com/acassen/keepalived/blob/84b48421870457c40d801b02968345affd6dadeb/keepalived/check/libipvs.c#L31-L34

Could any one give me a hint what the problem could be?
I have no solution!

**Comment by pqarmitage** [comment]
It's a long time since I used OpenWrt, and the build system seems to have changed since then, so I'm not up-to-date with how it all works any more.

At around about line 466 in configure.ac there is a check
`$PKG_CONFIG --exists libnl-3.0`
and if that is successful, that calls
`add_pkg_config([libnl-3.0], ...`
This in turn calls
`$PKG_CONFIG --cflags-only-I libnl-3.0` (so far as I can see OpenWrt is using libnl3)
This needs to return a path such that PATH/netlink/netlink.h exists (and is also the correct file for the build).

configure.ac uses $PKG_CONFIG quite extensively (it is defined by the call of PKG_PROG_PKG_CONFIG), and that will need to return the correct patch for include files and libraries for the build that you are doing. So see what configure has established, look at the definitions of KA_CPPFLAGS, KA_CFLAGS and KA_LIBS in config.log.

The build of keepalived is extensively influenced by what functionality is supported by the kernel, so it is extremely important that the right kernel headers are used when building keepalived.

**Comment by pqarmitage** [comment]
I meant to add that the latest version of keepalived is v1.3.8.

**Comment by feckert** [comment]
Thanks for your help and hint i will check this in the next days.
I know now where i have to check up.
@pqarmitage thanks :-)
