### ISSUE TITLE
keepalive vip can be achieved in different segments?

### ISSUE THREAD

**Issue by msdemt** [acassen/keepalived#709]
Hello everyone,

Can I install keepalive on different network segment？

host1:
centos7  192.168.14.5
host2:
test 192.168.15.3

192.168.14.5 can ping 192.168.15.3 and 192.168.15.3 can ping 192.168.14.5

Here are my keepalive.conf
**host centos7:**
# cat /etc/keepalived/keepalived.conf
! Configuration File for keepalived
global_defs {
router_id centos7
}
vrrp_instance VI_1 {
state MASTER
interface ens33
virtual_router_id 146
priority 100
advert_int 1
mcast_src_ip 192.168.14.5

authentication {
auth_type PASS
auth_pass 87654321
}
virtual_ipaddress {
192.168.14.6/24
}
}

**host test**
# cat /etc/keepalived/keepalived.conf
! Configuration File for keepalived
global_defs {
router_id test
}
vrrp_instance VI_1 {
state BACKUP
interface ens33
virtual_router_id 146
priority 10
advert_int 1
mcast_src_ip 192.168.15.3

authentication {
auth_type PASS
auth_pass 87654321
}
virtual_ipaddress {
192.168.14.6/24
}
}

Both servers have vip

**host centos7**
# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:0c:29:45:26:9c brd ff:ff:ff:ff:ff:ff
    inet 192.168.14.5/24 brd 192.168.14.255 scope global ens33
       valid_lft forever preferred_lft forever
    inet 192.168.14.6/24 scope global secondary ens33
       valid_lft forever preferred_lft forever
    inet6 fe80::fa91:67cb:d578:4e29/64 scope link 
       valid_lft forever preferred_lft forever

**host test**
# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:0c:29:c9:b2:37 brd ff:ff:ff:ff:ff:ff
    inet 192.168.15.3/24 brd 192.168.15.255 scope global ens33
       valid_lft forever preferred_lft forever
    inet6 fe80::21d6:e8ff:299c:9f45/64 scope link 
       valid_lft forever preferred_lft forever
3: ens34: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 00:0c:29:c9:b2:41 brd ff:ff:ff:ff:ff:ff
    inet 1.1.0.49/16 brd 1.1.255.255 scope global ens34
       valid_lft forever preferred_lft forever
    inet6 fe80::229c:69ff:452b:1189/64 scope link 
       valid_lft forever preferred_lft forever

The system is centos7.2
Has closed the firewall and selinux

How can I Do ? Help
Thanks

**Comment by pqarmitage** [comment]
Whether this could work depends on your network topology, in particular how the network segments 192.168.14.0/24 and 192.168.15.0/24 are connected. If there is layer 3 routing between them then your configuration will not work. The other question is how will the address 192.168.14.6 be reached when **test** is master, since there is presumably a different route to 192.168.14.0/24 installed on **test** so that it can ping 192.168.14.5.

If there is layer 3 routing between 192.168.14.0/24 and 192.168.15.0/24 then you will need to use `unicast_peer` and `unicast_src_ip`. On **centos7** change the virtual_ipaddress to be `192.168.14.6`, i.e. remove the /24, since the network already exists on that host. The only question then remains is how will 192.168.14.6 work when **test** is master, since the routing for 192.168.14.0/24 presumably will not forward traffic to the 192.168.15.0/24 network.

**Comment by msdemt** [comment]
@pqarmitage Thank you for your reply。My network should not be able to configure keepalive vip
