### ISSUE TITLE
Startup errors

### ISSUE THREAD

**Issue by sergefonville** [acassen/keepalived#710]
Hi,

I am trying to setup keepalived with haproxy.
When I start keepalived using `keepalived -f /etc/keepalived/keepalived.conf -l -n` I get the following output:
> Starting Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2
> Unable to resolve default script username 'keepalived_script' - ignoring
> Opening file '/etc/keepalived/keepalived.conf'.
> Starting Healthcheck child process, pid=13481
> Initializing ipvs
> Starting VRRP child process, pid=13482
> Registering Kernel netlink reflector
> Registering Kernel netlink command channel
> Error while registering gratuitous ARP shared channel
> Opening file '/etc/keepalived/keepalived.conf'.
> IPVS: Can't initialize ipvs: No such file or directory
> Keepalived_vrrp exited due to segmentation fault (SIGSEGV).
>   Please report a bug at https://github.com/acassen/keepalived/issues
>   and include this log from when keepalived started, what happened
>   immediately before the crash, and your configuration file.

keepalived.conf
```
global_defs {
    router_id haproxy01
    vrrp_version 3
}

vrrp_script check_haproxy {
    script "/etc/keepalived/check_haproxy.sh"
    interval 0.05
    fall 2
    rise 2
}

vrrp_instance haproxy_instance {
    state MASTER
    interface haproxy01vnic0
    virtual_router_id 25
    priority 150
    advert_int 0.05
    virtual_ipaddress {
        192.168.1.25/2 label haproxy01vnic0:0
    }
    track_script {
        check_haproxy
    }
}
```

/etc/keepalived/check_haproxy.sh
```
#!/bin/bash
kill -0 $(cat /run/haproxy.pid) && echo 'OK' && exit 0 || echo 'NOK' && exit 1
```

I am running CentOS Linux release 7.4.1708 (Core) on an OmniOS LX branded zone.

What do I need to do to fix these issues:

- Error while registering gratuitous ARP shared channel
- IPVS: Can't initialize ipvs: No such file or directory
- Keepalived_vrrp exited due to segmentation fault (SIGSEGV).

Thanks a lot in advance!

**Comment by rohara** [comment]
Is SELinux enabled? If so, try updating your selinux-policy.

**Comment by sergefonville** [comment]
When I execute `getenforce` it outputs `Disabled`
> [root@haproxy01 ~]# getenforce
> Disabled

**Comment by pqarmitage** [comment]
@sergefonville Are you running keepalived in a container? There are issues with running keepalived in a container unless the container is given sufficient privileges to be able to load kernel modules in the host kernel. 

The error message `IPVS: Can't initialize ipvs: No such file or directory` is typically what is seen when running keepalived in a container when the ipvs module isn't loaded in the host kernel. There was also a problem in the keepalived version you are using if the kernel was built with ipvs built into the kernel rather than being a loadable module. Commit dac727e resolved the issue of keepalived segfaulting if it couldn't load the ipvs module and the previous commit resolved a similar segfault if the modules needed for iptables/ip6tables support couldn't be loaded. These are only 7 commits on from the version you are using, although it might be best to use v1.3.9 or the latest version from git.

If you are running keepalived in a container, it is recommended that you update to the latest version of keepalived from git, and also ensure that the ip_vs, and the modules for iptables, ip6tables and ipset are all loaded prior to starting the container.

I've not seen the error `Error while registering gratuitous ARP shared channel` before, but it would be good to eliminate the other issues first, so we can focus on a smaller set of problems.

**Comment by pqarmitage** [comment]
Closing due to no response for over 1 month.

**Comment by sergefonville** [comment]
I am running keepalived in a OmniOS (Solaris) zone, that is probably the reason since it seems there is no Linux kernel in an LX branded zone.

**Comment by pqarmitage** [comment]
keepalived is only designed to work with the Linux kernel, and so far as I can tell using an OmniOS (Solaris) zone means that the kernel will be a Solaris based kernel.

In order to be able to run keepalived on a system running OnmiOS it would be necessary to run a full virtual machine which boots a Linux kernel.
