### ISSUE TITLE
What information gets adverstized when the primary system goes down?

### ISSUE THREAD

**Issue by LolikaPadmanbhan** [acassen/keepalived#711]
hi,
I am trying to understand what keepalived does and how it works. But am reading the user guide the information is not in detail. it just gives very upper layer information, its very difficult to know the actual process for fresher like me. so, i have few doubts it might look simple but didn't understand, kindly respond for these questions.
  
1. will the healthcheck happens in both primary and secondary?
2. if yes how frequently it happen who will inform that primary is down? and on what basis they say that?
3. As i understood when primary machine goes down it ll advertise to the other systems. can anyone tell me what information gets advertised and who does it.?

Kindly help me out by answering this.
Thanking you.

**Comment by knorrie** [comment]
Hi, I think you're mixing up two things, which makes it confusing.

A. The vrrp component in keepalived makes it possible to have an IP address that is active on a master instance and which fails over to another host running keepalived when the master crashes. The standby host listens to the master which is continously yelling "I'm still here!" "I'm still here!" "I'm still here!" "I'm still here!"... until it disappears, and then it'll put the IP address on its own interface. Of course the failover can also be triggered manually when doing maintenance.

B. The health checks are something else. Using keepalived and ipvsadm you can build a L3/L4 load balancer solution. The vrrp part seen above can make sure the IP address facing the outside world keeps being available. The health checks check the availability of backend servers that traffic is load balanced to. This can e.g. be a web server or dns or smtp etc... If a health check fails, a backend server will be taken out of the list with servers to send load balanced traffic to.

So A and B serve a different purpose.

Now to answer your questions:

1. If you have two hosts running keepalived, where one of the two handles incoming traffic as a load balancer, then still both of them will do the health checks and adjust the load balancing rules. The host who isn't master is just not currently processing traffic.
2. Usually no one is informing a primary is down, but it's the reverse way. If you don't see messages from the primary any more telling "Hey! I'm still here!!", then the backup assumes it's gone. For health checks to backend servers, it's the same. Check fails, backend server isn't reachable? Take it out of the list.
3. You should know this answer now. If the primary is down, it doesn't advertise anything any more, because it's down. :-)

HTH,
Knorrie
