### ISSUE TITLE
How to set a healthcheck for particular process in keepalived.conf?

### ISSUE THREAD

**Issue by LolikaPadmanbhan** [acassen/keepalived#712]
Hey,
I have installed and configured keepalived in 2 ubuntu16.04 machine using sudo apt-get install keepalived.
Now i want to run one process and monitor it. if that gets killed in primary i want that to be up and running in secondary. so what configuration i should do in keepalived.conf
kindly help me out. Below is my keepalived.conf file.
#( the same configuration with different priority is done on another device)
 ! Configuration File for keepalived 
   global_defs{
           notification_email {
           xxxxx@xxx.com
           }
           notification_email_from xxxxx@xxx.com
            smtp_server 127.0.0.1
            smpt_connect_timeout 30
  }
  
  vrrp_instance VI_1 {
          state MASTER
          interface
          virtual_router_id 51
          priority 101
          advert_int 1
          authentication {
                  auth_type PASS
                  auth_pass 1111
          }
          virtual_ipaddress {
                  10.10.0.1
          }
  }

Thanking you in advance.

**Comment by knorrie** [comment]
As seen in #711 the health checks in keepalived configuration are part of the configuration for builidng a load balancer solution using LVS http://www.linuxvirtualserver.org/whatis.html

Keepalived can be used without all of that, in which case it's just used to have an IP address that fails over to another host when the primary fails.

So, if I understand your example right, you just have two hosts, which both can offer the same service (themselves!). If the process on one of them fails, you also want the IP address to move to the secondary. The health check configuration will not help you in this case, because the only thing it can do is reconfigure load balancing rules on the fly (which you are not using).

**Comment by LolikaPadmanbhan** [comment]
@knorrie
 hi,
Thanks for the response. it was a good explanation my understanding got better.

Actually i want to use keepalived without load balancer. 
my problem is i want to use keepalived to moniter  a particular process which is running in my system.  **For example**: keepalived is running in both the systems with the above mentioned configuration and mean while i want to run a C program in one system which is primary as of now, if i kill process in the current machine (Master/Primary server) then automatically  it should switch to another server to continue its execution. is it possible in keepalived? if yes then how should i configure to do so?
I hope my question is clear and precise.
Thanks in advance ..

**Comment by pqarmitage** [comment]
Yes, this is possible, and it is something quite a few people do.

You need to configure a vrrp script such as:
```
vrrp_script haproxy {
    script "/usr/sbin/pidof C_program"
    interval 2
    timeout 1
}
```

In the vrrp_instance you need to add the following:
```
    track_script {
        haproxy
    }
```

This will execute pidof every two seconds, and if the pidof command fails, then the vrrp instance will transition to the fault state, thereby allowing the backup to start up.

The configuration given in issue 674 has the following alternative for the script definition:
```
vrrp_script haproxy {
        script "killall -0 haproxy" # cheaper than pidof
        interval 2 # check every 2 seconds
}
```

The slight disadvantage of this approach is that it has the overhead of executing a program every 2 (or however many you configure) seconds.

For both the previous and following versions, you may find using `no_preempt` helpful, depending on how you want the transitions to work.

There is a more efficient option that is available in the beta branch of keepalived by using a track_file. Add
```
vrrp_track_file haproxy {
    file "/var/data/haproxy.status"
}
```
and add to the vrrp instance
```
track_file {
    haproxy
}
```

You will now need to modify your C program so that at startup it writes a single byte with value 0 to /var/data/haproxy.status, and then forks a child process that does the work. The parent will need to do a waitpid() for the child and when it determines that the child has exited it writes a single byte with value 1 to the /var/data/haproxy.status file and terminates.

keepalived will monitor the /var/data/haproxy.status file and read its contents whenever it changes. If the first byte has a non-zero value, it will put the vrrp instance into fault state. If the file contains 0, the vrrp instance will transition out of fault state.

This has the advantage that there is negligible overhead, and code is only executed if the contents of the specified file change.

For both options, again depending on how you want things to work, you could specify a `notify_fault` script that executes your C_program if it is not already executing (this would also start the C_program when keepalived starts if the file contains a non-zero value). To really make things safe, you could also have a notify_backup script that executes the C_program if it is not running, so that if at startup the file contained a 0, you would then ensure that your C_program is started if it needs to be). Again, the beta version has a more efficient version of the notify scripts by using a notify_fifo, and a single process can monitor the FIFO and take whatever action it wants (e.g. re-executing the C_program if it is not running). Again this is more efficient that executing a script each time the fault transition occurs, although this shouldn't be a high overhead, but the motivation of notify_fifos was to ensure that notify events could be processed in the correct order, since using scripts was non deterministic.

**Comment by LolikaPadmanbhan** [comment]
@pqarmitage 
Thanks a lot...i could do it.

**Comment by lokeshh** [comment]
For me `pidof haproxy` didn't work but `pgrep haproxy` did.
