### ISSUE TITLE
Can i forward ipv6 to ipv4 service in the real server ?

### ISSUE THREAD

**Issue by sguphil** [acassen/keepalived#713]
can i forward ipv6 to ipv4 service in the real server ?

keepalived version:
Keepalived v1.2.23 (09/26,2016)

i have tried the following configuration in my lab, but  it doesn't work:
vrrp_instance intranet-vip6-ip {
	state BACKUP
	priority 100
        interface eth3
        virtual_router_id 8
        advert_int 1
        authentication {
            auth_type PASS
            auth_pass 1111
        }
        virtual_ipaddress {
            fdd6:5a50:af9e:1::5/64
        }
    }

 virtual_server fdd6:5a50:af9e:1::5/64 5555 {
		lb_algo rr
		lb_kind NAT
		#nat_mask 255.255.255.0
		protocol TCP
		real_server 10.175.147.247 3511 {
			weight 1
			TCP_CHECK {
				connect_timeout 3
				nb_get_retry 3
				delay_before_retry 3
				connect_port 3511
			}
		}
}

**Comment by pqarmitage** [comment]
First of all, the specification of virtual_server should be `virtual_server fdd6:5a50:af9e:1::5 5555`, i.e. remove the `/64`.

The simplest way to check is to see whether you can configure what you want with the `ipvsadm` command. If you can, then keepalived should be able to configure it (if keepalived can't configure it but ipvsadm can then report it as a bug).

A virtual server has an address family (IPv4 or IPv6), and the configuration parser checks that all addresses configured for a virtual server match the address family, so the configuration will not work.

I have checked your configuration with keepalived v1.3.9 and it logs the error message "Address family of virtual server and real server 10.175.147.247 don't match - skipping." keepalived v1.2.23 doesn't report this error, but it does report "IPVS: Invalid operation.  Possibly wrong module version, address not unicast, ..."

It also reports that VRRP version 3 does not support authentication (VRRPv3 is assumed since IPv6 is configured), and that the first IPv6 VIP address must be link local. It would be worth checking the log messages and fixing the configuration.

You would benefit from upgrading to the latest version of keepalived (v1.3.9), although your current configuration causes v1.3.9 to segfault (I have just committed a patch to resolve this), so you would need to either fix your configuration so that the virtual and real server ip address families match or use the latest source code.

**Comment by shuisheng** [comment]
thank you for fast replay.

1. I have tried the latest version of keepalived(v1.3.9), that occur error msg "Address family of virtual server and real server don't match"
2. Also I tryied ipvsadm add some rules as below:

>    ipvsadm -A -t [fdd6:5a50:af9e:10::5]:5555 -s rr
>    ipvsadm -a -t [fdd6:5a50:af9e:10::5]:5555 -r 10.172.36.89:80 -m

after that, run command "ipvsadm -Ln", shown as below:

> IP Virtual Server version 1.2.1 (size=4096)
> Prot LocalAddress:Port Scheduler Flags
>   -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
> TCP  [fdd6:5a50:af9e:10::5]:5555 rr
>   -> [aac:2459:af9e:10::5]:80     Masq    1      0          0

so, can I get the conclusion: LVS and keepalived both don't support ipv6 to ipv4 work mode?

**Comment by pqarmitage** [comment]
Your output of `ipvsadm -Ln` is very interesting, and is clearly a bug in ipvsadm, although it appears to have been fixed by ipvsadm v1.29. The first 4 bytes of the real server IPv6 address reported (`aac:2459:af9e:10::5`) when converted to decimal are 10 172 36 89, so the IPv6 address being reported is the IPV6 address of the virtual server, with the first 4 bytes overwritten by the IPv4 address configured.

If I try
```
ipvsadm -A -t [fdd6:5a50:af9e:10::5]:5555 -s rr
ipvsadm -a -t [fdd6:5a50:af9e:10::5]:5555 -r 10.172.36.89:80 -m
```
I get the error
`Different address family is allowed only for tunneling servers`
so it seems that it is possible to have an IPv6 virtual server and specify an IPv4 real server, but only if the IPv6 traffic is being encapsulated in (tunnelled over) IPv4, in other words it won't translate IPv6 traffic to IPv4, but will tunnel over it.

So,
```
ipvsadm -A -t [fdd6:5a50:af9e:10::5]:5555 -s rr
ipvsadm -a -t [fdd6:5a50:af9e:10::5]:5555 -r 10.172.36.89:80 -i
```
does work, and ipvsadm -Ln produces the following output:
```
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  [fdd6:5a50:af9e:10::5]:5555 rr
  -> 10.172.36.89:5555            Tunnel  1      0          0 
```

I can modify keepalived to support this tunnelling behaviour, but I'm not sure that is what you want.

**Comment by pqarmitage** [comment]
ipvsadm commit ed4a811f3329 introduced the restriction that the address families had to be the same unless tunnelling, and the first released version to support that feature was ipvsadm v1.29

**Comment by pqarmitage** [comment]
I have now merged a commit that allows the address family of tunnelling real servers to differ from the address family of the other real servers and the virtual server. We can't do any more than this since the kernel LVS code doesn't support direct translation from IPv4 to IPv6 or vice versa.

**Comment by pqarmitage** [comment]
Based on what I understand you want to achieve you can probably make it work using a combination of keepalived and NAT64 to do the IPv4 to IPv6 translation. There are a number of open-source implementations of NAT64 available for Linux, but which would be most appropriate is beyond the scope of keepalived.

If there is sufficient demand to integrate keepalived with a NAT64 implementation, or if someone wants to sponsor integrating keepalived with a NAT64 implementation, then we could investigate it further.
