### ISSUE TITLE
reloading with small advert_int cause a switchover

### ISSUE THREAD

**Issue by rik78** [acassen/keepalived#754]
When the slave keepalived is started the old master forces a switchover by going backup, even if the configuration contains nopreempt option, this happens with ka 1.3.9.
Is this the expected behavior?

> Jan 18 11:15:38 localhost Keepalived_vrrp[3222]: VRRP_Instance(VI_1) Received advert with **higher priority 253, ours 253**
> Jan 18 11:15:38 localhost Keepalived_vrrp[3222]: VRRP_Instance(VI_1) Entering BACKUP STATE

**Comment by pqarmitage** [comment]
@rik78 could you please provide copies of the configurations on your two systems so that I can test it.

**Comment by pqarmitage** [comment]
I have tried this with a simple test cast, and I can reproduce the problem if I have `state MASTER` in the vrrp_instance configuration. Without `state MASTER`, or with `state BACKUP` the issue doesn't occur.

The behaviour you are observing isn't correct, and it shouldn't need nopreempt either to stop it happening. For now you could simply remove the `state MASTER` but I will look at a fix for this problem.

RFC5798 states:
```
            (445) * If Preempt_Mode is False, or if the Priority in the ADVERTISEMENT is greater than or equal to the local Priority, then:
               (450) @ Set Master_Adver_Interval to Adver Interval contained in the ADVERTISEMENT
               (455) @ Recompute the Master_Down_Interval
               (460) @ Reset the Master_Down_Timer to Master_Down_Interval
            (465) * else // preempt was true or priority was less
               (470) @ Discard the ADVERTISEMENT
            (475) *endif // preempt test
```
so a backup router should not take over as master unless the priority received in an advert is strictly lower.

I have checked this with the beta branch, and that code does not exhibit this problem.

**Comment by pqarmitage** [comment]
I've looked at the code and thought about this a bit further. Can you confirm that you have `state MASTER` configured on both your systems. If so, when you configure nopreempt, you should get the warning in the log:
`(VI_0): Warning - nopreempt will not work with initial state MASTER`

I am assuming that you do have `state MASTER` configured, since I cannot reproduce this problem otherwise. If that is the case, then it could be argued that keepalived is behaving as you have requested and it starts in the master state; what is unhelpful is the error message, but keepalived would be performing correctly since RFC5798 states:
```
            (725) -* If the Priority in the ADVERTISEMENT is greater than the local Priority,
            (730) -* or
            (735) -* If the Priority in the ADVERTISEMENT is equal to
                           the local Priority and the primary IPvX Address of the
                           sender is greater than the local primary IPvX Address, then:
               ...
               (765) @ Transition to the {Backup} state
```
so I presume the primary IP address of the new master is higher than the primary IP address of the old master.

The right solution is to remove the `state MASTER` configuration, and then it should all work as expected.

I will have a look at the log message which states that 253 is higher than 253 which clearly isn't correct.

If my assumption is wrong and you don't have `state MASTER` configured, then please include a copy of your configuration so I can investigate further, otherwise it would be helpful if you could confirm that is the case and we can close this issue.

**Comment by pqarmitage** [comment]
@rik78 I've merge commit 497f173 which improves the log message which you reported.

**Comment by pqarmitage** [comment]
I've tested this with your configuration and I cannot reproduce the problem.

Could you please run keepalived with the -D option (detailed logging) on both your systems and provide the full logs from both systems from the time keepalived starts. We can then try and work out what is happening.

**Comment by rik78** [comment]
I think I've found the cause, since advert_int is very small sometimes when I send a sighup to master instance, the standby stop receiving adverts from master and initiate a failover.  I'm testing with this [config](https://gist.github.com/rik78/ac43523e954d7f8dbe685fc2828e0b47).

**Comment by pqarmitage** [comment]
I've tested your config, and in normal use it seems to work fine. I've also reduced the advert_int to 0.01 and that works too.

If you are reloading keepalived, with an advert interval of 0.33 secs (it is in units of 10ms), then the backup will consider that three advert intervals have elapsed somewhere between 0.66 and 0.99 seconds after the restart of the master commences. When the master restarts, after it has reloaded the configuration it will wait 1 advert interval before it sends an advert, so that means that the master has somewhere between 0.33 and 0.66 seconds to complete the shutdown of the old configuration, load the new configuration, work out the differences between the old and new configuration and make the necessary changes, otherwise the backup will timeout the master and take over as master itself.

If you can test it with a larger advert interval and the problem of the backup not preempting the master goes away, then I think you very likely have found the cause of the problem.

**Comment by rik78** [comment]
It happens more frequently with a bigger configuration and a slow machine. I don't know if I should close the issue or leave it open, since this is caused by an extreme condition.

**Comment by pqarmitage** [comment]
@rik78 This does sound as though this is down to the amount of time it is taking to do the reload. I think we can remove the wait of 1 advert interval before sending the advert, which should help to some extent, and we could also send an advert on every instance in master start immediately before the reload.

If that still doesn't sort it out for you, we could add a keyword `reload_advert_int`, so that the advert sent before the reload specifies a longer advert interval, thereby allowing longer for the reload to complete (this would only work with VRRPv3 though).

What are your thoughts about this?

**Comment by rik78** [comment]
Closed! thanks @pqarmitage
