### ISSUE TITLE
ystem

### ISSUE THREAD

**Issue by danrod1971** [acassen/keepalived#755]
Hello guys,
I'm trying to use Keepalived on 2 OVH dedicated server with no succes.
The process is respawning for ever and the log complains on IPVS: Can't initialize ipvs: No such file or directory.
If I try to list the modules load by the kernel I have this : 
lsmod
libkmod: kmod_module_new_from_loaded: could not open /proc/modules: No such file or directory
Error: could not get list of modules: No such file or directory

I think this is due to the kernel OVH ...
Any idea ?

thanks

**Comment by acassen** [comment]
hi,

maybe you should ask to OVH guys at first ;)

some people at OVH contributed code, so this could be a good starting point. If you are in a container and kernel doesnt support IPVS, then its gone a be tricky.

**Comment by danrod1971** [comment]
I create a request for OVH, i am waiting for the answer but I'm afraid to wait a long time. I'm not sure that it interests OVH. 
Otherwise I 'm not on docker.

**Comment by pqarmitage** [comment]
@danrof1971 You don't say what kernel/distro you are using, nor what version of keepalived; both would be helpful to know in advising what the problem is.

Since there is no directory /proc/modules, it sounds as though either the kernel is build without support for loadable modules or without the /proc filesystem. Can you check CONFIG_MODULES and CONFIG_PROC_FS in the kernel configuration and see if they are set to y or n. Can you also check CONFIG_IP_VS to see what that is set to. Attaching a copy of your kernel config file, either from /boot or /proc/config.gz (if that exists) would be helpful.

At one time there was a problem with keepalived when it would segfault if the ip_vs code was built into the kernel rather than a loadable module and it looks like it was either commit 5ca36cb5 or dac727e1 that resolved it, around the end of March last year meaning that the first version these patches were included in would be been v1.3.6.

There may be a further problem if the kernel is built without support for loadable modules or without the /proc filesystem, since I have never used a kernel without those, and keepalived may not be handling the situation correctly.

**Comment by danrod1971** [comment]
Sorry, here is the information : 
the kernel is 4.9.58-xxxx-std-ipv6-64 ( ovh specific )
The distrib is  centos 7.4.1708
The version of keepalive is 1.3.5-1

I thonk your are right the kernel doesn't support loadable module
As far I understand I can try with the 1.3.6 but it is not an clean installation and keepalive could be unstable ?

[config.gz](https://github.com/acassen/keepalived/files/1643452/config.gz)

**Comment by pqarmitage** [comment]
@danrod1971 I've had a look at your config.gz and indeed the kernel is built without loadable modules. The kernel is also built without IP_VS support (see `CONFIG_IP_VS is not set` in the config file).

It would be very helpful to know if there is a file `/proc/sys/kernel/modprobe` and if there is, what it contains.

Are you wanting to use Linux virtual servers, or are you just wanting to use keepalived for VRRP?
Commit 74a6c71f which also first appeared in keepalived v1.3.6 allows keepalived to run without attempting to initialise ipvs, but this only works if there are no virtual servers configured.

My recommendation regarding which version of keepalived to use would be the head of the master branch, which is currently v1.4.0 plus a few commits. If you want to use a released version, then v1.4.0 would be best, but you should apply commits d381daa and 4955985.

If you are wanting to use IPVS, i.e. virtual servers in keepalived, then you will need to use a different kernel since the OVH kernel doesn't support IP_VS. If you are just using the VRRP part of keepalived, then it should work with keepalived v1.3.6 onwards.

**Comment by danrod1971** [comment]
OVH confirm that the only way to use a Loadbalancer like keepalived with their kernel is to use their own loadbalancer
