### ISSUE TITLE
Lots of error happend when compiled at CentOS 6.9 with 1.3.9 version.

### ISSUE THREAD

**Issue by lxf1992521** [acassen/keepalived#759]
Did you try to compiled on latest centos 6.9 with 1.3.9 version when you release it ?

Env:
————————————————————————————
centos 6.9
kernel-2.6.32-696.el6.x86_64
m4-1.4.16-9.3.x86_64
autoconf-2.69-12.2.noarch
automake-1.11.1-4.el6.noarch
————————————————————————————

Lots of errors happend when i to to make it, there are lots of bugs:
1. O_PATH support on 2.6.32 kernel <issue: 703>
2. json.h not found <it is in json/json.h, not in json.h>
3. others like this
——————————————————————————————
check/libcheck.a(libipvs.o): In function `ipvs_nl_message':
/root/keepalived-1.3.9/keepalived/check/libipvs.c:223: undefined reference to `nlmsg_alloc'
/root/keepalived-1.3.9/keepalived/check/libipvs.c:227: undefined reference to `genlmsg_put'
check/libcheck.a(libipvs.o): In function `ipvs_nl_fill_service_attr':
/root/keepalived-1.3.9/keepalived/check/libipvs.c:390: undefined reference to `nla_nest_start'
/root/keepalived-1.3.9/keepalived/check/libipvs.c:394: undefined reference to `nla_put'
/root/keepalived-1.3.9/keepalived/check/libipvs.c:399: undefined reference to `nla_put'
/root/keepalived-1.3.9/keepalived/check/libipvs.c:400: undefined reference to `nla_put'
/root/keepalived-1.3.9/keepalived/check/libipvs.c:401: undefined reference to `nla_put'
/root/keepalived-1.3.9/keepalived/check/libipvs.c:404: undefined reference to `nla_put'
check/libcheck.a(libipvs.o):/root/keepalived-1.3.9/keepalived/check/libipvs.c:407: more undefined references to `nla_put' follow
check/libcheck.a(libipvs.o): In function `ipvs_nl_fill_service_attr':
......
/root/keepalived-1.3.9/keepalived/check/libipvs.c:680: undefined reference to `nla_put'
/root/keepalived-1.3.9/keepalived/check/libipvs.c:694: undefined reference to `nla_nest_end'
/root/keepalived-1.3.9/keepalived/check/libipvs.c:699: undefined reference to `nlmsg_free'
collect2: ld returned 1 exit status
——————————————————————————————

Thank you very much for your efforts to develop keepalived !
But it is too torture to compiled keepalived with 1.3.9

Hope rpm/deb binary packages, please forgive my rudeness.

**Comment by pqarmitage** [comment]
As issue #703 identifies, most of the issues you identified above are resolved but various commits, and those are included in keepalived v1.4.0.

The one issue that you refer to that isn't covered in #703 is building with json. The configure script uses pkg-config to determine the location of the json-c header files and library names, although there does seem to be an assumption that they are in /usr/include/json-c. On my Centos 6.9 VM the headers are in /usr/include/json-c, and keepalived v1.4.0 builds without any errors (there are lots of warnings but that is due to using an old compiler that doesn't detect initialisation of variables as well as more recent versions).

We have a policy of not backporting patches to earlier versions and so when the issues with v1.3.9 were identified and resolved, the first released version to support them was v1.4.0.

It would seem as though your simplest solution would be to use v1.4.0, I would suggest incorporating at least commits d381daa and 4955985

**Comment by lxf1992521** [comment]
Rebuild keepalived 1.4.0 with patch d381daa and 4955985 on CentOS 6.9, everything is OK, include json.
Thank you for your advice.

**Comment by acassen** [comment]
will release 1.4.1 based on current master repo.
