### ISSUE TITLE
the build will not support IPVS with IPv6 

### ISSUE THREAD

**Issue by Davidrjx** [acassen/keepalived#820]
1. Environment
keepalived 1.3.5 source code
OS system: Debian9 (stretch)  4.9.0-6-amd64
gcc: gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

2. build source
  when run ./configure , output "*** WARNING - this build will not support IPVS with IPv6. Please install libnl/libnl-3 dev libraries to support IPv6 with IPVS" but i install libssl-dev libnl-3-dev libnl-genl-3-dev libsnmp-dev dependencies

i want to resolve the warning, is there anyone having solutions?

**Comment by pqarmitage** [comment]
Have you installed all of:
iptables-dev libipset-dev libnfnetlink-dev libnl-3-dev libnl-genl-3-dev libnl-route-3-dev libssl-dev
(you don't mention libnfnetlink-dev or libnl-route-3-dev).

These requirements are listed in the INSTALL file.

Is there a reason why you are using v1.3.5? keepalived is now at v1.4.2.

**Comment by Davidrjx** [comment]
@pqarmitage thanks for your help, that is right as a few packages provided by you were omitted.
in my case, i use keepalived for k8s master's HA, now for specific versions

**Comment by pqarmitage** [comment]
@Davidrjx Can you confirm that you have resolved your problem and this issue can now be closed?

**Comment by Davidrjx** [comment]
@pqarmitage i'm sorry for another problem, just below
```
Mar 23 19:44:48 ***** Keepalived[42142]: Starting Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2
Mar 23 19:44:48 ***** Keepalived[42142]: WARNING - default user 'keepalived_script' for script execution does not exist - please create.
Mar 23 19:44:48 ***** systemd[1]: keepalived.service: PID file /usr/local/keepalived-1.3.5/var/run/keepalived.pid not readable (yet?) after start: No such file or directory
Mar 23 19:44:48 ***** Keepalived[42142]: Configuration file '/etc/keepalived/keepalived.conf' is not a regular non-executable file
Mar 23 19:44:48 ***** Keepalived[42142]: Stopped Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2
Mar 23 19:44:48 ***** systemd[1]: Failed to start LVS and VRRP High Availability Monitor.
-- Subject: Unit keepalived.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit keepalived.service has failed.
```

do i manually create keepalived-script user and /var/run under home dir?

**Comment by pqarmitage** [comment]
`Mar 23 19:44:48 ***** Keepalived[42142]: WARNING - default user 'keepalived_script' for script execution does not exist - please create.`
By default, keepalived will execute scripts as user keepalived_script or if that user doesn't exist, as root. Executing scripts with root privileges is not a good idea if the scripts don't need root privileges, so you will need to consider whether each script needs root privileges or not.

The best thing to do is to explicitly declare against each script what user you want the script to be run under, using `user USERNAME [GROUPNAME]` (i.e. GROUPNAME is optional). Alternatively if they can all be executed by the same user in `global_defs` you can add `script_user USERNAME [GROUPNAME]`. If for example all scripts need to execute with root privileges, then you could add `script_user root`.

If the user is specified for each script, either using `script_user` in `global_defs` or `script` for each script (or a combination of both since the script `user` statement will override `script_user` on a per script basis), then you don't need to add a `keepalived_script` user.

`keepalived.service: PID file /usr/local/keepalived-1.3.5/var/run/keepalived.pid`
keepalived by default creates pid files in /var/run. It appears that the keepalived.service file, or systemd configuration, on your system is expecting the pid file to be created in `/usr/local/keepalived-1.3.5/var/run`. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=860527 . It appears that you need to add to `/lib/systemd/system/keepalived.service` the line `PIDFile=/var/run/keepalived.pid` after the line `KillMode=process`

`Configuration file '/etc/keepalived/keepalived.conf' is not a regular non-executable file`
This suggests that `/etc/keepalived/keepalived.conf` is either executable of has some other strange file mode set.

**Comment by Davidrjx** [comment]
@pqarmitage much appreciation！as i am a freshman about keepalived, so faced with some puzzled problems. otherwise, could you please give some guide about my requirement, like two files:heathy_check.sh and keepalived.conf reside in /etc/keepalived/, starting service reports below error:
```
systemd[1]: Starting LVS and VRRP High Availability Monitor...
Mar 23 20:53:27 ****** Keepalived[51022]: Starting Keepalived v1.3.5 (03/19,2017), git commit v1.3.5-6-g6fa32f2
Mar 23 20:53:27 ****** systemd[1]: keepalived.service: PID file /var/run/keepalived.pid not readable (yet?) after start: No such file or directory
Mar 23 20:54:57 ****** systemd[1]: keepalived.service: Start operation timed out. Terminating.
Mar 23 20:54:57 ****** systemd[1]: Failed to start LVS and VRRP High Availability Monitor.
Mar 23 20:54:57 ****** systemd[1]: keepalived.service: Unit entered failed state.
Mar 23 20:54:57 ****** systemd[1]: keepalived.service: Failed with result 'timeout'
```
about keepalived config and use,below i paste two files' content in use, 
```
###keepalived.conf
! Configuration File for keepalived
global_defs {
    router_id LVS_DEVEL
}
  
vrrp_script check_apiserver {
    script "/etc/keepalived/check_apiserver.sh"
    interval 3
    weight -2
    fall 10
    rise 2
}
  
vrrp_instance VI_1 {
    state MASTER
    interface bond0
    virtual_router_id 51
    priority 3
    authentication {
        auth_type PASS
        auth_pass 4be37dc3b4c90194d1600c483e10ad1d
    }
    virtual_ipaddress {
        192.255.255.255
    }
    track_script {
        check_apiserver
    }
}

###check_apiserver.sh
#!/bin/sh

set -e

errorExit() {
    echo "*** $*" 1>&2
    exit 1
}

curl --silent --max-time 2 --insecure https://localhost:8445/ -o /dev/null || errorExit "Error GET https://localhost:8445/"
if ip addr | grep -q "192.255.255.255"; then
    curl --silent --max-time 2 --insecure https://192.255.255.255:8445/ -o /dev/null || errorExit "Error GET https://192.255.255.255:8445/"
fi

```

still please give some advice, thanks!

**Comment by pqarmitage** [comment]
Can you execute `systemctl start keepaqlived` and after it has failed run
`journalctl -t Keepalived -t Keepalived_vrrp -t Keepalived_healthcheckers --since=today`
and post that output here.

Can you also post the output of `ip addr show`.

I have run your configuration on a Debian 9 virtual machine using the standard Debian keepalived package, and it runs OK.

**Comment by pqarmitage** [comment]
Can you also try running keepalived directly from the command line - `/usr/sbin/keepalived -DRf /etc/keepalived/keepalived.conf`, or whatever the correct path is for keepalived. After running keepalived, can you also post the log output, as described above.

**Comment by pqarmitage** [comment]
Closing due to no response for 19 days. If you have any further issues, please post them here and the issue can be reopened.
