### ISSUE TITLE
feature request: environment to vrrp_script

### ISSUE THREAD

**Issue by lkarsten** [acassen/keepalived#837]
Hi.

I'd like to request a small new feature in keepalived, namely passing the configured and current status of the VRRP process to a vrrp_check script as an argument and/or environment variable.

This could be useful to allow for different flow in the check script if the configured state is different from the runtime state.

My use case is a simple two node active/passive setup that is only using vrrp.

In the case of an extra argument, the configuration file could grow a few macros like this:
```
vrrp_script foocheck {
    script "/etc/keepalived/healthcheck.sh %{CONFIGURED_STATE} %{RUNTIME_STATE} "
    # or:
    script_args "%{CONFIGURED_STATE} %{RUNTIME_STATE}"
}

vrrp_instance foo {
    state MASTER
    priority 100
[..]
    track_script {
        foocheck
    }
}
```

If passing through an environment variable is preferred, setting VRRP_INSTANCE_FOO_STATE="MASTER" and VRRP_INSTANCE_FOO_RUNSTATE="BACKUP" (or similar) would work.

**Comment by pqarmitage** [comment]
Could you please explain the reason for this request.

The currently supported way to determine the status of a vrrp instance is to use either notify scripts or a notify fifo.

**Comment by lkarsten** [comment]
Thanks for responding.

The envisioned use for this was as a way to work around #836. 

The check script on the master node would know that it was the active master and in that case the VIP should be in place in "ip addr". If the VIP was not in place, there is an error and the script should fail. If the master node for some reason was the backup (vip should not be there), the ip check part of the check script would not run.

On the backup node the VIP should not be looked for if the node is the passive one, but if it transitions into master/active state, the VIP must be in place for the node to be healthy.

The shell script doing the check would look something like: (freehand, untested)
shell cmd:  "./script.sh $current_state"
```
#!/bin/bash
pidof nginx || exit 1
pidof tomcat || exit 2
if [ "$1x" = "MASTERx" ]; then
    /bin/ip addr | grep -q 192.168.1.100 || exit 3
fi
```

In general this is a way to make vrrp_script more powerful to handle non-standard situations.

Using notify scripts was not an option since no state transition was happening.

**Comment by pqarmitage** [comment]
The notify script (or better the notify fifo handler) could record the latest state of a vrrp instance in a file, which could then be checked by the script you have outlined above.

Having said that, I think what you propose could be useful, and so I will add it to the list of things to implement. I think we will need to add an additional keyword such as `replace_parameters` in order to maintain backward compatibility with any scripts that already have %{...} sequences passed to scripts.

**Comment by pqarmitage** [comment]
@lkarsten I was just about to start implementing this when I realised that this proposal doesn't work.

A vrrp_script is not run in the context of a vrrp instance, and many vrrp instances can track the result of running the same script. Consider the following configuration extract:
```
vrrp_script SCRIPT {
    script /etc/keepalived/script.sh
    interval 60
    ...
}

vrrp_instance VI_0 {
     track_script {
          SCRIPT
    }
}

vrrp_instance VI_1 {
     track_script {
          SCRIPT weight -128
     }
}

vrrp_instance VI_2 {
     track_script {
          SCRIPT weight 128
     }
}
```

This means that the script /etc/keepalived/script.sh is run once per minute. A change from zero to non-zero exit status will cause VI_0 to go to fault state, VI_1 will have its priority reduced by 128 (possibly causing it to become backup), and VI_2 will have its priority increased by 128 (possibly causing it to become master).

So it simply isn't possible to have a `%{CONFIGURED_STATE} %{RUNTIME_STATE}` as parameters since there could be multiple different states for the various vrrp instances tracking the script.

Your suggestion of using environment variables could work, but has the disadvantage of potentially creating a very large environment; not only would users want configured state and runtime state, but also effective priority, time in current state, and perhaps several other variables, and these would need to be set for each vrrp instance, and there are some configurations with 500 vrrp instances. I therefore don't think this option is feasible.

I think the reason for these problems is that the suggestion doesn't fit with the design of keepalived. track_scripts are intended for the system to be able to notify keepalived of a condition that may change keepalived's behaviour, and not for keepalived to inform an external process about its own state.

Alternatives that would work currently without modification to the code are:
1. From a track_script, query keepalived for the state of an instance using SNMP; you would of course need to use a separately configured vrrp_script for each instance 
2. Use JSON to obtain the state of the vrrp instances (it may be that JSON support needs to be enhanced so that JSON output can be obtained over a socket)
3. Use notify scripts/fifos to update the state of each vrrp instance (perhaps in a database), and track_scripts could access that data when run
4. Use DBus to track the state of VRRP instances (similar to 3 above), and track scripts could access that data when run.

In order to implement what you originally proposed, I think it would require adding a script option to vrrp instances, so that the scripts are run with the context of a vrrp instance.

@lkarsten I see from issue #836 that you tried what is now the v2.0.x code which detects VIP removal, reverts to backup state, and when the veep instance becomes master again, the VIP will be restored. Does that resolve your problem and you no longer need this option of scripts with parameters?

Is there anyone else who sees a need to be able to run scripts with parameters in the context pf a vrrp instance?

If I don't get a response in the next 14 days I will close this issue, although if the need for scripts run in the context of VRRP instances subsequently arises, then this issue could be reopened.

**Comment by pqarmitage** [comment]
Closing since no update for over 4 weeks. If anyone has any further comments on this issue the issue can be reopened.
