### ISSUE TITLE
Issue due to maintaining VRRP subinterface in BACKUP router.

### ISSUE THREAD

**Issue by balmnm** [acassen/keepalived#882]
Hi All,
Im using keepalived version 1.3.9 , on top of Debian stretch to achieve VRRP functionality.
While testing IPv6 VRRP functionality, in the following setup, i have seen few issues.
```
             |-------------- Server  ------------|          
             |                                   |
   Router 1(R1) --------------Switch------- Router 2(R2)
                                 |
                               Host 

R1 and R2 are connected via Switch.
Host is connected only to switch.
Server has connection to both R1 and R2.
```

Configuration in R1:
```
global_defs {
  vrrp_version 3
}
vrrp_instance R1_instance {
  state BACKUP
  interface eth1
  virtual_router_id 1
  priority 150
  advert_int 1
  use_vmac
  virtual_ipaddress {
    fe80::1
  }
```
}

Configuration in R2:
```
global_defs {
  vrrp_version 3
}
vrrp_instance R2_instance {
  state BACKUP
  interface eth1
  virtual_router_id 1
  priority 100
  advert_int 1
  use_vmac
  virtual_ipaddress {
    fe80::1
  }
}
```
Assume vrrp ipv6 group is configured on R1 and R2.  R1 is MASTER and R2 is BACKUP.
Host  is configured with gateway as virtual ip and sending traffic to server.

I have enabled "use_vmac" option. So keepalived creates 'macvlan' subinterface on both R1 and R2 and assigns VMAC , parent interface's link-local address and another link-local address based on VMAC. As this is one time setup irrespective of state of the VRRP group, I see following problems.

**Problem 1:**
Traffic drop (Host ---> server) due to mac-movement. 
The mac movement is triggered due to IGMP/MLD report packets generated by linux kernel from both R1 and R2 routers.  In our case both MASTER and BACKUP routers uses vmac interface to join the multicast group. As BACKUP router also joins the multicast group using vmac interface, which is also having VMAC assigned, the packet reaches to the switch and mac movement happens. (VMAC is moved from R1 connected interface to R2 connected interface).  This mac movement is momentary untill MASTER sends subsequent advertisement. During this time any traffic from Host to Server with destination mac address as VMAC goes to BACKUP device and getting dropped. 

**Problem 2:**
Ping to virtual IP address from BACKUP to MASTER device is failing when ipv6 neighbour discovery is resolving VMAC for parent interface's link local address.

This problem is due to configuration of underlying parent interface's link local address also in sub-interface even for BACKUP/FAULT state instances. From R2 if the ping6 packet is initiated for the virtual ip address, the R1 responds with ICMPv6 Reply packet with following packet fields.

-- Source MAC         :      VMAC (as Virtual ip is owned by R1's subinterface)
---Destination MAC :      VMAC (as ipv6 neighbour discovery resolves with VMAC for parent interface's 
                                         link local)
--- Source IP            :       Virtual IP
--- Dest IP                :       Requestor's interface link local ipv6 address.

This reply reaches to the switch, and as the destination MAC address is VMAC which is learned on the port  on the same port this ICMP reply was received. Because of this switch drops the packet due to source suppression.

**My thoughts towards solution:**
- It would be good, if keepalived avoids adding vmac interface to the multicast group if the group is non MASTER and add the parent interface instead for BACKUP/FAULT/INIT state. (Solves Problem 1)
- Will it be good if we use VMAC interface only for MASTER instance, and parent interface for all other state ? This can be achieved by making vmac interface admin down when state transition from MASTER to BACKUP/FAULT.  When the state becomes MASTER, bring up the VMAC interface assign link local ip addresses. (Solves Problem 2).

Let me know , if any one has simple solution for this.
Also, please comment your view on this.

**Comment by balmnm** [comment]
@pqarmitage  could you please comment your view on this?

**Comment by pqarmitage** [comment]
@balmnm I read through this issue yesterday, and have been thinking about it since. It certainly seems that you have correctly identified a couple of problems, and your solutions may well work although there may be alternative ways to achieve this.

I need to think on about this, do some packet tracing, and look at what configuration options for links there are that might help. I certainly remember @jsouthworth telling me some years ago that taking interfaces up and down was not a good idea, so that is something we should probably avoid. One possibility might be to only assign the _proper_ virtual MAC address to the VMAC interface when it is master, and assign a dummy MAC address to it when it is in backup or fault state. Again, I haven't worked out the implications of that, but I think there is good logic to say that the _proper_ virtual MAC address should not exist on a VMAC interface when it is not master.

**Comment by balmnm** [comment]
Thanks @pqarmitage . Im also thinking about alternative ways. Will update you on that soon.

**Comment by balmnm** [comment]
@pqarmitage,  Regarding updation of MAC address upon transition to BACKUP/INIT

> One possibility might be to only assign the proper virtual MAC address to the VMAC interface when it is master, and assign a dummy MAC address to it when it is in backup or fault state.

I think we have to cache the allocated MAC address by kernel during the creation of VMAC interface. And this mac can be applied whenever VRRP leaves from MASTER state. And when VRRP transition to MASTER we can re-add the vmac  while adding the virtual IP's.  

Kindly let me know your comment on this.

**Comment by pqarmitage** [comment]
@balmnm Yes, caching the kernel allocated MAC address is what I had come around to as well.

**Comment by balmnm** [comment]
Thanks @pqarmitage  . I will work on this update you with the change.

**Comment by pqarmitage** [comment]
@balmnm A further thought. I'm not sure how the kernel generates locally administered MAC addresses, but if it just checks that the MAC address isn't in use, then if keepalived has a VMAC interface currently being master, then it may be possible for the kernel to generate the same MAC address for another VMAC or dummy interface, and then if we restore the originally allocated MAC address when the vrrp instance transitions to backup, there may be duplicate MAC addresses.

**Comment by balmnm** [comment]
@pqarmitage  Sorry for the late reply.
I just tried the following in **debian stretch** kernel and I see the mac-address is not duplicated.

```
root@RT:~# ip link add link eth1 vrrp1 type macvlan
root@RT:~# ifconfig vrrp1
vrrp1: flags=4098<BROADCAST,MULTICAST>  mtu 1500
        ether 0e:1b:56:47:e2:01  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@RT:~# ifconfig vrrp1 hw ether 00:00:5e:00:01:01
root@RT:~# ifconfig vrrp1
vrrp1: flags=4098<BROADCAST,MULTICAST>  mtu 1500
        ether 00:00:5e:00:01:01  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@RT:~# ip link add link eth1 vrrp2 type macvlan
root@RT:~# ifconfig vrrp2
vrrp2: flags=4098<BROADCAST,MULTICAST>  mtu 1500
        ether e2:d5:33:70:41:68  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
I think the same mac is not getting assigned for any new macvlan interface.
Do you foresee any issues with other linux kernels?

**Comment by pqarmitage** [comment]
@balmnm The MAC address is randomly generated, in which case there is a risk, albeit very small, that the same MAC address might be generated again. However, the Linux kernel doesn't appear to make any checks for uniqueness, so presumably the kernel has decided either the risk of a duplicate MAC address is too low to be worth worrying about, or it actually doesn't matter.

The code for the kernel generating a random MAC address is in include/linux/etherdevice.h in the kernel source tree. It is:
```
/**
 * eth_random_addr - Generate software assigned random Ethernet address
 * @addr: Pointer to a six-byte array containing the Ethernet address
 *
 * Generate a random Ethernet address (MAC) that is not multicast
 * and has the local assigned bit set.
 */
static inline void eth_random_addr(u8 *addr)
{
        get_random_bytes(addr, ETH_ALEN);
        addr[0] &= 0xfe;        /* clear multicast bit */
        addr[0] |= 0x02;        /* set local assignment bit (IEEE802) */
}
```

**Comment by balmnm** [comment]
@pqarmitage  Thanks for the suggestion.
Im planning to do the following code change.

- While creating sub-interface , the kernel allocated MAC address will not be changed to VMAC address.
- When the vrrp-group becomes master, VMAC is assigned to the sub-interface
- When the vrrp-group leaves from master, VMAC is removed from sub-interface and dummy MAC 00:00:5e:00:01:00 will be programmed on it.

The logic for VMAC assignment/removal is similar to VIP address assignment and removal.
Kindly let me know your comments on this approach.

What about using separate dummy MAC 00:00:5e:00:02:00 for VRRP IPv6 groups?
I do not see any advantage of using separate dummy MAC for IPv6 groups, but I do want to hear your view on this.

**Comment by pqarmitage** [comment]
I certainly think what you are suggesting is worth trying, and is a reasonable way to go, but until you try it I cannot say that it will work.

My preferences would be:
- When creating sub-interface, set dummy MAC 00:00:5e:00:01:00 immediately. This is so that the MAC is consistent when in backup mode, regardless of whether the vrrp instance has ever been master
- Use 00:00:5e:00:02:00 for IPv6 VMACs. It just seems more consistent to use the right family of dummy MAC address.

**Comment by balmnm** [comment]
@pqarmitage  I have tried the discussed solution, and here is the initial findings.
Im using debian stretch version of linux.

### 1. First mac address update always failing

If we try to change the MAC address virtual interface, very first time, it fails saying resource busy
But any subsequent mac update is passing without any issues. 

```
 Jun 21 15:03:00 OS Keepalived_vrrp_default[11173]: Netlink: error: Device or resource busy, type=(19), seq=1529593390, pid=0  
Jun 21 15:03:00 OS Keepalived_vrrp_default[11173]: Resetting VMAC failed

```

### 2. In case of IPv6 VRRP groups, the extra link local address is seen because of the dummy MAC configuration

root@OS# ifconfig eth1.v1
eth1.v1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 **fe80::200:5eff:fe00:200**  prefixlen 64  scopeid 0x20<link>
        inet6 fe80::20c:29ff:feb5:bbc0  prefixlen 64  scopeid 0x20<link>
        inet6 fe80::1  prefixlen 128  scopeid 0x20<link>
        inet6 f**e80::200:5eff:fe00:201**  prefixlen 64  scopeid 0x20<link>
        ether 00:00:5e:00:02:01  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 171  bytes 14878 (14.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

The first issue might be specific to debian kernel. I hope we can solve it or workaround this. Kindly let me know if you know the reason for this first failure.

But i feel the second behavior may create some other problems. Please let me know if you foresee any issue with this behavior?

**Comment by pqarmitage** [comment]
@balmnm Could you provide a copy of your patches so I can have a look and see if I have any suggestions. I can also see if any of the issues are Debian specific as you suggest.

**Comment by balmnm** [comment]
@pqarmitage  
Please find the changes in attachement. Kindly note that this change is based on 1.3.9 code base.
Let me know if you need code change based on latest release. 
Also now im not able to reproduce the debian specific issue (Issue #1)

[dummymac.patch.txt](https://github.com/acassen/keepalived/files/2127462/dummymac.patch.txt)

**Comment by pqarmitage** [comment]
@balmnm I have had a look at the patch and overall this looks good. Have you been able to verify that it resolves the two problems you identified at the beginning of this issue?

I have just a few comments on the patch:

1. The check in vrrp_complete_instance() for a matching VMAC interface needs changing. If the last byte of the MAC address of the interface is 0x00, then there will need to be a check that the interface name match as well.

2. In vrrp_complete_instance() again, if a matching VMAC interface is found and the last byte of the MAC address matches the vrid, then the MAC address of the interface needs to be set to the dummy mac address.

3. In netlink_link_add_vmac(), the vmac needs to be created with the dummy mac address.

4. I think we need a configuration option to enable this behaviour, so that the default behaviour is the same as the current behaviour (we don't know what impact it might have on other users yet). I suggest adding `vmac_dummy_mac` in the global defs section to enable this. 

5. The patch will need to apply to the current HEAD of the master branch (as opposed to v1.3.9).

6. The patch needs to be Linux formatted, and use the matching indentation as the existing keepalived code, i.e. one tab for each indent level (the patch file your provided has <CR> characters and is using 4 spaces to indent.

I haven't tested it yet on my system. I will provide an update when I have.

**Comment by pqarmitage** [comment]
@balmnm Apologies - I missed the change of creating the VMAC with the dummy MAC address.

I've been thinking a bit more about the original problems you mentioned. If all vrrp instances use the same dummy MAC address, and then multiple backup routers simultaneously do pings as you describe in Problem 2, the switch's view of where the dummy MAC address is will jump around between the different interfaces, and the ping responses will not necessarily be sent to the correct router. I think this means that the interfaces will need to use the random MAC address assigned by the kernel when in backup mode instead of the dummy MAC address. What do you think?

**Comment by balmnm** [comment]
@pqarmitage I think ping from backup node would be initiated from parent interface where the IP address is present.  So there will not be any issue in ping on simple configuration.  But there is a possibility of mac movement in switch when all the backup routers send IPV6 NS and NA packets.  
Also when user has scaled config such that R1 and R2 has mix of Backup and Master routers,  this mac movement problem occurs. 
Can we explore the solution which will make the VMAC interface up and down during master and non master?  

I know you already mentioned link up/down is not recommended. Curious to know possible issues with link up/down.

**Comment by pqarmitage** [comment]
@balmnm I'm not sure I every understood the reason why it was not a good idea to up/down the interface, but I was certainly advised that. I think my preference would be to got back to what we originally considered, and that was to remember the MAC address that the kernel configures by default, and use that when the vrrp instance is not master. Would that work for you?

**Comment by balmnm** [comment]
@pqarmitage  Ok.. Will rework on code changes and test the same.

**Comment by balmnm** [comment]
@pqarmitage  Sorry for the long delay . I have started working on implementation and got few doubts.

1. We decided to cache kernel generated mac address and use it when VRRP leaves from MASTER. This implies, we need to create vmac subinterface without any explicit specified mac input, so that kernel generates MAC on its own and assign it to the vmac sub-interface. correct?
2.  Im confused about assignment of link-local addresses to this interface. Current implementation assigns link local when the vmac is created. It assigns parent interface's link local address if the config does not have "source link local address".  And with flag "! HAVE_DECL_IFLA_INET6_ADDR_GEN_MODE" keepalived deletes the generated mac based link local too. This raises the following questions,
            
-  how to handle all these scenarios as and when the MAC is switched ? I think we need to delete existing link-local which is based on previous MAC and assign new link local based on new MAC for every mac reset. Correct?
- Do you see any performance degrade with this, as we often change the MAC and corresponding link local during state change?
- Is it OK to avoid changing of link-local addresses when the MAC is switched between VMAC and kernel assigned MAC. ? In this case one can see three link local addresses on the vmac sub-interface.  i) VMAC based link-local, ii) link-local based on kernel generated mac address, iii) parent's link local address for successful tx .

Kindly let me know your view on this.

**Comment by pqarmitage** [comment]
@balmnm I will follow your layout above for answering your questions:

1. I agree the interface needs to be created without any explicit MAC address in order to get a kernel generated MAC address.

2. Re assignment of IPv6 link local address

- I think the link-local address should remain as it is currently implemented (we certainly don't want to keep changing the link-local address); i.e. it uses the parent interface's link-local address if it has one, and if not it uses the MAC address of the parent interface to generate a link local address. The only purpose of using a VMAC is so that VRRP adverts are sent using the correct MAC address, and so for all other purposes we should take on the attributes of the underlying interface.
- I think if the link local address kept changing there could be some performance issues, but if we continue as set out in the point above and don't change the address then this won't be a problem.
- I can't see any problems with not changing the link-local address. If the link-local address is based on the parent interface, as now, then there should be no change that is noticeable outside the system.

Will /proc/sys/net/ipv6/conf/IF/ndisc_notify need to be set on the VMAC i/f so that ndisc messages are sent when the MAC address is changed?

**Comment by pqarmitage** [comment]
@balmnm The vmac interface should not have an auto generated link local address as in your point 1, since either IFLA_INET6_ADDR_GEN_MODE is set to IN6_ADDR_GEN_MODE_NONE which stops a link local address being auto generated, or if IFLA_INET6_ADDR_GEN_MODE is not supported by the kernel, the auto generated link local address is deleted in function remove_vmac_auto_gen_addr().

Re point 3, if IFLA_INET6_ADDR_GEN_MODE is set as above, then there shouldn't be an auto-generated link local address. I have just manually changed the MAC address of an interface, and it doesn't change the link local address, so if IFLA_INET6_ADDR_GEN_MODE isn't supported, it appears to me that there shouldn't be a problem.

**Comment by balmnm** [comment]
@pqarmitage  During testing of  dummymac_patch.txt, I noticed those extra link local address. (v1.3.9 is used). So I thought it would be auto-generated.
```
root@OS# ifconfig eth1.v1
eth1.v1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
inet6 **fe80::200:5eff:fe00:200** prefixlen 64 scopeid 0x20
inet6 **fe80::20c:29ff:feb5:bbc0** prefixlen 64 scopeid 0x20
inet6 fe80::1 prefixlen 128 scopeid 0x20
inet6 **fe80::200:5eff:fe00:201** prefixlen 64 scopeid 0x20
ether 00:00:5e:00:02:01 txqueuelen 1000 (Ethernet)
RX packets 0 bytes 0 (0.0 B)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 171 bytes 14878 (14.5 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0
```
Now with the introduction of "remove_vmac_auto_gen_addr()." API in latest keepalived version, I think we may not see the extra link-local address behavior. Will confirm after testing the changes on top of latest keepalived version.

**Comment by pqarmitage** [comment]
@balmnm The code using IFLA_INET6_ADDR_GEN_MODE was included in v1.3.9, and for some time before that I think.

**Comment by pqarmitage** [comment]
@balmnm Have you been able to test your changes against the latest version of keepalived?

**Comment by balmnm** [comment]
Sorry @pqarmitage . I have not yet done the changes fully. Plan to resume working on this on last week of september.

**Comment by pqarmitage** [comment]
@balmnm Have you had any more time to look at this? Is this still an issue for you?

**Comment by pqarmitage** [comment]
I have looked at problem 2 (ping from VMAC on backup to VIP on master) further, using directly connected systems without a switch. The master does not reply to the neighbour solicitation for the VIP address, since it sees the return MAC address (the MAC address of the VMAC interface) as a local address, and so does not send the reply to the neighbour solicitation.

**Comment by barak1adam** [comment]
Hi All,

I experienced this issue too.
I am running Keepalived 2.0.13 on our routers for VRRP capabilities.
Linux Kernel is 3.10.

Using the following basic VRRP setup:
=======================================


                                                Host 2
                                                   |
                                                   |
           -----------------------------------------------------------------
           +                                                                           +
           +                                                                           +
router A (master) ------- port 1| switch |port 2----- router B (VRRP backup)
                                                    |
                                                    |
                                                Host 1

Router A and Router B are running VRRP, protecting some virtual IPv4
address, let's say VIPx.
Host 1 is using this VIPx address as its default gateway.
Router A is VRRP Master, VIPx is UP and RUNNING associated with VMACx.
VMACx is learned by the switch port 1 connected to Router A.
Traffic sent from Host 1 to Host 2 via Router A - all good, no issues.

Now, rebooting Router B, IGMPv3 Report packets are sent with Group = VRRP
multicast IP. The source MAC of these packet =  VMACx.
This leads to the intermediate switch learning VMACx for a while on port 2
that is connected to Backup Router B. So, traffic sent by Host 1 is going
on the wrong direction (via Router B) and we loose traffic till VMACx is
learned again by the switch on port 1 connected to Router A.

I also found it in Debian bugs report logs:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=706198

I tried playing with the "vmac_xmit_base" flag in the past, not for this
issue.
But then I had the real MAC also used for VRRP advertisements and ARP
frames which was somehow problematic.

I am not sure but I think some source code change is needed for sending
IGMP packets with the base interface MAC and not with the VMAC.

I will be thankful for any idea to resolve it.

Thanks
Barak

**Comment by pqarmitage** [comment]
The same problem is referred to in [keepalived-devel message](https://sourceforge.net/p/keepalived/mailman/message/32386291/).

I investigating whether a `vmac_recv_base` option might work - in other words keepalived listens on the base interface, so the IGMP registration is done on the base interface, rather than the vmac interface.

**Comment by pqarmitage** [comment]
I cannot make receiving on the base interface work, since the packets are ignored due to the source MAC address being a local MAC address.

I have had some success blocking the GARP/GNA messages using nftables (iptables would work too), but it also means that the base interface has to register to receive the multicasts too. I assume it would also be possible to provide the same functionality using eBPF, but at the moment I haven't worked out how to do that.

**Comment by pqarmitage** [comment]
Commits b10bbfc and 72c4e54 resolve the issue of IGMP/MLD messages being sent with the source MAC address being the VMAC MAC. Commit b10bbfc uses nftables to do this, and commit 72c4e54 adds the option to use iptables/ipsets.

The ping issue is not resolvable without changing the MAC address of the VMAC, as explained at https://github.com/acassen/keepalived/issues/882#issuecomment-463253985
