### ISSUE TITLE
Why I cannot get 0.0.0.0:255 by run netstat -nap | grep keepalived

### ISSUE THREAD

**Issue by xufenghfut** [acassen/keepalived#884]
In my linux environment，when I run this cmd： netstat -nap | grep keepalived
I get the following message:
![image](https://user-images.githubusercontent.com/31697358/40522352-0a89f1dc-6003-11e8-88ff-392b1f72f8e6.png)

But I find somebody could get  0.0.0.0:255
![image](https://user-images.githubusercontent.com/31697358/40521645-28095cec-5fff-11e8-8642-b86ef250df12.png)
![image](https://user-images.githubusercontent.com/31697358/40522369-2d6ccddc-6003-11e8-8257-94a7efd436a0.png)
![image](https://user-images.githubusercontent.com/31697358/40522370-349cd50c-6003-11e8-8b2e-5dc4402eafa3.png)

My keepalived version is 1.2.13.      Why I cannot get 0.0.0.0:255 ?

**Comment by acassen** [comment]
1.2.13 ??? is way too old... please consider upgrading to last stable release (1.4.4 currently)

**Comment by xufenghfut** [comment]
I just want to know the usage of **0.0.0.0:255** and how could I get it?
If any one can give an explanation？

**Comment by pqarmitage** [comment]
The 0.0.0.0.255 socket is used send commands to the kernel if netlink isn't available. Between commits 057b376 and fdc58299 it was always used due to a bug introduced in commit 057b376. See commit for further explanation.

Older systems are more likely to use the socket (i.e. if libnl/libnl-3 aren't available), but there is some functionality but there is some functionality such as IPVS with IPv6 that is not supported over the socket interface, but only via netlink.
