### ISSUE TITLE
why github version  2.0.7 source tar file is different from the keepalive.org's

### ISSUE THREAD

**Issue by 402309718** [acassen/keepalived#994]
download from github I find it has no configure file inside, but in keealived.org it has,so ?any other method to compile this ?tks

**Comment by pqarmitage** [comment]
Github has the source files, and since configure is generated from configure.ac it isn't in the Github source tree (the same applies to the Makefile.in and Makefile files and various other files generated from the source tree). The files is the tarball contain configure, the Makefile.in and Makefile files etc, so that keepalived can be built without having autotools installed.

If you read the INSTALL file in the root of the source tree in the sections "Installing from a git repo" and "Installation" it explains what you need to do.
