### ISSUE TITLE
The arbitration of master and backup are disordered

### ISSUE THREAD

**Issue by ox123** [acassen/keepalived#996]
I have two host and multi network card eth0 and eth1, both of them are bind with vip,but when I used the cmd[service keepalived stop] to force the cluster to do the master and backup switch,it failed, when I searching the logs in the /var/log/messages,the two node are as bellow, I find some issues about the arbitration.
**The master node**:
Line 19970: Aug 31 22:01:15 I-RegionLB02 Keepalived_vrrp[27566]: VRRP_Instance(VI_64) Entering BACKUP STATE
	Line 19971: Aug 31 22:01:15 I-RegionLB02 Keepalived_vrrp[27566]: VRRP_Instance(VI_96) Entering BACKUP STATE
	Line 20087: Aug 31 22:02:14 I-RegionLB02 Keepalived_vrrp[34639]: VRRP_Instance(VI_64) Entering BACKUP STATE
	Line 20088: Aug 31 22:02:14 I-RegionLB02 Keepalived_vrrp[34639]: VRRP_Instance(VI_96) Entering BACKUP STATE
	Line 20204: Aug 31 22:06:14 I-RegionLB02 Keepalived_vrrp[59037]: VRRP_Instance(VI_64) Entering BACKUP STATE
	Line 20205: Aug 31 22:06:14 I-RegionLB02 Keepalived_vrrp[59037]: VRRP_Instance(VI_96) Entering BACKUP STATE
	Line 20321: Aug 31 22:08:19 I-RegionLB02 Keepalived_vrrp[70629]: VRRP_Instance(VI_64) Entering BACKUP STATE
	Line 20322: Aug 31 22:08:19 I-RegionLB02 Keepalived_vrrp[70629]: VRRP_Instance(VI_96) Entering BACKUP STATE
	Line 20385: Aug 31 22:12:56 I-RegionLB02 Keepalived_vrrp[70629]: VRRP_Instance(VI_64) Entering MASTER STATE

The backup node:
Line 203: Aug 31 22:01:02 I-RegionLB01 Keepalived_vrrp[35215]: VRRP_Instance(VI_64) Entering MASTER STATE
	Line 391: Aug 31 22:08:15 I-RegionLB01 Keepalived_vrrp[89601]: VRRP_Instance(VI_64) Entering BACKUP STATE
	Line 392: Aug 31 22:08:15 I-RegionLB01 Keepalived_vrrp[89601]: VRRP_Instance(VI_96) Entering BACKUP STATE
	Line 397: Aug 31 22:08:20 I-RegionLB01 Keepalived_vrrp[89601]: VRRP_Instance(VI_64) Entering MASTER STATE

My problem is why the two node roles switching are so long?

**Comment by pqarmitage** [comment]
From the information you have provided it isn't possible to tell what is happening. What is clear is that keepalived is stopping and restarting, since different PIDs are being logged, and so there must be other keepalived log entries that you haven't provided.

Can you please provide the following information:
1. The output of `keepalived -v`
2. What distro and version you are running on
3. Copies of your keepalived configuration files
4. The output of `ip link show` on each system
5. All keepalived log entries

We can then investigate what is happening.

**Comment by pqarmitage** [comment]
Closing due to no response for over 3 weeks. If further information is provided this issue can be reopened.

**Comment by ox123** [comment]
- keepalive

 version as bellow
[root@iaas-haproxy02 ulb]# keepalived -v
Keepalived v1.2.13 (10/11,2016)

- keepalived.conf file 
! Configuration File for keepalived

vrrp_script chk_http_port {
    script "/home/elb/keepalived/script/check_haproxy.sh"
    interval 2
    weight 2
}

                    vrrp_instance VI_1 {
            state BACKUP
	        interface eth0
	        virtual_router_id 150
                nopreempt
                priority 150
	        advert_int 1
	        virtual_ipaddress {
                                172.30.49.152
                                172.30.49.153
                                172.30.49.154
                                172.30.49.155
                                172.30.49.156
                                172.30.49.157
                                172.30.49.158
                	        }
             		
	        track_script {
               chk_http_port
            }
notify_master ".../script/notify.sh eth0 master"
notify_backup ".../script/notify.sh eth0 backup"
notify_fault ".../script/notify.sh eth0 fault"
        }
              
****

The other env also have this issues, according the the messages log, the last  master select in this node should be BACKUP,  but according the the notify script execute log(notify.log), It was master
---------
messages log
Oct  8 05:01:03 IAAS-LB-Haproxy01 Keepalived_vrrp[24681]: VRRP_Instance(VI_1) Entering BACKUP STATE
Oct  8 07:01:04 IAAS-LB-Haproxy01 Keepalived_vrrp[24681]: VRRP_Instance(VI_1) Entering MASTER STATE
Oct  8 07:01:04 IAAS-LB-Haproxy01 Keepalived_vrrp[24681]: VRRP_Instance(VI_1) Entering BACKUP STATE
Oct  8 08:01:04 IAAS-LB-Haproxy01 Keepalived_vrrp[24681]: VRRP_Instance(VI_1) Entering MASTER STATE
Oct  8 08:01:06 IAAS-LB-Haproxy01 Keepalived_vrrp[24681]: VRRP_Instance(VI_1) Entering BACKUP STATE
Oct  8 22:01:04 IAAS-LB-Haproxy01 Keepalived_vrrp[24681]: VRRP_Instance(VI_1) Entering BACKUP STATE
Oct  8 23:01:05 IAAS-LB-Haproxy01 Keepalived_vrrp[24681]: VRRP_Instance(VI_1) Entering MASTER STATE
Oct  8 23:01:06 IAAS-LB-Haproxy01 Keepalived_vrrp[24681]: VRRP_Instance(VI_1) Entering BACKUP STATE

----
notify log(This log generated by the notify script)
2018-10-08 23:01:06 009 Enter into nofify... PID[41297] [eth0 backup], lock it and Others need to wait
2018-10-08 23:01:06 652 Getout notify...     PID[41297] [eth0 backup]
2018-10-08 23:01:06 680 Enter into nofify... PID[41298] [eth0 master], lock it and Others need to wait
2018-10-08 23:01:06 710 Getout notify...     PID[41298] [eth0 master]

---
we have analyzed the keeplaived source and found the bellow script can not ensure the execution order when it runs the two notify script at the same time.  ----------------I just want to know is there any idea about this issues.
```c
/* Execute external script/program */
int
notify_exec(const notify_script_t *script)
{
	pid_t pid;

	if (log_file_name)
		flush_log_file();

	pid = local_fork();

	if (pid < 0) {
		/* fork error */
		log_message(LOG_INFO, "Failed fork process");
		return -1;
	}

	if (pid) {
		/* parent process */
		return 0;
	}

#ifdef _MEM_CHECK_
	skip_mem_dump();
#endif

	system_call(script);

	/* We should never get here */
	exit(0);
}
```

**Comment by pqarmitage** [comment]
Yes, you are correct. The notify scripts are run asynchronously; keepalived does not wait for the completion of one notify script before it runs another one. This means that notify scripts can execute concurrently, and so the sequence of the events being processed by notify scripts is non-deterministic.

It was for this reason that I added notify_fifos, which not only guarantees the ordered delivery of notify events, but is also much more efficient than notify scripts.

In order to use notify FIFOs  you will need to upgrade to a more recent version of keepalived, at least v1.3.6. If you are upgrading you may as well upgrade to v2.0.8 since there are many feature enhancements, performance enhancements and bug fixes between v1.3.6 and v2.0.8.

**Comment by ox123** [comment]
Thank you for your reply, So if I upgrade to the nearest version,I can resolve this issues with the same notify_master/notify_backup/notify_fault or other method?

**Comment by ox123** [comment]
But now it is difficult for us to upgrade to the nearest version at least , because we have so many clusers distributed the whole world in the production env. is there any way to resolve this issues without upgrading the version? especially how to judge the master or backup of the keepalived node.

**Comment by pqarmitage** [comment]
@ox123 If you upgrade, rather than using `notify_master`/`notify_backup`/`notify_fault`, you would use `vrrp_notify_fifo`. You will need to write a script/program to read the fifo, and keepalived can run that script if you use the `vrrp_notify_fifo_script` option. An example script is included at doc/samples/sample_notify_fifo.sh

Since the execution order of notify scripts is not guaranteed, using the notify scripts they would need to check the current state of the vrrp instance. That could be done using SNMP (provided that you have built keepalived with SNMP enabled), and I was going to suggest another way, but that doesn't appear to be supported by keepalived v1.2.13.

keepalived v1.2.13 is _very_ old, and there have been very many bug fixes, security fixes, feature enhancements and performance improvements since v1.2.13 (there have been a total of 2375 non merge commits since v1.2.13). Further, we don't backport bug fixes, so if you found a bug in keepalived, it would only be resolved in the then current version. It would probably be worth your while looking at developing a mechanism that would allow you to upgrade keepalived across your production environment in case you had an urgent need to upgrade to fix a bug (or indeed make use of new functionality such as notify fifos).

**Comment by ox123** [comment]
@pqarmitage Thanks，  and now we are confused the switch of the master and backup, I do not why the cluster will do the master and backup switch except for the vrrp packet lost, But we are monitoring the transimit of the network packets and find no packets missing.

My question is when will the keepalived do the switch except for the vrrp packet lost? can you give me some ideas. Thanks

**Comment by ox123** [comment]
At now we setting  the advert_int value to 1s
